apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: ocidex-git-clone
  namespace: ocidex-ci
spec:
  params:
    - name: url
      type: string
    - name: revision
      type: string
  stepTemplate:
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
  steps:
    - image: cgr.dev/chainguard/git:latest
      name: clone
      script: |-
        #!/bin/sh
        set -e
        git clone -v $(params.url) .
        git config --global --add safe.directory $(workspaces.workspace.path)
        git checkout $(params.revision)
      workingDir: $(workspaces.workspace.path)
  workspaces:
    - name: workspace
