---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocidex.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ocidex.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    {{- include "ocidex.selectorLabels" (dict "root" . "component" "api") | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocidex.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ocidex.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    {{- include "ocidex.selectorLabels" (dict "root" . "component" "web") | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocidex.fullname" . }}-nats
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ocidex.labels" . | nindent 4 }}
    app.kubernetes.io/component: nats
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "ocidex.selectorLabels" (dict "root" . "component" "nats") | nindent 4 }}
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: monitoring
      port: 8222
      targetPort: 8222
