apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocidex-api
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocidex-scanner-worker
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocidex-enrichment-worker
spec:
  replicas: 2
