// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifact_relations.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getArtifactCurrentVersion = `-- name: GetArtifactCurrentVersion :one

SELECT s.subject_version
FROM sbom s
WHERE s.artifact_id = $1
  AND sbom_visible(s.namespace_id, $2::uuid, $3::boolean)
ORDER BY s.created_at DESC, s.id DESC
LIMIT 1
`

type GetArtifactCurrentVersionParams struct {
	ArtifactID pgtype.UUID `json:"artifact_id"`
	UserID     pgtype.UUID `json:"user_id"`
	IsAdmin    pgtype.Bool `json:"is_admin"`
}

// Artifact relationship queries (ADR-041).
//
// Relationships are DERIVED here, not stored. Both queries do a COARSE match in
// SQL and leave the EXACT match to componentKey() in Go — see ADR-041 R1 and the
// indexing caveat. The SQL side matches on the purl base
// (split_part(split_part(purl,'?',1),'@',1), backed by idx_component_purl_base)
// or, for purl-less rows, the (type, name, group) tuple. Identity qualifiers are
// neither filtered nor sorted here, so these results are a superset; the service
// narrows them with the same key function diff uses.
//
// '?' is split before '@' to mirror normalizeComponentPurl(): qualifiers follow
// the version in purl format, so a component with qualifiers and no version
// (pkg:golang/foo?arch=amd64) would otherwise keep its qualifiers in the base.
//
// Both directions define "latest SBOM" the same way ListSBOMsByArtifact orders:
// created_at DESC, id DESC, restricted to SBOMs the caller can see. The
// visibility predicate is inside the latest-SBOM subquery as well as outside it,
// so a caller never resolves a relationship against an SBOM they cannot read —
// and never sees "no relationship" merely because someone else's newer SBOM is
// shadowing a visible one.
// subject_version of the artifact's latest visible SBOM. Used to answer "is the
// version shipped here the current one?" without a second round-trip per usage.
func (q *Queries) GetArtifactCurrentVersion(ctx context.Context, arg GetArtifactCurrentVersionParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getArtifactCurrentVersion, arg.ArtifactID, arg.UserID, arg.IsAdmin)
	var subject_version pgtype.Text
	err := row.Scan(&subject_version)
	return subject_version, err
}

const listArtifactContains = `-- name: ListArtifactContains :many
WITH subject_latest AS (
    SELECT s.id
    FROM sbom s
    WHERE s.artifact_id = $3
      AND sbom_visible(s.namespace_id, $1::uuid, $2::boolean)
    ORDER BY s.created_at DESC, s.id DESC
    LIMIT 1
)
SELECT a.id           AS artifact_id,
       a.type         AS artifact_type,
       a.name         AS artifact_name,
       a.group_name   AS artifact_group,
       a.purl         AS artifact_purl,
       c.type         AS matched_type,
       c.name         AS matched_name,
       c.group_name   AS matched_group,
       c.version      AS matched_version,
       c.purl         AS matched_purl,
       ls.subject_version AS current_version,
       ls.digest          AS current_digest,
       ls.flavor          AS current_flavor,
       ls.id              AS current_sbom_id
FROM component c
JOIN artifact a ON (
        (c.purl IS NOT NULL AND a.purl IS NOT NULL
         AND split_part(split_part(c.purl, '?', 1), '@', 1)
           = split_part(split_part(a.purl, '?', 1), '@', 1))
     OR (c.purl IS NULL AND a.purl IS NULL
         AND a.type = c.type
         AND a.name = c.name
         AND COALESCE(a.group_name, '') = COALESCE(c.group_name, ''))
)
LEFT JOIN LATERAL (
    SELECT s2.id, s2.subject_version, s2.digest, s2.flavor
    FROM sbom s2
    WHERE s2.artifact_id = a.id
      AND sbom_visible(s2.namespace_id, $1::uuid, $2::boolean)
    ORDER BY s2.created_at DESC, s2.id DESC
    LIMIT 1
) ls ON true
WHERE c.sbom_id = (SELECT id FROM subject_latest)
  AND a.id <> $3
  AND artifact_visible(a.id, $1::uuid, $2::boolean)
ORDER BY a.name, a.type, a.id
LIMIT $4
`

type ListArtifactContainsParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	IsAdmin    pgtype.Bool `json:"is_admin"`
	ArtifactID pgtype.UUID `json:"artifact_id"`
	RowLimit   int32       `json:"row_limit"`
}

type ListArtifactContainsRow struct {
	ArtifactID     pgtype.UUID `json:"artifact_id"`
	ArtifactType   string      `json:"artifact_type"`
	ArtifactName   string      `json:"artifact_name"`
	ArtifactGroup  pgtype.Text `json:"artifact_group"`
	ArtifactPurl   pgtype.Text `json:"artifact_purl"`
	MatchedType    string      `json:"matched_type"`
	MatchedName    string      `json:"matched_name"`
	MatchedGroup   pgtype.Text `json:"matched_group"`
	MatchedVersion pgtype.Text `json:"matched_version"`
	MatchedPurl    pgtype.Text `json:"matched_purl"`
	CurrentVersion pgtype.Text `json:"current_version"`
	CurrentDigest  pgtype.Text `json:"current_digest"`
	CurrentFlavor  pgtype.Text `json:"current_flavor"`
	CurrentSbomID  pgtype.UUID `json:"current_sbom_id"`
}

// "What of ours does this carry?" — tracked artifacts matched by components of
// the subject artifact's latest visible SBOM (ADR-041 R5). The inverse of
// ListArtifactUsages, and the join condition is the same coarse match read from
// the other side.
//
// The LATERAL supplies each matched artifact's own current version/digest/flavor
// so the caller can report drift (ADR-041 R2) without an N+1. LEFT JOIN, not
// inner: an artifact whose SBOMs are all invisible to this caller is already
// excluded by artifact_visible below, but an artifact row with no SBOM at all is
// a legitimate (if unusual) match and should not vanish silently.
func (q *Queries) ListArtifactContains(ctx context.Context, arg ListArtifactContainsParams) ([]ListArtifactContainsRow, error) {
	rows, err := q.db.Query(ctx, listArtifactContains,
		arg.UserID,
		arg.IsAdmin,
		arg.ArtifactID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtifactContainsRow{}
	for rows.Next() {
		var i ListArtifactContainsRow
		if err := rows.Scan(
			&i.ArtifactID,
			&i.ArtifactType,
			&i.ArtifactName,
			&i.ArtifactGroup,
			&i.ArtifactPurl,
			&i.MatchedType,
			&i.MatchedName,
			&i.MatchedGroup,
			&i.MatchedVersion,
			&i.MatchedPurl,
			&i.CurrentVersion,
			&i.CurrentDigest,
			&i.CurrentFlavor,
			&i.CurrentSbomID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactUsages = `-- name: ListArtifactUsages :many
SELECT a.id           AS artifact_id,
       a.type         AS artifact_type,
       a.name         AS artifact_name,
       a.group_name   AS artifact_group,
       a.purl         AS artifact_purl,
       s.id           AS sbom_id,
       s.subject_version,
       s.digest,
       s.flavor,
       s.created_at,
       c.type         AS matched_type,
       c.name         AS matched_name,
       c.group_name   AS matched_group,
       c.version      AS matched_version,
       c.purl         AS matched_purl
FROM component c
JOIN sbom s ON s.id = c.sbom_id
JOIN artifact a ON a.id = s.artifact_id
WHERE (
        ($1::text IS NOT NULL
         AND c.purl IS NOT NULL
         AND split_part(split_part(c.purl, '?', 1), '@', 1) = $1::text)
     OR ($1::text IS NULL
         AND c.purl IS NULL
         AND c.type = $2
         AND c.name = $3
         AND COALESCE(c.group_name, '') = $4)
      )
  AND s.artifact_id <> $5
  AND sbom_visible(s.namespace_id, $6::uuid, $7::boolean)
  AND s.id = (
      SELECT s2.id FROM sbom s2
      WHERE s2.artifact_id = s.artifact_id
        AND sbom_visible(s2.namespace_id, $6::uuid, $7::boolean)
      ORDER BY s2.created_at DESC, s2.id DESC
      LIMIT 1
  )
ORDER BY a.name, a.type, a.id
LIMIT $8
`

type ListArtifactUsagesParams struct {
	PurlBase     pgtype.Text `json:"purl_base"`
	SubjectType  string      `json:"subject_type"`
	SubjectName  string      `json:"subject_name"`
	SubjectGroup pgtype.Text `json:"subject_group"`
	ArtifactID   pgtype.UUID `json:"artifact_id"`
	UserID       pgtype.UUID `json:"user_id"`
	IsAdmin      pgtype.Bool `json:"is_admin"`
	RowLimit     int32       `json:"row_limit"`
}

type ListArtifactUsagesRow struct {
	ArtifactID     pgtype.UUID        `json:"artifact_id"`
	ArtifactType   string             `json:"artifact_type"`
	ArtifactName   string             `json:"artifact_name"`
	ArtifactGroup  pgtype.Text        `json:"artifact_group"`
	ArtifactPurl   pgtype.Text        `json:"artifact_purl"`
	SbomID         pgtype.UUID        `json:"sbom_id"`
	SubjectVersion pgtype.Text        `json:"subject_version"`
	Digest         pgtype.Text        `json:"digest"`
	Flavor         pgtype.Text        `json:"flavor"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	MatchedType    string             `json:"matched_type"`
	MatchedName    string             `json:"matched_name"`
	MatchedGroup   pgtype.Text        `json:"matched_group"`
	MatchedVersion pgtype.Text        `json:"matched_version"`
	MatchedPurl    pgtype.Text        `json:"matched_purl"`
}

// "Where does this ship?" — artifacts whose latest visible SBOM contains a
// component matching the subject artifact (ADR-041 R5).
//
// Leads with the component predicate rather than the SBOM set: component is the
// large table, and the purl-base expression index makes that the selective step.
// The latest-SBOM test is then a correlated lookup on idx_sbom_artifact_id per
// surviving row, not a DISTINCT ON over every SBOM in the database.
//
// purl_base NULL selects the Rule 2 branch. It is not merely "the subject has no
// purl": a purl-keyed subject can only match purl-keyed components and a
// tuple-keyed subject only tuple-keyed ones, because componentKey() picks its
// branch per row. Mixed pairs are non-matches by construction, so the two
// branches are exclusive here too.
func (q *Queries) ListArtifactUsages(ctx context.Context, arg ListArtifactUsagesParams) ([]ListArtifactUsagesRow, error) {
	rows, err := q.db.Query(ctx, listArtifactUsages,
		arg.PurlBase,
		arg.SubjectType,
		arg.SubjectName,
		arg.SubjectGroup,
		arg.ArtifactID,
		arg.UserID,
		arg.IsAdmin,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtifactUsagesRow{}
	for rows.Next() {
		var i ListArtifactUsagesRow
		if err := rows.Scan(
			&i.ArtifactID,
			&i.ArtifactType,
			&i.ArtifactName,
			&i.ArtifactGroup,
			&i.ArtifactPurl,
			&i.SbomID,
			&i.SubjectVersion,
			&i.Digest,
			&i.Flavor,
			&i.CreatedAt,
			&i.MatchedType,
			&i.MatchedName,
			&i.MatchedGroup,
			&i.MatchedVersion,
			&i.MatchedPurl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
