// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifact.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countArtifactVersions = `-- name: CountArtifactVersions :one
SELECT COUNT(DISTINCT
    COALESCE(s.subject_version,
        COALESCE(e.data->>'imageVersion', u.data->>'imageVersion'),
        s.id::text)
)::bigint AS version_count
FROM sbom s
LEFT JOIN enrichment e ON e.sbom_id = s.id AND e.enricher_name = 'oci-metadata' AND e.status = 'success'
LEFT JOIN enrichment u ON u.sbom_id = s.id AND u.enricher_name = 'user'         AND u.status = 'success'
WHERE s.artifact_id = $1
  AND sbom_visible(s.namespace_id, $2::uuid, $3::boolean)
`

type CountArtifactVersionsParams struct {
	ArtifactID pgtype.UUID `json:"artifact_id"`
	UserID     pgtype.UUID `json:"user_id"`
	IsAdmin    pgtype.Bool `json:"is_admin"`
}

func (q *Queries) CountArtifactVersions(ctx context.Context, arg CountArtifactVersionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countArtifactVersions, arg.ArtifactID, arg.UserID, arg.IsAdmin)
	var version_count int64
	err := row.Scan(&version_count)
	return version_count, err
}

const countSBOMsByArtifact = `-- name: CountSBOMsByArtifact :one
SELECT COUNT(*)
FROM sbom s
WHERE s.artifact_id = $1
  AND sbom_visible(s.namespace_id, $2::uuid, $3::boolean)
`

type CountSBOMsByArtifactParams struct {
	ArtifactID pgtype.UUID `json:"artifact_id"`
	UserID     pgtype.UUID `json:"user_id"`
	IsAdmin    pgtype.Bool `json:"is_admin"`
}

// Counts visible SBOMs for an artifact. Replaces the prior trick of reading
// COUNT(*) OVER() off ListSBOMsByArtifact, which is now keyset-paginated.
func (q *Queries) CountSBOMsByArtifact(ctx context.Context, arg CountSBOMsByArtifactParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSBOMsByArtifact, arg.ArtifactID, arg.UserID, arg.IsAdmin)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSufficientSBOMsByArtifact = `-- name: CountSufficientSBOMsByArtifact :one
SELECT COUNT(*)
FROM sbom s
WHERE s.artifact_id = $1
  AND s.enrichment_sufficient
  AND sbom_visible(s.namespace_id, $2::uuid, $3::boolean)
`

type CountSufficientSBOMsByArtifactParams struct {
	ArtifactID pgtype.UUID `json:"artifact_id"`
	UserID     pgtype.UUID `json:"user_id"`
	IsAdmin    pgtype.Bool `json:"is_admin"`
}

// Counts visible SBOMs for an artifact whose enrichment is sufficient. Kept
// separate from CountSBOMsByArtifact rather than added to it as a second
// column: that query's callers all want the plain total, and widening its
// return type to a row struct would churn every one of them.
func (q *Queries) CountSufficientSBOMsByArtifact(ctx context.Context, arg CountSufficientSBOMsByArtifactParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSufficientSBOMsByArtifact, arg.ArtifactID, arg.UserID, arg.IsAdmin)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteArtifact = `-- name: DeleteArtifact :execrows
DELETE FROM artifact WHERE id = $1
`

func (q *Queries) DeleteArtifact(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteArtifact, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSBOMsByArtifact = `-- name: DeleteSBOMsByArtifact :execrows
DELETE FROM sbom WHERE artifact_id = $1
`

func (q *Queries) DeleteSBOMsByArtifact(ctx context.Context, artifactID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSBOMsByArtifact, artifactID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getArtifact = `-- name: GetArtifact :one
SELECT a.id, a.type, a.name, a.group_name, a.purl, a.cpe, a.created_at,
       (SELECT CASE
           WHEN EXISTS (
               SELECT 1 FROM enrichment pe JOIN sbom sx ON sx.id = pe.sbom_id
               WHERE sx.artifact_id = a.id AND pe.enricher_name = 'provenance'
                 AND pe.status = 'success' AND signing_status(pe.data) = 'artifact_missing'
           ) THEN 'artifact_missing'
           WHEN EXISTS (
               SELECT 1 FROM enrichment pe JOIN sbom sx ON sx.id = pe.sbom_id
               WHERE sx.artifact_id = a.id AND pe.enricher_name = 'provenance'
                 AND pe.status = 'success' AND signing_status(pe.data) = 'verified'
           ) THEN 'verified'
           WHEN EXISTS (
               SELECT 1 FROM enrichment pe JOIN sbom sx ON sx.id = pe.sbom_id
               WHERE sx.artifact_id = a.id AND pe.enricher_name = 'provenance'
                 AND pe.status = 'success' AND signing_status(pe.data) = 'verification_failed'
           ) THEN 'verification_failed'
           WHEN EXISTS (
               SELECT 1 FROM enrichment pe JOIN sbom sx ON sx.id = pe.sbom_id
               WHERE sx.artifact_id = a.id AND pe.enricher_name = 'provenance'
                 AND pe.status = 'success' AND signing_status(pe.data) = 'signed'
           ) THEN 'signed'
           ELSE 'unsigned'
       END)::text AS signing_status
FROM artifact a
WHERE a.id = $1
`

type GetArtifactRow struct {
	ID            pgtype.UUID        `json:"id"`
	Type          string             `json:"type"`
	Name          string             `json:"name"`
	GroupName     pgtype.Text        `json:"group_name"`
	Purl          pgtype.Text        `json:"purl"`
	Cpe           pgtype.Text        `json:"cpe"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	SigningStatus string             `json:"signing_status"`
}

// The nested CASE aggregates signing_status(pe.data) across every SBOM under
// this artifact, so unlike signing_status()'s single-row ladder (mutually
// exclusive fields on one enrichment blob), here multiple WHEN branches can
// independently be true across different SBOMs. artifact_missing is checked
// first deliberately: it's worst-case-first so one missing artifact among
// many SBOMs dominates the rollup rather than being masked by a sibling
// SBOM that still verifies. This intentionally inverts the "best status
// wins" instinct one might expect from a rollup. See ocidex-goh.16 and
// TestArtifactRollupSigningStatus_ArtifactMissingDominates in
// tests/integration_test.go.
func (q *Queries) GetArtifact(ctx context.Context, id pgtype.UUID) (GetArtifactRow, error) {
	row := q.db.QueryRow(ctx, getArtifact, id)
	var i GetArtifactRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.GroupName,
		&i.Purl,
		&i.Cpe,
		&i.CreatedAt,
		&i.SigningStatus,
	)
	return i, err
}

const getArtifactNamespaceID = `-- name: GetArtifactNamespaceID :one
SELECT an.namespace_id
FROM artifact_namespace an
WHERE an.artifact_id = $1
ORDER BY an.namespace_id
LIMIT 1
`

// Any one namespace holding the artifact. An artifact can hang from several
// namespaces with different members, and this answers with whichever row comes
// first — as its owner-returning predecessor did (ocidex-y0hg.5). The caller is
// a capability check, so the question it settles is now "may you do this here"
// rather than "are you this one user"; asking it of every namespace the artifact
// belongs to is ocidex-y0hg.6.
//
// Ordered rather than left to the heap, so that "whichever row came first" is a
// stable answer across two identical requests instead of a plan detail.
func (q *Queries) GetArtifactNamespaceID(ctx context.Context, artifactID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getArtifactNamespaceID, artifactID)
	var namespace_id pgtype.UUID
	err := row.Scan(&namespace_id)
	return namespace_id, err
}

const listArtifactVersions = `-- name: ListArtifactVersions :many
WITH sboms_meta AS (
    SELECT
        s.id,
        s.created_at,
        s.enrichment_sufficient,
        COALESCE(s.subject_version,
            COALESCE(e.data->>'imageVersion', u.data->>'imageVersion'),
            s.id::text)                                                  AS version_key,
        COALESCE(e.data->>'architecture', u.data->>'architecture')       AS architecture,
        COALESCE(e.data->>'imageVersion',  u.data->>'imageVersion')      AS image_version,
        COALESCE(e.data->>'revision',      u.data->>'revision')          AS revision,
        COALESCE(e.data->>'sourceUrl',     u.data->>'sourceUrl')         AS source_url,
        (COALESCE(e.data->>'created',      u.data->>'created'))::timestamptz AS build_date,
        signing_status(p.data) AS signing_status
    FROM sbom s
    LEFT JOIN enrichment e ON e.sbom_id = s.id AND e.enricher_name = 'oci-metadata' AND e.status = 'success'
    LEFT JOIN enrichment u ON u.sbom_id = s.id AND u.enricher_name = 'user'         AND u.status = 'success'
    LEFT JOIN enrichment p ON p.sbom_id = s.id AND p.enricher_name = 'provenance'   AND p.status = 'success'
    WHERE s.artifact_id = $1
      AND sbom_visible(s.namespace_id, $4::uuid, $5::boolean)
),
newest_per_version AS (
    SELECT DISTINCT ON (version_key)
        id, version_key, created_at, enrichment_sufficient, image_version, revision, source_url, build_date, signing_status
    FROM sboms_meta
    ORDER BY version_key, created_at DESC
),
architectures_per_version AS (
    SELECT
        version_key,
        array_agg(DISTINCT architecture) FILTER (WHERE architecture IS NOT NULL) AS architectures
    FROM sboms_meta
    GROUP BY version_key
),
sbom_count_per_version AS (
    SELECT version_key, COUNT(*) AS sbom_count
    FROM sboms_meta
    GROUP BY version_key
)
SELECT
    n.version_key,
    n.id           AS newest_sbom_id,
    n.created_at,
    n.enrichment_sufficient,
    n.image_version,
    n.revision,
    n.source_url,
    n.build_date,
    n.signing_status,
    a.architectures,
    c.sbom_count,
    -- Severity counts come from the version's newest SBOM, the same row every
    -- other column here already describes. Unioning findings across every SBOM
    -- in the version would keep reporting it vulnerable after the fix shipped.
    --
    -- sbom_vuln_rollup holds a row only for an SBOM with at least one finding,
    -- so a missing row is "no known vulnerabilities" *or* "never scanned" and
    -- this join cannot tell them apart (ADR-044). Coalescing to zero here is
    -- safe only because that same invariant makes a zero total unambiguous:
    -- it can only have come from a missing row, never from a real scan. The
    -- service maps a zero total back to a nil summary so the UI says "not
    -- scanned"; rendering it as a clean zero is the bug.
    COALESCE(r.critical, 0)::bigint AS vuln_critical,
    COALESCE(r.high,     0)::bigint AS vuln_high,
    COALESCE(r.medium,   0)::bigint AS vuln_medium,
    COALESCE(r.low,      0)::bigint AS vuln_low,
    COALESCE(r.unknown,  0)::bigint AS vuln_unknown,
    COUNT(*) OVER() AS total_count
FROM newest_per_version n
JOIN architectures_per_version a ON a.version_key = n.version_key
JOIN sbom_count_per_version c ON c.version_key = n.version_key
LEFT JOIN sbom_vuln_rollup r ON r.sbom_id = n.id
ORDER BY n.created_at DESC
LIMIT $3 OFFSET $2
`

type ListArtifactVersionsParams struct {
	ArtifactID pgtype.UUID `json:"artifact_id"`
	RowOffset  int32       `json:"row_offset"`
	RowLimit   int32       `json:"row_limit"`
	UserID     pgtype.UUID `json:"user_id"`
	IsAdmin    pgtype.Bool `json:"is_admin"`
}

type ListArtifactVersionsRow struct {
	VersionKey           pgtype.Text        `json:"version_key"`
	NewestSbomID         pgtype.UUID        `json:"newest_sbom_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	EnrichmentSufficient bool               `json:"enrichment_sufficient"`
	ImageVersion         interface{}        `json:"image_version"`
	Revision             interface{}        `json:"revision"`
	SourceUrl            interface{}        `json:"source_url"`
	BuildDate            pgtype.Timestamptz `json:"build_date"`
	SigningStatus        string             `json:"signing_status"`
	Architectures        interface{}        `json:"architectures"`
	SbomCount            int64              `json:"sbom_count"`
	VulnCritical         int64              `json:"vuln_critical"`
	VulnHigh             int64              `json:"vuln_high"`
	VulnMedium           int64              `json:"vuln_medium"`
	VulnLow              int64              `json:"vuln_low"`
	VulnUnknown          int64              `json:"vuln_unknown"`
	TotalCount           int64              `json:"total_count"`
}

func (q *Queries) ListArtifactVersions(ctx context.Context, arg ListArtifactVersionsParams) ([]ListArtifactVersionsRow, error) {
	rows, err := q.db.Query(ctx, listArtifactVersions,
		arg.ArtifactID,
		arg.RowOffset,
		arg.RowLimit,
		arg.UserID,
		arg.IsAdmin,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtifactVersionsRow{}
	for rows.Next() {
		var i ListArtifactVersionsRow
		if err := rows.Scan(
			&i.VersionKey,
			&i.NewestSbomID,
			&i.CreatedAt,
			&i.EnrichmentSufficient,
			&i.ImageVersion,
			&i.Revision,
			&i.SourceUrl,
			&i.BuildDate,
			&i.SigningStatus,
			&i.Architectures,
			&i.SbomCount,
			&i.VulnCritical,
			&i.VulnHigh,
			&i.VulnMedium,
			&i.VulnLow,
			&i.VulnUnknown,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifacts = `-- name: ListArtifacts :many
SELECT a.id, a.type, a.name, a.group_name, a.purl, a.cpe, a.created_at,
       COUNT(s.id) AS sbom_count,
       COUNT(s.id) FILTER (WHERE s.enrichment_sufficient) AS sufficient_sbom_count,
       (SELECT CASE
           WHEN EXISTS (
               SELECT 1 FROM enrichment pe JOIN sbom sx ON sx.id = pe.sbom_id
               WHERE sx.artifact_id = a.id AND pe.enricher_name = 'provenance'
                 AND pe.status = 'success' AND signing_status(pe.data) = 'artifact_missing'
           ) THEN 'artifact_missing'
           WHEN EXISTS (
               SELECT 1 FROM enrichment pe JOIN sbom sx ON sx.id = pe.sbom_id
               WHERE sx.artifact_id = a.id AND pe.enricher_name = 'provenance'
                 AND pe.status = 'success' AND signing_status(pe.data) = 'verified'
           ) THEN 'verified'
           WHEN EXISTS (
               SELECT 1 FROM enrichment pe JOIN sbom sx ON sx.id = pe.sbom_id
               WHERE sx.artifact_id = a.id AND pe.enricher_name = 'provenance'
                 AND pe.status = 'success' AND signing_status(pe.data) = 'verification_failed'
           ) THEN 'verification_failed'
           WHEN EXISTS (
               SELECT 1 FROM enrichment pe JOIN sbom sx ON sx.id = pe.sbom_id
               WHERE sx.artifact_id = a.id AND pe.enricher_name = 'provenance'
                 AND pe.status = 'success' AND signing_status(pe.data) = 'signed'
           ) THEN 'signed'
           ELSE 'unsigned'
       END)::text AS signing_status,
       -- Severity counts for this artifact's newest SBOM (ocidex-unn8.9). They
       -- come from sbom_vuln_rollup rather than an aggregate over component:
       -- ocidex-ckv.2 measured that shape at ~53s against a 30s timeout, which
       -- is why the rollups exist at all.
       --
       -- Newest SBOM, not a union across every SBOM under the artifact: a union
       -- would keep reporting the artifact vulnerable long after the fix
       -- shipped, because the fixed version does not delete its predecessors.
       -- That differs from the signing_status ladder above, which *is*
       -- worst-case-across-SBOMs — deliberately, since an unsigned sibling is a
       -- live gap while a superseded CVE is not.
       --
       -- The rollup holds a row only for an SBOM with at least one finding, so
       -- a zero total here means "no findings" *or* "never scanned" and this
       -- join cannot tell them apart (ADR-044). Coalescing to zero is safe only
       -- because that same invariant makes a zero unambiguous — it can only
       -- have come from a missing row. The service maps a zero total back to a
       -- nil summary so the UI says "not scanned"; rendering it as a clean zero
       -- is the bug.
       COALESCE(vr.critical, 0)::bigint AS vuln_critical,
       COALESCE(vr.high,     0)::bigint AS vuln_high,
       COALESCE(vr.medium,   0)::bigint AS vuln_medium,
       COALESCE(vr.low,      0)::bigint AS vuln_low,
       COALESCE(vr.unknown,  0)::bigint AS vuln_unknown
FROM artifact a
LEFT JOIN sbom s ON s.artifact_id = a.id
LEFT JOIN LATERAL (
    SELECT COALESCE(r.critical, 0)::bigint AS critical,
           COALESCE(r.high,     0)::bigint AS high,
           COALESCE(r.medium,   0)::bigint AS medium,
           COALESCE(r.low,      0)::bigint AS low,
           COALESCE(r.unknown,  0)::bigint AS unknown,
           (COALESCE(r.critical, 0) + COALESCE(r.high, 0) + COALESCE(r.medium, 0)
            + COALESCE(r.low, 0) + COALESCE(r.unknown, 0))::bigint AS total
    FROM sbom sv
    LEFT JOIN sbom_vuln_rollup r ON r.sbom_id = sv.id
    WHERE sv.artifact_id = a.id
    ORDER BY sv.created_at DESC, sv.id DESC
    LIMIT 1
) vr ON TRUE
WHERE ($1::text IS NULL OR a.type = $1)
  AND ($2::text IS NULL OR a.name ILIKE '%' || $2::text || '%')
  AND ($3::boolean IS NULL
       OR NOT $3::boolean
       OR EXISTS (SELECT 1 FROM sbom s2 WHERE s2.artifact_id = a.id AND s2.enrichment_sufficient))
  -- owned_only is the ownership path for /api/v1/users/me/artifacts. An
  -- artifact is "mine" when it appears in a namespace I own; artifact_visible()
  -- would additionally admit every public artifact and every artifact with no
  -- namespace link at all, which is exactly what this collection must exclude
  -- (ocidex-998g.2, and see ListNamespaces).
  AND CASE WHEN COALESCE($4::boolean, false)
           THEN EXISTS (
               SELECT 1 FROM artifact_namespace an
               WHERE an.artifact_id = a.id
                 AND an.namespace_id IN (
                       SELECT owned_namespace_ids($5::uuid)))
           ELSE artifact_visible(a.id, $5::uuid, $6::boolean)
      END
  AND (
    NOT $7::boolean
    OR (a.name, a.type, a.id) > ($8::text, $9::text, $10::uuid)
  )
GROUP BY a.id, vr.critical, vr.high, vr.medium, vr.low, vr.unknown, vr.total
ORDER BY
    CASE WHEN $11::boolean THEN COALESCE(vr.total, 0) = 0 END,
    CASE WHEN $11::boolean THEN COALESCE(vr.critical, 0) * $12::int END DESC,
    CASE WHEN $11::boolean THEN COALESCE(vr.high,     0) * $12::int END DESC,
    CASE WHEN $11::boolean THEN COALESCE(vr.medium,   0) * $12::int END DESC,
    CASE WHEN $11::boolean THEN COALESCE(vr.low,      0) * $12::int END DESC,
    CASE WHEN $11::boolean THEN COALESCE(vr.unknown,  0) * $12::int END DESC,
    a.name, a.type, a.id
LIMIT $14 OFFSET $13
`

type ListArtifactsParams struct {
	Type              pgtype.Text `json:"type"`
	Name              pgtype.Text `json:"name"`
	RequireSufficient pgtype.Bool `json:"require_sufficient"`
	OwnedOnly         pgtype.Bool `json:"owned_only"`
	UserID            pgtype.UUID `json:"user_id"`
	IsAdmin           pgtype.Bool `json:"is_admin"`
	HasCursor         pgtype.Bool `json:"has_cursor"`
	CursorName        pgtype.Text `json:"cursor_name"`
	CursorType        pgtype.Text `json:"cursor_type"`
	CursorID          pgtype.UUID `json:"cursor_id"`
	SortSeverity      bool        `json:"sort_severity"`
	SortDir           int32       `json:"sort_dir"`
	RowOffset         int32       `json:"row_offset"`
	RowLimit          int32       `json:"row_limit"`
}

type ListArtifactsRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Type                string             `json:"type"`
	Name                string             `json:"name"`
	GroupName           pgtype.Text        `json:"group_name"`
	Purl                pgtype.Text        `json:"purl"`
	Cpe                 pgtype.Text        `json:"cpe"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	SbomCount           int64              `json:"sbom_count"`
	SufficientSbomCount int64              `json:"sufficient_sbom_count"`
	SigningStatus       string             `json:"signing_status"`
	VulnCritical        int64              `json:"vuln_critical"`
	VulnHigh            int64              `json:"vuln_high"`
	VulnMedium          int64              `json:"vuln_medium"`
	VulnLow             int64              `json:"vuln_low"`
	VulnUnknown         int64              `json:"vuln_unknown"`
}

// Same artifact_missing-first rollup precedence as GetArtifact above — see
// that query's comment for why this cross-SBOM ladder deliberately checks
// worst-case first.
// The inner join is LEFT so the lateral picks the *newest* SBOM and then looks
// for its rollup row, rather than the newest SBOM that happens to have one:
// an inner join would silently fall back to a superseded SBOM's findings.
// Two orderings in one query. The severity keys are wrapped in a CASE that
// collapses to NULL when @sort_severity is false, which makes every row tie on
// them and hands the decision to the trailing (name, type, id) — the default
// ordering, unchanged. A second query would have meant a second copy of the
// WHERE clause above, and a filter that drifts between the two paths is a
// worse bug than six CASEs.
//
// Direction is a sign flip (@sort_dir is 1 for desc, -1 for asc) rather than a
// second pair of keys, which works because counts are non-negative. The
// zero-total gate is *outside* that flip on purpose: a zero total is unknown,
// not clean, so it sorts last in both directions. Floating never-scanned
// artifacts to the top of an ascending sort would present them as the safest
// thing on the page, which is the ADR-044 mistake.
//
// Counts are compared rank by rank rather than as one total so a single
// critical outranks a hundred lows.
// Offset is 0 on the keyset path; it only moves under the severity sort, where
// ADR-043 rule (1) rules a keyset cursor out — the ORDER BY columns are a
// rollup that a refresh pass rewrites under the reader's feet.
func (q *Queries) ListArtifacts(ctx context.Context, arg ListArtifactsParams) ([]ListArtifactsRow, error) {
	rows, err := q.db.Query(ctx, listArtifacts,
		arg.Type,
		arg.Name,
		arg.RequireSufficient,
		arg.OwnedOnly,
		arg.UserID,
		arg.IsAdmin,
		arg.HasCursor,
		arg.CursorName,
		arg.CursorType,
		arg.CursorID,
		arg.SortSeverity,
		arg.SortDir,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtifactsRow{}
	for rows.Next() {
		var i ListArtifactsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.GroupName,
			&i.Purl,
			&i.Cpe,
			&i.CreatedAt,
			&i.SbomCount,
			&i.SufficientSbomCount,
			&i.SigningStatus,
			&i.VulnCritical,
			&i.VulnHigh,
			&i.VulnMedium,
			&i.VulnLow,
			&i.VulnUnknown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSBOMsByArtifact = `-- name: ListSBOMsByArtifact :many
SELECT s.id, s.serial_number, s.spec_version, s.version, s.subject_version, s.digest, s.created_at,
       (SELECT COUNT(*) FROM component c WHERE c.sbom_id = s.id) AS component_count,
       (COALESCE(e.data->>'created', u.data->>'created'))::timestamptz AS build_date,
       COALESCE(e.data->>'imageVersion', u.data->>'imageVersion') AS image_version,
       COALESCE(e.data->>'architecture', u.data->>'architecture') AS architecture,
       COALESCE(e.data->>'revision', u.data->>'revision') AS revision,
       COALESCE(e.data->>'sourceUrl', u.data->>'sourceUrl') AS source_url,
       s.enrichment_sufficient,
       s.flavor
FROM sbom s
LEFT JOIN enrichment e ON e.sbom_id = s.id AND e.enricher_name = 'oci-metadata' AND e.status = 'success'
LEFT JOIN enrichment u ON u.sbom_id = s.id AND u.enricher_name = 'user' AND u.status = 'success'
WHERE s.artifact_id = $1
  AND ($2::text IS NULL OR s.subject_version = $2)
  AND ($3::text IS NULL
       OR COALESCE(e.data->>'imageVersion', u.data->>'imageVersion') = $3)
  AND sbom_visible(s.namespace_id, $4::uuid, $5::boolean)
  AND (
    NOT $6::boolean
    OR (s.created_at, s.id) < ($7::timestamptz, $8::uuid)
  )
ORDER BY s.created_at DESC, s.id DESC
LIMIT $9
`

type ListSBOMsByArtifactParams struct {
	ArtifactID      pgtype.UUID        `json:"artifact_id"`
	SubjectVersion  pgtype.Text        `json:"subject_version"`
	ImageVersion    pgtype.Text        `json:"image_version"`
	UserID          pgtype.UUID        `json:"user_id"`
	IsAdmin         pgtype.Bool        `json:"is_admin"`
	HasCursor       pgtype.Bool        `json:"has_cursor"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	RowLimit        int32              `json:"row_limit"`
}

type ListSBOMsByArtifactRow struct {
	ID                   pgtype.UUID        `json:"id"`
	SerialNumber         pgtype.Text        `json:"serial_number"`
	SpecVersion          string             `json:"spec_version"`
	Version              int32              `json:"version"`
	SubjectVersion       pgtype.Text        `json:"subject_version"`
	Digest               pgtype.Text        `json:"digest"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	ComponentCount       int64              `json:"component_count"`
	BuildDate            pgtype.Timestamptz `json:"build_date"`
	ImageVersion         interface{}        `json:"image_version"`
	Architecture         interface{}        `json:"architecture"`
	Revision             interface{}        `json:"revision"`
	SourceUrl            interface{}        `json:"source_url"`
	EnrichmentSufficient bool               `json:"enrichment_sufficient"`
	Flavor               pgtype.Text        `json:"flavor"`
}

func (q *Queries) ListSBOMsByArtifact(ctx context.Context, arg ListSBOMsByArtifactParams) ([]ListSBOMsByArtifactRow, error) {
	rows, err := q.db.Query(ctx, listSBOMsByArtifact,
		arg.ArtifactID,
		arg.SubjectVersion,
		arg.ImageVersion,
		arg.UserID,
		arg.IsAdmin,
		arg.HasCursor,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSBOMsByArtifactRow{}
	for rows.Next() {
		var i ListSBOMsByArtifactRow
		if err := rows.Scan(
			&i.ID,
			&i.SerialNumber,
			&i.SpecVersion,
			&i.Version,
			&i.SubjectVersion,
			&i.Digest,
			&i.CreatedAt,
			&i.ComponentCount,
			&i.BuildDate,
			&i.ImageVersion,
			&i.Architecture,
			&i.Revision,
			&i.SourceUrl,
			&i.EnrichmentSufficient,
			&i.Flavor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupArtifacts = `-- name: LookupArtifacts :many
SELECT a.id, a.type, a.name, a.group_name
FROM artifact a
WHERE a.name = $1::text
  AND ($2::text IS NULL OR a.type = $2)
  AND ($3::text IS NULL OR COALESCE(a.group_name, '') = $3)
  AND artifact_visible(a.id, $4::uuid, $5::boolean)
ORDER BY a.type, a.group_name NULLS FIRST, a.id
LIMIT 50
`

type LookupArtifactsParams struct {
	Name      string      `json:"name"`
	Type      pgtype.Text `json:"type"`
	GroupName pgtype.Text `json:"group_name"`
	UserID    pgtype.UUID `json:"user_id"`
	IsAdmin   pgtype.Bool `json:"is_admin"`
}

type LookupArtifactsRow struct {
	ID        pgtype.UUID `json:"id"`
	Type      string      `json:"type"`
	Name      string      `json:"name"`
	GroupName pgtype.Text `json:"group_name"`
}

// ADR-042 R3/R4: name-keyed resolver. Unlike ListArtifacts, `name` here is an
// exact key, not an ILIKE search — the resolver's contract is unique-or-409,
// so a substring match would make ambiguity the normal case. `type` and
// `group_name` are the R4 ladder rungs; NULL means wildcard, not an
// empty-string match, so omitting a qualifier widens the query rather than
// pinning it to rows with an empty value.
//
// R5: artifact_visible() is applied here so the caller counts only visible
// candidates. A private artifact must not turn a unique public match into a
// 409 — that would leak its existence.
func (q *Queries) LookupArtifacts(ctx context.Context, arg LookupArtifactsParams) ([]LookupArtifactsRow, error) {
	rows, err := q.db.Query(ctx, lookupArtifacts,
		arg.Name,
		arg.Type,
		arg.GroupName,
		arg.UserID,
		arg.IsAdmin,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LookupArtifactsRow{}
	for rows.Next() {
		var i LookupArtifactsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertArtifact = `-- name: UpsertArtifact :one
INSERT INTO artifact (type, name, group_name, purl, cpe)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (type, name, COALESCE(group_name, ''))
DO UPDATE SET
    purl = COALESCE(EXCLUDED.purl, artifact.purl),
    cpe  = COALESCE(EXCLUDED.cpe, artifact.cpe)
RETURNING id
`

type UpsertArtifactParams struct {
	Type      string      `json:"type"`
	Name      string      `json:"name"`
	GroupName pgtype.Text `json:"group_name"`
	Purl      pgtype.Text `json:"purl"`
	Cpe       pgtype.Text `json:"cpe"`
}

func (q *Queries) UpsertArtifact(ctx context.Context, arg UpsertArtifactParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertArtifact,
		arg.Type,
		arg.Name,
		arg.GroupName,
		arg.Purl,
		arg.Cpe,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertArtifactNamespace = `-- name: UpsertArtifactNamespace :exec
INSERT INTO artifact_namespace (artifact_id, namespace_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type UpsertArtifactNamespaceParams struct {
	ArtifactID  pgtype.UUID `json:"artifact_id"`
	NamespaceID pgtype.UUID `json:"namespace_id"`
}

func (q *Queries) UpsertArtifactNamespace(ctx context.Context, arg UpsertArtifactNamespaceParams) error {
	_, err := q.db.Exec(ctx, upsertArtifactNamespace, arg.ArtifactID, arg.NamespaceID)
	return err
}
