// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countIdentitiesByUser = `-- name: CountIdentitiesByUser :one
SELECT count(*) FROM user_identity WHERE user_id = $1
`

func (q *Queries) CountIdentitiesByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countIdentitiesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_key (user_id, name, key_hash, prefix, capabilities)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, key_hash, prefix, created_at, last_used_at, capabilities
`

type CreateAPIKeyParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	Name         string      `json:"name"`
	KeyHash      string      `json:"key_hash"`
	Prefix       string      `json:"prefix"`
	Capabilities []string    `json:"capabilities"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.UserID,
		arg.Name,
		arg.KeyHash,
		arg.Prefix,
		arg.Capabilities,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.Prefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Capabilities,
	)
	return i, err
}

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO user_identity (user_id, provider, subject, email)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, provider, subject, email, created_at, updated_at
`

type CreateIdentityParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Provider string      `json:"provider"`
	Subject  string      `json:"subject"`
	Email    pgtype.Text `json:"email"`
}

// Link a second issuer to an account that already exists. UNIQUE (provider,
// subject) is what stops one identity being attached to two accounts; the
// service checks first so it can say which case it hit, but the constraint is
// the thing that actually holds.
func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.UserID,
		arg.Provider,
		arg.Subject,
		arg.Email,
	)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO session (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, created_at
`

type CreateSessionParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUserWithIdentity = `-- name: CreateUserWithIdentity :one
WITH new_user AS (
    INSERT INTO ocidex_user (display_name, email)
    VALUES ($1, $2)
    RETURNING id, role, created_at, updated_at, email, display_name
), new_identity AS (
    INSERT INTO user_identity (user_id, provider, subject, email)
    SELECT id, $3, $4, $2 FROM new_user
)
SELECT id, role, created_at, updated_at, email, display_name FROM new_user
`

type CreateUserWithIdentityParams struct {
	DisplayName pgtype.Text `json:"display_name"`
	Email       pgtype.Text `json:"email"`
	Provider    string      `json:"provider"`
	Subject     string      `json:"subject"`
}

type CreateUserWithIdentityRow struct {
	ID          pgtype.UUID        `json:"id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Email       pgtype.Text        `json:"email"`
	DisplayName pgtype.Text        `json:"display_name"`
}

// The account and its first identity are written by one statement so a failure
// between them cannot leave an account nobody can sign in to.
func (q *Queries) CreateUserWithIdentity(ctx context.Context, arg CreateUserWithIdentityParams) (CreateUserWithIdentityRow, error) {
	row := q.db.QueryRow(ctx, createUserWithIdentity,
		arg.DisplayName,
		arg.Email,
		arg.Provider,
		arg.Subject,
	)
	var i CreateUserWithIdentityRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.DisplayName,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :execrows
DELETE FROM api_key WHERE id = $1 AND user_id = $2
`

type DeleteAPIKeyParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAPIKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM session WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteIdentity = `-- name: DeleteIdentity :execrows
DELETE FROM user_identity WHERE id = $1 AND user_id = $2
`

type DeleteIdentityParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Scoped by user_id as well as id: an identity row is only ever the caller's to
// remove, and matching on id alone would let anyone unlink anyone.
func (q *Queries) DeleteIdentity(ctx context.Context, arg DeleteIdentityParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIdentity, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM session WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT k.id, k.user_id, k.name, k.key_hash, k.prefix, k.capabilities, k.created_at, k.last_used_at,
       u.display_name, u.role
FROM api_key k
JOIN ocidex_user u ON u.id = k.user_id
WHERE k.key_hash = $1
`

type GetAPIKeyByHashRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Name         string             `json:"name"`
	KeyHash      string             `json:"key_hash"`
	Prefix       string             `json:"prefix"`
	Capabilities []string           `json:"capabilities"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastUsedAt   pgtype.Timestamptz `json:"last_used_at"`
	DisplayName  pgtype.Text        `json:"display_name"`
	Role         string             `json:"role"`
}

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.Prefix,
		&i.Capabilities,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.DisplayName,
		&i.Role,
	)
	return i, err
}

const getIdentity = `-- name: GetIdentity :one
SELECT id, user_id, provider, subject, email, created_at, updated_at FROM user_identity WHERE provider = $1 AND subject = $2
`

type GetIdentityParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

func (q *Queries) GetIdentity(ctx context.Context, arg GetIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, getIdentity, arg.Provider, arg.Subject)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT s.id, s.user_id, s.token_hash, s.expires_at, s.created_at, u.display_name, u.role
FROM session s
JOIN ocidex_user u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.expires_at > now()
`

type GetSessionByTokenHashRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	TokenHash   string             `json:"token_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DisplayName pgtype.Text        `json:"display_name"`
	Role        string             `json:"role"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Role,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, role, created_at, updated_at, email, display_name FROM ocidex_user WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (OcidexUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i OcidexUser
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.DisplayName,
	)
	return i, err
}

const getUserByIdentity = `-- name: GetUserByIdentity :one
SELECT u.id, u.role, u.created_at, u.updated_at, u.email, u.display_name
FROM ocidex_user u
JOIN user_identity i ON i.user_id = u.id
WHERE i.provider = $1
  AND i.subject  = $2
`

type GetUserByIdentityParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

func (q *Queries) GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (OcidexUser, error) {
	row := q.db.QueryRow(ctx, getUserByIdentity, arg.Provider, arg.Subject)
	var i OcidexUser
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.DisplayName,
	)
	return i, err
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id, name, prefix, capabilities, created_at, last_used_at
FROM api_key
WHERE user_id = $1
ORDER BY created_at ASC
`

type ListAPIKeysByUserRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Prefix       string             `json:"prefix"`
	Capabilities []string           `json:"capabilities"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastUsedAt   pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) ListAPIKeysByUser(ctx context.Context, userID pgtype.UUID) ([]ListAPIKeysByUserRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysByUserRow{}
	for rows.Next() {
		var i ListAPIKeysByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.Capabilities,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentitiesByUser = `-- name: ListIdentitiesByUser :many
SELECT id, provider, subject, email, created_at
FROM user_identity
WHERE user_id = $1
ORDER BY created_at ASC, id ASC
`

type ListIdentitiesByUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	Provider  string             `json:"provider"`
	Subject   string             `json:"subject"`
	Email     pgtype.Text        `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// The identities an account can sign in with, oldest first, for the owner's own
// account page. Nothing here is shown to anybody else: a subject is an issuer's
// internal key for a person, and publishing the set of issuers somebody uses is
// a fingerprint they did not ask to hand out.
func (q *Queries) ListIdentitiesByUser(ctx context.Context, userID pgtype.UUID) ([]ListIdentitiesByUserRow, error) {
	rows, err := q.db.Query(ctx, listIdentitiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIdentitiesByUserRow{}
	for rows.Next() {
		var i ListIdentitiesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Subject,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, role, created_at, updated_at, email, display_name FROM ocidex_user ORDER BY created_at ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]OcidexUser, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OcidexUser{}
	for rows.Next() {
		var i OcidexUser
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_key SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, id)
	return err
}

const touchUserProfile = `-- name: TouchUserProfile :one
UPDATE ocidex_user
SET display_name = COALESCE(NULLIF($1::text, ''), display_name),
    email        = COALESCE(NULLIF($2::text, ''), email),
    updated_at   = now()
WHERE id = $3
RETURNING id, role, created_at, updated_at, email, display_name
`

type TouchUserProfileParams struct {
	DisplayName string      `json:"display_name"`
	Email       string      `json:"email"`
	ID          pgtype.UUID `json:"id"`
}

// Refresh the cosmetic fields from whatever the issuer released this sign-in.
// An issuer that released nothing must not blank what another one set, hence
// COALESCE over NULLIF rather than a plain assignment.
func (q *Queries) TouchUserProfile(ctx context.Context, arg TouchUserProfileParams) (OcidexUser, error) {
	row := q.db.QueryRow(ctx, touchUserProfile, arg.DisplayName, arg.Email, arg.ID)
	var i OcidexUser
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.DisplayName,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE ocidex_user
SET role       = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, role, created_at, updated_at, email, display_name
`

type UpdateUserRoleParams struct {
	ID   pgtype.UUID `json:"id"`
	Role string      `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (OcidexUser, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i OcidexUser
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.DisplayName,
	)
	return i, err
}

const upsertIdentityEmail = `-- name: UpsertIdentityEmail :exec
UPDATE user_identity
SET email      = COALESCE(NULLIF($1::text, ''), email),
    updated_at = now()
WHERE provider = $2
  AND subject  = $3
`

type UpsertIdentityEmailParams struct {
	Email    string `json:"email"`
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

// Keep the identity row's own email in step with the issuer. It is separate
// from ocidex_user.email because an account may hold several identities and
// each carries the address its issuer knows.
func (q *Queries) UpsertIdentityEmail(ctx context.Context, arg UpsertIdentityEmailParams) error {
	_, err := q.db.Exec(ctx, upsertIdentityEmail, arg.Email, arg.Provider, arg.Subject)
	return err
}
