// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cluster.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countClusterRunningVulns = `-- name: CountClusterRunningVulns :one
WITH running AS (
    SELECT
        COALESCE(NULLIF(v.canonical_id, ''), v.id) AS canonical_id,
        v.severity                                 AS severity
    FROM cluster_workload w
    JOIN cluster c ON c.id = w.cluster_id
    JOIN LATERAL (
        SELECT s2.id
        FROM sbom s2
        WHERE w.image_digest IS NOT NULL
          AND (s2.digest = w.image_digest OR s2.index_digest = w.image_digest)
        ORDER BY (s2.digest = w.image_digest) DESC, s2.created_at DESC
        LIMIT 1
    ) s ON true
    JOIN component comp ON comp.sbom_id = s.id AND comp.purl IS NOT NULL
    JOIN package_vulnerability pv ON pv.purl = comp.purl
    JOIN vulnerability v ON v.id = pv.vulnerability_id
    WHERE w.cluster_id = $1
      AND c.namespace_id IN (SELECT visible_namespace_ids($3::uuid, $4::boolean))
)
SELECT COUNT(DISTINCT canonical_id)::bigint AS total
FROM running
WHERE ($2::text IS NULL OR severity = $2::text)
`

type CountClusterRunningVulnsParams struct {
	ClusterID pgtype.UUID `json:"cluster_id"`
	Severity  pgtype.Text `json:"severity"`
	UserID    pgtype.UUID `json:"user_id"`
	IsAdmin   pgtype.Bool `json:"is_admin"`
}

// The total for ListClusterRunningVulns' pagination, counted over the same
// canonical_id grouping so the total and the page agree about what one row is.
func (q *Queries) CountClusterRunningVulns(ctx context.Context, arg CountClusterRunningVulnsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countClusterRunningVulns,
		arg.ClusterID,
		arg.Severity,
		arg.UserID,
		arg.IsAdmin,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countClusterWorkloads = `-- name: CountClusterWorkloads :one
SELECT COUNT(*)::bigint AS total
FROM cluster_workload w
JOIN cluster c ON c.id = w.cluster_id
LEFT JOIN LATERAL (
    SELECT s2.id, s2.digest
    FROM sbom s2
    WHERE w.image_digest IS NOT NULL
      AND (s2.digest = w.image_digest OR s2.index_digest = w.image_digest)
    ORDER BY (s2.digest = w.image_digest) DESC, s2.created_at DESC
    LIMIT 1
) s ON true
CROSS JOIN LATERAL (
    SELECT (CASE WHEN s.id IS NOT NULL AND s.digest = w.image_digest THEN 'exact'
                 WHEN s.id IS NOT NULL                               THEN 'index'
                 WHEN w.image_digest IS NULL                         THEN 'unresolvable'
                 ELSE                                                     'unknown'
            END)::text AS state
) ms
WHERE w.cluster_id = $1
  AND c.namespace_id IN (SELECT visible_namespace_ids($2::uuid, $3::boolean))
  AND ($4::text IS NULL OR w.k8s_namespace = $4::text)
  AND ($5::text IS NULL OR ms.state = $5::text)
  AND ($6::text IS NULL OR (
        w.workload_name  ILIKE '%' || $6::text || '%'
     OR w.container_name ILIKE '%' || $6::text || '%'
     OR w.image_ref      ILIKE '%' || $6::text || '%'))
`

type CountClusterWorkloadsParams struct {
	ClusterID    pgtype.UUID `json:"cluster_id"`
	UserID       pgtype.UUID `json:"user_id"`
	IsAdmin      pgtype.Bool `json:"is_admin"`
	K8sNamespace pgtype.Text `json:"k8s_namespace"`
	MatchState   pgtype.Text `json:"match_state"`
	Q            pgtype.Text `json:"q"`
}

// The total for ListClusterWorkloads' pagination. It takes the same filters, and
// only the filters — it is the size of the filtered list, never a substitute for
// GetClusterWorkloadCoverage, which is deliberately unfiltered.
func (q *Queries) CountClusterWorkloads(ctx context.Context, arg CountClusterWorkloadsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countClusterWorkloads,
		arg.ClusterID,
		arg.UserID,
		arg.IsAdmin,
		arg.K8sNamespace,
		arg.MatchState,
		arg.Q,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createCluster = `-- name: CreateCluster :one

INSERT INTO cluster (namespace_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, namespace_id, name, description, last_seen_at, created_at, updated_at, auto_ingest
`

type CreateClusterParams struct {
	NamespaceID pgtype.UUID `json:"namespace_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
}

// Kubernetes deployment inventory (ADR-044).
//
// A cluster is owned by a namespace and has no visibility of its own, so every
// read path here resolves visibility through `namespace` exactly as source.sql
// does. Nothing in this file may be called without a visibility gate either in
// the query or at the service boundary; the comment on each read says which.
func (q *Queries) CreateCluster(ctx context.Context, arg CreateClusterParams) (Cluster, error) {
	row := q.db.QueryRow(ctx, createCluster, arg.NamespaceID, arg.Name, arg.Description)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.Name,
		&i.Description,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoIngest,
	)
	return i, err
}

const deleteCluster = `-- name: DeleteCluster :execrows
DELETE FROM cluster WHERE id = $1
`

// Cascades to cluster_workload. Inventory is derived state reported by an
// agent, so losing it with the cluster is correct.
func (q *Queries) DeleteCluster(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCluster, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCluster = `-- name: GetCluster :one
SELECT id, namespace_id, name, description, last_seen_at, created_at, updated_at, auto_ingest FROM cluster WHERE id = $1
`

func (q *Queries) GetCluster(ctx context.Context, id pgtype.UUID) (Cluster, error) {
	row := q.db.QueryRow(ctx, getCluster, id)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.Name,
		&i.Description,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoIngest,
	)
	return i, err
}

const getClusterByName = `-- name: GetClusterByName :one
SELECT id, namespace_id, name, description, last_seen_at, created_at, updated_at, auto_ingest FROM cluster WHERE namespace_id = $1 AND name = $2
`

type GetClusterByNameParams struct {
	NamespaceID pgtype.UUID `json:"namespace_id"`
	Name        string      `json:"name"`
}

func (q *Queries) GetClusterByName(ctx context.Context, arg GetClusterByNameParams) (Cluster, error) {
	row := q.db.QueryRow(ctx, getClusterByName, arg.NamespaceID, arg.Name)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.Name,
		&i.Description,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoIngest,
	)
	return i, err
}

const getClusterWorkloadCoverage = `-- name: GetClusterWorkloadCoverage :one
SELECT
    COUNT(*)                                                            AS total,
    COUNT(*) FILTER (WHERE w.image_digest IS NULL)                      AS unresolvable,
    COUNT(*) FILTER (WHERE w.image_digest IS NOT NULL AND s.id IS NULL) AS unknown,
    COUNT(*) FILTER (WHERE s.id IS NOT NULL)                            AS matched,
    -- The four counts above are workload-containers, which is the unit the
    -- match states partition and therefore the denominator under every
    -- vulnerability figure on the page. Pods is reported alongside so the
    -- reader can tell a 40-replica Deployment from 40 distinct services; it is
    -- a second figure, never a substitute for the denominator.
    COALESCE(SUM(w.pod_count), 0)::bigint                               AS pods
FROM cluster_workload w
JOIN cluster c ON c.id = w.cluster_id
LEFT JOIN LATERAL (
    SELECT s2.id
    FROM sbom s2
    WHERE w.image_digest IS NOT NULL
      AND (s2.digest = w.image_digest OR s2.index_digest = w.image_digest)
    LIMIT 1
) s ON true
WHERE w.cluster_id = $1
  AND c.namespace_id IN (SELECT visible_namespace_ids($2::uuid, $3::boolean))
`

type GetClusterWorkloadCoverageParams struct {
	ClusterID pgtype.UUID `json:"cluster_id"`
	UserID    pgtype.UUID `json:"user_id"`
	IsAdmin   pgtype.Bool `json:"is_admin"`
}

type GetClusterWorkloadCoverageRow struct {
	Total        int64 `json:"total"`
	Unresolvable int64 `json:"unresolvable"`
	Unknown      int64 `json:"unknown"`
	Matched      int64 `json:"matched"`
	Pods         int64 `json:"pods"`
}

// The counts that must accompany any vulnerability figure reported over running
// workloads (ADR-044 K5). Without these, "3 criticals running" is misleadingly
// reassuring — it silently omits every workload OCIDex could not match.
func (q *Queries) GetClusterWorkloadCoverage(ctx context.Context, arg GetClusterWorkloadCoverageParams) (GetClusterWorkloadCoverageRow, error) {
	row := q.db.QueryRow(ctx, getClusterWorkloadCoverage, arg.ClusterID, arg.UserID, arg.IsAdmin)
	var i GetClusterWorkloadCoverageRow
	err := row.Scan(
		&i.Total,
		&i.Unresolvable,
		&i.Unknown,
		&i.Matched,
		&i.Pods,
	)
	return i, err
}

const listClusterK8sNamespaces = `-- name: ListClusterK8sNamespaces :many
SELECT
    w.k8s_namespace,
    COUNT(*)::bigint AS workload_count
FROM cluster_workload w
JOIN cluster c ON c.id = w.cluster_id
WHERE w.cluster_id = $1
  AND c.namespace_id IN (SELECT visible_namespace_ids($2::uuid, $3::boolean))
GROUP BY w.k8s_namespace
ORDER BY w.k8s_namespace ASC
`

type ListClusterK8sNamespacesParams struct {
	ClusterID pgtype.UUID `json:"cluster_id"`
	UserID    pgtype.UUID `json:"user_id"`
	IsAdmin   pgtype.Bool `json:"is_admin"`
}

type ListClusterK8sNamespacesRow struct {
	K8sNamespace  string `json:"k8s_namespace"`
	WorkloadCount int64  `json:"workload_count"`
}

// The namespace facet for the workload filter. It exists because the list is
// paginated: the set of namespaces present in the cluster is not derivable from
// one page of rows, and a filter that only offers the values on the current page
// silently hides the rest of the cluster.
func (q *Queries) ListClusterK8sNamespaces(ctx context.Context, arg ListClusterK8sNamespacesParams) ([]ListClusterK8sNamespacesRow, error) {
	rows, err := q.db.Query(ctx, listClusterK8sNamespaces, arg.ClusterID, arg.UserID, arg.IsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClusterK8sNamespacesRow{}
	for rows.Next() {
		var i ListClusterK8sNamespacesRow
		if err := rows.Scan(&i.K8sNamespace, &i.WorkloadCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClusterRunningVulns = `-- name: ListClusterRunningVulns :many
WITH running AS (
    SELECT
        COALESCE(NULLIF(v.canonical_id, ''), v.id) AS canonical_id,
        w.id                                       AS workload_id
    FROM cluster_workload w
    JOIN cluster c ON c.id = w.cluster_id
    JOIN LATERAL (
        SELECT s2.id
        FROM sbom s2
        WHERE w.image_digest IS NOT NULL
          AND (s2.digest = w.image_digest OR s2.index_digest = w.image_digest)
        ORDER BY (s2.digest = w.image_digest) DESC, s2.created_at DESC
        LIMIT 1
    ) s ON true
    JOIN component comp ON comp.sbom_id = s.id AND comp.purl IS NOT NULL
    JOIN package_vulnerability pv ON pv.purl = comp.purl
    JOIN vulnerability v ON v.id = pv.vulnerability_id
    WHERE w.cluster_id = $1
      AND c.namespace_id IN (SELECT visible_namespace_ids($7::uuid, $8::boolean))
),
counts AS (
    SELECT canonical_id, COUNT(DISTINCT workload_id)::bigint AS workload_count
    FROM running
    GROUP BY canonical_id
),
canonical AS (
    SELECT DISTINCT ON (COALESCE(NULLIF(v.canonical_id, ''), v.id))
        v.id,
        COALESCE(NULLIF(v.canonical_id, ''), v.id) AS canonical_id,
        v.severity,
        v.cvss_score,
        v.summary
    FROM vulnerability v
    WHERE COALESCE(NULLIF(v.canonical_id, ''), v.id) IN (SELECT canonical_id FROM counts)
    ORDER BY
        COALESCE(NULLIF(v.canonical_id, ''), v.id),
        CASE v.severity
            WHEN 'CRITICAL' THEN 4
            WHEN 'HIGH'     THEN 3
            WHEN 'MEDIUM'   THEN 2
            WHEN 'LOW'      THEN 1
            ELSE 0
        END DESC,
        v.cvss_score DESC NULLS LAST
)
SELECT
    cv.id,
    cv.canonical_id,
    cv.severity,
    cv.cvss_score,
    cv.summary,
    k.workload_count
FROM canonical cv
JOIN counts k ON k.canonical_id = cv.canonical_id
WHERE ($2::text IS NULL OR cv.severity = $2::text)
ORDER BY
    CASE $3::text
        WHEN 'cvss_score'     THEN cv.cvss_score::float8
        WHEN 'workload_count' THEN k.workload_count::float8
        WHEN 'severity'       THEN (CASE cv.severity
                                        WHEN 'CRITICAL' THEN 4
                                        WHEN 'HIGH'     THEN 3
                                        WHEN 'MEDIUM'   THEN 2
                                        WHEN 'LOW'      THEN 1
                                        ELSE 0
                                    END)::float8
    END * CASE $4::text WHEN 'asc' THEN 1 ELSE -1 END ASC NULLS LAST,
    CASE WHEN $3::text = 'canonical_id' AND $4::text = 'asc'  THEN cv.canonical_id END ASC  NULLS LAST,
    CASE WHEN $3::text = 'canonical_id' AND $4::text = 'desc' THEN cv.canonical_id END DESC NULLS LAST,
    -- Severity then CVSS remain the tiebreakers, which keeps the default
    -- ordering byte-identical to the hardcoded one this replaced.
    CASE cv.severity
        WHEN 'CRITICAL' THEN 4
        WHEN 'HIGH'     THEN 3
        WHEN 'MEDIUM'   THEN 2
        WHEN 'LOW'      THEN 1
        ELSE 0
    END DESC,
    cv.cvss_score DESC NULLS LAST,
    cv.canonical_id ASC
LIMIT $6::int OFFSET $5::int
`

type ListClusterRunningVulnsParams struct {
	ClusterID pgtype.UUID `json:"cluster_id"`
	Severity  pgtype.Text `json:"severity"`
	SortBy    string      `json:"sort_by"`
	SortDir   string      `json:"sort_dir"`
	Offset    pgtype.Int4 `json:"offset"`
	Limit     pgtype.Int4 `json:"limit"`
	UserID    pgtype.UUID `json:"user_id"`
	IsAdmin   pgtype.Bool `json:"is_admin"`
}

type ListClusterRunningVulnsRow struct {
	ID            string        `json:"id"`
	CanonicalID   string        `json:"canonical_id"`
	Severity      pgtype.Text   `json:"severity"`
	CvssScore     pgtype.Float4 `json:"cvss_score"`
	Summary       pgtype.Text   `json:"summary"`
	WorkloadCount int64         `json:"workload_count"`
}

// Vulnerabilities scoped to images actually running in one cluster — the view
// the whole epic exists for.
//
// Rows are keyed by canonical_id, not by vulnerability.id: OSV publishes the
// same finding under several native ids (GO-… and GHSA-… both aliasing one
// CVE), and listing each of them separately would report one problem three
// times. The representative row is the highest-severity member of the alias
// group, which is also the one the UI links to.
//
// Workloads are counted DISTINCT across the whole alias group, so "affects 3
// running workloads" is a number a user can act on rather than a count of
// component rows.
//
// Read alongside GetClusterWorkloadCoverage, never alone.
// Sorting is parameterised for the same reason as ListTopVulnerabilities: the
// list is server-paginated, so reordering the rows on the current page would
// claim a ranking the other pages do not share.
func (q *Queries) ListClusterRunningVulns(ctx context.Context, arg ListClusterRunningVulnsParams) ([]ListClusterRunningVulnsRow, error) {
	rows, err := q.db.Query(ctx, listClusterRunningVulns,
		arg.ClusterID,
		arg.Severity,
		arg.SortBy,
		arg.SortDir,
		arg.Offset,
		arg.Limit,
		arg.UserID,
		arg.IsAdmin,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClusterRunningVulnsRow{}
	for rows.Next() {
		var i ListClusterRunningVulnsRow
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalID,
			&i.Severity,
			&i.CvssScore,
			&i.Summary,
			&i.WorkloadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClusterUnknownImages = `-- name: ListClusterUnknownImages :many
SELECT
    w.image_ref,
    w.image_digest::text                     AS image_digest,
    COUNT(*)::bigint                         AS workload_count,
    SUM(w.pod_count)::bigint                 AS pod_count,
    MIN(w.k8s_namespace)::text               AS sample_k8s_namespace,
    MIN(w.workload_name)::text               AS sample_workload_name,
    MAX(w.last_seen_at)::timestamptz         AS last_seen_at
FROM cluster_workload w
JOIN cluster c ON c.id = w.cluster_id
LEFT JOIN LATERAL (
    SELECT s2.id
    FROM sbom s2
    WHERE (s2.digest = w.image_digest OR s2.index_digest = w.image_digest)
    LIMIT 1
) s ON true
WHERE w.cluster_id = $1
  AND w.image_digest IS NOT NULL
  AND s.id IS NULL
  AND c.namespace_id IN (SELECT visible_namespace_ids($2::uuid, $3::boolean))
GROUP BY w.image_ref, w.image_digest
ORDER BY COUNT(*) DESC, w.image_ref ASC
LIMIT $4::int
`

type ListClusterUnknownImagesParams struct {
	ClusterID pgtype.UUID `json:"cluster_id"`
	UserID    pgtype.UUID `json:"user_id"`
	IsAdmin   pgtype.Bool `json:"is_admin"`
	Limit     pgtype.Int4 `json:"limit"`
}

type ListClusterUnknownImagesRow struct {
	ImageRef           string             `json:"image_ref"`
	ImageDigest        string             `json:"image_digest"`
	WorkloadCount      int64              `json:"workload_count"`
	PodCount           int64              `json:"pod_count"`
	SampleK8sNamespace string             `json:"sample_k8s_namespace"`
	SampleWorkloadName string             `json:"sample_workload_name"`
	LastSeenAt         pgtype.Timestamptz `json:"last_seen_at"`
}

// The No-SBOM gap, grouped by image rather than by container.
//
// The workload table lists containers, but the remedy is per image: twelve
// replicas of one unscanned image are one thing to ingest, not twelve. Grouping
// here rather than in the browser also means the count is the whole cluster's,
// not the current page's.
//
// Only rows with a readable digest are included. A NULL digest is the
// 'unresolvable' state, which no amount of ingesting will fix, and folding the
// two together would offer an action that cannot work (ADR-044 K3/K5).
func (q *Queries) ListClusterUnknownImages(ctx context.Context, arg ListClusterUnknownImagesParams) ([]ListClusterUnknownImagesRow, error) {
	rows, err := q.db.Query(ctx, listClusterUnknownImages,
		arg.ClusterID,
		arg.UserID,
		arg.IsAdmin,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClusterUnknownImagesRow{}
	for rows.Next() {
		var i ListClusterUnknownImagesRow
		if err := rows.Scan(
			&i.ImageRef,
			&i.ImageDigest,
			&i.WorkloadCount,
			&i.PodCount,
			&i.SampleK8sNamespace,
			&i.SampleWorkloadName,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClusterWorkloads = `-- name: ListClusterWorkloads :many
SELECT
    w.id, w.cluster_id, w.k8s_namespace, w.workload_kind, w.workload_name, w.container_name, w.image_ref, w.image_digest, w.pod_count, w.first_seen_at, w.last_seen_at,
    s.id            AS sbom_id,
    s.artifact_id   AS artifact_id,
    s.subject_version AS subject_version,
    a.name          AS artifact_name,
    a.type          AS artifact_type,
    ms.state        AS match_state,
    COALESCE(vs.critical, 0)::bigint AS critical_count,
    COALESCE(vs.high, 0)::bigint     AS high_count,
    COALESCE(vs.medium, 0)::bigint   AS medium_count,
    COALESCE(vs.low, 0)::bigint      AS low_count
FROM cluster_workload w
JOIN cluster c ON c.id = w.cluster_id
LEFT JOIN LATERAL (
    SELECT s2.id, s2.artifact_id, s2.subject_version, s2.digest
    FROM sbom s2
    WHERE w.image_digest IS NOT NULL
      AND (s2.digest = w.image_digest OR s2.index_digest = w.image_digest)
    ORDER BY (s2.digest = w.image_digest) DESC, s2.created_at DESC
    LIMIT 1
) s ON true
LEFT JOIN artifact a ON a.id = s.artifact_id
CROSS JOIN LATERAL (
    SELECT (CASE WHEN s.id IS NOT NULL AND s.digest = w.image_digest THEN 'exact'
                 WHEN s.id IS NOT NULL                               THEN 'index'
                 WHEN w.image_digest IS NULL                         THEN 'unresolvable'
                 ELSE                                                     'unknown'
            END)::text AS state
) ms
LEFT JOIN LATERAL (
    SELECT
        COUNT(DISTINCT COALESCE(NULLIF(v.canonical_id, ''), v.id))
            FILTER (WHERE v.severity = 'CRITICAL')::bigint AS critical,
        COUNT(DISTINCT COALESCE(NULLIF(v.canonical_id, ''), v.id))
            FILTER (WHERE v.severity = 'HIGH')::bigint     AS high,
        COUNT(DISTINCT COALESCE(NULLIF(v.canonical_id, ''), v.id))
            FILTER (WHERE v.severity = 'MEDIUM')::bigint   AS medium,
        COUNT(DISTINCT COALESCE(NULLIF(v.canonical_id, ''), v.id))
            FILTER (WHERE v.severity = 'LOW')::bigint      AS low
    FROM (SELECT DISTINCT purl FROM component WHERE sbom_id = s.id AND purl IS NOT NULL) comp
    JOIN package_vulnerability pv ON pv.purl = comp.purl
    JOIN vulnerability v ON v.id = pv.vulnerability_id
) vs ON s.id IS NOT NULL
WHERE w.cluster_id = $1
  AND c.namespace_id IN (SELECT visible_namespace_ids($2::uuid, $3::boolean))
  AND ($4::text IS NULL OR w.k8s_namespace = $4::text)
  AND ($5::text IS NULL OR ms.state = $5::text)
  AND ($6::text IS NULL OR (
        w.workload_name  ILIKE '%' || $6::text || '%'
     OR w.container_name ILIKE '%' || $6::text || '%'
     OR w.image_ref      ILIKE '%' || $6::text || '%'))
ORDER BY
    -- Numeric keys share one term; the direction flips the sign.
    CASE $7::text
        WHEN 'pod_count'    THEN w.pod_count::float8
        WHEN 'last_seen_at' THEN EXTRACT(EPOCH FROM w.last_seen_at)::float8
        -- Severity counts packed into one number, most severe most
        -- significant, so "worst first" is one sort rather than four. NULL
        -- (never assessed) stays NULL and sorts last in both directions —
        -- an unassessed workload must not rank alongside a clean one.
        WHEN 'vuln_count'   THEN (vs.critical * 1000000 + vs.high * 1000 + vs.medium)::float8
    END * CASE $8::text WHEN 'asc' THEN 1 ELSE -1 END ASC NULLS LAST,
    -- Text keys can't ride the sign trick, but they can share one nested CASE
    -- per direction instead of two terms per key.
    CASE WHEN $8::text = 'asc' THEN
        CASE $7::text
            WHEN 'k8s_namespace'  THEN w.k8s_namespace
            WHEN 'workload_name'  THEN w.workload_name
            WHEN 'container_name' THEN w.container_name
            WHEN 'image_ref'      THEN w.image_ref
            WHEN 'match_state'    THEN ms.state
        END
    END ASC NULLS LAST,
    CASE WHEN $8::text = 'desc' THEN
        CASE $7::text
            WHEN 'k8s_namespace'  THEN w.k8s_namespace
            WHEN 'workload_name'  THEN w.workload_name
            WHEN 'container_name' THEN w.container_name
            WHEN 'image_ref'      THEN w.image_ref
            WHEN 'match_state'    THEN ms.state
        END
    END DESC NULLS LAST,
    -- The default ordering, and the tiebreaker under every other key: without
    -- a total order, two pages of an offset-paginated list can repeat a row.
    w.k8s_namespace ASC, w.workload_name ASC, w.container_name ASC
LIMIT $10::int OFFSET $9::int
`

type ListClusterWorkloadsParams struct {
	ClusterID    pgtype.UUID `json:"cluster_id"`
	UserID       pgtype.UUID `json:"user_id"`
	IsAdmin      pgtype.Bool `json:"is_admin"`
	K8sNamespace pgtype.Text `json:"k8s_namespace"`
	MatchState   pgtype.Text `json:"match_state"`
	Q            pgtype.Text `json:"q"`
	SortBy       string      `json:"sort_by"`
	SortDir      string      `json:"sort_dir"`
	Offset       pgtype.Int4 `json:"offset"`
	Limit        pgtype.Int4 `json:"limit"`
}

type ListClusterWorkloadsRow struct {
	ClusterWorkload ClusterWorkload `json:"cluster_workload"`
	SbomID          pgtype.UUID     `json:"sbom_id"`
	ArtifactID      pgtype.UUID     `json:"artifact_id"`
	SubjectVersion  pgtype.Text     `json:"subject_version"`
	ArtifactName    pgtype.Text     `json:"artifact_name"`
	ArtifactType    pgtype.Text     `json:"artifact_type"`
	MatchState      string          `json:"match_state"`
	CriticalCount   int64           `json:"critical_count"`
	HighCount       int64           `json:"high_count"`
	MediumCount     int64           `json:"medium_count"`
	LowCount        int64           `json:"low_count"`
}

// The payoff join (ADR-044 K4/K5). match_state is a single NOT NULL enum-ish
// column carrying all four outcomes:
//
//	'exact'        — image_digest = sbom.digest, a per-platform match.
//	'index'        — image_digest = sbom.index_digest, i.e. the workload runs
//	                 some platform of a scanned multi-arch image. One-to-many by
//	                 nature, so the newest such SBOM is chosen deterministically.
//	'unknown'      — a valid digest matching no ingested SBOM: a coverage gap.
//	'unresolvable' — no digest could be read from imageID: an agent/runtime gap.
//
// It is deliberately not a nullable match_tier. A NULL is trivially ignored by a
// caller, and the one thing this feature must never do is let a workload with no
// SBOM render the same as a matched workload with zero vulnerabilities (K5).
// Making the state non-null means every consumer has to name the case.
//
// The state is computed in a LATERAL rather than inline so the projection and
// the match_state filter below read the same expression. Two copies of a CASE
// this load-bearing would eventually disagree, and a filter that disagreed with
// the column it filters is invisible until someone counts the rows.
//
// Visibility is enforced here, not by the caller: the cluster's namespace must
// be visible. The matched SBOM is NOT re-filtered — a workload's own cluster
// being visible is the authorization for seeing what it runs, and hiding the
// match would report a coverage gap that does not exist.
// Per-severity finding counts for the matched SBOM, so "which images have
// vulnerabilities" is answerable from the table instead of by fanning out one
// request per row from the browser. Counts distinct canonical_ids, matching
// GetSBOMVulnSummary, so an alias group is one finding here too.
//
// The join is LEFT ... ON s.id IS NOT NULL, so an unmatched workload produces
// no counts at all. They are projected through COALESCE only because a NULL
// bigint out of a lateral aggregate is not something sqlc can type; the
// zero it yields for an unmatched row is not a finding count and must never be
// read as one. match_state is the column that says which, and it is non-null
// precisely so every consumer has to name the case (K5) — the service layer
// drops the counts entirely for a workload that never matched.
//
// The sort term below reads vs.* directly rather than the coalesced projection,
// so an unassessed workload sorts last in both directions instead of ranking
// alongside a clean one.
// Sorting is parameterised because the list is server-paginated: reordering
// only the rows that happen to be on the current page would misrepresent the
// whole cluster (same argument as ListTopVulnerabilities).
func (q *Queries) ListClusterWorkloads(ctx context.Context, arg ListClusterWorkloadsParams) ([]ListClusterWorkloadsRow, error) {
	rows, err := q.db.Query(ctx, listClusterWorkloads,
		arg.ClusterID,
		arg.UserID,
		arg.IsAdmin,
		arg.K8sNamespace,
		arg.MatchState,
		arg.Q,
		arg.SortBy,
		arg.SortDir,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClusterWorkloadsRow{}
	for rows.Next() {
		var i ListClusterWorkloadsRow
		if err := rows.Scan(
			&i.ClusterWorkload.ID,
			&i.ClusterWorkload.ClusterID,
			&i.ClusterWorkload.K8sNamespace,
			&i.ClusterWorkload.WorkloadKind,
			&i.ClusterWorkload.WorkloadName,
			&i.ClusterWorkload.ContainerName,
			&i.ClusterWorkload.ImageRef,
			&i.ClusterWorkload.ImageDigest,
			&i.ClusterWorkload.PodCount,
			&i.ClusterWorkload.FirstSeenAt,
			&i.ClusterWorkload.LastSeenAt,
			&i.SbomID,
			&i.ArtifactID,
			&i.SubjectVersion,
			&i.ArtifactName,
			&i.ArtifactType,
			&i.MatchState,
			&i.CriticalCount,
			&i.HighCount,
			&i.MediumCount,
			&i.LowCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClusters = `-- name: ListClusters :many
SELECT c.id, c.namespace_id, c.name, c.description, c.last_seen_at, c.created_at, c.updated_at, c.auto_ingest, n.name AS namespace_name, n.owner_id, n.visibility
FROM cluster c
JOIN namespace n ON n.id = c.namespace_id
WHERE (
    CASE WHEN COALESCE($1::boolean, false)
         THEN n.owner_id = $2::uuid
         ELSE $3::boolean = true
              OR n.visibility = 'public'
              OR ($2::uuid IS NOT NULL AND n.owner_id = $2::uuid)
    END
)
ORDER BY c.created_at ASC
`

type ListClustersParams struct {
	OwnedOnly pgtype.Bool `json:"owned_only"`
	UserID    pgtype.UUID `json:"user_id"`
	IsAdmin   pgtype.Bool `json:"is_admin"`
}

type ListClustersRow struct {
	Cluster       Cluster     `json:"cluster"`
	NamespaceName string      `json:"namespace_name"`
	OwnerID       pgtype.UUID `json:"owner_id"`
	Visibility    string      `json:"visibility"`
}

// Visibility resolved through the owning namespace; owned_only switches to the
// ownership path. Same two-paths-one-query shape as ListSources and
// ListNamespaces — see ListNamespaces for why they are not split.
func (q *Queries) ListClusters(ctx context.Context, arg ListClustersParams) ([]ListClustersRow, error) {
	rows, err := q.db.Query(ctx, listClusters, arg.OwnedOnly, arg.UserID, arg.IsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClustersRow{}
	for rows.Next() {
		var i ListClustersRow
		if err := rows.Scan(
			&i.Cluster.ID,
			&i.Cluster.NamespaceID,
			&i.Cluster.Name,
			&i.Cluster.Description,
			&i.Cluster.LastSeenAt,
			&i.Cluster.CreatedAt,
			&i.Cluster.UpdatedAt,
			&i.Cluster.AutoIngest,
			&i.NamespaceName,
			&i.OwnerID,
			&i.Visibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClustersByNamespace = `-- name: ListClustersByNamespace :many
SELECT id, namespace_id, name, description, last_seen_at, created_at, updated_at, auto_ingest FROM cluster WHERE namespace_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListClustersByNamespace(ctx context.Context, namespaceID pgtype.UUID) ([]Cluster, error) {
	rows, err := q.db.Query(ctx, listClustersByNamespace, namespaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cluster{}
	for rows.Next() {
		var i Cluster
		if err := rows.Scan(
			&i.ID,
			&i.NamespaceID,
			&i.Name,
			&i.Description,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AutoIngest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkloadsForVulnerability = `-- name: ListWorkloadsForVulnerability :many
SELECT
    w.id, w.cluster_id, w.k8s_namespace, w.workload_kind, w.workload_name, w.container_name, w.image_ref, w.image_digest, w.pod_count, w.first_seen_at, w.last_seen_at,
    c.id            AS cluster_id_out,
    c.name          AS cluster_name,
    s.id            AS sbom_id,
    s.artifact_id   AS artifact_id,
    s.subject_version AS subject_version,
    a.name          AS artifact_name,
    -- Matched by construction here (the LATERAL join is inner), but which tier
    -- still has to be reported: an index match means the running platform is
    -- unknown, and a caller must be able to say so rather than imply an exact
    -- per-platform match it does not have (ADR-044 K4).
    (CASE WHEN s.digest = w.image_digest THEN 'exact' ELSE 'index' END)::text AS match_state
FROM cluster_workload w
JOIN cluster c ON c.id = w.cluster_id
JOIN LATERAL (
    SELECT s2.id, s2.artifact_id, s2.subject_version, s2.digest
    FROM sbom s2
    WHERE w.image_digest IS NOT NULL
      AND (s2.digest = w.image_digest OR s2.index_digest = w.image_digest)
    ORDER BY (s2.digest = w.image_digest) DESC, s2.created_at DESC
    LIMIT 1
) s ON true
LEFT JOIN artifact a ON a.id = s.artifact_id
WHERE EXISTS (
    SELECT 1
    FROM component comp
    JOIN package_vulnerability pv ON pv.purl = comp.purl
    JOIN vulnerability v ON v.id = pv.vulnerability_id
    WHERE comp.sbom_id = s.id
      AND comp.purl IS NOT NULL
      AND COALESCE(NULLIF(v.canonical_id, ''), v.id) = $1::text
)
  AND ($2::uuid IS NULL OR w.cluster_id = $2::uuid)
  AND c.namespace_id IN (SELECT visible_namespace_ids($3::uuid, $4::boolean))
ORDER BY c.name ASC, w.k8s_namespace ASC, w.workload_name ASC
LIMIT $5::int
`

type ListWorkloadsForVulnerabilityParams struct {
	CanonicalID string      `json:"canonical_id"`
	ClusterID   pgtype.UUID `json:"cluster_id"`
	UserID      pgtype.UUID `json:"user_id"`
	IsAdmin     pgtype.Bool `json:"is_admin"`
	Limit       pgtype.Int4 `json:"limit"`
}

type ListWorkloadsForVulnerabilityRow struct {
	ClusterWorkload ClusterWorkload `json:"cluster_workload"`
	ClusterIDOut    pgtype.UUID     `json:"cluster_id_out"`
	ClusterName     string          `json:"cluster_name"`
	SbomID          pgtype.UUID     `json:"sbom_id"`
	ArtifactID      pgtype.UUID     `json:"artifact_id"`
	SubjectVersion  pgtype.Text     `json:"subject_version"`
	ArtifactName    pgtype.Text     `json:"artifact_name"`
	MatchState      string          `json:"match_state"`
}

// The reverse of ListClusterRunningVulns: given a vulnerability, which running
// workloads carry it. "These three Deployments have CVE-X" in one query.
//
// Keyed by canonical_id rather than vulnerability.id for two reasons: it is
// what travels in the URL (/vulns/{canonical}/workloads), and matching the id
// alone would miss workloads affected through a sibling alias record.
//
// cluster_id is optional. Passed, this is the cluster page's drill-down; NULL,
// it answers "where is this CVE running anywhere I can see", which is the
// question the catalogue's vulnerability page cannot otherwise answer.
func (q *Queries) ListWorkloadsForVulnerability(ctx context.Context, arg ListWorkloadsForVulnerabilityParams) ([]ListWorkloadsForVulnerabilityRow, error) {
	rows, err := q.db.Query(ctx, listWorkloadsForVulnerability,
		arg.CanonicalID,
		arg.ClusterID,
		arg.UserID,
		arg.IsAdmin,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkloadsForVulnerabilityRow{}
	for rows.Next() {
		var i ListWorkloadsForVulnerabilityRow
		if err := rows.Scan(
			&i.ClusterWorkload.ID,
			&i.ClusterWorkload.ClusterID,
			&i.ClusterWorkload.K8sNamespace,
			&i.ClusterWorkload.WorkloadKind,
			&i.ClusterWorkload.WorkloadName,
			&i.ClusterWorkload.ContainerName,
			&i.ClusterWorkload.ImageRef,
			&i.ClusterWorkload.ImageDigest,
			&i.ClusterWorkload.PodCount,
			&i.ClusterWorkload.FirstSeenAt,
			&i.ClusterWorkload.LastSeenAt,
			&i.ClusterIDOut,
			&i.ClusterName,
			&i.SbomID,
			&i.ArtifactID,
			&i.SubjectVersion,
			&i.ArtifactName,
			&i.MatchState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneClusterWorkloads = `-- name: PruneClusterWorkloads :execrows
DELETE FROM cluster_workload
WHERE cluster_id = $1 AND last_seen_at < $2
`

type PruneClusterWorkloadsParams struct {
	ClusterID  pgtype.UUID        `json:"cluster_id"`
	ObservedAt pgtype.Timestamptz `json:"observed_at"`
}

// The second half of full-snapshot semantics (ADR-044 K7). Every row the
// snapshot touched carries the snapshot's observed_at; anything older was not
// reported and is therefore no longer running.
//
// Strictly `<`, not `<>`: a concurrent later snapshot must not have its rows
// deleted by an older one still committing.
func (q *Queries) PruneClusterWorkloads(ctx context.Context, arg PruneClusterWorkloadsParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneClusterWorkloads, arg.ClusterID, arg.ObservedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchClusterLastSeen = `-- name: TouchClusterLastSeen :exec
UPDATE cluster SET last_seen_at = $2, updated_at = now() WHERE id = $1
`

type TouchClusterLastSeenParams struct {
	ID         pgtype.UUID        `json:"id"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

// Stamped once per accepted snapshot, inside the ingest transaction. This is
// what makes "dead agent" distinguishable from "empty cluster" (ADR-044 K2).
func (q *Queries) TouchClusterLastSeen(ctx context.Context, arg TouchClusterLastSeenParams) error {
	_, err := q.db.Exec(ctx, touchClusterLastSeen, arg.ID, arg.LastSeenAt)
	return err
}

const updateCluster = `-- name: UpdateCluster :one
UPDATE cluster
SET name        = $2,
    description = $3,
    auto_ingest = COALESCE($4::boolean, auto_ingest),
    updated_at  = now()
WHERE id = $1
RETURNING id, namespace_id, name, description, last_seen_at, created_at, updated_at, auto_ingest
`

type UpdateClusterParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	AutoIngest  pgtype.Bool `json:"auto_ingest"`
}

// auto_ingest is a narg rather than a plain column: a PATCH that only renames
// the cluster must not silently switch ingest off by omitting the field.
func (q *Queries) UpdateCluster(ctx context.Context, arg UpdateClusterParams) (Cluster, error) {
	row := q.db.QueryRow(ctx, updateCluster,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.AutoIngest,
	)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.Name,
		&i.Description,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoIngest,
	)
	return i, err
}

const upsertClusterWorkload = `-- name: UpsertClusterWorkload :exec
INSERT INTO cluster_workload (
    cluster_id, k8s_namespace, workload_kind, workload_name, container_name,
    image_ref, image_digest, pod_count, first_seen_at, last_seen_at
)
VALUES ($1, $2, $3, $4, $5, $6, $8::text, $7, $9, $9)
ON CONFLICT (cluster_id, k8s_namespace, workload_kind, workload_name, container_name, image_digest)
DO UPDATE SET
    image_ref    = EXCLUDED.image_ref,
    pod_count    = EXCLUDED.pod_count,
    last_seen_at = EXCLUDED.last_seen_at
`

type UpsertClusterWorkloadParams struct {
	ClusterID     pgtype.UUID        `json:"cluster_id"`
	K8sNamespace  string             `json:"k8s_namespace"`
	WorkloadKind  string             `json:"workload_kind"`
	WorkloadName  string             `json:"workload_name"`
	ContainerName string             `json:"container_name"`
	ImageRef      string             `json:"image_ref"`
	PodCount      int32              `json:"pod_count"`
	ImageDigest   pgtype.Text        `json:"image_digest"`
	ObservedAt    pgtype.Timestamptz `json:"observed_at"`
}

// One row of a snapshot. The conflict target is the full natural key including
// image_digest, so a rollout running two digests of one container yields two
// rows rather than one overwriting the other.
//
// first_seen_at is deliberately absent from the UPDATE set: it is the one field
// that must survive re-reporting, and "running since" is the only history this
// current-state table keeps.
func (q *Queries) UpsertClusterWorkload(ctx context.Context, arg UpsertClusterWorkloadParams) error {
	_, err := q.db.Exec(ctx, upsertClusterWorkload,
		arg.ClusterID,
		arg.K8sNamespace,
		arg.WorkloadKind,
		arg.WorkloadName,
		arg.ContainerName,
		arg.ImageRef,
		arg.PodCount,
		arg.ImageDigest,
		arg.ObservedAt,
	)
	return err
}
