// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discover.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDiscoverLicenseSpread = `-- name: GetDiscoverLicenseSpread :many
SELECT l.id,
       l.spdx_id,
       l.name,
       license_category(l.spdx_id)             AS category,
       COUNT(DISTINCT lr.identity_key)::bigint AS component_count
FROM license l
JOIN license_rollup lr
  ON lr.license_id = l.id
 AND lr.namespace_id IN (SELECT visible_namespace_ids(NULL::uuid, false))
GROUP BY l.id, l.spdx_id, l.name
ORDER BY component_count DESC, l.name
LIMIT $1::int
`

type GetDiscoverLicenseSpreadRow struct {
	ID             pgtype.UUID `json:"id"`
	SpdxID         pgtype.Text `json:"spdx_id"`
	Name           string      `json:"name"`
	Category       string      `json:"category"`
	ComponentCount int64       `json:"component_count"`
}

// License distribution across public content, by distinct package identity.
//
// Inner JOIN, unlike ListLicenses' LEFT JOIN: that list is a catalog of every
// license OCIDex knows and must show one with a zero count, whereas this is a
// distribution, and a zero-weight slice describes nothing.
func (q *Queries) GetDiscoverLicenseSpread(ctx context.Context, rowLimit int32) ([]GetDiscoverLicenseSpreadRow, error) {
	rows, err := q.db.Query(ctx, getDiscoverLicenseSpread, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDiscoverLicenseSpreadRow{}
	for rows.Next() {
		var i GetDiscoverLicenseSpreadRow
		if err := rows.Scan(
			&i.ID,
			&i.SpdxID,
			&i.Name,
			&i.Category,
			&i.ComponentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDiscoverRecentArtifacts = `-- name: GetDiscoverRecentArtifacts :many
WITH latest AS (
    SELECT DISTINCT ON (s.artifact_id)
           a.id   AS artifact_id,
           a.type,
           a.name,
           a.group_name,
           s.id   AS sbom_id,
           s.subject_version,
           s.digest,
           s.flavor,
           s.created_at
    FROM sbom s
    JOIN artifact a ON a.id = s.artifact_id
    WHERE s.namespace_id IN (SELECT visible_namespace_ids(NULL::uuid, false))
    ORDER BY s.artifact_id, s.created_at DESC, s.id DESC
)
SELECT artifact_id, type, name, group_name, sbom_id, subject_version, digest, flavor, created_at
FROM latest
ORDER BY created_at DESC, artifact_id
LIMIT $1::int
`

type GetDiscoverRecentArtifactsRow struct {
	ArtifactID     pgtype.UUID        `json:"artifact_id"`
	Type           string             `json:"type"`
	Name           string             `json:"name"`
	GroupName      pgtype.Text        `json:"group_name"`
	SbomID         pgtype.UUID        `json:"sbom_id"`
	SubjectVersion pgtype.Text        `json:"subject_version"`
	Digest         pgtype.Text        `json:"digest"`
	Flavor         pgtype.Text        `json:"flavor"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// Most recently updated public artifacts, one row per artifact.
//
// DISTINCT ON collapses to the newest SBOM per artifact, which forces its ORDER
// BY to lead with artifact_id; the outer select restores the ordering the page
// actually wants. Without the collapse, a single artifact re-scanned hourly
// would fill the whole list and the panel would report activity rather than
// breadth.
func (q *Queries) GetDiscoverRecentArtifacts(ctx context.Context, rowLimit int32) ([]GetDiscoverRecentArtifactsRow, error) {
	rows, err := q.db.Query(ctx, getDiscoverRecentArtifacts, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDiscoverRecentArtifactsRow{}
	for rows.Next() {
		var i GetDiscoverRecentArtifactsRow
		if err := rows.Scan(
			&i.ArtifactID,
			&i.Type,
			&i.Name,
			&i.GroupName,
			&i.SbomID,
			&i.SubjectVersion,
			&i.Digest,
			&i.Flavor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDiscoverTopArtifacts = `-- name: GetDiscoverTopArtifacts :many

WITH public_ns AS (
    SELECT visible_namespace_ids(NULL::uuid, false) AS id
),
public_sbom AS (
    SELECT s.id, s.artifact_id, s.subject_version, s.created_at
    FROM sbom s
    WHERE s.namespace_id IN (SELECT id FROM public_ns)
),
subject AS (
    -- Only artifacts with at least one public SBOM are candidates: the JOIN is
    -- inner, so an artifact whose SBOMs are all private is not merely scored
    -- zero, it is absent.
    SELECT a.id,
           a.type,
           a.name,
           a.group_name,
           a.purl,
           CASE WHEN a.purl IS NULL THEN NULL
                ELSE split_part(split_part(a.purl, '?', 1), '@', 1)
           END                                                   AS purl_base,
           COUNT(DISTINCT COALESCE(ps.subject_version, ''))::bigint AS version_count,
           COUNT(DISTINCT ps.id)::bigint                         AS sbom_count,
           MAX(ps.created_at)::timestamptz                       AS last_seen_at
    FROM artifact a
    JOIN public_sbom ps ON ps.artifact_id = a.id
    GROUP BY a.id, a.type, a.name, a.group_name, a.purl
),
usage_purl AS (
    SELECT sub.id AS artifact_id, ps.id AS sbom_id
    FROM subject sub
    JOIN component c
      ON c.purl IS NOT NULL
     AND split_part(split_part(c.purl, '?', 1), '@', 1) = sub.purl_base
    JOIN public_sbom ps ON ps.id = c.sbom_id AND ps.artifact_id <> sub.id
    WHERE sub.purl_base IS NOT NULL
),
usage_tuple AS (
    SELECT sub.id AS artifact_id, ps.id AS sbom_id
    FROM subject sub
    JOIN component c
      ON c.purl IS NULL
     AND c.type = sub.type
     AND c.name = sub.name
     AND COALESCE(c.group_name, '') = COALESCE(sub.group_name, '')
    JOIN public_sbom ps ON ps.id = c.sbom_id AND ps.artifact_id <> sub.id
    WHERE sub.purl_base IS NULL
),
usage AS (
    SELECT m.artifact_id, COUNT(DISTINCT m.sbom_id)::bigint AS usage_count
    FROM (
        SELECT artifact_id, sbom_id FROM usage_purl
        UNION ALL
        SELECT artifact_id, sbom_id FROM usage_tuple
    ) m
    GROUP BY m.artifact_id
)
SELECT sub.id                                AS artifact_id,
       sub.type,
       sub.name,
       sub.group_name,
       sub.purl,
       COALESCE(u.usage_count, 0)::bigint    AS usage_count,
       sub.version_count,
       sub.sbom_count,
       sub.last_seen_at,
       discovery_score(COALESCE(u.usage_count, 0), sub.version_count, sub.last_seen_at)::float8 AS score
FROM subject sub
LEFT JOIN usage u ON u.artifact_id = sub.id
ORDER BY score DESC, sub.name, sub.id
LIMIT $1::int
`

type GetDiscoverTopArtifactsRow struct {
	ArtifactID   pgtype.UUID        `json:"artifact_id"`
	Type         string             `json:"type"`
	Name         string             `json:"name"`
	GroupName    pgtype.Text        `json:"group_name"`
	Purl         pgtype.Text        `json:"purl"`
	UsageCount   int64              `json:"usage_count"`
	VersionCount int64              `json:"version_count"`
	SbomCount    int64              `json:"sbom_count"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
	Score        float64            `json:"score"`
}

// Public discovery queries (ocidex-q1z7.1).
//
// Every query here feeds an anonymous, edge-cacheable surface, so all four are
// scoped to PUBLIC namespaces only — and they express that scope the same way,
// by testing namespace_id against visible_namespace_ids(NULL, false).
//
// That call reduces to `visibility = public`, because the
// admin term is false and nobody is a member of anything as nobody. Reusing the
// function rather than writing `n.visibility = 'public'` inline keeps one
// definition of visibility in the database, so a future change to the rule
// cannot leave the discovery surface behind on the old one.
//
// None of these take a viewer parameter, and that is deliberate. The response is
// identical for every caller, which is what makes it cacheable at the edge; it
// also means there is no code path by which a viewer's own private data could
// widen an aggregate that anonymous visitors read back.
//
// The aggregates are expensive by nature (they rank the whole public catalog).
// They are computed by the stats warmer out of band, never on a request path.
// Artifacts ranked by discovery_score: usage breadth, version breadth, recency.
//
// usage_count is the ADR-041 "usages" relation counted rather than listed — how
// many *other* artifacts' SBOMs contain a component matching this artifact. The
// match is the same coarse one ListArtifactUsages does (purl base via
// idx_component_purl_base, or the (type, name, group) tuple for purl-less rows),
// and it is a superset for the same reason: identity qualifiers are settled in
// Go by componentKey(). A count does not need that exactness — the ranking is
// ordinal, and an over-count of a few qualifier variants cannot reorder a
// log-damped score — so the Go pass is skipped here rather than pulling every
// matching component row into the service to be filtered and thrown away.
//
// The two match branches are separate CTEs unioned, not one predicate with OR.
// An OR across two relations cannot be planned as a hash join, so the combined
// form degrades to a nested loop over the component table; split, each branch is
// a clean join against its own index.
func (q *Queries) GetDiscoverTopArtifacts(ctx context.Context, rowLimit int32) ([]GetDiscoverTopArtifactsRow, error) {
	rows, err := q.db.Query(ctx, getDiscoverTopArtifacts, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDiscoverTopArtifactsRow{}
	for rows.Next() {
		var i GetDiscoverTopArtifactsRow
		if err := rows.Scan(
			&i.ArtifactID,
			&i.Type,
			&i.Name,
			&i.GroupName,
			&i.Purl,
			&i.UsageCount,
			&i.VersionCount,
			&i.SbomCount,
			&i.LastSeenAt,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDiscoverTopVulnerabilities = `-- name: GetDiscoverTopVulnerabilities :many
WITH public_ns AS (
    SELECT visible_namespace_ids(NULL::uuid, false) AS id
),
canonical AS (
    -- Collapse aliased OSV records (GO-xxxx + GHSA-yyyy) to one row per
    -- real-world vulnerability, preferring the alias that carries a severity.
    SELECT DISTINCT ON (canonical_id)
           id, canonical_id, severity, cvss_score, summary, published_at
    FROM vulnerability
    WHERE canonical_id <> ''
    ORDER BY canonical_id,
             CASE WHEN severity IS NOT NULL AND severity NOT IN ('UNKNOWN') THEN 0 ELSE 1 END,
             modified_at DESC NULLS LAST
),
candidate AS (
    SELECT vr.canonical_id,
           COALESCE(SUM(vr.sbom_count) FILTER (WHERE COALESCE(p.ord, 1) = 1), 0)::bigint AS affected_sbom_count,
           COALESCE(array_agg(DISTINCT p.purl) FILTER (WHERE p.purl IS NOT NULL), '{}')::text[] AS purls
    FROM vuln_rollup vr
    LEFT JOIN LATERAL unnest(vr.purls) WITH ORDINALITY AS p(purl, ord) ON true
    WHERE vr.namespace_id IN (SELECT id FROM public_ns)
    GROUP BY vr.canonical_id
    ORDER BY affected_sbom_count DESC, vr.canonical_id
    LIMIT $2::int
)
SELECT v.id,
       v.canonical_id,
       v.severity,
       v.cvss_score,
       v.summary,
       v.published_at,
       cd.affected_sbom_count,
       ar.affected_artifact_count
FROM candidate cd
JOIN canonical v ON v.canonical_id = cd.canonical_id
CROSS JOIN LATERAL (
    SELECT COUNT(DISTINCT s.artifact_id)::bigint AS affected_artifact_count
    FROM component c
    JOIN sbom s ON s.id = c.sbom_id
    WHERE c.purl = ANY (cd.purls)
      AND s.namespace_id IN (SELECT id FROM public_ns)
) ar
ORDER BY ar.affected_artifact_count DESC,
         CASE v.severity
             WHEN 'CRITICAL' THEN 4
             WHEN 'HIGH'     THEN 3
             WHEN 'MEDIUM'   THEN 2
             WHEN 'LOW'      THEN 1
             ELSE 0
         END DESC,
         v.cvss_score DESC NULLS LAST,
         v.canonical_id
LIMIT $1::int
`

type GetDiscoverTopVulnerabilitiesParams struct {
	RowLimit       int32 `json:"row_limit"`
	CandidateLimit int32 `json:"candidate_limit"`
}

type GetDiscoverTopVulnerabilitiesRow struct {
	ID                    string             `json:"id"`
	CanonicalID           string             `json:"canonical_id"`
	Severity              pgtype.Text        `json:"severity"`
	CvssScore             pgtype.Float4      `json:"cvss_score"`
	Summary               pgtype.Text        `json:"summary"`
	PublishedAt           pgtype.Timestamptz `json:"published_at"`
	AffectedSbomCount     int64              `json:"affected_sbom_count"`
	AffectedArtifactCount int64              `json:"affected_artifact_count"`
}

// Vulnerabilities ranked by blast radius across public content.
//
// Two stages on purpose. Stage one ranks candidates from vuln_rollup, which is
// pre-aggregated per (canonical_id, namespace) and cheap; stage two computes the
// affected *artifact* count, which needs the purl -> component -> sbom join that
// ocidex-ckv.2 removed from the request path, and runs it only for the handful
// of candidates that survived. Artifact count is the honest headline for a
// discovery page — "affects 14 public images" is a claim a visitor can act on,
// where an SBOM count double-counts every rescan of the same image — but it is
// not worth a full join over 10.9M component rows to rank the whole catalog by.
//
// The ordinality filter on the unnest is the vuln_rollup idiom from
// ListTopVulnerabilities: unnesting purls multiplies the rows SUM would see, so
// each rollup row is charged exactly once.
func (q *Queries) GetDiscoverTopVulnerabilities(ctx context.Context, arg GetDiscoverTopVulnerabilitiesParams) ([]GetDiscoverTopVulnerabilitiesRow, error) {
	rows, err := q.db.Query(ctx, getDiscoverTopVulnerabilities, arg.RowLimit, arg.CandidateLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDiscoverTopVulnerabilitiesRow{}
	for rows.Next() {
		var i GetDiscoverTopVulnerabilitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalID,
			&i.Severity,
			&i.CvssScore,
			&i.Summary,
			&i.PublishedAt,
			&i.AffectedSbomCount,
			&i.AffectedArtifactCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
