// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrichment.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEnrichment = `-- name: GetEnrichment :one
SELECT id, sbom_id, enricher_name, status, data, error_message, created_at, updated_at
FROM enrichment
WHERE sbom_id = $1 AND enricher_name = $2
`

type GetEnrichmentParams struct {
	SbomID       pgtype.UUID `json:"sbom_id"`
	EnricherName string      `json:"enricher_name"`
}

func (q *Queries) GetEnrichment(ctx context.Context, arg GetEnrichmentParams) (Enrichment, error) {
	row := q.db.QueryRow(ctx, getEnrichment, arg.SbomID, arg.EnricherName)
	var i Enrichment
	err := row.Scan(
		&i.ID,
		&i.SbomID,
		&i.EnricherName,
		&i.Status,
		&i.Data,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnrichmentsBySBOM = `-- name: ListEnrichmentsBySBOM :many
SELECT id, enricher_name, status, data, error_message, updated_at
FROM enrichment
WHERE sbom_id = $1
ORDER BY enricher_name
`

type ListEnrichmentsBySBOMRow struct {
	ID           pgtype.UUID        `json:"id"`
	EnricherName string             `json:"enricher_name"`
	Status       string             `json:"status"`
	Data         []byte             `json:"data"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListEnrichmentsBySBOM(ctx context.Context, sbomID pgtype.UUID) ([]ListEnrichmentsBySBOMRow, error) {
	rows, err := q.db.Query(ctx, listEnrichmentsBySBOM, sbomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnrichmentsBySBOMRow{}
	for rows.Next() {
		var i ListEnrichmentsBySBOMRow
		if err := rows.Scan(
			&i.ID,
			&i.EnricherName,
			&i.Status,
			&i.Data,
			&i.ErrorMessage,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSBOMEnrichmentsByArtifact = `-- name: ListSBOMEnrichmentsByArtifact :many
SELECT e.sbom_id, e.enricher_name, e.data
FROM enrichment e
JOIN sbom s ON s.id = e.sbom_id
WHERE s.artifact_id = $1 AND e.status = 'success'
ORDER BY e.sbom_id
`

type ListSBOMEnrichmentsByArtifactRow struct {
	SbomID       pgtype.UUID `json:"sbom_id"`
	EnricherName string      `json:"enricher_name"`
	Data         []byte      `json:"data"`
}

func (q *Queries) ListSBOMEnrichmentsByArtifact(ctx context.Context, artifactID pgtype.UUID) ([]ListSBOMEnrichmentsByArtifactRow, error) {
	rows, err := q.db.Query(ctx, listSBOMEnrichmentsByArtifact, artifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSBOMEnrichmentsByArtifactRow{}
	for rows.Next() {
		var i ListSBOMEnrichmentsByArtifactRow
		if err := rows.Scan(&i.SbomID, &i.EnricherName, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSBOMsDueForProvenanceRecheck = `-- name: ListSBOMsDueForProvenanceRecheck :many
SELECT sbom_id
FROM enrichment
WHERE enricher_name = 'provenance'
  AND status = 'success'
  AND updated_at < $1::timestamptz
ORDER BY updated_at
LIMIT $2::int
`

type ListSBOMsDueForProvenanceRecheckParams struct {
	Cutoff   pgtype.Timestamptz `json:"cutoff"`
	RowLimit int32              `json:"row_limit"`
}

func (q *Queries) ListSBOMsDueForProvenanceRecheck(ctx context.Context, arg ListSBOMsDueForProvenanceRecheckParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listSBOMsDueForProvenanceRecheck, arg.Cutoff, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var sbom_id pgtype.UUID
		if err := rows.Scan(&sbom_id); err != nil {
			return nil, err
		}
		items = append(items, sbom_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSBOMEnrichmentSufficient = `-- name: UpdateSBOMEnrichmentSufficient :exec
UPDATE sbom SET enrichment_sufficient = $2 WHERE id = $1
`

type UpdateSBOMEnrichmentSufficientParams struct {
	ID                   pgtype.UUID `json:"id"`
	EnrichmentSufficient bool        `json:"enrichment_sufficient"`
}

func (q *Queries) UpdateSBOMEnrichmentSufficient(ctx context.Context, arg UpdateSBOMEnrichmentSufficientParams) error {
	_, err := q.db.Exec(ctx, updateSBOMEnrichmentSufficient, arg.ID, arg.EnrichmentSufficient)
	return err
}

const upsertEnrichment = `-- name: UpsertEnrichment :exec
INSERT INTO enrichment (sbom_id, enricher_name, status, data, error_message, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (sbom_id, enricher_name)
DO UPDATE SET
    status = CASE
        WHEN EXCLUDED.status = 'error' AND enrichment.data IS NOT NULL THEN enrichment.status
        ELSE EXCLUDED.status
    END,
    data = COALESCE(EXCLUDED.data, enrichment.data),
    error_message = EXCLUDED.error_message,
    updated_at = now()
`

type UpsertEnrichmentParams struct {
	SbomID       pgtype.UUID `json:"sbom_id"`
	EnricherName string      `json:"enricher_name"`
	Status       string      `json:"status"`
	Data         []byte      `json:"data"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

// A transient enricher error must not clobber a prior successful result: status
// only moves to 'error' if there was no prior good data, and data is preserved
// via COALESCE when the new result carries none (see ocidex-goh.2).
func (q *Queries) UpsertEnrichment(ctx context.Context, arg UpsertEnrichmentParams) error {
	_, err := q.db.Exec(ctx, upsertEnrichment,
		arg.SbomID,
		arg.EnricherName,
		arg.Status,
		arg.Data,
		arg.ErrorMessage,
	)
	return err
}
