// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrichment_jobs.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimEnrichmentJobByID = `-- name: ClaimEnrichmentJobByID :one
WITH claimed AS (
    UPDATE enrichment_jobs
    SET state           = 'running',
        started_at      = COALESCE(started_at, now()),
        last_attempt_at = now(),
        worker_id       = $1::text,
        attempts        = attempts + 1
    WHERE id = $2::uuid
      AND state = 'queued'
    RETURNING id, sbom_id, attempts, architecture, build_date
)
SELECT
    c.id,
    c.sbom_id,
    c.attempts,
    COALESCE(c.architecture, '')::text        AS architecture,
    COALESCE(c.build_date, '')::text          AS build_date,
    COALESCE(s.digest, '')::text              AS digest,
    COALESCE(s.subject_version, '')::text     AS subject_version,
    COALESCE(a.type, '')::text                AS artifact_type,
    COALESCE(a.name, '')::text                AS artifact_name
FROM claimed c
JOIN sbom s ON s.id = c.sbom_id
JOIN artifact a ON a.id = s.artifact_id
`

type ClaimEnrichmentJobByIDParams struct {
	WorkerID string      `json:"worker_id"`
	ID       pgtype.UUID `json:"id"`
}

type ClaimEnrichmentJobByIDRow struct {
	ID             pgtype.UUID `json:"id"`
	SbomID         pgtype.UUID `json:"sbom_id"`
	Attempts       int32       `json:"attempts"`
	Architecture   string      `json:"architecture"`
	BuildDate      string      `json:"build_date"`
	Digest         string      `json:"digest"`
	SubjectVersion string      `json:"subject_version"`
	ArtifactType   string      `json:"artifact_type"`
	ArtifactName   string      `json:"artifact_name"`
}

func (q *Queries) ClaimEnrichmentJobByID(ctx context.Context, arg ClaimEnrichmentJobByIDParams) (ClaimEnrichmentJobByIDRow, error) {
	row := q.db.QueryRow(ctx, claimEnrichmentJobByID, arg.WorkerID, arg.ID)
	var i ClaimEnrichmentJobByIDRow
	err := row.Scan(
		&i.ID,
		&i.SbomID,
		&i.Attempts,
		&i.Architecture,
		&i.BuildDate,
		&i.Digest,
		&i.SubjectVersion,
		&i.ArtifactType,
		&i.ArtifactName,
	)
	return i, err
}

const claimNextEnrichmentJob = `-- name: ClaimNextEnrichmentJob :one
WITH next_id AS (
    SELECT id FROM enrichment_jobs
    WHERE state = 'queued'
      AND enricher_name = $1::text
    ORDER BY created_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
),
claimed AS (
    UPDATE enrichment_jobs
    SET state           = 'running',
        started_at      = COALESCE(started_at, now()),
        last_attempt_at = now(),
        worker_id       = $2::text,
        attempts        = attempts + 1
    WHERE id IN (SELECT id FROM next_id)
    RETURNING id, sbom_id, attempts, architecture, build_date, enricher_name
)
SELECT
    c.id,
    c.sbom_id,
    c.attempts,
    COALESCE(c.architecture, '')::text        AS architecture,
    COALESCE(c.build_date, '')::text          AS build_date,
    c.enricher_name                           AS enricher_name,
    COALESCE(s.digest, '')::text              AS digest,
    COALESCE(s.subject_version, '')::text     AS subject_version,
    COALESCE(a.type, '')::text                AS artifact_type,
    COALESCE(a.name, '')::text                AS artifact_name
FROM claimed c
JOIN sbom s ON s.id = c.sbom_id
JOIN artifact a ON a.id = s.artifact_id
`

type ClaimNextEnrichmentJobParams struct {
	EnricherName string `json:"enricher_name"`
	WorkerID     string `json:"worker_id"`
}

type ClaimNextEnrichmentJobRow struct {
	ID             pgtype.UUID `json:"id"`
	SbomID         pgtype.UUID `json:"sbom_id"`
	Attempts       int32       `json:"attempts"`
	Architecture   string      `json:"architecture"`
	BuildDate      string      `json:"build_date"`
	EnricherName   string      `json:"enricher_name"`
	Digest         string      `json:"digest"`
	SubjectVersion string      `json:"subject_version"`
	ArtifactType   string      `json:"artifact_type"`
	ArtifactName   string      `json:"artifact_name"`
}

func (q *Queries) ClaimNextEnrichmentJob(ctx context.Context, arg ClaimNextEnrichmentJobParams) (ClaimNextEnrichmentJobRow, error) {
	row := q.db.QueryRow(ctx, claimNextEnrichmentJob, arg.EnricherName, arg.WorkerID)
	var i ClaimNextEnrichmentJobRow
	err := row.Scan(
		&i.ID,
		&i.SbomID,
		&i.Attempts,
		&i.Architecture,
		&i.BuildDate,
		&i.EnricherName,
		&i.Digest,
		&i.SubjectVersion,
		&i.ArtifactType,
		&i.ArtifactName,
	)
	return i, err
}

const countEnrichmentJobs = `-- name: CountEnrichmentJobs :one
SELECT COUNT(*) FROM enrichment_jobs j
WHERE ($1::text IS NULL OR j.state = $1::text)
  AND ($2::text IS NULL OR j.enricher_name = $2::text)
`

type CountEnrichmentJobsParams struct {
	State        pgtype.Text `json:"state"`
	EnricherName pgtype.Text `json:"enricher_name"`
}

func (q *Queries) CountEnrichmentJobs(ctx context.Context, arg CountEnrichmentJobsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEnrichmentJobs, arg.State, arg.EnricherName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const failOrRequeueEnrichmentJobByID = `-- name: FailOrRequeueEnrichmentJobByID :one
UPDATE enrichment_jobs
SET state       = CASE
        WHEN attempts >= $1::int THEN 'failed'
        ELSE 'queued'
    END,
    last_error  = $2,
    finished_at = CASE
        WHEN attempts >= $1::int THEN now()
        ELSE NULL
    END
WHERE id = $3::uuid
  AND state NOT IN ('succeeded', 'failed')
RETURNING state
`

type FailOrRequeueEnrichmentJobByIDParams struct {
	MaxAttempts int32       `json:"max_attempts"`
	LastError   pgtype.Text `json:"last_error"`
	ID          pgtype.UUID `json:"id"`
}

// FailOrRequeueEnrichmentJobByID transitions a running job back to 'queued'
// for retry, or to 'failed' when the retry budget is exhausted.
func (q *Queries) FailOrRequeueEnrichmentJobByID(ctx context.Context, arg FailOrRequeueEnrichmentJobByIDParams) (string, error) {
	row := q.db.QueryRow(ctx, failOrRequeueEnrichmentJobByID, arg.MaxAttempts, arg.LastError, arg.ID)
	var state string
	err := row.Scan(&state)
	return state, err
}

const finishEnrichmentJobByID = `-- name: FinishEnrichmentJobByID :exec
UPDATE enrichment_jobs
SET state = 'succeeded', finished_at = now()
WHERE id = $1::uuid
`

func (q *Queries) FinishEnrichmentJobByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, finishEnrichmentJobByID, id)
	return err
}

const insertEnrichmentJob = `-- name: InsertEnrichmentJob :one
INSERT INTO enrichment_jobs (sbom_id, idempotency_key, architecture, build_date, enricher_name)
VALUES (
    $1::uuid,
    $2,
    $3,
    $4,
    $5::text
)
RETURNING id, sbom_id, state, attempts, last_error, idempotency_key, worker_id, architecture, build_date, created_at, started_at, last_attempt_at, finished_at, enricher_name
`

type InsertEnrichmentJobParams struct {
	SbomID         pgtype.UUID `json:"sbom_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	Architecture   pgtype.Text `json:"architecture"`
	BuildDate      pgtype.Text `json:"build_date"`
	EnricherName   string      `json:"enricher_name"`
}

func (q *Queries) InsertEnrichmentJob(ctx context.Context, arg InsertEnrichmentJobParams) (EnrichmentJob, error) {
	row := q.db.QueryRow(ctx, insertEnrichmentJob,
		arg.SbomID,
		arg.IdempotencyKey,
		arg.Architecture,
		arg.BuildDate,
		arg.EnricherName,
	)
	var i EnrichmentJob
	err := row.Scan(
		&i.ID,
		&i.SbomID,
		&i.State,
		&i.Attempts,
		&i.LastError,
		&i.IdempotencyKey,
		&i.WorkerID,
		&i.Architecture,
		&i.BuildDate,
		&i.CreatedAt,
		&i.StartedAt,
		&i.LastAttemptAt,
		&i.FinishedAt,
		&i.EnricherName,
	)
	return i, err
}

const listEnrichmentJobs = `-- name: ListEnrichmentJobs :many
SELECT
    j.id, j.sbom_id, j.state, j.attempts, j.last_error, j.worker_id,
    j.enricher_name, j.created_at, j.started_at, j.last_attempt_at, j.finished_at,
    s.digest AS sbom_digest,
    a.name   AS artifact_name
FROM enrichment_jobs j
LEFT JOIN sbom s     ON s.id = j.sbom_id
LEFT JOIN artifact a ON a.id = s.artifact_id
WHERE ($1::text IS NULL OR j.state = $1::text)
  AND ($2::text IS NULL OR j.enricher_name = $2::text)
ORDER BY
    CASE j.state
        WHEN 'running'   THEN 1
        WHEN 'queued'    THEN 2
        WHEN 'failed'    THEN 3
        WHEN 'succeeded' THEN 4
        ELSE 5
    END,
    j.created_at DESC
LIMIT $4 OFFSET $3
`

type ListEnrichmentJobsParams struct {
	State        pgtype.Text `json:"state"`
	EnricherName pgtype.Text `json:"enricher_name"`
	Offset       int32       `json:"offset_"`
	Limit        int32       `json:"limit_"`
}

type ListEnrichmentJobsRow struct {
	ID            pgtype.UUID        `json:"id"`
	SbomID        pgtype.UUID        `json:"sbom_id"`
	State         string             `json:"state"`
	Attempts      int32              `json:"attempts"`
	LastError     pgtype.Text        `json:"last_error"`
	WorkerID      pgtype.Text        `json:"worker_id"`
	EnricherName  string             `json:"enricher_name"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	LastAttemptAt pgtype.Timestamptz `json:"last_attempt_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	SbomDigest    pgtype.Text        `json:"sbom_digest"`
	ArtifactName  pgtype.Text        `json:"artifact_name"`
}

// ListEnrichmentJobs returns enrichment jobs for the admin Jobs page, optionally
// filtered by state and/or enricher, joined to the SBOM/artifact for display.
func (q *Queries) ListEnrichmentJobs(ctx context.Context, arg ListEnrichmentJobsParams) ([]ListEnrichmentJobsRow, error) {
	rows, err := q.db.Query(ctx, listEnrichmentJobs,
		arg.State,
		arg.EnricherName,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnrichmentJobsRow{}
	for rows.Next() {
		var i ListEnrichmentJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.SbomID,
			&i.State,
			&i.Attempts,
			&i.LastError,
			&i.WorkerID,
			&i.EnricherName,
			&i.CreatedAt,
			&i.StartedAt,
			&i.LastAttemptAt,
			&i.FinishedAt,
			&i.SbomDigest,
			&i.ArtifactName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueStuckEnrichmentJobs = `-- name: RequeueStuckEnrichmentJobs :exec
UPDATE enrichment_jobs
SET state = CASE
        WHEN attempts >= $1::int THEN 'failed'
        ELSE 'queued'
    END,
    last_error = CASE
        WHEN attempts >= $1::int
            THEN 'stuck: worker did not complete and retries exhausted'
        ELSE last_error
    END,
    finished_at = CASE
        WHEN attempts >= $1::int THEN now()
        ELSE NULL
    END
WHERE state = 'running'
  AND last_attempt_at < $2::timestamptz
`

type RequeueStuckEnrichmentJobsParams struct {
	MaxAttempts int32              `json:"max_attempts"`
	StuckBefore pgtype.Timestamptz `json:"stuck_before"`
}

// RequeueStuckEnrichmentJobs sweeps running rows whose worker has gone silent.
func (q *Queries) RequeueStuckEnrichmentJobs(ctx context.Context, arg RequeueStuckEnrichmentJobsParams) error {
	_, err := q.db.Exec(ctx, requeueStuckEnrichmentJobs, arg.MaxAttempts, arg.StuckBefore)
	return err
}

const retryAllFailedEnrichmentJobs = `-- name: RetryAllFailedEnrichmentJobs :execrows
UPDATE enrichment_jobs
SET state           = 'queued',
    attempts        = 0,
    last_error      = NULL,
    finished_at     = NULL,
    started_at      = NULL,
    last_attempt_at = NULL
WHERE state = 'failed'
  AND ($1::text IS NULL OR enricher_name = $1::text)
`

// RetryAllFailedEnrichmentJobs resets every 'failed' row back to 'queued',
// optionally scoped to a single enricher. Returns the row count.
func (q *Queries) RetryAllFailedEnrichmentJobs(ctx context.Context, enricherName pgtype.Text) (int64, error) {
	result, err := q.db.Exec(ctx, retryAllFailedEnrichmentJobs, enricherName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryEnrichmentJob = `-- name: RetryEnrichmentJob :exec
UPDATE enrichment_jobs
SET state           = 'queued',
    attempts        = 0,
    last_error      = NULL,
    finished_at     = NULL,
    started_at      = NULL,
    last_attempt_at = NULL
WHERE id = $1::uuid
  AND state = 'failed'
`

func (q *Queries) RetryEnrichmentJob(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, retryEnrichmentJob, id)
	return err
}

const summarizeEnrichmentJobs = `-- name: SummarizeEnrichmentJobs :many
SELECT enricher_name, state, COUNT(*) AS count
FROM enrichment_jobs
GROUP BY enricher_name, state
`

type SummarizeEnrichmentJobsRow struct {
	EnricherName string `json:"enricher_name"`
	State        string `json:"state"`
	Count        int64  `json:"count"`
}

// SummarizeEnrichmentJobs returns one row per (enricher, state) with its count,
// powering the per-enricher health matrix on the admin Jobs page.
func (q *Queries) SummarizeEnrichmentJobs(ctx context.Context) ([]SummarizeEnrichmentJobsRow, error) {
	rows, err := q.db.Query(ctx, summarizeEnrichmentJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SummarizeEnrichmentJobsRow{}
	for rows.Next() {
		var i SummarizeEnrichmentJobsRow
		if err := rows.Scan(&i.EnricherName, &i.State, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
