// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrichment_jobs.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimEnrichmentJobByID = `-- name: ClaimEnrichmentJobByID :one
WITH claimed AS (
    UPDATE enrichment_jobs
    SET state           = 'running',
        started_at      = COALESCE(started_at, now()),
        last_attempt_at = now(),
        worker_id       = $1::text,
        attempts        = attempts + 1
    WHERE id = $2::uuid
      AND state = 'queued'
    RETURNING id, sbom_id, attempts, architecture, build_date
)
SELECT
    c.id,
    c.sbom_id,
    c.attempts,
    COALESCE(c.architecture, '')::text        AS architecture,
    COALESCE(c.build_date, '')::text          AS build_date,
    COALESCE(s.digest, '')::text              AS digest,
    COALESCE(s.subject_version, '')::text     AS subject_version,
    COALESCE(a.type, '')::text                AS artifact_type,
    COALESCE(a.name, '')::text                AS artifact_name
FROM claimed c
JOIN sbom s ON s.id = c.sbom_id
JOIN artifact a ON a.id = s.artifact_id
`

type ClaimEnrichmentJobByIDParams struct {
	WorkerID string      `json:"worker_id"`
	ID       pgtype.UUID `json:"id"`
}

type ClaimEnrichmentJobByIDRow struct {
	ID             pgtype.UUID `json:"id"`
	SbomID         pgtype.UUID `json:"sbom_id"`
	Attempts       int32       `json:"attempts"`
	Architecture   string      `json:"architecture"`
	BuildDate      string      `json:"build_date"`
	Digest         string      `json:"digest"`
	SubjectVersion string      `json:"subject_version"`
	ArtifactType   string      `json:"artifact_type"`
	ArtifactName   string      `json:"artifact_name"`
}

func (q *Queries) ClaimEnrichmentJobByID(ctx context.Context, arg ClaimEnrichmentJobByIDParams) (ClaimEnrichmentJobByIDRow, error) {
	row := q.db.QueryRow(ctx, claimEnrichmentJobByID, arg.WorkerID, arg.ID)
	var i ClaimEnrichmentJobByIDRow
	err := row.Scan(
		&i.ID,
		&i.SbomID,
		&i.Attempts,
		&i.Architecture,
		&i.BuildDate,
		&i.Digest,
		&i.SubjectVersion,
		&i.ArtifactType,
		&i.ArtifactName,
	)
	return i, err
}

const claimNextEnrichmentJob = `-- name: ClaimNextEnrichmentJob :one
WITH next_id AS (
    SELECT id FROM enrichment_jobs
    WHERE state = 'queued'
    ORDER BY created_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
),
claimed AS (
    UPDATE enrichment_jobs
    SET state           = 'running',
        started_at      = COALESCE(started_at, now()),
        last_attempt_at = now(),
        worker_id       = $1::text,
        attempts        = attempts + 1
    WHERE id IN (SELECT id FROM next_id)
    RETURNING id, sbom_id, attempts, architecture, build_date
)
SELECT
    c.id,
    c.sbom_id,
    c.attempts,
    COALESCE(c.architecture, '')::text        AS architecture,
    COALESCE(c.build_date, '')::text          AS build_date,
    COALESCE(s.digest, '')::text              AS digest,
    COALESCE(s.subject_version, '')::text     AS subject_version,
    COALESCE(a.type, '')::text                AS artifact_type,
    COALESCE(a.name, '')::text                AS artifact_name
FROM claimed c
JOIN sbom s ON s.id = c.sbom_id
JOIN artifact a ON a.id = s.artifact_id
`

type ClaimNextEnrichmentJobRow struct {
	ID             pgtype.UUID `json:"id"`
	SbomID         pgtype.UUID `json:"sbom_id"`
	Attempts       int32       `json:"attempts"`
	Architecture   string      `json:"architecture"`
	BuildDate      string      `json:"build_date"`
	Digest         string      `json:"digest"`
	SubjectVersion string      `json:"subject_version"`
	ArtifactType   string      `json:"artifact_type"`
	ArtifactName   string      `json:"artifact_name"`
}

func (q *Queries) ClaimNextEnrichmentJob(ctx context.Context, workerID string) (ClaimNextEnrichmentJobRow, error) {
	row := q.db.QueryRow(ctx, claimNextEnrichmentJob, workerID)
	var i ClaimNextEnrichmentJobRow
	err := row.Scan(
		&i.ID,
		&i.SbomID,
		&i.Attempts,
		&i.Architecture,
		&i.BuildDate,
		&i.Digest,
		&i.SubjectVersion,
		&i.ArtifactType,
		&i.ArtifactName,
	)
	return i, err
}

const failOrRequeueEnrichmentJobByID = `-- name: FailOrRequeueEnrichmentJobByID :one
UPDATE enrichment_jobs
SET state       = CASE
        WHEN attempts >= $1::int THEN 'failed'
        ELSE 'queued'
    END,
    last_error  = $2,
    finished_at = CASE
        WHEN attempts >= $1::int THEN now()
        ELSE NULL
    END
WHERE id = $3::uuid
  AND state NOT IN ('succeeded', 'failed')
RETURNING state
`

type FailOrRequeueEnrichmentJobByIDParams struct {
	MaxAttempts int32       `json:"max_attempts"`
	LastError   pgtype.Text `json:"last_error"`
	ID          pgtype.UUID `json:"id"`
}

// FailOrRequeueEnrichmentJobByID transitions a running job back to 'queued'
// for retry, or to 'failed' when the retry budget is exhausted.
func (q *Queries) FailOrRequeueEnrichmentJobByID(ctx context.Context, arg FailOrRequeueEnrichmentJobByIDParams) (string, error) {
	row := q.db.QueryRow(ctx, failOrRequeueEnrichmentJobByID, arg.MaxAttempts, arg.LastError, arg.ID)
	var state string
	err := row.Scan(&state)
	return state, err
}

const finishEnrichmentJobByID = `-- name: FinishEnrichmentJobByID :exec
UPDATE enrichment_jobs
SET state = 'succeeded', finished_at = now()
WHERE id = $1::uuid
`

func (q *Queries) FinishEnrichmentJobByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, finishEnrichmentJobByID, id)
	return err
}

const insertEnrichmentJob = `-- name: InsertEnrichmentJob :one
INSERT INTO enrichment_jobs (sbom_id, idempotency_key, architecture, build_date)
VALUES (
    $1::uuid,
    $2,
    $3,
    $4
)
RETURNING id, sbom_id, state, attempts, last_error, idempotency_key, worker_id, architecture, build_date, created_at, started_at, last_attempt_at, finished_at
`

type InsertEnrichmentJobParams struct {
	SbomID         pgtype.UUID `json:"sbom_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	Architecture   pgtype.Text `json:"architecture"`
	BuildDate      pgtype.Text `json:"build_date"`
}

func (q *Queries) InsertEnrichmentJob(ctx context.Context, arg InsertEnrichmentJobParams) (EnrichmentJob, error) {
	row := q.db.QueryRow(ctx, insertEnrichmentJob,
		arg.SbomID,
		arg.IdempotencyKey,
		arg.Architecture,
		arg.BuildDate,
	)
	var i EnrichmentJob
	err := row.Scan(
		&i.ID,
		&i.SbomID,
		&i.State,
		&i.Attempts,
		&i.LastError,
		&i.IdempotencyKey,
		&i.WorkerID,
		&i.Architecture,
		&i.BuildDate,
		&i.CreatedAt,
		&i.StartedAt,
		&i.LastAttemptAt,
		&i.FinishedAt,
	)
	return i, err
}

const requeueStuckEnrichmentJobs = `-- name: RequeueStuckEnrichmentJobs :exec
UPDATE enrichment_jobs
SET state = CASE
        WHEN attempts >= $1::int THEN 'failed'
        ELSE 'queued'
    END,
    last_error = CASE
        WHEN attempts >= $1::int
            THEN 'stuck: worker did not complete and retries exhausted'
        ELSE last_error
    END,
    finished_at = CASE
        WHEN attempts >= $1::int THEN now()
        ELSE NULL
    END
WHERE state = 'running'
  AND last_attempt_at < $2::timestamptz
`

type RequeueStuckEnrichmentJobsParams struct {
	MaxAttempts int32              `json:"max_attempts"`
	StuckBefore pgtype.Timestamptz `json:"stuck_before"`
}

// RequeueStuckEnrichmentJobs sweeps running rows whose worker has gone silent.
func (q *Queries) RequeueStuckEnrichmentJobs(ctx context.Context, arg RequeueStuckEnrichmentJobsParams) error {
	_, err := q.db.Exec(ctx, requeueStuckEnrichmentJobs, arg.MaxAttempts, arg.StuckBefore)
	return err
}
