// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Name       string             `json:"name"`
	KeyHash    string             `json:"key_hash"`
	Prefix     string             `json:"prefix"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	// Ceiling on what this key may do, intersected at validation time with the owner's live namespace roles. Mirrors the Capability constants in internal/authz.
	Capabilities []string `json:"capabilities"`
}

type Artifact struct {
	ID        pgtype.UUID        `json:"id"`
	Type      string             `json:"type"`
	Name      string             `json:"name"`
	GroupName pgtype.Text        `json:"group_name"`
	Purl      pgtype.Text        `json:"purl"`
	Cpe       pgtype.Text        `json:"cpe"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ArtifactNamespace struct {
	ArtifactID  pgtype.UUID        `json:"artifact_id"`
	NamespaceID pgtype.UUID        `json:"namespace_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// Per-user artifact bookmarks. Not an ownership or visibility relation: watching a public artifact owned by someone else is the primary use case.
type ArtifactWatch struct {
	UserID     pgtype.UUID        `json:"user_id"`
	ArtifactID pgtype.UUID        `json:"artifact_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// A registered Kubernetes cluster reporting its running workloads (ADR-044). Owned by a namespace; visibility is inherited from it, never stored here.
type Cluster struct {
	ID          pgtype.UUID `json:"id"`
	NamespaceID pgtype.UUID `json:"namespace_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	// Stamped on every accepted inventory snapshot. NULL means no agent has ever reported. Staleness is how a dead agent is distinguished from an empty cluster (ADR-044 K2) — a cluster showing zero workloads because nothing reported must never read as a cluster running nothing.
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	// When true, an accepted inventory snapshot submits scan jobs for every running image with no SBOM whose host resolves to a registry in this cluster's namespace (ADR-044). Defaults to true: a cluster that reports what it runs and then leaves it unscanned is the gap the inventory exists to close. Resolution never leaves the namespace — using another namespace's registry would pull with credentials this cluster was never granted.
	AutoIngest bool `json:"auto_ingest"`
}

// Current running-image inventory reported by a cluster agent. Full-snapshot semantics: rows absent from a snapshot are deleted (ADR-044 K7). Not a history table.
type ClusterWorkload struct {
	ID            pgtype.UUID `json:"id"`
	ClusterID     pgtype.UUID `json:"cluster_id"`
	K8sNamespace  string      `json:"k8s_namespace"`
	WorkloadKind  string      `json:"workload_kind"`
	WorkloadName  string      `json:"workload_name"`
	ContainerName string      `json:"container_name"`
	// The image reference for display only. Never a join key: a tag is mutable and is not an identity (ADR-044 K3).
	ImageRef string `json:"image_ref"`
	// Normalized sha256 digest read from status.containerStatuses[].imageID. NULL means the agent could not extract a digest at all (ADR-044 K5 "unresolvable") — distinct from a digest that matches no ingested SBOM ("unknown"), because the remedy differs: investigate the node runtime versus ingest an SBOM.
	ImageDigest pgtype.Text `json:"image_digest"`
	// How many running pods of this workload carry this container at this digest. Greater than one is normal; two rows for one container differing only by digest is a rollout in progress.
	PodCount    int32              `json:"pod_count"`
	FirstSeenAt pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
}

type Component struct {
	ID            pgtype.UUID `json:"id"`
	SbomID        pgtype.UUID `json:"sbom_id"`
	ParentID      pgtype.UUID `json:"parent_id"`
	BomRef        pgtype.Text `json:"bom_ref"`
	Type          string      `json:"type"`
	Name          string      `json:"name"`
	GroupName     pgtype.Text `json:"group_name"`
	Version       pgtype.Text `json:"version"`
	VersionMajor  pgtype.Int4 `json:"version_major"`
	VersionMinor  pgtype.Int4 `json:"version_minor"`
	VersionPatch  pgtype.Int4 `json:"version_patch"`
	Purl          pgtype.Text `json:"purl"`
	Cpe           pgtype.Text `json:"cpe"`
	Description   pgtype.Text `json:"description"`
	Scope         pgtype.Text `json:"scope"`
	Publisher     pgtype.Text `json:"publisher"`
	Copyright     pgtype.Text `json:"copyright"`
	LayerID       pgtype.Text `json:"layer_id"`
	FoundBy       pgtype.Text `json:"found_by"`
	SourcePackage pgtype.Text `json:"source_package"`
	SourceVersion pgtype.Text `json:"source_version"`
	SourcePurl    pgtype.Text `json:"source_purl"`
	FilePath      pgtype.Text `json:"file_path"`
}

type ComponentHash struct {
	ID          pgtype.UUID `json:"id"`
	ComponentID pgtype.UUID `json:"component_id"`
	Algorithm   string      `json:"algorithm"`
	Value       string      `json:"value"`
}

type ComponentLicense struct {
	ComponentID pgtype.UUID `json:"component_id"`
	LicenseID   pgtype.UUID `json:"license_id"`
}

type ComponentRollup struct {
	NamespaceID pgtype.UUID `json:"namespace_id"`
	Type        string      `json:"type"`
	Name        string      `json:"name"`
	GroupName   pgtype.Text `json:"group_name"`
	// Distinct purl type prefixes seen for this identity. A purl_type filter selects the whole group, so for the rare identity that spans two ecosystems the filtered version/sbom counts cover both.
	PurlTypes []string `json:"purl_types"`
	Versions  []string `json:"versions"`
	SbomCount int64    `json:"sbom_count"`
	// Distinct canonical vulnerability ids of CRITICAL severity reachable from any version of this package identity in this namespace. A CVE affecting two versions counts once: the row is the identity, not a version.
	Critical int64 `json:"critical"`
	High     int64 `json:"high"`
	Medium   int64 `json:"medium"`
	Low      int64 `json:"low"`
	Unknown  int64 `json:"unknown"`
}

type Dependency struct {
	ID        pgtype.UUID `json:"id"`
	SbomID    pgtype.UUID `json:"sbom_id"`
	Ref       string      `json:"ref"`
	DependsOn string      `json:"depends_on"`
}

type Enrichment struct {
	ID           pgtype.UUID        `json:"id"`
	SbomID       pgtype.UUID        `json:"sbom_id"`
	EnricherName string             `json:"enricher_name"`
	Status       string             `json:"status"`
	Data         []byte             `json:"data"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type EnrichmentJob struct {
	ID             pgtype.UUID        `json:"id"`
	SbomID         pgtype.UUID        `json:"sbom_id"`
	State          string             `json:"state"`
	Attempts       int32              `json:"attempts"`
	LastError      pgtype.Text        `json:"last_error"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	WorkerID       pgtype.Text        `json:"worker_id"`
	Architecture   pgtype.Text        `json:"architecture"`
	BuildDate      pgtype.Text        `json:"build_date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	LastAttemptAt  pgtype.Timestamptz `json:"last_attempt_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	EnricherName   string             `json:"enricher_name"`
}

type ExternalReference struct {
	ID          pgtype.UUID `json:"id"`
	ComponentID pgtype.UUID `json:"component_id"`
	Type        string      `json:"type"`
	Url         string      `json:"url"`
	Comment     pgtype.Text `json:"comment"`
}

type License struct {
	ID     pgtype.UUID `json:"id"`
	SpdxID pgtype.Text `json:"spdx_id"`
	Name   string      `json:"name"`
	Url    pgtype.Text `json:"url"`
}

type LicenseRollup struct {
	LicenseID   pgtype.UUID `json:"license_id"`
	NamespaceID pgtype.UUID `json:"namespace_id"`
	IdentityKey string      `json:"identity_key"`
}

// Tenancy boundary. The only table carrying ownership and visibility (ADR-039). A namespace may hold several sources.
type Namespace struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	// Defaults to private. Namespaces migrated from registries keep the registry's existing value, so this default only applies to namespaces created after the migration.
	Visibility string             `json:"visibility"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Membership of a namespace, with a per-namespace role. The namespace is the team (ADR-046); this table is what makes it one.
type NamespaceMember struct {
	NamespaceID pgtype.UUID `json:"namespace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	// Closed set, mapped to compile-time capability sets in internal/auth. Not a DB-defined role: a new role is a code change.
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OcidexUser struct {
	ID          pgtype.UUID        `json:"id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Email       pgtype.Text        `json:"email"`
	DisplayName pgtype.Text        `json:"display_name"`
}

type PackageVulnerability struct {
	Purl            string             `json:"purl"`
	VulnerabilityID string             `json:"vulnerability_id"`
	FixedVersion    pgtype.Text        `json:"fixed_version"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ProvenanceDriftEvent struct {
	ID             pgtype.UUID        `json:"id"`
	SbomID         pgtype.UUID        `json:"sbom_id"`
	PreviousStatus string             `json:"previous_status"`
	NewStatus      string             `json:"new_status"`
	Reason         string             `json:"reason"`
	PreviousData   []byte             `json:"previous_data"`
	NewData        []byte             `json:"new_data"`
	DetectedAt     pgtype.Timestamptz `json:"detected_at"`
}

type ProvenanceDriftPending struct {
	SbomID         pgtype.UUID        `json:"sbom_id"`
	PreviousStatus string             `json:"previous_status"`
	NewStatus      string             `json:"new_status"`
	Reason         string             `json:"reason"`
	PreviousData   []byte             `json:"previous_data"`
	NewData        []byte             `json:"new_data"`
	FirstSeenAt    pgtype.Timestamptz `json:"first_seen_at"`
}

type PurlVulnState struct {
	Purl      string             `json:"purl"`
	CheckedAt pgtype.Timestamptz `json:"checked_at"`
}

// OCI-specific discovery and trust config. Subtype of source: registry.id IS the source id. Ownership lives on namespace (ADR-039).
type Registry struct {
	ID                  pgtype.UUID        `json:"id"`
	Type                string             `json:"type"`
	Url                 string             `json:"url"`
	Insecure            bool               `json:"insecure"`
	WebhookSecret       pgtype.Text        `json:"webhook_secret"`
	Enabled             bool               `json:"enabled"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	RepositoryPatterns  []string           `json:"repository_patterns"`
	TagPatterns         []string           `json:"tag_patterns"`
	ScanMode            string             `json:"scan_mode"`
	PollIntervalMinutes int32              `json:"poll_interval_minutes"`
	LastPolledAt        pgtype.Timestamptz `json:"last_polled_at"`
	Repositories        []string           `json:"repositories"`
	AuthUsername        pgtype.Text        `json:"auth_username"`
	AuthToken           pgtype.Text        `json:"auth_token"`
	IncludeUntagged     bool               `json:"include_untagged"`
	VerificationMode    string             `json:"verification_mode"`
	TrustPublicKey      pgtype.Text        `json:"trust_public_key"`
	TrustIdentity       pgtype.Text        `json:"trust_identity"`
	TrustIssuer         pgtype.Text        `json:"trust_issuer"`
	ManagedBy           pgtype.Text        `json:"managed_by"`
	ManagedRef          pgtype.Text        `json:"managed_ref"`
}

type Sbom struct {
	ID                   pgtype.UUID        `json:"id"`
	SerialNumber         pgtype.Text        `json:"serial_number"`
	SpecVersion          string             `json:"spec_version"`
	Version              int32              `json:"version"`
	RawBom               []byte             `json:"raw_bom"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	ArtifactID           pgtype.UUID        `json:"artifact_id"`
	SubjectVersion       pgtype.Text        `json:"subject_version"`
	Digest               pgtype.Text        `json:"digest"`
	EnrichmentSufficient bool               `json:"enrichment_sufficient"`
	// Who may see this SBOM. NOT NULL since 00054: ingest resolves a source, and through it a namespace, or fails (ADR-039, ocidex-0gp.3).
	NamespaceID pgtype.UUID `json:"namespace_id"`
	Flavor      pgtype.Text `json:"flavor"`
	IndexDigest pgtype.Text `json:"index_digest"`
	// How this SBOM arrived. ON DELETE SET NULL: removing a channel loses attribution, never the SBOM and never its visibility.
	SourceID     pgtype.UUID `json:"source_id"`
	VersionMajor pgtype.Int4 `json:"version_major"`
	VersionMinor pgtype.Int4 `json:"version_minor"`
	VersionPatch pgtype.Int4 `json:"version_patch"`
}

// Per-severity finding counts per SBOM, deduplicated by canonical_id, scoped purl ∪ source_purl. Absence of a row means no findings OR never scanned — callers must not render it as a clean zero.
type SbomVulnRollup struct {
	SbomID      pgtype.UUID `json:"sbom_id"`
	NamespaceID pgtype.UUID `json:"namespace_id"`
	Critical    int64       `json:"critical"`
	High        int64       `json:"high"`
	Medium      int64       `json:"medium"`
	Low         int64       `json:"low"`
	Unknown     int64       `json:"unknown"`
}

type ScanJob struct {
	ID            pgtype.UUID        `json:"id"`
	RegistryID    pgtype.UUID        `json:"registry_id"`
	Repository    string             `json:"repository"`
	Digest        string             `json:"digest"`
	Tag           pgtype.Text        `json:"tag"`
	State         string             `json:"state"`
	Attempts      int32              `json:"attempts"`
	LastError     pgtype.Text        `json:"last_error"`
	NatsMsgID     pgtype.Text        `json:"nats_msg_id"`
	SbomID        pgtype.UUID        `json:"sbom_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	LastAttemptAt pgtype.Timestamptz `json:"last_attempt_at"`
	WorkerID      pgtype.Text        `json:"worker_id"`
	IndexDigest   pgtype.Text        `json:"index_digest"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// How an SBOM reached OCIDex. kind is the subtype discriminator; an oci_registry source has a matching registry row, an upload source has none.
type Source struct {
	ID          pgtype.UUID `json:"id"`
	NamespaceID pgtype.UUID `json:"namespace_id"`
	// Not to be confused with registry.type (zot/harbor/docker/generic), which is an OCI-flavour hint for the scanner and is meaningless for an upload.
	Kind      string             `json:"kind"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserIdentity struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	// Issuer key: 'github' for the GitHub OAuth2 app, 'oidc:<name>' for a configured OIDC issuer.
	Provider string `json:"provider"`
	// The issuer's stable subject. GitHub's numeric user id as text, or the OIDC ID token 'sub' claim.
	Subject   string             `json:"subject"`
	Email     pgtype.Text        `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type VulnEcosystemState struct {
	Ecosystem      string             `json:"ecosystem"`
	LastModifiedAt pgtype.Timestamptz `json:"last_modified_at"`
	CheckedAt      pgtype.Timestamptz `json:"checked_at"`
}

type VulnRefreshState struct {
	ID              bool               `json:"id"`
	LastRefreshedAt pgtype.Timestamptz `json:"last_refreshed_at"`
}

type VulnRollup struct {
	CanonicalID string      `json:"canonical_id"`
	NamespaceID pgtype.UUID `json:"namespace_id"`
	SbomCount   int64       `json:"sbom_count"`
	Purls       []string    `json:"purls"`
}

type Vulnerability struct {
	ID          string             `json:"id"`
	Aliases     []string           `json:"aliases"`
	Summary     pgtype.Text        `json:"summary"`
	Details     pgtype.Text        `json:"details"`
	Severity    pgtype.Text        `json:"severity"`
	CvssScore   pgtype.Float4      `json:"cvss_score"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	ModifiedAt  pgtype.Timestamptz `json:"modified_at"`
	Raw         []byte             `json:"raw"`
	RefreshedAt pgtype.Timestamptz `json:"refreshed_at"`
	CanonicalID string             `json:"canonical_id"`
	CvssVector  pgtype.Text        `json:"cvss_vector"`
}

type VulnerabilityReference struct {
	VulnerabilityID string `json:"vulnerability_id"`
	Type            string `json:"type"`
	Url             string `json:"url"`
}
