// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Name       string             `json:"name"`
	KeyHash    string             `json:"key_hash"`
	Prefix     string             `json:"prefix"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	Scope      string             `json:"scope"`
}

type Artifact struct {
	ID        pgtype.UUID        `json:"id"`
	Type      string             `json:"type"`
	Name      string             `json:"name"`
	GroupName pgtype.Text        `json:"group_name"`
	Purl      pgtype.Text        `json:"purl"`
	Cpe       pgtype.Text        `json:"cpe"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ArtifactNamespace struct {
	ArtifactID  pgtype.UUID        `json:"artifact_id"`
	NamespaceID pgtype.UUID        `json:"namespace_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Component struct {
	ID            pgtype.UUID `json:"id"`
	SbomID        pgtype.UUID `json:"sbom_id"`
	ParentID      pgtype.UUID `json:"parent_id"`
	BomRef        pgtype.Text `json:"bom_ref"`
	Type          string      `json:"type"`
	Name          string      `json:"name"`
	GroupName     pgtype.Text `json:"group_name"`
	Version       pgtype.Text `json:"version"`
	VersionMajor  pgtype.Int4 `json:"version_major"`
	VersionMinor  pgtype.Int4 `json:"version_minor"`
	VersionPatch  pgtype.Int4 `json:"version_patch"`
	Purl          pgtype.Text `json:"purl"`
	Cpe           pgtype.Text `json:"cpe"`
	Description   pgtype.Text `json:"description"`
	Scope         pgtype.Text `json:"scope"`
	Publisher     pgtype.Text `json:"publisher"`
	Copyright     pgtype.Text `json:"copyright"`
	LayerID       pgtype.Text `json:"layer_id"`
	FoundBy       pgtype.Text `json:"found_by"`
	SourcePackage pgtype.Text `json:"source_package"`
	SourceVersion pgtype.Text `json:"source_version"`
	SourcePurl    pgtype.Text `json:"source_purl"`
}

type ComponentHash struct {
	ID          pgtype.UUID `json:"id"`
	ComponentID pgtype.UUID `json:"component_id"`
	Algorithm   string      `json:"algorithm"`
	Value       string      `json:"value"`
}

type ComponentLicense struct {
	ComponentID pgtype.UUID `json:"component_id"`
	LicenseID   pgtype.UUID `json:"license_id"`
}

type ComponentRollup struct {
	NamespaceID pgtype.UUID `json:"namespace_id"`
	Type        string      `json:"type"`
	Name        string      `json:"name"`
	GroupName   pgtype.Text `json:"group_name"`
	// Distinct purl type prefixes seen for this identity. A purl_type filter selects the whole group, so for the rare identity that spans two ecosystems the filtered version/sbom counts cover both.
	PurlTypes []string `json:"purl_types"`
	Versions  []string `json:"versions"`
	SbomCount int64    `json:"sbom_count"`
}

type Dependency struct {
	ID        pgtype.UUID `json:"id"`
	SbomID    pgtype.UUID `json:"sbom_id"`
	Ref       string      `json:"ref"`
	DependsOn string      `json:"depends_on"`
}

type Enrichment struct {
	ID           pgtype.UUID        `json:"id"`
	SbomID       pgtype.UUID        `json:"sbom_id"`
	EnricherName string             `json:"enricher_name"`
	Status       string             `json:"status"`
	Data         []byte             `json:"data"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type EnrichmentJob struct {
	ID             pgtype.UUID        `json:"id"`
	SbomID         pgtype.UUID        `json:"sbom_id"`
	State          string             `json:"state"`
	Attempts       int32              `json:"attempts"`
	LastError      pgtype.Text        `json:"last_error"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	WorkerID       pgtype.Text        `json:"worker_id"`
	Architecture   pgtype.Text        `json:"architecture"`
	BuildDate      pgtype.Text        `json:"build_date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	LastAttemptAt  pgtype.Timestamptz `json:"last_attempt_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	EnricherName   string             `json:"enricher_name"`
}

type ExternalReference struct {
	ID          pgtype.UUID `json:"id"`
	ComponentID pgtype.UUID `json:"component_id"`
	Type        string      `json:"type"`
	Url         string      `json:"url"`
	Comment     pgtype.Text `json:"comment"`
}

type License struct {
	ID     pgtype.UUID `json:"id"`
	SpdxID pgtype.Text `json:"spdx_id"`
	Name   string      `json:"name"`
	Url    pgtype.Text `json:"url"`
}

type LicenseRollup struct {
	LicenseID   pgtype.UUID `json:"license_id"`
	NamespaceID pgtype.UUID `json:"namespace_id"`
	IdentityKey string      `json:"identity_key"`
}

// Tenancy boundary. The only table carrying ownership and visibility (ADR-039). A namespace may hold several sources.
type Namespace struct {
	ID      pgtype.UUID `json:"id"`
	Name    string      `json:"name"`
	OwnerID pgtype.UUID `json:"owner_id"`
	// Defaults to private. Namespaces migrated from registries keep the registry's existing value, so this default only applies to namespaces created after the migration.
	Visibility string             `json:"visibility"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type OcidexUser struct {
	ID             pgtype.UUID        `json:"id"`
	GithubID       int64              `json:"github_id"`
	GithubUsername string             `json:"github_username"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type PackageVulnerability struct {
	Purl            string             `json:"purl"`
	VulnerabilityID string             `json:"vulnerability_id"`
	FixedVersion    pgtype.Text        `json:"fixed_version"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ProvenanceDriftEvent struct {
	ID             pgtype.UUID        `json:"id"`
	SbomID         pgtype.UUID        `json:"sbom_id"`
	PreviousStatus string             `json:"previous_status"`
	NewStatus      string             `json:"new_status"`
	Reason         string             `json:"reason"`
	PreviousData   []byte             `json:"previous_data"`
	NewData        []byte             `json:"new_data"`
	DetectedAt     pgtype.Timestamptz `json:"detected_at"`
}

type PurlVulnState struct {
	Purl      string             `json:"purl"`
	CheckedAt pgtype.Timestamptz `json:"checked_at"`
}

// OCI-specific discovery and trust config. Subtype of source: registry.id IS the source id. Ownership lives on namespace (ADR-039).
type Registry struct {
	ID                  pgtype.UUID        `json:"id"`
	Type                string             `json:"type"`
	Url                 string             `json:"url"`
	Insecure            bool               `json:"insecure"`
	WebhookSecret       pgtype.Text        `json:"webhook_secret"`
	Enabled             bool               `json:"enabled"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	RepositoryPatterns  []string           `json:"repository_patterns"`
	TagPatterns         []string           `json:"tag_patterns"`
	ScanMode            string             `json:"scan_mode"`
	PollIntervalMinutes int32              `json:"poll_interval_minutes"`
	LastPolledAt        pgtype.Timestamptz `json:"last_polled_at"`
	Repositories        []string           `json:"repositories"`
	AuthUsername        pgtype.Text        `json:"auth_username"`
	AuthToken           pgtype.Text        `json:"auth_token"`
	IncludeUntagged     bool               `json:"include_untagged"`
	VerificationMode    string             `json:"verification_mode"`
	TrustPublicKey      pgtype.Text        `json:"trust_public_key"`
	TrustIdentity       pgtype.Text        `json:"trust_identity"`
	TrustIssuer         pgtype.Text        `json:"trust_issuer"`
	ManagedBy           pgtype.Text        `json:"managed_by"`
	ManagedRef          pgtype.Text        `json:"managed_ref"`
}

type Sbom struct {
	ID                   pgtype.UUID        `json:"id"`
	SerialNumber         pgtype.Text        `json:"serial_number"`
	SpecVersion          string             `json:"spec_version"`
	Version              int32              `json:"version"`
	RawBom               []byte             `json:"raw_bom"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	ArtifactID           pgtype.UUID        `json:"artifact_id"`
	SubjectVersion       pgtype.Text        `json:"subject_version"`
	Digest               pgtype.Text        `json:"digest"`
	EnrichmentSufficient bool               `json:"enrichment_sufficient"`
	// Who may see this SBOM. Still nullable: legacy uploaded rows have no owner until ocidex-0gp.3 assigns one.
	NamespaceID pgtype.UUID `json:"namespace_id"`
	Flavor      pgtype.Text `json:"flavor"`
	IndexDigest pgtype.Text `json:"index_digest"`
	// How this SBOM arrived. ON DELETE SET NULL: removing a channel loses attribution, never the SBOM and never its visibility.
	SourceID pgtype.UUID `json:"source_id"`
}

type ScanJob struct {
	ID            pgtype.UUID        `json:"id"`
	RegistryID    pgtype.UUID        `json:"registry_id"`
	Repository    string             `json:"repository"`
	Digest        string             `json:"digest"`
	Tag           pgtype.Text        `json:"tag"`
	State         string             `json:"state"`
	Attempts      int32              `json:"attempts"`
	LastError     pgtype.Text        `json:"last_error"`
	NatsMsgID     pgtype.Text        `json:"nats_msg_id"`
	SbomID        pgtype.UUID        `json:"sbom_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	LastAttemptAt pgtype.Timestamptz `json:"last_attempt_at"`
	WorkerID      pgtype.Text        `json:"worker_id"`
	IndexDigest   pgtype.Text        `json:"index_digest"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// How an SBOM reached OCIDex. kind is the subtype discriminator; an oci_registry source has a matching registry row, an upload source has none.
type Source struct {
	ID          pgtype.UUID `json:"id"`
	NamespaceID pgtype.UUID `json:"namespace_id"`
	// Not to be confused with registry.type (zot/harbor/docker/generic), which is an OCI-flavour hint for the scanner and is meaningless for an upload.
	Kind      string             `json:"kind"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type VulnEcosystemState struct {
	Ecosystem      string             `json:"ecosystem"`
	LastModifiedAt pgtype.Timestamptz `json:"last_modified_at"`
	CheckedAt      pgtype.Timestamptz `json:"checked_at"`
}

type VulnRefreshState struct {
	ID              bool               `json:"id"`
	LastRefreshedAt pgtype.Timestamptz `json:"last_refreshed_at"`
}

type VulnRollup struct {
	CanonicalID string      `json:"canonical_id"`
	NamespaceID pgtype.UUID `json:"namespace_id"`
	SbomCount   int64       `json:"sbom_count"`
	Purls       []string    `json:"purls"`
}

type Vulnerability struct {
	ID          string             `json:"id"`
	Aliases     []string           `json:"aliases"`
	Summary     pgtype.Text        `json:"summary"`
	Details     pgtype.Text        `json:"details"`
	Severity    pgtype.Text        `json:"severity"`
	CvssScore   pgtype.Float4      `json:"cvss_score"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	ModifiedAt  pgtype.Timestamptz `json:"modified_at"`
	Raw         []byte             `json:"raw"`
	RefreshedAt pgtype.Timestamptz `json:"refreshed_at"`
	CanonicalID string             `json:"canonical_id"`
	CvssVector  pgtype.Text        `json:"cvss_vector"`
}

type VulnerabilityReference struct {
	VulnerabilityID string `json:"vulnerability_id"`
	Type            string `json:"type"`
	Url             string `json:"url"`
}
