// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: namespace.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOwnedPrivateNamespaces = `-- name: CountOwnedPrivateNamespaces :one
SELECT COUNT(*) FROM namespace
WHERE owner_id = $1 AND visibility <> 'public'
`

// A viewer who owns no private namespace sees exactly the public set, i.e. the
// same data as an anonymous viewer. The dashboard-stats cache uses this to
// collapse such viewers onto the shared anonymous scope instead of minting a
// per-user scope that the background warmer can never enumerate.
func (q *Queries) CountOwnedPrivateNamespaces(ctx context.Context, ownerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnedPrivateNamespaces, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNamespace = `-- name: CreateNamespace :one

INSERT INTO namespace (name, owner_id, visibility)
VALUES ($1, $2, $3)
RETURNING id, name, owner_id, visibility, created_at, updated_at
`

type CreateNamespaceParams struct {
	Name       string      `json:"name"`
	OwnerID    pgtype.UUID `json:"owner_id"`
	Visibility string      `json:"visibility"`
}

// Namespace is the authorization anchor (ADR-039): ownership and visibility live
// here and nowhere else. Everything about *how* an SBOM arrived belongs on
// source; everything that needs an OCI manifest belongs on registry.
func (q *Queries) CreateNamespace(ctx context.Context, arg CreateNamespaceParams) (Namespace, error) {
	row := q.db.QueryRow(ctx, createNamespace, arg.Name, arg.OwnerID, arg.Visibility)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNamespace = `-- name: DeleteNamespace :execrows
DELETE FROM namespace WHERE id = $1
`

func (q *Queries) DeleteNamespace(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNamespace, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNamespace = `-- name: GetNamespace :one
SELECT id, name, owner_id, visibility, created_at, updated_at FROM namespace WHERE id = $1
`

func (q *Queries) GetNamespace(ctx context.Context, id pgtype.UUID) (Namespace, error) {
	row := q.db.QueryRow(ctx, getNamespace, id)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNamespaceByName = `-- name: GetNamespaceByName :one
SELECT id, name, owner_id, visibility, created_at, updated_at FROM namespace WHERE name = $1
`

func (q *Queries) GetNamespaceByName(ctx context.Context, name string) (Namespace, error) {
	row := q.db.QueryRow(ctx, getNamespaceByName, name)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNamespaces = `-- name: ListNamespaces :many
SELECT id, name, owner_id, visibility, created_at, updated_at FROM namespace
WHERE (
    $1::boolean = true
    OR visibility = 'public'
    OR ($2::uuid IS NOT NULL AND owner_id = $2::uuid)
)
ORDER BY created_at ASC
`

type ListNamespacesParams struct {
	IsAdmin pgtype.Bool `json:"is_admin"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListNamespaces(ctx context.Context, arg ListNamespacesParams) ([]Namespace, error) {
	rows, err := q.db.Query(ctx, listNamespaces, arg.IsAdmin, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Namespace{}
	for rows.Next() {
		var i Namespace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNamespace = `-- name: UpdateNamespace :one
UPDATE namespace
SET name       = $2,
    owner_id   = $3,
    visibility = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, name, owner_id, visibility, created_at, updated_at
`

type UpdateNamespaceParams struct {
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	OwnerID    pgtype.UUID `json:"owner_id"`
	Visibility string      `json:"visibility"`
}

func (q *Queries) UpdateNamespace(ctx context.Context, arg UpdateNamespaceParams) (Namespace, error) {
	row := q.db.QueryRow(ctx, updateNamespace,
		arg.ID,
		arg.Name,
		arg.OwnerID,
		arg.Visibility,
	)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
