// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provenance_drift.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestProvenanceDrift = `-- name: GetLatestProvenanceDrift :one
SELECT id, sbom_id, previous_status, new_status, reason, previous_data, new_data, detected_at
FROM provenance_drift_events
WHERE sbom_id = $1
ORDER BY detected_at DESC
LIMIT 1
`

func (q *Queries) GetLatestProvenanceDrift(ctx context.Context, sbomID pgtype.UUID) (ProvenanceDriftEvent, error) {
	row := q.db.QueryRow(ctx, getLatestProvenanceDrift, sbomID)
	var i ProvenanceDriftEvent
	err := row.Scan(
		&i.ID,
		&i.SbomID,
		&i.PreviousStatus,
		&i.NewStatus,
		&i.Reason,
		&i.PreviousData,
		&i.NewData,
		&i.DetectedAt,
	)
	return i, err
}

const insertProvenanceDrift = `-- name: InsertProvenanceDrift :exec
INSERT INTO provenance_drift_events (sbom_id, previous_status, new_status, reason, previous_data, new_data)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertProvenanceDriftParams struct {
	SbomID         pgtype.UUID `json:"sbom_id"`
	PreviousStatus string      `json:"previous_status"`
	NewStatus      string      `json:"new_status"`
	Reason         string      `json:"reason"`
	PreviousData   []byte      `json:"previous_data"`
	NewData        []byte      `json:"new_data"`
}

func (q *Queries) InsertProvenanceDrift(ctx context.Context, arg InsertProvenanceDriftParams) error {
	_, err := q.db.Exec(ctx, insertProvenanceDrift,
		arg.SbomID,
		arg.PreviousStatus,
		arg.NewStatus,
		arg.Reason,
		arg.PreviousData,
		arg.NewData,
	)
	return err
}
