// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provenance_drift.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestProvenanceDrift = `-- name: GetLatestProvenanceDrift :one
SELECT id, sbom_id, previous_status, new_status, reason, previous_data, new_data, detected_at
FROM provenance_drift_events
WHERE sbom_id = $1
ORDER BY detected_at DESC
LIMIT 1
`

func (q *Queries) GetLatestProvenanceDrift(ctx context.Context, sbomID pgtype.UUID) (ProvenanceDriftEvent, error) {
	row := q.db.QueryRow(ctx, getLatestProvenanceDrift, sbomID)
	var i ProvenanceDriftEvent
	err := row.Scan(
		&i.ID,
		&i.SbomID,
		&i.PreviousStatus,
		&i.NewStatus,
		&i.Reason,
		&i.PreviousData,
		&i.NewData,
		&i.DetectedAt,
	)
	return i, err
}

const insertProvenanceDrift = `-- name: InsertProvenanceDrift :exec
INSERT INTO provenance_drift_events (sbom_id, previous_status, new_status, reason, previous_data, new_data)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertProvenanceDriftParams struct {
	SbomID         pgtype.UUID `json:"sbom_id"`
	PreviousStatus string      `json:"previous_status"`
	NewStatus      string      `json:"new_status"`
	Reason         string      `json:"reason"`
	PreviousData   []byte      `json:"previous_data"`
	NewData        []byte      `json:"new_data"`
}

func (q *Queries) InsertProvenanceDrift(ctx context.Context, arg InsertProvenanceDriftParams) error {
	_, err := q.db.Exec(ctx, insertProvenanceDrift,
		arg.SbomID,
		arg.PreviousStatus,
		arg.NewStatus,
		arg.Reason,
		arg.PreviousData,
		arg.NewData,
	)
	return err
}

const listProvenanceDriftBySBOM = `-- name: ListProvenanceDriftBySBOM :many
SELECT id, sbom_id, previous_status, new_status, reason, detected_at,
       COUNT(*) OVER() AS total_count
FROM provenance_drift_events
WHERE sbom_id = $1
ORDER BY detected_at DESC
LIMIT $3 OFFSET $2
`

type ListProvenanceDriftBySBOMParams struct {
	SbomID    pgtype.UUID `json:"sbom_id"`
	RowOffset int32       `json:"row_offset"`
	RowLimit  int32       `json:"row_limit"`
}

type ListProvenanceDriftBySBOMRow struct {
	ID             pgtype.UUID        `json:"id"`
	SbomID         pgtype.UUID        `json:"sbom_id"`
	PreviousStatus string             `json:"previous_status"`
	NewStatus      string             `json:"new_status"`
	Reason         string             `json:"reason"`
	DetectedAt     pgtype.Timestamptz `json:"detected_at"`
	TotalCount     int64              `json:"total_count"`
}

func (q *Queries) ListProvenanceDriftBySBOM(ctx context.Context, arg ListProvenanceDriftBySBOMParams) ([]ListProvenanceDriftBySBOMRow, error) {
	rows, err := q.db.Query(ctx, listProvenanceDriftBySBOM, arg.SbomID, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProvenanceDriftBySBOMRow{}
	for rows.Next() {
		var i ListProvenanceDriftBySBOMRow
		if err := rows.Scan(
			&i.ID,
			&i.SbomID,
			&i.PreviousStatus,
			&i.NewStatus,
			&i.Reason,
			&i.DetectedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentProvenanceDrift = `-- name: ListRecentProvenanceDrift :many
SELECT
    d.id, d.sbom_id, d.previous_status, d.new_status, d.reason, d.detected_at,
    s.source_id, s.artifact_id,
    a.name AS artifact_name, a.type AS artifact_type,
    src.name AS source_name,
    COUNT(*) OVER() AS total_count
FROM provenance_drift_events d
JOIN sbom s ON s.id = d.sbom_id
LEFT JOIN artifact a ON a.id = s.artifact_id
LEFT JOIN source src ON src.id = s.source_id
ORDER BY d.detected_at DESC
LIMIT $2 OFFSET $1
`

type ListRecentProvenanceDriftParams struct {
	RowOffset int32 `json:"row_offset"`
	RowLimit  int32 `json:"row_limit"`
}

type ListRecentProvenanceDriftRow struct {
	ID             pgtype.UUID        `json:"id"`
	SbomID         pgtype.UUID        `json:"sbom_id"`
	PreviousStatus string             `json:"previous_status"`
	NewStatus      string             `json:"new_status"`
	Reason         string             `json:"reason"`
	DetectedAt     pgtype.Timestamptz `json:"detected_at"`
	SourceID       pgtype.UUID        `json:"source_id"`
	ArtifactID     pgtype.UUID        `json:"artifact_id"`
	ArtifactName   pgtype.Text        `json:"artifact_name"`
	ArtifactType   pgtype.Text        `json:"artifact_type"`
	SourceName     pgtype.Text        `json:"source_name"`
	TotalCount     int64              `json:"total_count"`
}

func (q *Queries) ListRecentProvenanceDrift(ctx context.Context, arg ListRecentProvenanceDriftParams) ([]ListRecentProvenanceDriftRow, error) {
	rows, err := q.db.Query(ctx, listRecentProvenanceDrift, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentProvenanceDriftRow{}
	for rows.Next() {
		var i ListRecentProvenanceDriftRow
		if err := rows.Scan(
			&i.ID,
			&i.SbomID,
			&i.PreviousStatus,
			&i.NewStatus,
			&i.Reason,
			&i.DetectedAt,
			&i.SourceID,
			&i.ArtifactID,
			&i.ArtifactName,
			&i.ArtifactType,
			&i.SourceName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
