// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registry.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRegistry = `-- name: CreateRegistry :one

WITH new_id AS (
    SELECT gen_random_uuid() AS id
),
ns AS (
    INSERT INTO namespace (id, name, owner_id, visibility)
    SELECT n.id, $19::text, $20::uuid, $21::text
    FROM new_id n
    WHERE $22::uuid IS NULL
    RETURNING id
),
target_ns AS (
    SELECT COALESCE($22::uuid, (SELECT id FROM ns)) AS id
),
src AS (
    INSERT INTO source (id, namespace_id, kind, name)
    SELECT n.id, t.id, 'oci_registry', $19::text FROM new_id n, target_ns t
    RETURNING id
)
INSERT INTO registry (
    id, type, url, insecure, webhook_secret, repository_patterns, tag_patterns,
    scan_mode, poll_interval_minutes, repositories, auth_username, auth_token,
    include_untagged, verification_mode, trust_public_key, trust_identity,
    trust_issuer, managed_by, managed_ref
)
SELECT
    src.id, $1::text, $2::text, $3::boolean, $4::text,
    $5::text[], $6::text[], $7::text,
    $8::int, $9::text[], $10::text,
    $11::text, $12::boolean, $13::text,
    $14::text, $15::text, $16::text,
    $17::text, $18::text
FROM src
RETURNING id, type, url, insecure, webhook_secret, enabled, created_at, updated_at, repository_patterns, tag_patterns, scan_mode, poll_interval_minutes, last_polled_at, repositories, auth_username, auth_token, include_untagged, verification_mode, trust_public_key, trust_identity, trust_issuer, managed_by, managed_ref
`

type CreateRegistryParams struct {
	Type                string      `json:"type"`
	Url                 string      `json:"url"`
	Insecure            bool        `json:"insecure"`
	WebhookSecret       pgtype.Text `json:"webhook_secret"`
	RepositoryPatterns  []string    `json:"repository_patterns"`
	TagPatterns         []string    `json:"tag_patterns"`
	ScanMode            string      `json:"scan_mode"`
	PollIntervalMinutes int32       `json:"poll_interval_minutes"`
	Repositories        []string    `json:"repositories"`
	AuthUsername        pgtype.Text `json:"auth_username"`
	AuthToken           pgtype.Text `json:"auth_token"`
	IncludeUntagged     bool        `json:"include_untagged"`
	VerificationMode    string      `json:"verification_mode"`
	TrustPublicKey      pgtype.Text `json:"trust_public_key"`
	TrustIdentity       pgtype.Text `json:"trust_identity"`
	TrustIssuer         pgtype.Text `json:"trust_issuer"`
	ManagedBy           pgtype.Text `json:"managed_by"`
	ManagedRef          pgtype.Text `json:"managed_ref"`
	Name                string      `json:"name"`
	OwnerID             pgtype.UUID `json:"owner_id"`
	Visibility          string      `json:"visibility"`
	NamespaceID         pgtype.UUID `json:"namespace_id"`
}

// Registry is the oci_registry subtype of source (ADR-039): it holds discovery
// config and trust policy only. Its id *is* the source id, which is also the
// namespace id for registries created here. Name, owner and visibility live on
// namespace and are joined back in on read so the API surface is unchanged.
// Writes namespace, source and registry in one statement. Data-modifying CTEs
// share a snapshot and FK triggers fire once at statement end, so the three
// rows may reference each other.
//
// When namespace_id is NULL the registry gets a namespace of its own named
// after it, and all three rows share an id — the shape migration 00053 produced
// for pre-existing registries. When namespace_id is supplied (the operator
// defaulting an OCIDex namespace from the CR's K8s namespace) only source and
// registry are written, and they share an id inside the existing namespace.
func (q *Queries) CreateRegistry(ctx context.Context, arg CreateRegistryParams) (Registry, error) {
	row := q.db.QueryRow(ctx, createRegistry,
		arg.Type,
		arg.Url,
		arg.Insecure,
		arg.WebhookSecret,
		arg.RepositoryPatterns,
		arg.TagPatterns,
		arg.ScanMode,
		arg.PollIntervalMinutes,
		arg.Repositories,
		arg.AuthUsername,
		arg.AuthToken,
		arg.IncludeUntagged,
		arg.VerificationMode,
		arg.TrustPublicKey,
		arg.TrustIdentity,
		arg.TrustIssuer,
		arg.ManagedBy,
		arg.ManagedRef,
		arg.Name,
		arg.OwnerID,
		arg.Visibility,
		arg.NamespaceID,
	)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Url,
		&i.Insecure,
		&i.WebhookSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepositoryPatterns,
		&i.TagPatterns,
		&i.ScanMode,
		&i.PollIntervalMinutes,
		&i.LastPolledAt,
		&i.Repositories,
		&i.AuthUsername,
		&i.AuthToken,
		&i.IncludeUntagged,
		&i.VerificationMode,
		&i.TrustPublicKey,
		&i.TrustIdentity,
		&i.TrustIssuer,
		&i.ManagedBy,
		&i.ManagedRef,
	)
	return i, err
}

const deleteRegistry = `-- name: DeleteRegistry :execrows
DELETE FROM source WHERE id = $1
`

// Deletes the source, which cascades to this registry row. The namespace and
// its SBOMs survive: previously dropping a registry NULLed sbom.registry_id and
// a NULL registry was visible to everyone.
func (q *Queries) DeleteRegistry(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRegistry, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRegistry = `-- name: GetRegistry :one
SELECT r.id, r.type, r.url, r.insecure, r.webhook_secret, r.enabled, r.created_at, r.updated_at, r.repository_patterns, r.tag_patterns, r.scan_mode, r.poll_interval_minutes, r.last_polled_at, r.repositories, r.auth_username, r.auth_token, r.include_untagged, r.verification_mode, r.trust_public_key, r.trust_identity, r.trust_issuer, r.managed_by, r.managed_ref, src.name, n.owner_id, n.visibility
FROM registry r
JOIN source src ON src.id = r.id
JOIN namespace n ON n.id = src.namespace_id
WHERE r.id = $1
`

type GetRegistryRow struct {
	Registry   Registry    `json:"registry"`
	Name       string      `json:"name"`
	OwnerID    pgtype.UUID `json:"owner_id"`
	Visibility string      `json:"visibility"`
}

func (q *Queries) GetRegistry(ctx context.Context, id pgtype.UUID) (GetRegistryRow, error) {
	row := q.db.QueryRow(ctx, getRegistry, id)
	var i GetRegistryRow
	err := row.Scan(
		&i.Registry.ID,
		&i.Registry.Type,
		&i.Registry.Url,
		&i.Registry.Insecure,
		&i.Registry.WebhookSecret,
		&i.Registry.Enabled,
		&i.Registry.CreatedAt,
		&i.Registry.UpdatedAt,
		&i.Registry.RepositoryPatterns,
		&i.Registry.TagPatterns,
		&i.Registry.ScanMode,
		&i.Registry.PollIntervalMinutes,
		&i.Registry.LastPolledAt,
		&i.Registry.Repositories,
		&i.Registry.AuthUsername,
		&i.Registry.AuthToken,
		&i.Registry.IncludeUntagged,
		&i.Registry.VerificationMode,
		&i.Registry.TrustPublicKey,
		&i.Registry.TrustIdentity,
		&i.Registry.TrustIssuer,
		&i.Registry.ManagedBy,
		&i.Registry.ManagedRef,
		&i.Name,
		&i.OwnerID,
		&i.Visibility,
	)
	return i, err
}

const getRegistryByName = `-- name: GetRegistryByName :one
SELECT r.id, r.type, r.url, r.insecure, r.webhook_secret, r.enabled, r.created_at, r.updated_at, r.repository_patterns, r.tag_patterns, r.scan_mode, r.poll_interval_minutes, r.last_polled_at, r.repositories, r.auth_username, r.auth_token, r.include_untagged, r.verification_mode, r.trust_public_key, r.trust_identity, r.trust_issuer, r.managed_by, r.managed_ref, src.name, n.owner_id, n.visibility
FROM registry r
JOIN source src ON src.id = r.id
JOIN namespace n ON n.id = src.namespace_id
WHERE src.name = $1
ORDER BY r.created_at ASC
LIMIT 1
`

type GetRegistryByNameRow struct {
	Registry   Registry    `json:"registry"`
	Name       string      `json:"name"`
	OwnerID    pgtype.UUID `json:"owner_id"`
	Visibility string      `json:"visibility"`
}

// Matches on the source name, which is what the caller supplied as the registry
// name. source.name is unique per namespace, not globally, so once registries
// share a namespace this can in principle match more than one row; the oldest
// wins. Callers that need an exact handle should use the id.
func (q *Queries) GetRegistryByName(ctx context.Context, name string) (GetRegistryByNameRow, error) {
	row := q.db.QueryRow(ctx, getRegistryByName, name)
	var i GetRegistryByNameRow
	err := row.Scan(
		&i.Registry.ID,
		&i.Registry.Type,
		&i.Registry.Url,
		&i.Registry.Insecure,
		&i.Registry.WebhookSecret,
		&i.Registry.Enabled,
		&i.Registry.CreatedAt,
		&i.Registry.UpdatedAt,
		&i.Registry.RepositoryPatterns,
		&i.Registry.TagPatterns,
		&i.Registry.ScanMode,
		&i.Registry.PollIntervalMinutes,
		&i.Registry.LastPolledAt,
		&i.Registry.Repositories,
		&i.Registry.AuthUsername,
		&i.Registry.AuthToken,
		&i.Registry.IncludeUntagged,
		&i.Registry.VerificationMode,
		&i.Registry.TrustPublicKey,
		&i.Registry.TrustIdentity,
		&i.Registry.TrustIssuer,
		&i.Registry.ManagedBy,
		&i.Registry.ManagedRef,
		&i.Name,
		&i.OwnerID,
		&i.Visibility,
	)
	return i, err
}

const listPollableRegistries = `-- name: ListPollableRegistries :many
SELECT r.id, r.type, r.url, r.insecure, r.webhook_secret, r.enabled, r.created_at, r.updated_at, r.repository_patterns, r.tag_patterns, r.scan_mode, r.poll_interval_minutes, r.last_polled_at, r.repositories, r.auth_username, r.auth_token, r.include_untagged, r.verification_mode, r.trust_public_key, r.trust_identity, r.trust_issuer, r.managed_by, r.managed_ref, src.name, n.owner_id, n.visibility
FROM registry r
JOIN source src ON src.id = r.id
JOIN namespace n ON n.id = src.namespace_id
WHERE r.enabled = true AND r.scan_mode IN ('poll', 'both')
ORDER BY r.created_at ASC
`

type ListPollableRegistriesRow struct {
	Registry   Registry    `json:"registry"`
	Name       string      `json:"name"`
	OwnerID    pgtype.UUID `json:"owner_id"`
	Visibility string      `json:"visibility"`
}

func (q *Queries) ListPollableRegistries(ctx context.Context) ([]ListPollableRegistriesRow, error) {
	rows, err := q.db.Query(ctx, listPollableRegistries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPollableRegistriesRow{}
	for rows.Next() {
		var i ListPollableRegistriesRow
		if err := rows.Scan(
			&i.Registry.ID,
			&i.Registry.Type,
			&i.Registry.Url,
			&i.Registry.Insecure,
			&i.Registry.WebhookSecret,
			&i.Registry.Enabled,
			&i.Registry.CreatedAt,
			&i.Registry.UpdatedAt,
			&i.Registry.RepositoryPatterns,
			&i.Registry.TagPatterns,
			&i.Registry.ScanMode,
			&i.Registry.PollIntervalMinutes,
			&i.Registry.LastPolledAt,
			&i.Registry.Repositories,
			&i.Registry.AuthUsername,
			&i.Registry.AuthToken,
			&i.Registry.IncludeUntagged,
			&i.Registry.VerificationMode,
			&i.Registry.TrustPublicKey,
			&i.Registry.TrustIdentity,
			&i.Registry.TrustIssuer,
			&i.Registry.ManagedBy,
			&i.Registry.ManagedRef,
			&i.Name,
			&i.OwnerID,
			&i.Visibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistries = `-- name: ListRegistries :many
SELECT r.id, r.type, r.url, r.insecure, r.webhook_secret, r.enabled, r.created_at, r.updated_at, r.repository_patterns, r.tag_patterns, r.scan_mode, r.poll_interval_minutes, r.last_polled_at, r.repositories, r.auth_username, r.auth_token, r.include_untagged, r.verification_mode, r.trust_public_key, r.trust_identity, r.trust_issuer, r.managed_by, r.managed_ref, src.name, n.owner_id, n.visibility
FROM registry r
JOIN source src ON src.id = r.id
JOIN namespace n ON n.id = src.namespace_id
WHERE (
    $1::boolean = true
    OR n.visibility = 'public'
    OR ($2::uuid IS NOT NULL AND n.owner_id = $2::uuid)
)
ORDER BY r.created_at ASC
`

type ListRegistriesParams struct {
	IsAdmin pgtype.Bool `json:"is_admin"`
	UserID  pgtype.UUID `json:"user_id"`
}

type ListRegistriesRow struct {
	Registry   Registry    `json:"registry"`
	Name       string      `json:"name"`
	OwnerID    pgtype.UUID `json:"owner_id"`
	Visibility string      `json:"visibility"`
}

func (q *Queries) ListRegistries(ctx context.Context, arg ListRegistriesParams) ([]ListRegistriesRow, error) {
	rows, err := q.db.Query(ctx, listRegistries, arg.IsAdmin, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRegistriesRow{}
	for rows.Next() {
		var i ListRegistriesRow
		if err := rows.Scan(
			&i.Registry.ID,
			&i.Registry.Type,
			&i.Registry.Url,
			&i.Registry.Insecure,
			&i.Registry.WebhookSecret,
			&i.Registry.Enabled,
			&i.Registry.CreatedAt,
			&i.Registry.UpdatedAt,
			&i.Registry.RepositoryPatterns,
			&i.Registry.TagPatterns,
			&i.Registry.ScanMode,
			&i.Registry.PollIntervalMinutes,
			&i.Registry.LastPolledAt,
			&i.Registry.Repositories,
			&i.Registry.AuthUsername,
			&i.Registry.AuthToken,
			&i.Registry.IncludeUntagged,
			&i.Registry.VerificationMode,
			&i.Registry.TrustPublicKey,
			&i.Registry.TrustIdentity,
			&i.Registry.TrustIssuer,
			&i.Registry.ManagedBy,
			&i.Registry.ManagedRef,
			&i.Name,
			&i.OwnerID,
			&i.Visibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistriesPaged = `-- name: ListRegistriesPaged :many
SELECT r.id, r.type, r.url, r.insecure, r.webhook_secret, r.enabled, r.created_at, r.updated_at, r.repository_patterns, r.tag_patterns, r.scan_mode, r.poll_interval_minutes, r.last_polled_at, r.repositories, r.auth_username, r.auth_token, r.include_untagged, r.verification_mode, r.trust_public_key, r.trust_identity, r.trust_issuer, r.managed_by, r.managed_ref, src.name, n.owner_id, n.visibility, COUNT(*) OVER() AS total_count
FROM registry r
JOIN source src ON src.id = r.id
JOIN namespace n ON n.id = src.namespace_id
WHERE (
    CASE WHEN COALESCE($1::boolean, false)
         THEN n.owner_id = $2::uuid
         ELSE $3::boolean = true
              OR n.visibility = 'public'
              OR ($2::uuid IS NOT NULL AND n.owner_id = $2::uuid)
    END
)
ORDER BY r.created_at ASC
LIMIT $5 OFFSET $4
`

type ListRegistriesPagedParams struct {
	OwnedOnly pgtype.Bool `json:"owned_only"`
	UserID    pgtype.UUID `json:"user_id"`
	IsAdmin   pgtype.Bool `json:"is_admin"`
	RowOffset int32       `json:"row_offset"`
	RowLimit  int32       `json:"row_limit"`
}

type ListRegistriesPagedRow struct {
	Registry   Registry    `json:"registry"`
	Name       string      `json:"name"`
	OwnerID    pgtype.UUID `json:"owner_id"`
	Visibility string      `json:"visibility"`
	TotalCount int64       `json:"total_count"`
}

// owned_only switches from the visibility path to the ownership path, which is
// what /api/v1/users/me/registries needs — see ListNamespaces.
func (q *Queries) ListRegistriesPaged(ctx context.Context, arg ListRegistriesPagedParams) ([]ListRegistriesPagedRow, error) {
	rows, err := q.db.Query(ctx, listRegistriesPaged,
		arg.OwnedOnly,
		arg.UserID,
		arg.IsAdmin,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRegistriesPagedRow{}
	for rows.Next() {
		var i ListRegistriesPagedRow
		if err := rows.Scan(
			&i.Registry.ID,
			&i.Registry.Type,
			&i.Registry.Url,
			&i.Registry.Insecure,
			&i.Registry.WebhookSecret,
			&i.Registry.Enabled,
			&i.Registry.CreatedAt,
			&i.Registry.UpdatedAt,
			&i.Registry.RepositoryPatterns,
			&i.Registry.TagPatterns,
			&i.Registry.ScanMode,
			&i.Registry.PollIntervalMinutes,
			&i.Registry.LastPolledAt,
			&i.Registry.Repositories,
			&i.Registry.AuthUsername,
			&i.Registry.AuthToken,
			&i.Registry.IncludeUntagged,
			&i.Registry.VerificationMode,
			&i.Registry.TrustPublicKey,
			&i.Registry.TrustIdentity,
			&i.Registry.TrustIssuer,
			&i.Registry.ManagedBy,
			&i.Registry.ManagedRef,
			&i.Name,
			&i.OwnerID,
			&i.Visibility,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistryTrustSummary = `-- name: ListRegistryTrustSummary :many
WITH latest_provenance AS (
    SELECT DISTINCT ON (s.source_id, s.artifact_id)
        s.source_id,
        signing_status(p.data) AS signing_status
    FROM sbom s
    JOIN registry rg ON rg.id = s.source_id
    LEFT JOIN enrichment p ON p.sbom_id = s.id AND p.enricher_name = 'provenance' AND p.status = 'success'
    WHERE s.artifact_id IS NOT NULL
      AND s.namespace_id IN (
          SELECT visible_namespace_ids($1::uuid, $2::boolean))
    ORDER BY s.source_id, s.artifact_id, s.created_at DESC
)
SELECT source_id AS registry_id, signing_status, COUNT(*) AS artifact_count
FROM latest_provenance
GROUP BY source_id, signing_status
ORDER BY source_id, signing_status
`

type ListRegistryTrustSummaryParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	IsAdmin pgtype.Bool `json:"is_admin"`
}

type ListRegistryTrustSummaryRow struct {
	RegistryID    pgtype.UUID `json:"registry_id"`
	SigningStatus string      `json:"signing_status"`
	ArtifactCount int64       `json:"artifact_count"`
}

// Per-registry counts across the five signing statuses, one row per
// (registry, status) with a nonzero count. Derives each artifact's *current*
// status from its most recently created SBOM per source — reuses the
// signing_status() function from ocidex-82g.3 rather than re-deriving. The join
// to registry restricts this to OCI sources; an upload source has no trust
// config to summarise. Scoped to the caller's visible namespaces so a namespace
// owner can read their own signing posture without the admin role.
func (q *Queries) ListRegistryTrustSummary(ctx context.Context, arg ListRegistryTrustSummaryParams) ([]ListRegistryTrustSummaryRow, error) {
	rows, err := q.db.Query(ctx, listRegistryTrustSummary, arg.UserID, arg.IsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRegistryTrustSummaryRow{}
	for rows.Next() {
		var i ListRegistryTrustSummaryRow
		if err := rows.Scan(&i.RegistryID, &i.SigningStatus, &i.ArtifactCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRegistryEnabled = `-- name: SetRegistryEnabled :one
UPDATE registry
SET enabled    = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, type, url, insecure, webhook_secret, enabled, created_at, updated_at, repository_patterns, tag_patterns, scan_mode, poll_interval_minutes, last_polled_at, repositories, auth_username, auth_token, include_untagged, verification_mode, trust_public_key, trust_identity, trust_issuer, managed_by, managed_ref
`

type SetRegistryEnabledParams struct {
	ID      pgtype.UUID `json:"id"`
	Enabled bool        `json:"enabled"`
}

func (q *Queries) SetRegistryEnabled(ctx context.Context, arg SetRegistryEnabledParams) (Registry, error) {
	row := q.db.QueryRow(ctx, setRegistryEnabled, arg.ID, arg.Enabled)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Url,
		&i.Insecure,
		&i.WebhookSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepositoryPatterns,
		&i.TagPatterns,
		&i.ScanMode,
		&i.PollIntervalMinutes,
		&i.LastPolledAt,
		&i.Repositories,
		&i.AuthUsername,
		&i.AuthToken,
		&i.IncludeUntagged,
		&i.VerificationMode,
		&i.TrustPublicKey,
		&i.TrustIdentity,
		&i.TrustIssuer,
		&i.ManagedBy,
		&i.ManagedRef,
	)
	return i, err
}

const updateRegistry = `-- name: UpdateRegistry :one
WITH ns AS (
    UPDATE namespace
    SET name       = $21::text,
        visibility = $22::text,
        updated_at = now()
    WHERE namespace.id = $20
    RETURNING namespace.id
),
src AS (
    UPDATE source
    SET name       = $21::text,
        updated_at = now()
    WHERE source.id = $20
    RETURNING source.id
)
UPDATE registry
SET type                  = $1::text,
    url                   = $2::text,
    insecure              = $3::boolean,
    webhook_secret        = $4::text,
    enabled               = $5::boolean,
    repository_patterns   = $6::text[],
    tag_patterns          = $7::text[],
    scan_mode             = $8::text,
    poll_interval_minutes = $9::int,
    repositories          = $10::text[],
    auth_username         = $11::text,
    auth_token            = $12::text,
    include_untagged      = $13::boolean,
    verification_mode     = $14::text,
    trust_public_key      = $15::text,
    trust_identity        = $16::text,
    trust_issuer          = $17::text,
    managed_by            = $18::text,
    managed_ref           = $19::text,
    updated_at            = now()
WHERE registry.id = $20
RETURNING id, type, url, insecure, webhook_secret, enabled, created_at, updated_at, repository_patterns, tag_patterns, scan_mode, poll_interval_minutes, last_polled_at, repositories, auth_username, auth_token, include_untagged, verification_mode, trust_public_key, trust_identity, trust_issuer, managed_by, managed_ref
`

type UpdateRegistryParams struct {
	Type                string      `json:"type"`
	Url                 string      `json:"url"`
	Insecure            bool        `json:"insecure"`
	WebhookSecret       pgtype.Text `json:"webhook_secret"`
	Enabled             bool        `json:"enabled"`
	RepositoryPatterns  []string    `json:"repository_patterns"`
	TagPatterns         []string    `json:"tag_patterns"`
	ScanMode            string      `json:"scan_mode"`
	PollIntervalMinutes int32       `json:"poll_interval_minutes"`
	Repositories        []string    `json:"repositories"`
	AuthUsername        pgtype.Text `json:"auth_username"`
	AuthToken           pgtype.Text `json:"auth_token"`
	IncludeUntagged     bool        `json:"include_untagged"`
	VerificationMode    string      `json:"verification_mode"`
	TrustPublicKey      pgtype.Text `json:"trust_public_key"`
	TrustIdentity       pgtype.Text `json:"trust_identity"`
	TrustIssuer         pgtype.Text `json:"trust_issuer"`
	ManagedBy           pgtype.Text `json:"managed_by"`
	ManagedRef          pgtype.Text `json:"managed_ref"`
	ID                  pgtype.UUID `json:"id"`
	Name                string      `json:"name"`
	Visibility          string      `json:"visibility"`
}

// Mirror of CreateRegistry: the channel name lands on source, everything else
// on registry, in one statement.
//
// Name and visibility only propagate to the namespace when the registry owns it
// outright — the id-sharing case CreateRegistry produces for a registry with no
// explicit namespace. A registry that was created into an existing namespace
// must not rename it or flip its visibility out from under its siblings; that
// goes through PATCH /api/v1/namespaces/{id}.
func (q *Queries) UpdateRegistry(ctx context.Context, arg UpdateRegistryParams) (Registry, error) {
	row := q.db.QueryRow(ctx, updateRegistry,
		arg.Type,
		arg.Url,
		arg.Insecure,
		arg.WebhookSecret,
		arg.Enabled,
		arg.RepositoryPatterns,
		arg.TagPatterns,
		arg.ScanMode,
		arg.PollIntervalMinutes,
		arg.Repositories,
		arg.AuthUsername,
		arg.AuthToken,
		arg.IncludeUntagged,
		arg.VerificationMode,
		arg.TrustPublicKey,
		arg.TrustIdentity,
		arg.TrustIssuer,
		arg.ManagedBy,
		arg.ManagedRef,
		arg.ID,
		arg.Name,
		arg.Visibility,
	)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Url,
		&i.Insecure,
		&i.WebhookSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepositoryPatterns,
		&i.TagPatterns,
		&i.ScanMode,
		&i.PollIntervalMinutes,
		&i.LastPolledAt,
		&i.Repositories,
		&i.AuthUsername,
		&i.AuthToken,
		&i.IncludeUntagged,
		&i.VerificationMode,
		&i.TrustPublicKey,
		&i.TrustIdentity,
		&i.TrustIssuer,
		&i.ManagedBy,
		&i.ManagedRef,
	)
	return i, err
}

const updateRegistryLastPolled = `-- name: UpdateRegistryLastPolled :one
UPDATE registry
SET last_polled_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, type, url, insecure, webhook_secret, enabled, created_at, updated_at, repository_patterns, tag_patterns, scan_mode, poll_interval_minutes, last_polled_at, repositories, auth_username, auth_token, include_untagged, verification_mode, trust_public_key, trust_identity, trust_issuer, managed_by, managed_ref
`

func (q *Queries) UpdateRegistryLastPolled(ctx context.Context, id pgtype.UUID) (Registry, error) {
	row := q.db.QueryRow(ctx, updateRegistryLastPolled, id)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Url,
		&i.Insecure,
		&i.WebhookSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepositoryPatterns,
		&i.TagPatterns,
		&i.ScanMode,
		&i.PollIntervalMinutes,
		&i.LastPolledAt,
		&i.Repositories,
		&i.AuthUsername,
		&i.AuthToken,
		&i.IncludeUntagged,
		&i.VerificationMode,
		&i.TrustPublicKey,
		&i.TrustIdentity,
		&i.TrustIssuer,
		&i.ManagedBy,
		&i.ManagedRef,
	)
	return i, err
}
