// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registry.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRegistry = `-- name: CreateRegistry :one
INSERT INTO registry (name, type, url, insecure, webhook_secret, repository_patterns, tag_patterns)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, type, url, insecure, webhook_secret, enabled, created_at, updated_at, repository_patterns, tag_patterns
`

type CreateRegistryParams struct {
	Name               string      `json:"name"`
	Type               string      `json:"type"`
	Url                string      `json:"url"`
	Insecure           bool        `json:"insecure"`
	WebhookSecret      pgtype.Text `json:"webhook_secret"`
	RepositoryPatterns []string    `json:"repository_patterns"`
	TagPatterns        []string    `json:"tag_patterns"`
}

func (q *Queries) CreateRegistry(ctx context.Context, arg CreateRegistryParams) (Registry, error) {
	row := q.db.QueryRow(ctx, createRegistry,
		arg.Name,
		arg.Type,
		arg.Url,
		arg.Insecure,
		arg.WebhookSecret,
		arg.RepositoryPatterns,
		arg.TagPatterns,
	)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.Insecure,
		&i.WebhookSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepositoryPatterns,
		&i.TagPatterns,
	)
	return i, err
}

const deleteRegistry = `-- name: DeleteRegistry :execrows
DELETE FROM registry WHERE id = $1
`

func (q *Queries) DeleteRegistry(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRegistry, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRegistry = `-- name: GetRegistry :one
SELECT id, name, type, url, insecure, webhook_secret, enabled, created_at, updated_at, repository_patterns, tag_patterns FROM registry WHERE id = $1
`

func (q *Queries) GetRegistry(ctx context.Context, id pgtype.UUID) (Registry, error) {
	row := q.db.QueryRow(ctx, getRegistry, id)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.Insecure,
		&i.WebhookSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepositoryPatterns,
		&i.TagPatterns,
	)
	return i, err
}

const listRegistries = `-- name: ListRegistries :many
SELECT id, name, type, url, insecure, webhook_secret, enabled, created_at, updated_at, repository_patterns, tag_patterns FROM registry ORDER BY created_at ASC
`

func (q *Queries) ListRegistries(ctx context.Context) ([]Registry, error) {
	rows, err := q.db.Query(ctx, listRegistries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Registry{}
	for rows.Next() {
		var i Registry
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Url,
			&i.Insecure,
			&i.WebhookSecret,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RepositoryPatterns,
			&i.TagPatterns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRegistryEnabled = `-- name: SetRegistryEnabled :one
UPDATE registry
SET enabled    = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, name, type, url, insecure, webhook_secret, enabled, created_at, updated_at, repository_patterns, tag_patterns
`

type SetRegistryEnabledParams struct {
	ID      pgtype.UUID `json:"id"`
	Enabled bool        `json:"enabled"`
}

func (q *Queries) SetRegistryEnabled(ctx context.Context, arg SetRegistryEnabledParams) (Registry, error) {
	row := q.db.QueryRow(ctx, setRegistryEnabled, arg.ID, arg.Enabled)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.Insecure,
		&i.WebhookSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepositoryPatterns,
		&i.TagPatterns,
	)
	return i, err
}

const updateRegistry = `-- name: UpdateRegistry :one
UPDATE registry
SET name                = $2,
    type                = $3,
    url                 = $4,
    insecure            = $5,
    webhook_secret      = $6,
    enabled             = $7,
    repository_patterns = $8,
    tag_patterns        = $9,
    updated_at          = now()
WHERE id = $1
RETURNING id, name, type, url, insecure, webhook_secret, enabled, created_at, updated_at, repository_patterns, tag_patterns
`

type UpdateRegistryParams struct {
	ID                 pgtype.UUID `json:"id"`
	Name               string      `json:"name"`
	Type               string      `json:"type"`
	Url                string      `json:"url"`
	Insecure           bool        `json:"insecure"`
	WebhookSecret      pgtype.Text `json:"webhook_secret"`
	Enabled            bool        `json:"enabled"`
	RepositoryPatterns []string    `json:"repository_patterns"`
	TagPatterns        []string    `json:"tag_patterns"`
}

func (q *Queries) UpdateRegistry(ctx context.Context, arg UpdateRegistryParams) (Registry, error) {
	row := q.db.QueryRow(ctx, updateRegistry,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Url,
		arg.Insecure,
		arg.WebhookSecret,
		arg.Enabled,
		arg.RepositoryPatterns,
		arg.TagPatterns,
	)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.Insecure,
		&i.WebhookSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepositoryPatterns,
		&i.TagPatterns,
	)
	return i, err
}
