// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scan_jobs.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextQueuedJob = `-- name: ClaimNextQueuedJob :one
WITH next_id AS (
    SELECT id FROM scan_jobs
    WHERE state = 'queued'
    ORDER BY created_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
),
claimed AS (
    UPDATE scan_jobs
    SET state           = 'running',
        started_at      = COALESCE(started_at, now()),
        last_attempt_at = now(),
        worker_id       = $1::text,
        attempts        = attempts + 1
    WHERE id IN (SELECT id FROM next_id)
    RETURNING id, registry_id, repository, digest, tag, attempts
)
SELECT
    c.id,
    COALESCE(c.registry_id::text, '')::text     AS registry_id,
    c.repository,
    c.digest,
    COALESCE(c.tag, '')::text                   AS tag,
    COALESCE(r.url, '')::text                   AS registry_url,
    COALESCE(r.insecure, false)::bool           AS insecure,
    COALESCE(r.auth_username, '')::text         AS auth_username,
    COALESCE(r.auth_token, '')::text            AS auth_token,
    c.attempts
FROM claimed c
LEFT JOIN registry r ON r.id = c.registry_id
`

type ClaimNextQueuedJobRow struct {
	ID           pgtype.UUID `json:"id"`
	RegistryID   string      `json:"registry_id"`
	Repository   string      `json:"repository"`
	Digest       string      `json:"digest"`
	Tag          string      `json:"tag"`
	RegistryUrl  string      `json:"registry_url"`
	Insecure     bool        `json:"insecure"`
	AuthUsername string      `json:"auth_username"`
	AuthToken    string      `json:"auth_token"`
	Attempts     int32       `json:"attempts"`
}

func (q *Queries) ClaimNextQueuedJob(ctx context.Context, workerID string) (ClaimNextQueuedJobRow, error) {
	row := q.db.QueryRow(ctx, claimNextQueuedJob, workerID)
	var i ClaimNextQueuedJobRow
	err := row.Scan(
		&i.ID,
		&i.RegistryID,
		&i.Repository,
		&i.Digest,
		&i.Tag,
		&i.RegistryUrl,
		&i.Insecure,
		&i.AuthUsername,
		&i.AuthToken,
		&i.Attempts,
	)
	return i, err
}

const claimScanJobByID = `-- name: ClaimScanJobByID :one

WITH claimed AS (
    UPDATE scan_jobs
    SET state           = 'running',
        started_at      = COALESCE(started_at, now()),
        last_attempt_at = now(),
        worker_id       = $1::text,
        attempts        = attempts + 1
    WHERE id = $2::uuid
      AND state = 'queued'
    RETURNING id, registry_id, repository, digest, tag, attempts
)
SELECT
    c.id,
    COALESCE(c.registry_id::text, '')::text     AS registry_id,
    c.repository,
    c.digest,
    COALESCE(c.tag, '')::text                   AS tag,
    COALESCE(r.url, '')::text                   AS registry_url,
    COALESCE(r.insecure, false)::bool           AS insecure,
    COALESCE(r.auth_username, '')::text         AS auth_username,
    COALESCE(r.auth_token, '')::text            AS auth_token,
    c.attempts
FROM claimed c
LEFT JOIN registry r ON r.id = c.registry_id
`

type ClaimScanJobByIDParams struct {
	WorkerID string      `json:"worker_id"`
	ID       pgtype.UUID `json:"id"`
}

type ClaimScanJobByIDRow struct {
	ID           pgtype.UUID `json:"id"`
	RegistryID   string      `json:"registry_id"`
	Repository   string      `json:"repository"`
	Digest       string      `json:"digest"`
	Tag          string      `json:"tag"`
	RegistryUrl  string      `json:"registry_url"`
	Insecure     bool        `json:"insecure"`
	AuthUsername string      `json:"auth_username"`
	AuthToken    string      `json:"auth_token"`
	Attempts     int32       `json:"attempts"`
}

// Outbox-pattern queries. The scan_jobs row IS the queue; NATS hints just
// trigger faster wakeup. ClaimScanJobByID handles the hint path; ClaimNextQueuedJob
// handles the poll-loop fallback. Both atomically transition queued → running and
// return the data needed to run the scan.
func (q *Queries) ClaimScanJobByID(ctx context.Context, arg ClaimScanJobByIDParams) (ClaimScanJobByIDRow, error) {
	row := q.db.QueryRow(ctx, claimScanJobByID, arg.WorkerID, arg.ID)
	var i ClaimScanJobByIDRow
	err := row.Scan(
		&i.ID,
		&i.RegistryID,
		&i.Repository,
		&i.Digest,
		&i.Tag,
		&i.RegistryUrl,
		&i.Insecure,
		&i.AuthUsername,
		&i.AuthToken,
		&i.Attempts,
	)
	return i, err
}

const claimStaleQueuedJobs = `-- name: ClaimStaleQueuedJobs :many
WITH candidates AS (
    SELECT sj.id
    FROM scan_jobs sj
    WHERE sj.state = 'queued'
      AND sj.nats_msg_id IS NOT NULL
      AND sj.reconcile_attempts < $1::int
      AND sj.created_at < now() - (
          interval '10 minutes' *
          LEAST(power(2, sj.reconcile_attempts)::int, $2::int)
      )
    ORDER BY sj.created_at
    LIMIT $3::int
    FOR UPDATE SKIP LOCKED
)
UPDATE scan_jobs sj
SET reconcile_attempts = sj.reconcile_attempts + 1
FROM candidates c, registry r
WHERE sj.id = c.id
  AND r.id = sj.registry_id
RETURNING
    sj.nats_msg_id::text          AS nats_msg_id,
    r.id::text                    AS registry_id,
    sj.repository                 AS repository,
    sj.digest                     AS digest,
    COALESCE(sj.tag, '')::text    AS tag,
    r.url                         AS registry_url,
    r.insecure                    AS insecure,
    COALESCE(r.auth_username, '')::text AS auth_username,
    COALESCE(r.auth_token, '')::text    AS auth_token,
    sj.reconcile_attempts         AS reconcile_attempts
`

type ClaimStaleQueuedJobsParams struct {
	MaxAttempts int32 `json:"max_attempts"`
	BackoffCap  int32 `json:"backoff_cap"`
	BatchSize   int32 `json:"batch_size"`
}

type ClaimStaleQueuedJobsRow struct {
	NatsMsgID         string `json:"nats_msg_id"`
	RegistryID        string `json:"registry_id"`
	Repository        string `json:"repository"`
	Digest            string `json:"digest"`
	Tag               string `json:"tag"`
	RegistryUrl       string `json:"registry_url"`
	Insecure          bool   `json:"insecure"`
	AuthUsername      string `json:"auth_username"`
	AuthToken         string `json:"auth_token"`
	ReconcileAttempts int32  `json:"reconcile_attempts"`
}

// ClaimStaleQueuedJobs atomically selects scan_jobs stuck in 'queued' past their
// per-attempt backoff threshold (10m * 2^reconcile_attempts, capped) and increments
// reconcile_attempts so concurrent worker pods can't double-republish the same row.
// Returns the data the reconciler needs to rebuild the NATS scan request.
func (q *Queries) ClaimStaleQueuedJobs(ctx context.Context, arg ClaimStaleQueuedJobsParams) ([]ClaimStaleQueuedJobsRow, error) {
	rows, err := q.db.Query(ctx, claimStaleQueuedJobs, arg.MaxAttempts, arg.BackoffCap, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimStaleQueuedJobsRow{}
	for rows.Next() {
		var i ClaimStaleQueuedJobsRow
		if err := rows.Scan(
			&i.NatsMsgID,
			&i.RegistryID,
			&i.Repository,
			&i.Digest,
			&i.Tag,
			&i.RegistryUrl,
			&i.Insecure,
			&i.AuthUsername,
			&i.AuthToken,
			&i.ReconcileAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countScanJobFailures = `-- name: CountScanJobFailures :one
SELECT COUNT(*) FROM scan_job_failures
`

func (q *Queries) CountScanJobFailures(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countScanJobFailures)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countScanJobs = `-- name: CountScanJobs :one
SELECT COUNT(*) FROM scan_jobs
WHERE ($1::text IS NULL OR state = $1::text)
`

func (q *Queries) CountScanJobs(ctx context.Context, state pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countScanJobs, state)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countScanJobsSince = `-- name: CountScanJobsSince :one
SELECT COUNT(*) FROM scan_jobs
WHERE state = $1::text AND finished_at >= $2::timestamptz
`

type CountScanJobsSinceParams struct {
	State string             `json:"state"`
	Since pgtype.Timestamptz `json:"since"`
}

func (q *Queries) CountScanJobsSince(ctx context.Context, arg CountScanJobsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countScanJobsSince, arg.State, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOldScanJobFailures = `-- name: DeleteOldScanJobFailures :execrows
DELETE FROM scan_job_failures
WHERE created_at < $1::timestamptz
`

func (q *Queries) DeleteOldScanJobFailures(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldScanJobFailures, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failExhaustedQueuedJobs = `-- name: FailExhaustedQueuedJobs :exec
UPDATE scan_jobs
SET state       = 'failed',
    finished_at = now(),
    last_error  = 'orphaned: max reconcile attempts'
WHERE state = 'queued'
  AND reconcile_attempts >= $1::int
`

// FailExhaustedQueuedJobs marks queued jobs that exceeded the reconciler attempt
// budget as permanently failed so they stop being scanned every tick.
func (q *Queries) FailExhaustedQueuedJobs(ctx context.Context, maxAttempts int32) error {
	_, err := q.db.Exec(ctx, failExhaustedQueuedJobs, maxAttempts)
	return err
}

const failOrRequeueScanJobByID = `-- name: FailOrRequeueScanJobByID :one
UPDATE scan_jobs
SET state       = CASE
        WHEN attempts >= $1::int THEN 'failed'
        ELSE 'queued'
    END,
    last_error  = $2,
    finished_at = CASE
        WHEN attempts >= $1::int THEN now()
        ELSE NULL
    END
WHERE id = $3::uuid
  AND state NOT IN ('succeeded', 'failed')
RETURNING state
`

type FailOrRequeueScanJobByIDParams struct {
	MaxAttempts int32       `json:"max_attempts"`
	LastError   pgtype.Text `json:"last_error"`
	ID          pgtype.UUID `json:"id"`
}

// FailOrRequeueScanJobByID transitions a 'running' job back to 'queued' for
// retry, or to 'failed' if it has exhausted its attempts. Idempotent on
// already-terminal rows: the WHERE clause skips them.
func (q *Queries) FailOrRequeueScanJobByID(ctx context.Context, arg FailOrRequeueScanJobByIDParams) (string, error) {
	row := q.db.QueryRow(ctx, failOrRequeueScanJobByID, arg.MaxAttempts, arg.LastError, arg.ID)
	var state string
	err := row.Scan(&state)
	return state, err
}

const failScanJob = `-- name: FailScanJob :exec
UPDATE scan_jobs
SET state = 'failed', finished_at = now(), last_error = $1
WHERE nats_msg_id = $2
`

type FailScanJobParams struct {
	LastError pgtype.Text `json:"last_error"`
	NatsMsgID pgtype.Text `json:"nats_msg_id"`
}

func (q *Queries) FailScanJob(ctx context.Context, arg FailScanJobParams) error {
	_, err := q.db.Exec(ctx, failScanJob, arg.LastError, arg.NatsMsgID)
	return err
}

const finishScanJob = `-- name: FinishScanJob :exec
UPDATE scan_jobs
SET state = 'succeeded', finished_at = now(), sbom_id = $1::uuid
WHERE nats_msg_id = $2
`

type FinishScanJobParams struct {
	SbomID    pgtype.UUID `json:"sbom_id"`
	NatsMsgID pgtype.Text `json:"nats_msg_id"`
}

func (q *Queries) FinishScanJob(ctx context.Context, arg FinishScanJobParams) error {
	_, err := q.db.Exec(ctx, finishScanJob, arg.SbomID, arg.NatsMsgID)
	return err
}

const finishScanJobByID = `-- name: FinishScanJobByID :exec
UPDATE scan_jobs
SET state = 'succeeded', finished_at = now(), sbom_id = $1::uuid
WHERE id = $2::uuid
`

type FinishScanJobByIDParams struct {
	SbomID pgtype.UUID `json:"sbom_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) FinishScanJobByID(ctx context.Context, arg FinishScanJobByIDParams) error {
	_, err := q.db.Exec(ctx, finishScanJobByID, arg.SbomID, arg.ID)
	return err
}

const getScanJob = `-- name: GetScanJob :one
SELECT id, registry_id, repository, digest, tag, state, attempts, last_error, nats_msg_id, sbom_id, created_at, started_at, finished_at, last_attempt_at, worker_id, reconcile_attempts FROM scan_jobs WHERE id = $1
`

func (q *Queries) GetScanJob(ctx context.Context, id pgtype.UUID) (ScanJob, error) {
	row := q.db.QueryRow(ctx, getScanJob, id)
	var i ScanJob
	err := row.Scan(
		&i.ID,
		&i.RegistryID,
		&i.Repository,
		&i.Digest,
		&i.Tag,
		&i.State,
		&i.Attempts,
		&i.LastError,
		&i.NatsMsgID,
		&i.SbomID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastAttemptAt,
		&i.WorkerID,
		&i.ReconcileAttempts,
	)
	return i, err
}

const insertScanJob = `-- name: InsertScanJob :one
INSERT INTO scan_jobs (registry_id, repository, digest, tag, nats_msg_id)
VALUES ($1::uuid, $2, $3, $4, $5)
RETURNING id, registry_id, repository, digest, tag, state, attempts, last_error, nats_msg_id, sbom_id, created_at, started_at, finished_at, last_attempt_at, worker_id, reconcile_attempts
`

type InsertScanJobParams struct {
	RegistryID pgtype.UUID `json:"registry_id"`
	Repository string      `json:"repository"`
	Digest     string      `json:"digest"`
	Tag        pgtype.Text `json:"tag"`
	NatsMsgID  pgtype.Text `json:"nats_msg_id"`
}

func (q *Queries) InsertScanJob(ctx context.Context, arg InsertScanJobParams) (ScanJob, error) {
	row := q.db.QueryRow(ctx, insertScanJob,
		arg.RegistryID,
		arg.Repository,
		arg.Digest,
		arg.Tag,
		arg.NatsMsgID,
	)
	var i ScanJob
	err := row.Scan(
		&i.ID,
		&i.RegistryID,
		&i.Repository,
		&i.Digest,
		&i.Tag,
		&i.State,
		&i.Attempts,
		&i.LastError,
		&i.NatsMsgID,
		&i.SbomID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastAttemptAt,
		&i.WorkerID,
		&i.ReconcileAttempts,
	)
	return i, err
}

const insertScanJobFailure = `-- name: InsertScanJobFailure :one
INSERT INTO scan_job_failures (nats_msg_id, payload, failure_reason, delivery_count)
VALUES ($1, $2, $3, $4)
RETURNING id, nats_msg_id, payload, failure_reason, delivery_count, created_at
`

type InsertScanJobFailureParams struct {
	NatsMsgID     pgtype.Text `json:"nats_msg_id"`
	Payload       []byte      `json:"payload"`
	FailureReason string      `json:"failure_reason"`
	DeliveryCount int32       `json:"delivery_count"`
}

func (q *Queries) InsertScanJobFailure(ctx context.Context, arg InsertScanJobFailureParams) (ScanJobFailure, error) {
	row := q.db.QueryRow(ctx, insertScanJobFailure,
		arg.NatsMsgID,
		arg.Payload,
		arg.FailureReason,
		arg.DeliveryCount,
	)
	var i ScanJobFailure
	err := row.Scan(
		&i.ID,
		&i.NatsMsgID,
		&i.Payload,
		&i.FailureReason,
		&i.DeliveryCount,
		&i.CreatedAt,
	)
	return i, err
}

const listScanJobFailures = `-- name: ListScanJobFailures :many
SELECT id, nats_msg_id, failure_reason, delivery_count, created_at
FROM scan_job_failures
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListScanJobFailuresParams struct {
	Offset int32 `json:"offset_"`
	Limit  int32 `json:"limit_"`
}

type ListScanJobFailuresRow struct {
	ID            pgtype.UUID        `json:"id"`
	NatsMsgID     pgtype.Text        `json:"nats_msg_id"`
	FailureReason string             `json:"failure_reason"`
	DeliveryCount int32              `json:"delivery_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListScanJobFailures(ctx context.Context, arg ListScanJobFailuresParams) ([]ListScanJobFailuresRow, error) {
	rows, err := q.db.Query(ctx, listScanJobFailures, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScanJobFailuresRow{}
	for rows.Next() {
		var i ListScanJobFailuresRow
		if err := rows.Scan(
			&i.ID,
			&i.NatsMsgID,
			&i.FailureReason,
			&i.DeliveryCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanJobs = `-- name: ListScanJobs :many
SELECT id, registry_id, repository, digest, tag, state, attempts, last_error, nats_msg_id, sbom_id, created_at, started_at, finished_at, last_attempt_at, worker_id, reconcile_attempts FROM scan_jobs
WHERE ($1::text IS NULL OR state = $1::text)
ORDER BY
    CASE state
        WHEN 'running'   THEN 1
        WHEN 'queued'    THEN 2
        WHEN 'failed'    THEN 3
        WHEN 'succeeded' THEN 4
        ELSE 5
    END,
    created_at DESC
LIMIT $3 OFFSET $2
`

type ListScanJobsParams struct {
	State  pgtype.Text `json:"state"`
	Offset int32       `json:"offset_"`
	Limit  int32       `json:"limit_"`
}

func (q *Queries) ListScanJobs(ctx context.Context, arg ListScanJobsParams) ([]ScanJob, error) {
	rows, err := q.db.Query(ctx, listScanJobs, arg.State, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJob{}
	for rows.Next() {
		var i ScanJob
		if err := rows.Scan(
			&i.ID,
			&i.RegistryID,
			&i.Repository,
			&i.Digest,
			&i.Tag,
			&i.State,
			&i.Attempts,
			&i.LastError,
			&i.NatsMsgID,
			&i.SbomID,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.LastAttemptAt,
			&i.WorkerID,
			&i.ReconcileAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueStuckRunning = `-- name: RequeueStuckRunning :exec
UPDATE scan_jobs
SET state = CASE
        WHEN attempts >= $1::int THEN 'failed'
        ELSE 'queued'
    END,
    last_error = CASE
        WHEN attempts >= $1::int
            THEN 'stuck: worker did not complete and retries exhausted'
        ELSE last_error
    END,
    finished_at = CASE
        WHEN attempts >= $1::int THEN now()
        ELSE NULL
    END
WHERE state = 'running'
  AND last_attempt_at < $2::timestamptz
`

type RequeueStuckRunningParams struct {
	MaxAttempts int32              `json:"max_attempts"`
	StuckBefore pgtype.Timestamptz `json:"stuck_before"`
}

// RequeueStuckRunning replaces the orphan reconciler. A 'running' row whose
// worker hasn't updated last_attempt_at recently is presumed dead; we move it
// back to 'queued' for another worker to claim, or 'failed' if it has used up
// its retries. This is the only stuck-job sweep the outbox model needs.
func (q *Queries) RequeueStuckRunning(ctx context.Context, arg RequeueStuckRunningParams) error {
	_, err := q.db.Exec(ctx, requeueStuckRunning, arg.MaxAttempts, arg.StuckBefore)
	return err
}

const startScanJob = `-- name: StartScanJob :exec
UPDATE scan_jobs
SET state           = 'running',
    started_at      = COALESCE(started_at, now()),
    last_attempt_at = now(),
    worker_id       = $1,
    attempts        = attempts + 1
WHERE nats_msg_id = $2
  AND state NOT IN ('succeeded', 'failed')
`

type StartScanJobParams struct {
	WorkerID  pgtype.Text `json:"worker_id"`
	NatsMsgID pgtype.Text `json:"nats_msg_id"`
}

func (q *Queries) StartScanJob(ctx context.Context, arg StartScanJobParams) error {
	_, err := q.db.Exec(ctx, startScanJob, arg.WorkerID, arg.NatsMsgID)
	return err
}

const timeoutScanJobs = `-- name: TimeoutScanJobs :exec
UPDATE scan_jobs
SET state = 'failed', finished_at = now(),
    last_error = 'timed out: job was still running after timeout threshold'
WHERE state = 'running'
  AND COALESCE(last_attempt_at, started_at) < $1::timestamptz
`

func (q *Queries) TimeoutScanJobs(ctx context.Context, startedBefore pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, timeoutScanJobs, startedBefore)
	return err
}
