// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: source.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSource = `-- name: CreateSource :one

INSERT INTO source (namespace_id, kind, name)
VALUES ($1, $2, $3)
RETURNING id, namespace_id, kind, name, created_at, updated_at
`

type CreateSourceParams struct {
	NamespaceID pgtype.UUID `json:"namespace_id"`
	Kind        string      `json:"kind"`
	Name        string      `json:"name"`
}

// Source is the ingest channel (ADR-039). `kind` is the subtype discriminator
// ('oci_registry' | 'upload'); an oci_registry source has a matching registry
// row sharing its id, an upload source has none.
func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, createSource, arg.NamespaceID, arg.Kind, arg.Name)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.Kind,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSource = `-- name: DeleteSource :execrows
DELETE FROM source WHERE id = $1
`

// Cascades to the registry subtype row. The owning namespace is deliberately
// left standing: a namespace outliving its last source is correct, not a leak
// (ADR-039). SBOMs keep their namespace and only lose source_id.
func (q *Queries) DeleteSource(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSource, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSource = `-- name: GetSource :one
SELECT id, namespace_id, kind, name, created_at, updated_at FROM source WHERE id = $1
`

func (q *Queries) GetSource(ctx context.Context, id pgtype.UUID) (Source, error) {
	row := q.db.QueryRow(ctx, getSource, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.Kind,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSourceByName = `-- name: GetSourceByName :one
SELECT id, namespace_id, kind, name, created_at, updated_at FROM source WHERE namespace_id = $1 AND name = $2
`

type GetSourceByNameParams struct {
	NamespaceID pgtype.UUID `json:"namespace_id"`
	Name        string      `json:"name"`
}

func (q *Queries) GetSourceByName(ctx context.Context, arg GetSourceByNameParams) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByName, arg.NamespaceID, arg.Name)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.Kind,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSources = `-- name: ListSources :many
SELECT s.id, s.namespace_id, s.kind, s.name, s.created_at, s.updated_at, n.name AS namespace_name, n.owner_id, n.visibility
FROM source s
JOIN namespace n ON n.id = s.namespace_id
WHERE (
    CASE WHEN COALESCE($1::boolean, false)
         THEN n.owner_id = $2::uuid
         ELSE $3::boolean = true
              OR n.visibility = 'public'
              OR ($2::uuid IS NOT NULL AND n.owner_id = $2::uuid)
    END
)
ORDER BY s.created_at ASC
`

type ListSourcesParams struct {
	OwnedOnly pgtype.Bool `json:"owned_only"`
	UserID    pgtype.UUID `json:"user_id"`
	IsAdmin   pgtype.Bool `json:"is_admin"`
}

type ListSourcesRow struct {
	Source        Source      `json:"source"`
	NamespaceName string      `json:"namespace_name"`
	OwnerID       pgtype.UUID `json:"owner_id"`
	Visibility    string      `json:"visibility"`
}

// Visibility is resolved through the owning namespace, so a source is never
// listed to a viewer who cannot see the namespace holding it. owned_only
// switches to the ownership path — see ListNamespaces for why the two live in
// one query.
func (q *Queries) ListSources(ctx context.Context, arg ListSourcesParams) ([]ListSourcesRow, error) {
	rows, err := q.db.Query(ctx, listSources, arg.OwnedOnly, arg.UserID, arg.IsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSourcesRow{}
	for rows.Next() {
		var i ListSourcesRow
		if err := rows.Scan(
			&i.Source.ID,
			&i.Source.NamespaceID,
			&i.Source.Kind,
			&i.Source.Name,
			&i.Source.CreatedAt,
			&i.Source.UpdatedAt,
			&i.NamespaceName,
			&i.OwnerID,
			&i.Visibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourcesByNamespace = `-- name: ListSourcesByNamespace :many
SELECT id, namespace_id, kind, name, created_at, updated_at FROM source WHERE namespace_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListSourcesByNamespace(ctx context.Context, namespaceID pgtype.UUID) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSourcesByNamespace, namespaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.NamespaceID,
			&i.Kind,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSource = `-- name: UpdateSource :one
UPDATE source
SET name       = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, namespace_id, kind, name, created_at, updated_at
`

type UpdateSourceParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, updateSource, arg.ID, arg.Name)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.Kind,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
