// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLicenseCategoryCounts = `-- name: GetLicenseCategoryCounts :many
WITH visible_sbom AS (
    SELECT s.id
    FROM sbom s
    LEFT JOIN registry r ON r.id = s.registry_id
    WHERE s.registry_id IS NULL
       OR r.visibility = 'public'
       OR r.owner_id = $1::uuid
       OR COALESCE($2::boolean, false)
)
SELECT
    license_category(l.spdx_id) AS category,
    COUNT(DISTINCT cl.component_id)::bigint AS component_count
FROM license l
JOIN component_license cl ON cl.license_id = l.id
JOIN component c ON c.id = cl.component_id
JOIN visible_sbom vs ON vs.id = c.sbom_id
GROUP BY 1
ORDER BY component_count DESC
`

type GetLicenseCategoryCountsParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	IsAdmin pgtype.Bool `json:"is_admin"`
}

type GetLicenseCategoryCountsRow struct {
	Category       string `json:"category"`
	ComponentCount int64  `json:"component_count"`
}

func (q *Queries) GetLicenseCategoryCounts(ctx context.Context, arg GetLicenseCategoryCountsParams) ([]GetLicenseCategoryCountsRow, error) {
	rows, err := q.db.Query(ctx, getLicenseCategoryCounts, arg.UserID, arg.IsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLicenseCategoryCountsRow{}
	for rows.Next() {
		var i GetLicenseCategoryCountsRow
		if err := rows.Scan(&i.Category, &i.ComponentCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPackageGrowthTimeline = `-- name: GetPackageGrowthTimeline :many
WITH visible_sbom AS (
    SELECT s.id, s.created_at
    FROM sbom s
    LEFT JOIN registry r ON r.id = s.registry_id
    WHERE s.registry_id IS NULL
       OR r.visibility = 'public'
       OR r.owner_id = $1::uuid
       OR COALESCE($2::boolean, false)
),
pkg_first_seen AS (
    SELECT DATE(MIN(vs.created_at)) AS first_seen
    FROM component c
    JOIN visible_sbom vs ON vs.id = c.sbom_id
    GROUP BY c.name, COALESCE(c.group_name, ''), c.type
),
daily_new AS (
    SELECT first_seen, COUNT(*)::bigint AS new_count
    FROM pkg_first_seen
    WHERE first_seen <= CURRENT_DATE
    GROUP BY first_seen
)
SELECT
    first_seen::text AS day,
    SUM(new_count) OVER (ORDER BY first_seen)::bigint AS cumulative_count
FROM daily_new
ORDER BY first_seen
`

type GetPackageGrowthTimelineParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	IsAdmin pgtype.Bool `json:"is_admin"`
}

type GetPackageGrowthTimelineRow struct {
	Day             string `json:"day"`
	CumulativeCount int64  `json:"cumulative_count"`
}

// Cumulative distinct packages (name+group+type) by the day each first appeared.
func (q *Queries) GetPackageGrowthTimeline(ctx context.Context, arg GetPackageGrowthTimelineParams) ([]GetPackageGrowthTimelineRow, error) {
	rows, err := q.db.Query(ctx, getPackageGrowthTimeline, arg.UserID, arg.IsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPackageGrowthTimelineRow{}
	for rows.Next() {
		var i GetPackageGrowthTimelineRow
		if err := rows.Scan(&i.Day, &i.CumulativeCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSBOMIngestionTimeline = `-- name: GetSBOMIngestionTimeline :many
WITH visible_sbom AS (
    SELECT s.id, s.created_at
    FROM sbom s
    LEFT JOIN registry r ON r.id = s.registry_id
    WHERE s.registry_id IS NULL
       OR r.visibility = 'public'
       OR r.owner_id = $2::uuid
       OR COALESCE($3::boolean, false)
)
SELECT
    DATE(created_at)::text AS day,
    COUNT(*)::bigint       AS count
FROM visible_sbom
WHERE created_at >= CURRENT_DATE - $1::int
  AND DATE(created_at) <= CURRENT_DATE
GROUP BY DATE(created_at)::text
ORDER BY day
`

type GetSBOMIngestionTimelineParams struct {
	NumDays int32       `json:"num_days"`
	UserID  pgtype.UUID `json:"user_id"`
	IsAdmin pgtype.Bool `json:"is_admin"`
}

type GetSBOMIngestionTimelineRow struct {
	Day   string `json:"day"`
	Count int64  `json:"count"`
}

func (q *Queries) GetSBOMIngestionTimeline(ctx context.Context, arg GetSBOMIngestionTimelineParams) ([]GetSBOMIngestionTimelineRow, error) {
	rows, err := q.db.Query(ctx, getSBOMIngestionTimeline, arg.NumDays, arg.UserID, arg.IsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSBOMIngestionTimelineRow{}
	for rows.Next() {
		var i GetSBOMIngestionTimelineRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSummaryCounts = `-- name: GetSummaryCounts :one
WITH visible_sbom AS (
    SELECT s.id
    FROM sbom s
    LEFT JOIN registry r ON r.id = s.registry_id
    WHERE s.registry_id IS NULL
       OR r.visibility = 'public'
       OR r.owner_id = $1::uuid
       OR COALESCE($2::boolean, false)
)
SELECT
    (SELECT COUNT(*)::bigint FROM artifact a
       WHERE artifact_visible(a.id, $1::uuid, $2::boolean)
    ) AS artifact_count,
    (SELECT COUNT(*)::bigint FROM visible_sbom) AS sbom_count,
    (SELECT COUNT(*)::bigint FROM (
        SELECT DISTINCT c.name, COALESCE(c.group_name,'') AS g, c.type
        FROM component c
        JOIN visible_sbom vs ON vs.id = c.sbom_id
    ) t) AS package_count,
    (SELECT COUNT(*)::bigint FROM (
        SELECT DISTINCT c.name, COALESCE(c.group_name,'') AS g, COALESCE(c.version,'') AS v, c.type
        FROM component c
        JOIN visible_sbom vs ON vs.id = c.sbom_id
    ) t) AS version_count,
    (SELECT COUNT(*)::bigint FROM license) AS license_count
`

type GetSummaryCountsParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	IsAdmin pgtype.Bool `json:"is_admin"`
}

type GetSummaryCountsRow struct {
	ArtifactCount int64 `json:"artifact_count"`
	SbomCount     int64 `json:"sbom_count"`
	PackageCount  int64 `json:"package_count"`
	VersionCount  int64 `json:"version_count"`
	LicenseCount  int64 `json:"license_count"`
}

func (q *Queries) GetSummaryCounts(ctx context.Context, arg GetSummaryCountsParams) (GetSummaryCountsRow, error) {
	row := q.db.QueryRow(ctx, getSummaryCounts, arg.UserID, arg.IsAdmin)
	var i GetSummaryCountsRow
	err := row.Scan(
		&i.ArtifactCount,
		&i.SbomCount,
		&i.PackageCount,
		&i.VersionCount,
		&i.LicenseCount,
	)
	return i, err
}

const getTopPackagesByVersionCount = `-- name: GetTopPackagesByVersionCount :many
WITH visible_sbom AS (
    SELECT s.id
    FROM sbom s
    LEFT JOIN registry r ON r.id = s.registry_id
    WHERE s.registry_id IS NULL
       OR r.visibility = 'public'
       OR r.owner_id = $2::uuid
       OR COALESCE($3::boolean, false)
)
SELECT
    c.name,
    c.group_name,
    c.type,
    COUNT(DISTINCT COALESCE(c.version, ''))::bigint AS version_count,
    COUNT(DISTINCT c.sbom_id)::bigint               AS sbom_count
FROM component c
JOIN visible_sbom vs ON vs.id = c.sbom_id
GROUP BY c.name, c.group_name, c.type
ORDER BY version_count DESC
LIMIT $1::int
`

type GetTopPackagesByVersionCountParams struct {
	TopN    int32       `json:"top_n"`
	UserID  pgtype.UUID `json:"user_id"`
	IsAdmin pgtype.Bool `json:"is_admin"`
}

type GetTopPackagesByVersionCountRow struct {
	Name         string      `json:"name"`
	GroupName    pgtype.Text `json:"group_name"`
	Type         string      `json:"type"`
	VersionCount int64       `json:"version_count"`
	SbomCount    int64       `json:"sbom_count"`
}

func (q *Queries) GetTopPackagesByVersionCount(ctx context.Context, arg GetTopPackagesByVersionCountParams) ([]GetTopPackagesByVersionCountRow, error) {
	rows, err := q.db.Query(ctx, getTopPackagesByVersionCount, arg.TopN, arg.UserID, arg.IsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopPackagesByVersionCountRow{}
	for rows.Next() {
		var i GetTopPackagesByVersionCountRow
		if err := rows.Scan(
			&i.Name,
			&i.GroupName,
			&i.Type,
			&i.VersionCount,
			&i.SbomCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVersionGrowthTimeline = `-- name: GetVersionGrowthTimeline :many
WITH visible_sbom AS (
    SELECT s.id, s.created_at
    FROM sbom s
    LEFT JOIN registry r ON r.id = s.registry_id
    WHERE s.registry_id IS NULL
       OR r.visibility = 'public'
       OR r.owner_id = $1::uuid
       OR COALESCE($2::boolean, false)
),
ver_first_seen AS (
    SELECT DATE(MIN(vs.created_at)) AS first_seen
    FROM component c
    JOIN visible_sbom vs ON vs.id = c.sbom_id
    GROUP BY c.name, COALESCE(c.group_name, ''), COALESCE(c.version, ''), c.type
),
daily_new AS (
    SELECT first_seen, COUNT(*)::bigint AS new_count
    FROM ver_first_seen
    WHERE first_seen <= CURRENT_DATE
    GROUP BY first_seen
)
SELECT
    first_seen::text AS day,
    SUM(new_count) OVER (ORDER BY first_seen)::bigint AS cumulative_count
FROM daily_new
ORDER BY first_seen
`

type GetVersionGrowthTimelineParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	IsAdmin pgtype.Bool `json:"is_admin"`
}

type GetVersionGrowthTimelineRow struct {
	Day             string `json:"day"`
	CumulativeCount int64  `json:"cumulative_count"`
}

// Cumulative distinct package versions (name+group+version+type) by the day each first appeared.
func (q *Queries) GetVersionGrowthTimeline(ctx context.Context, arg GetVersionGrowthTimelineParams) ([]GetVersionGrowthTimelineRow, error) {
	rows, err := q.db.Query(ctx, getVersionGrowthTimeline, arg.UserID, arg.IsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVersionGrowthTimelineRow{}
	for rows.Next() {
		var i GetVersionGrowthTimelineRow
		if err := rows.Scan(&i.Day, &i.CumulativeCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVulnStats = `-- name: GetVulnStats :one
WITH visible_sbom AS (
    SELECT s.id
    FROM sbom s
    LEFT JOIN registry r ON r.id = s.registry_id
    WHERE s.registry_id IS NULL
       OR r.visibility = 'public'
       OR r.owner_id = $1::uuid
       OR COALESCE($2::boolean, false)
)
SELECT
    COUNT(DISTINCT v.canonical_id)::bigint AS total_vulns,
    COUNT(DISTINCT v.canonical_id) FILTER (WHERE v.severity = 'CRITICAL')::bigint AS critical_count,
    COUNT(DISTINCT v.canonical_id) FILTER (WHERE v.severity = 'HIGH')::bigint     AS high_count,
    COUNT(DISTINCT v.canonical_id) FILTER (WHERE v.severity = 'MEDIUM')::bigint   AS medium_count,
    COUNT(DISTINCT v.canonical_id) FILTER (WHERE v.severity = 'LOW')::bigint      AS low_count,
    COUNT(DISTINCT v.canonical_id) FILTER (
        WHERE v.severity IS NULL OR v.severity NOT IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW')
    )::bigint AS unknown_count
FROM component c
JOIN visible_sbom vs ON vs.id = c.sbom_id
JOIN package_vulnerability pv ON pv.purl = c.purl
JOIN vulnerability v ON v.id = pv.vulnerability_id
WHERE c.purl IS NOT NULL
`

type GetVulnStatsParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	IsAdmin pgtype.Bool `json:"is_admin"`
}

type GetVulnStatsRow struct {
	TotalVulns    int64 `json:"total_vulns"`
	CriticalCount int64 `json:"critical_count"`
	HighCount     int64 `json:"high_count"`
	MediumCount   int64 `json:"medium_count"`
	LowCount      int64 `json:"low_count"`
	UnknownCount  int64 `json:"unknown_count"`
}

// Distinct tracked vulnerabilities reachable from any visible SBOM, with per-severity breakdown.
// Deduplicates aliased OSV records (e.g. GO-xxxx + GHSA-yyyy) by canonical_id so each
// real-world CVE is counted once.
func (q *Queries) GetVulnStats(ctx context.Context, arg GetVulnStatsParams) (GetVulnStatsRow, error) {
	row := q.db.QueryRow(ctx, getVulnStats, arg.UserID, arg.IsAdmin)
	var i GetVulnStatsRow
	err := row.Scan(
		&i.TotalVulns,
		&i.CriticalCount,
		&i.HighCount,
		&i.MediumCount,
		&i.LowCount,
		&i.UnknownCount,
	)
	return i, err
}
