// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watch_feed.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listWatchedArtifactEvents = `-- name: ListWatchedArtifactEvents :many

WITH watched AS (
    SELECT w.artifact_id, a.name AS artifact_name, a.type AS artifact_type
    FROM artifact_watch w
    JOIN artifact a ON a.id = w.artifact_id
    WHERE w.user_id = $2::uuid
),
visible_sbom AS (
    SELECT s.id, s.artifact_id, s.subject_version, s.created_at,
           w.artifact_name, w.artifact_type
    FROM sbom s
    JOIN watched w ON w.artifact_id = s.artifact_id
    WHERE s.namespace_id IN (
        SELECT visible_namespace_ids($3::uuid, $4::boolean)
    )
),
version_events AS (
    SELECT
        'new_version'::text AS kind,
        vs.id AS event_id,
        vs.created_at AS occurred_at,
        vs.artifact_id,
        vs.artifact_name,
        vs.artifact_type,
        vs.id AS sbom_id,
        vs.subject_version,
        -- The version this one succeeded, so the UI can deep-link straight to
        -- the existing changelog endpoint instead of restating what changed.
        -- COALESCE to '' rather than leaving it NULL: sqlc reads the cast as
        -- non-null, and '' already means exactly what NULL would here — there is
        -- no predecessor to link from, either because this is the artifact's
        -- first version or because that version carries no subject_version.
        COALESCE(LAG(vs.subject_version) OVER (
            PARTITION BY vs.artifact_id ORDER BY vs.created_at, vs.id
        ), '')::text AS previous_version,
        NULL::text AS previous_status,
        NULL::text AS new_status,
        NULL::text AS reason,
        NULL::text AS vuln_id,
        NULL::text AS vuln_severity,
        NULL::real AS vuln_cvss_score,
        NULL::text AS vuln_summary
    FROM visible_sbom vs
),
drift_events AS (
    SELECT
        'drift'::text AS kind,
        d.id AS event_id,
        d.detected_at AS occurred_at,
        vs.artifact_id,
        vs.artifact_name,
        vs.artifact_type,
        vs.id AS sbom_id,
        vs.subject_version,
        -- '' rather than NULL: sqlc types every UNION column from the first
        -- branch, where previous_version is non-null, so a NULL here would fail
        -- to scan. '' is already this query's "no predecessor" value.
        ''::text AS previous_version,
        d.previous_status,
        d.new_status,
        d.reason,
        NULL::text AS vuln_id,
        NULL::text AS vuln_severity,
        NULL::real AS vuln_cvss_score,
        NULL::text AS vuln_summary
    FROM provenance_drift_events d
    JOIN visible_sbom vs ON vs.id = d.sbom_id
),
latest_sbom AS (
    SELECT DISTINCT ON (vs.artifact_id)
        vs.id, vs.artifact_id, vs.subject_version, vs.created_at,
        vs.artifact_name, vs.artifact_type
    FROM visible_sbom vs
    ORDER BY vs.artifact_id, vs.created_at DESC, vs.id DESC
),
vuln_events AS (
    SELECT
        'vulnerability'::text AS kind,
        -- vulnerability.id is text, not a uuid, and the feed cursor is
        -- (timestamptz, uuid) like every other keyset feed here. Hashing the
        -- pair that identifies the event gives a stable, unique uuid without
        -- widening the cursor for one branch.
        md5(v.canonical_id || ls.artifact_id::text)::uuid AS event_id,
        -- "Newly affecting" is whichever happened later: the advisory being
        -- published, or this artifact coming into existence. package_vulnerability
        -- has no usable first-seen column — the refresh loop delete-then-inserts
        -- every purl each cycle, so its updated_at would re-float the whole
        -- backlog to the top of the feed on every refresh.
        GREATEST(v.published_at, ls.created_at) AS occurred_at,
        ls.artifact_id,
        ls.artifact_name,
        ls.artifact_type,
        ls.id AS sbom_id,
        ls.subject_version,
        ''::text AS previous_version,
        NULL::text AS previous_status,
        NULL::text AS new_status,
        NULL::text AS reason,
        v.canonical_id AS vuln_id,
        v.severity AS vuln_severity,
        v.cvss_score AS vuln_cvss_score,
        v.summary AS vuln_summary
    FROM latest_sbom ls
    JOIN (SELECT DISTINCT sbom_id, purl FROM component WHERE purl IS NOT NULL) c
        ON c.sbom_id = ls.id
    JOIN package_vulnerability pv ON pv.purl = c.purl
    JOIN vulnerability v ON v.id = pv.vulnerability_id
    -- One row per (artifact, canonical vuln): the same advisory usually matches
    -- several purls in one image, and aliased OSV records collapse onto one
    -- canonical_id (same rule as GetArtifactVulnSummary).
    GROUP BY v.canonical_id, ls.artifact_id, ls.artifact_name, ls.artifact_type,
             ls.id, ls.subject_version, ls.created_at, v.published_at,
             v.severity, v.cvss_score, v.summary
),
merged AS (
    (SELECT kind, event_id, occurred_at, artifact_id, artifact_name, artifact_type, sbom_id, subject_version, previous_version, previous_status, new_status, reason, vuln_id, vuln_severity, vuln_cvss_score, vuln_summary FROM version_events
     WHERE NOT $5::boolean
        OR (occurred_at, event_id) < ($6::timestamptz, $7::uuid)
     ORDER BY occurred_at DESC, event_id DESC
     LIMIT $1)
    UNION ALL
    (SELECT kind, event_id, occurred_at, artifact_id, artifact_name, artifact_type, sbom_id, subject_version, previous_version, previous_status, new_status, reason, vuln_id, vuln_severity, vuln_cvss_score, vuln_summary FROM drift_events
     WHERE NOT $5::boolean
        OR (occurred_at, event_id) < ($6::timestamptz, $7::uuid)
     ORDER BY occurred_at DESC, event_id DESC
     LIMIT $1)
    UNION ALL
    (SELECT kind, event_id, occurred_at, artifact_id, artifact_name, artifact_type, sbom_id, subject_version, previous_version, previous_status, new_status, reason, vuln_id, vuln_severity, vuln_cvss_score, vuln_summary FROM vuln_events
     WHERE NOT $5::boolean
        OR (occurred_at, event_id) < ($6::timestamptz, $7::uuid)
     ORDER BY occurred_at DESC, event_id DESC
     LIMIT $1)
)
SELECT kind, event_id, occurred_at, artifact_id, artifact_name, artifact_type, sbom_id, subject_version, previous_version, previous_status, new_status, reason, vuln_id, vuln_severity, vuln_cvss_score, vuln_summary FROM merged
ORDER BY occurred_at DESC, event_id DESC
LIMIT $1
`

type ListWatchedArtifactEventsParams struct {
	RowLimit         int32              `json:"row_limit"`
	WatcherID        pgtype.UUID        `json:"watcher_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	IsAdmin          pgtype.Bool        `json:"is_admin"`
	HasCursor        pgtype.Bool        `json:"has_cursor"`
	CursorOccurredAt pgtype.Timestamptz `json:"cursor_occurred_at"`
	CursorID         pgtype.UUID        `json:"cursor_id"`
}

type ListWatchedArtifactEventsRow struct {
	Kind            string             `json:"kind"`
	EventID         pgtype.UUID        `json:"event_id"`
	OccurredAt      pgtype.Timestamptz `json:"occurred_at"`
	ArtifactID      pgtype.UUID        `json:"artifact_id"`
	ArtifactName    string             `json:"artifact_name"`
	ArtifactType    string             `json:"artifact_type"`
	SbomID          pgtype.UUID        `json:"sbom_id"`
	SubjectVersion  pgtype.Text        `json:"subject_version"`
	PreviousVersion string             `json:"previous_version"`
	PreviousStatus  pgtype.Text        `json:"previous_status"`
	NewStatus       pgtype.Text        `json:"new_status"`
	Reason          pgtype.Text        `json:"reason"`
	VulnID          pgtype.Text        `json:"vuln_id"`
	VulnSeverity    pgtype.Text        `json:"vuln_severity"`
	VulnCvssScore   pgtype.Float4      `json:"vuln_cvss_score"`
	VulnSummary     pgtype.Text        `json:"vuln_summary"`
}

// Watched-artifact change feed (ocidex-998g.4).
//
// Three signals already exist in the schema and none of them are recomputed
// here: a new version is a `sbom` row, a drift event is a
// `provenance_drift_events` row, and a vulnerability finding is the same
// component→package_vulnerability→vulnerability join the SBOM and artifact
// vuln panels use. This query only scopes those to the caller's watch set and
// merges them onto one timeline.
//
// Visibility IS re-checked here, which is the deliberate opposite of
// ListArtifactWatches. A watch row is the user's own bookmark and survives its
// artifact going private; the *events* are content, and content the caller can
// no longer see must not keep streaming into their feed. So a since-privatised
// artifact stays on the watchlist and drops out of the feed.
// Keyset on (occurred_at DESC, event_id DESC) per ADR-043 rule 2 — every branch
// appends at the head of an ordering that does not reshuffle underneath it.
//
// Each branch applies the cursor and takes row_limit rows before the merge, so
// one noisy artifact cannot make the union arbitrarily large; the outer LIMIT
// then takes the globally newest row_limit of those. The caller passes
// row_limit+1 to detect whether a further page exists.
// The single visibility gate. Everything downstream reads from here, so no
// branch can accidentally bypass it.
// Vulnerabilities are reported against the newest visible SBOM only. Fanning
// out over every version would re-emit the same CVE once per tag for no new
// information.
func (q *Queries) ListWatchedArtifactEvents(ctx context.Context, arg ListWatchedArtifactEventsParams) ([]ListWatchedArtifactEventsRow, error) {
	rows, err := q.db.Query(ctx, listWatchedArtifactEvents,
		arg.RowLimit,
		arg.WatcherID,
		arg.UserID,
		arg.IsAdmin,
		arg.HasCursor,
		arg.CursorOccurredAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWatchedArtifactEventsRow{}
	for rows.Next() {
		var i ListWatchedArtifactEventsRow
		if err := rows.Scan(
			&i.Kind,
			&i.EventID,
			&i.OccurredAt,
			&i.ArtifactID,
			&i.ArtifactName,
			&i.ArtifactType,
			&i.SbomID,
			&i.SubjectVersion,
			&i.PreviousVersion,
			&i.PreviousStatus,
			&i.NewStatus,
			&i.Reason,
			&i.VulnID,
			&i.VulnSeverity,
			&i.VulnCvssScore,
			&i.VulnSummary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
