apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocidex-scanner-worker
spec:
  template:
    spec:
      containers:
        - name: scanner-worker
          imagePullPolicy: IfNotPresent
          env:
            - name: NATS_STREAM_REPLICAS
              value: "1"
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: ocidex-secrets
                  key: github-client-id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ocidex-secrets
                  key: github-client-secret
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: ocidex-secrets
                  key: session-secret
