#!/usr/bin/env bash
# Local authenticated dev rig — a real API on :8080 backed by a real Postgres,
# so auth-gated pages (/clusters, /dashboard, /admin) can be looked at in a
# browser instead of only asserted against in happy-dom.
#
# Why this exists: `make frontend-dev-live` proxies to production and is
# therefore signed-out and read-only, which leaves a third of the app
# unverifiable. This rig is the opposite trade: entirely local, so writes are
# safe, and it serves THIS branch's API rather than the deployed one.
#
# No containers. postgresql and nats-server are native binaries in the Flox
# environment; everything below runs out of .dev/ (gitignored).
#
# The GitHub OAuth vars are set to placeholders only because the API validates
# their presence at startup. The /auth routes are never exercised here — the
# rig authenticates by API key — so no OAuth app exists and none is needed.
#
# Auth uses no bypass and no new code path. internal/api/middleware.go already
# accepts `Authorization: Bearer <api-key>` as equivalent to a session cookie,
# so the rig mints a read-write key for a local admin and the dev vite config
# injects it. GitHub OAuth is never involved; its config vars stay empty.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEV="$ROOT/.dev"
PGDATA="$DEV/pgdata"
PGPORT=5433
NATS_PORT=4222
API_PORT=8080
ENVFILE="$DEV/dev-auth.env"

export PGHOST=127.0.0.1
export PGPORT
export PGUSER=ocidex
export PGDATABASE=ocidex

log() { printf '\033[36m▸\033[0m %s\n' "$*"; }
die() { printf '\033[31m✗\033[0m %s\n' "$*" >&2; exit 1; }

# ── Postgres ────────────────────────────────────────────────────────────────
pg_running() { pg_ctl -D "$PGDATA" status >/dev/null 2>&1; }

start_pg() {
    if [ ! -d "$PGDATA" ]; then
        log "initdb $PGDATA"
        # trust auth: the socket is bound to loopback on a non-default port and
        # holds nothing but throwaway fixture data.
        initdb -D "$PGDATA" -U ocidex --auth=trust >"$DEV/initdb.log" 2>&1 \
            || { cat "$DEV/initdb.log"; die "initdb failed"; }
    fi
    if pg_running; then
        log "postgres already running on :$PGPORT"
    else
        log "starting postgres on :$PGPORT"
        pg_ctl -D "$PGDATA" -l "$DEV/postgres.log" \
            -o "-p $PGPORT -k $DEV -h 127.0.0.1" -w start \
            || { tail -20 "$DEV/postgres.log"; die "postgres failed to start"; }
    fi
    createdb ocidex 2>/dev/null && log "created database ocidex" || true
}

# ── NATS ────────────────────────────────────────────────────────────────────
start_nats() {
    if [ -f "$DEV/nats.pid" ] && kill -0 "$(cat "$DEV/nats.pid")" 2>/dev/null; then
        log "nats already running on :$NATS_PORT"
        return
    fi
    log "starting nats-server on :$NATS_PORT"
    nats-server -p "$NATS_PORT" -js -sd "$DEV/nats" >"$DEV/nats.log" 2>&1 &
    echo $! > "$DEV/nats.pid"
    sleep 1
    kill -0 "$(cat "$DEV/nats.pid")" 2>/dev/null || { tail -20 "$DEV/nats.log"; die "nats failed to start"; }
}

# ── Schema + fixtures ───────────────────────────────────────────────────────
DB_URL="postgres://ocidex@127.0.0.1:$PGPORT/ocidex?sslmode=disable"

migrate() {
    log "applying migrations"
    (cd "$ROOT" && DATABASE_URL="$DB_URL" go run ./cmd/ocidex migrate up) \
        || die "migrations failed"
}

# Mints the local admin and a read-write API key. The key is hashed exactly as
# internal/service/auth.go does it — hex(SHA-256(plaintext)), prefix = first 8
# chars — so it validates through the ordinary ValidateAPIKey path.
seed_auth() {
    if [ -f "$ENVFILE" ] && psql -tAc "SELECT 1 FROM api_key LIMIT 1" | grep -q 1; then
        log "reusing existing dev credentials ($ENVFILE)"
        return
    fi
    local raw key hash prefix
    raw="$(openssl rand -base64 32 | tr '+/' '-_' | tr -d '=\n')"
    key="ocidex_${raw}"
    hash="$(printf '%s' "$key" | shasum -a 256 | cut -d' ' -f1)"
    prefix="${key:0:8}"

    log "seeding admin user + read-write API key"
    psql -v ON_ERROR_STOP=1 -q <<SQL
INSERT INTO ocidex_user (github_id, github_username, role)
VALUES (1, 'devadmin', 'admin')
ON CONFLICT (github_id) DO UPDATE SET role = 'admin';

INSERT INTO api_key (user_id, name, key_hash, prefix, scope)
SELECT id, 'local dev rig', '$hash', '$prefix', 'read-write'
FROM ocidex_user WHERE github_id = 1;

INSERT INTO namespace (name, owner_id, visibility)
SELECT 'local', id, 'private' FROM ocidex_user WHERE github_id = 1
ON CONFLICT (name) DO NOTHING;
SQL
    cat > "$ENVFILE" <<ENV
# Generated by scripts/dev-auth.sh — local only, never a real credential.
OCIDEX_DEV_API_KEY=$key
DATABASE_URL=$DB_URL
ENV
    log "credentials written to $ENVFILE"
}

# ── API ─────────────────────────────────────────────────────────────────────
start_api() {
    if [ -f "$DEV/api.pid" ] && kill -0 "$(cat "$DEV/api.pid")" 2>/dev/null; then
        log "api already running on :$API_PORT"
        return
    fi
    log "starting api on :$API_PORT"
    (
        cd "$ROOT"
        DATABASE_URL="$DB_URL" \
        NATS_URL="nats://127.0.0.1:$NATS_PORT" \
        PORT="$API_PORT" \
        ENVIRONMENT=development \
        LOG_LEVEL=info \
        SESSION_SECRET="$(openssl rand -hex 32)" \
        GITHUB_CLIENT_ID=dev-unused \
        GITHUB_CLIENT_SECRET=dev-unused \
        FRONTEND_URL="http://localhost:3200" \
        CORS_ALLOWED_ORIGINS="http://localhost:3200" \
        nohup go run ./cmd/ocidex >"$DEV/api.log" 2>&1 &
        echo $! > "$DEV/api.pid"
    )
    for _ in $(seq 1 60); do
        if curl -sf "http://127.0.0.1:$API_PORT/ready" >/dev/null 2>&1; then
            log "api ready"
            return
        fi
        sleep 1
    done
    tail -30 "$DEV/api.log"
    die "api did not become ready"
}

# The fixtures are a separate script and a separate step on purpose: `up` has to
# stay runnable against an already-seeded rig, and a corpus is the part most
# likely to need re-running on its own while iterating on a page.
seed_fixtures() {
    (cd "$ROOT" && python3 scripts/dev-fixtures.py)
}

stop_all() {
    for svc in api nats; do
        if [ -f "$DEV/$svc.pid" ]; then
            # go run spawns the real binary as a child; kill the group.
            pkill -P "$(cat "$DEV/$svc.pid")" 2>/dev/null || true
            kill "$(cat "$DEV/$svc.pid")" 2>/dev/null || true
            rm -f "$DEV/$svc.pid"
            log "stopped $svc"
        fi
    done
    pkill -f 'ocidex/exe/ocidex' 2>/dev/null || true
    if pg_running; then
        pg_ctl -D "$PGDATA" -m fast stop >/dev/null && log "stopped postgres"
    fi
}

case "${1:-up}" in
    up)
        mkdir -p "$DEV"
        start_pg
        start_nats
        migrate
        seed_auth
        start_api
        seed_fixtures
        printf '\n\033[32m✓\033[0m rig up — api :%s, postgres :%s, nats :%s\n' \
            "$API_PORT" "$PGPORT" "$NATS_PORT"
        printf '  next: \033[1mmake frontend-dev-auth\033[0m  (:3200, signed in as devadmin/admin)\n'
        ;;
    fixtures) seed_fixtures ;;
    down)   stop_all ;;
    status)
        pg_running && echo "postgres: up" || echo "postgres: down"
        [ -f "$DEV/nats.pid" ] && kill -0 "$(cat "$DEV/nats.pid")" 2>/dev/null \
            && echo "nats: up" || echo "nats: down"
        curl -sf "http://127.0.0.1:$API_PORT/ready" >/dev/null 2>&1 \
            && echo "api: up" || echo "api: down"
        ;;
    key)    grep OCIDEX_DEV_API_KEY "$ENVFILE" | cut -d= -f2 ;;
    reset)
        stop_all
        rm -rf "$DEV"
        log "removed $DEV — next 'up' starts from an empty database"
        ;;
    *) die "usage: dev-auth.sh [up|down|status|key|fixtures|reset]" ;;
esac
