apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/task: "[.tekton/tasks/set-status-pending-ocidex-push.k8s.yaml, .tekton/tasks/git-clone.k8s.yaml, .tekton/tasks/gofmt-check.k8s.yaml, .tekton/tasks/go-test.k8s.yaml, .tekton/tasks/go-build.k8s.yaml, .tekton/tasks/openapi-verify.k8s.yaml, .tekton/tasks/eslint-lint-web.k8s.yaml, .tekton/tasks/go-integration-test.k8s.yaml, .tekton/tasks/govulncheck-scan.k8s.yaml, .tekton/tasks/grype-vuln-web.k8s.yaml, .tekton/tasks/gitleaks-secrets.k8s.yaml, .tekton/tasks/semgrep-sast.k8s.yaml, .tekton/tasks/image-build-api.k8s.yaml, .tekton/tasks/image-build-scanner-worker.k8s.yaml, .tekton/tasks/image-build-oci-metadata-worker.k8s.yaml, .tekton/tasks/image-build-git-worker.k8s.yaml, .tekton/tasks/image-build-user-enricher-worker.k8s.yaml, .tekton/tasks/image-build-provenance-worker.k8s.yaml, .tekton/tasks/image-build-vuln-worker.k8s.yaml, .tekton/tasks/image-build-web.k8s.yaml, .tekton/tasks/image-build-k8s-agent.k8s.yaml, .tekton/tasks/image-build-operator.k8s.yaml, .tekton/tasks/image-build-cli.k8s.yaml, .tekton/tasks/helm-check.k8s.yaml, .tekton/tasks/helm-publish.k8s.yaml, .tekton/tasks/sbom-push.k8s.yaml, .tekton/tasks/set-status-pending-ocidex-pull-request.k8s.yaml, .tekton/tasks/detect-go.k8s.yaml, .tekton/tasks/detect-node.k8s.yaml, .tekton/tasks/detect-source.k8s.yaml, .tekton/tasks/detect-pipeline.k8s.yaml, .tekton/tasks/detect-charts.k8s.yaml, .tekton/tasks/tekton-check.k8s.yaml, .tekton/tasks/resolve-skipped-status-ocidex-pull-request.k8s.yaml, .tekton/tasks/set-status-pending-ocidex-tag.k8s.yaml, .tekton/tasks/image-release-api.k8s.yaml, .tekton/tasks/image-release-scanner-worker.k8s.yaml, .tekton/tasks/image-release-oci-metadata-worker.k8s.yaml, .tekton/tasks/image-release-git-worker.k8s.yaml, .tekton/tasks/image-release-user-enricher-worker.k8s.yaml, .tekton/tasks/image-release-provenance-worker.k8s.yaml, .tekton/tasks/image-release-vuln-worker.k8s.yaml, .tekton/tasks/image-release-web.k8s.yaml, .tekton/tasks/image-release-k8s-agent.k8s.yaml, .tekton/tasks/image-release-operator.k8s.yaml, .tekton/tasks/image-release-cli.k8s.yaml, .tekton/tasks/helm-release.k8s.yaml, .tekton/tasks/gh-release.k8s.yaml]"
  name: ocidex-ocidex-push
spec:
  params:
    - name: project-name
      value: "{{ repo_name }}"
    - name: repo-full-name
      value: "{{ repo_owner }}/{{ repo_name }}"
    - name: source-branch
      value: "{{ source_branch }}"
    - name: revision
      value: "{{ revision }}"
    - name: url
      value: "{{ repo_url }}"
  pipelineSpec:
    params:
      - name: project-name
        type: string
      - name: repo-full-name
        type: string
      - name: source-branch
        type: string
      - name: revision
        type: string
      - name: url
        type: string
    tasks:
      - name: set-status-pending-ocidex-push
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - git-clone
        taskRef:
          kind: Task
          name: ocidex-set-status-pending-ocidex-push
      - name: git-clone
        params:
          - name: url
            value: $(params.url)
          - name: revision
            value: $(params.revision)
        taskRef:
          kind: Task
          name: ocidex-git-clone
        workspaces:
          - name: workspace
            workspace: workspace
      - name: gofmt-check
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - set-status-pending-ocidex-push
        taskRef:
          kind: Task
          name: ocidex-gofmt-check
        workspaces:
          - name: workspace
            workspace: workspace
      - name: go-build
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - set-status-pending-ocidex-push
        taskRef:
          kind: Task
          name: ocidex-go-build
        workspaces:
          - name: go-cache
            workspace: go-cache
          - name: workspace
            workspace: workspace
      - name: go-test
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - go-build
          - set-status-pending-ocidex-push
        taskRef:
          kind: Task
          name: ocidex-go-test
        workspaces:
          - name: go-cache
            workspace: go-cache
          - name: workspace
            workspace: workspace
      - name: eslint-lint-web
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - set-status-pending-ocidex-push
        taskRef:
          kind: Task
          name: ocidex-eslint-lint-web
        workspaces:
          - name: node-cache
            workspace: node-cache
          - name: workspace
            workspace: workspace
      - name: openapi-verify
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - go-build
          - eslint-lint-web
          - set-status-pending-ocidex-push
        taskRef:
          kind: Task
          name: ocidex-openapi-verify
        workspaces:
          - name: workspace
            workspace: workspace
      - name: go-integration-test
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - go-build
          - set-status-pending-ocidex-push
        taskRef:
          kind: Task
          name: ocidex-go-integration-test
        timeout: 30m
        workspaces:
          - name: go-cache
            workspace: go-cache
          - name: workspace
            workspace: workspace
      - name: govulncheck-scan
        params:
          - name: source-branch
            value: $(params.source-branch)
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - go-build
          - set-status-pending-ocidex-push
        taskRef:
          kind: Task
          name: ocidex-govulncheck-scan
        workspaces:
          - name: go-cache
            workspace: go-cache
          - name: workspace
            workspace: workspace
      - name: grype-vuln-web
        params:
          - name: source-branch
            value: $(params.source-branch)
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - set-status-pending-ocidex-push
        taskRef:
          kind: Task
          name: ocidex-grype-vuln-web
        workspaces:
          - name: workspace
            workspace: workspace
      - name: gitleaks-secrets
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - set-status-pending-ocidex-push
        taskRef:
          kind: Task
          name: ocidex-gitleaks-secrets
        workspaces:
          - name: workspace
            workspace: workspace
      - name: semgrep-sast
        params:
          - name: source-branch
            value: $(params.source-branch)
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - set-status-pending-ocidex-push
        taskRef:
          kind: Task
          name: ocidex-semgrep-sast
        workspaces:
          - name: workspace
            workspace: workspace
      - name: image-build-api
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - go-test
          - go-integration-test
          - openapi-verify
          - set-status-pending-ocidex-push
        taskRef:
          kind: Task
          name: ocidex-image-build-api
        workspaces:
          - name: buildkit-cache
            workspace: buildkit-cache
          - name: workspace
            workspace: workspace
      - name: image-build-scanner-worker
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - go-test
          - go-integration-test
          - openapi-verify
          - image-build-api
          - set-status-pending-ocidex-push
        taskRef:
          kind: Task
          name: ocidex-image-build-scanner-worker
        workspaces:
          - name: buildkit-cache
            workspace: buildkit-cache
          - name: workspace
            workspace: workspace
      - name: image-build-oci-metadata-worker
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - go-test
          - go-integration-test
          - openapi-verify
          - image-build-scanner-worker
          - set-status-pending-ocidex-push
        taskRef:
          kind: Task
          name: ocidex-image-build-oci-metadata-worker
        workspaces:
          - name: buildkit-cache
            workspace: buildkit-cache
          - name: workspace
            workspace: workspace
      - name: image-build-git-worker
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - go-test
          - go-integration-test
          - openapi-verify
          - image-build-oci-metadata-worker
          - set-status-pending-ocidex-push
        taskRef:
          kind: Task
          name: ocidex-image-build-git-worker
        workspaces:
          - name: buildkit-cache
            workspace: buildkit-cache
          - name: workspace
            workspace: workspace
      - name: image-build-user-enricher-worker
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - go-test
          - go-integration-test
          - openapi-verify
          - image-build-git-worker
          - set-status-pending-ocidex-push
        taskRef:
          kind: Task
          name: ocidex-image-build-user-enricher-worker
        workspaces:
          - name: buildkit-cache
            workspace: buildkit-cache
          - name: workspace
            workspace: workspace
      - name: image-build-provenance-worker
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - go-test
          - go-integration-test
          - openapi-verify
          - image-build-user-enricher-worker
          - set-status-pending-ocidex-push
        taskRef:
          kind: Task
          name: ocidex-image-build-provenance-worker
        workspaces:
          - name: buildkit-cache
            workspace: buildkit-cache
          - name: workspace
            workspace: workspace
      - name: image-build-vuln-worker
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - go-test
          - go-integration-test
          - openapi-verify
          - image-build-provenance-worker
          - set-status-pending-ocidex-push
        taskRef:
          kind: Task
          name: ocidex-image-build-vuln-worker
        workspaces:
          - name: buildkit-cache
            workspace: buildkit-cache
          - name: workspace
            workspace: workspace
      - name: image-build-web
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - go-test
          - go-integration-test
          - openapi-verify
          - image-build-vuln-worker
          - set-status-pending-ocidex-push
        taskRef:
          kind: Task
          name: ocidex-image-build-web
        workspaces:
          - name: buildkit-cache
            workspace: buildkit-cache
          - name: workspace
            workspace: workspace
      - name: image-build-k8s-agent
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - go-test
          - go-integration-test
          - openapi-verify
          - image-build-web
          - set-status-pending-ocidex-push
        taskRef:
          kind: Task
          name: ocidex-image-build-k8s-agent
        workspaces:
          - name: buildkit-cache
            workspace: buildkit-cache
          - name: workspace
            workspace: workspace
      - name: image-build-operator
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - go-test
          - go-integration-test
          - openapi-verify
          - image-build-k8s-agent
          - set-status-pending-ocidex-push
        taskRef:
          kind: Task
          name: ocidex-image-build-operator
        workspaces:
          - name: buildkit-cache
            workspace: buildkit-cache
          - name: workspace
            workspace: workspace
      - name: image-build-cli
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - go-test
          - go-integration-test
          - openapi-verify
          - image-build-operator
          - set-status-pending-ocidex-push
        taskRef:
          kind: Task
          name: ocidex-image-build-cli
        workspaces:
          - name: buildkit-cache
            workspace: buildkit-cache
          - name: workspace
            workspace: workspace
      - name: helm-check
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - set-status-pending-ocidex-push
        taskRef:
          kind: Task
          name: ocidex-helm-check
        workspaces:
          - name: workspace
            workspace: workspace
      - name: helm-publish
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - image-build-api
          - image-build-scanner-worker
          - image-build-oci-metadata-worker
          - image-build-git-worker
          - image-build-user-enricher-worker
          - image-build-provenance-worker
          - image-build-vuln-worker
          - image-build-web
          - image-build-k8s-agent
          - image-build-operator
          - image-build-cli
          - helm-check
          - set-status-pending-ocidex-push
        taskRef:
          kind: Task
          name: ocidex-helm-publish
        workspaces:
          - name: workspace
            workspace: workspace
      - name: sbom-push
        params:
          - name: source-branch
            value: $(params.source-branch)
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - go-build
          - set-status-pending-ocidex-push
        taskRef:
          kind: Task
          name: ocidex-sbom-push
        workspaces:
          - name: go-cache
            workspace: go-cache
          - name: workspace
            workspace: workspace
    workspaces:
      - name: workspace
      - name: go-cache
      - name: node-cache
      - name: buildkit-cache
  taskRunTemplate:
    podTemplate:
      env:
        - name: PAC_EVENT_TYPE
          value: "{{ event_type }}"
        - name: PAC_TARGET_BRANCH
          value: "{{ target_branch }}"
        - name: HOME
          value: /tekton/home
      securityContext:
        fsGroup: 1024
        runAsGroup: 1024
        runAsNonRoot: true
        runAsUser: 1024
        seccompProfile:
          type: RuntimeDefault
    serviceAccountName: default
  timeouts:
    pipeline: 3h
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: local-path
    - name: go-cache
      persistentVolumeClaim:
        claimName: ocidex-go-cache
    - name: node-cache
      persistentVolumeClaim:
        claimName: ocidex-node-cache
    - name: buildkit-cache
      persistentVolumeClaim:
        claimName: ocidex-buildkit-cache
