apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    pipelinesascode.tekton.dev/max-keep-runs: "5"
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[*]"
    pipelinesascode.tekton.dev/task: "[.tekton/tasks/set-status-pending.k8s.yaml, .tekton/tasks/git-clone.k8s.yaml, .tekton/tasks/go-fmt.k8s.yaml, .tekton/tasks/go-test.k8s.yaml, .tekton/tasks/go-build.k8s.yaml, .tekton/tasks/openapi-check.k8s.yaml, .tekton/tasks/frontend-lint.k8s.yaml, .tekton/tasks/image-build-api.k8s.yaml, .tekton/tasks/image-build-scanner-worker.k8s.yaml, .tekton/tasks/image-build-enrichment-worker.k8s.yaml, .tekton/tasks/image-build-web.k8s.yaml, .tekton/tasks/image-build-operator.k8s.yaml, .tekton/tasks/helm-publish.k8s.yaml]"
  name: ocidex-ocidex-push
spec:
  params:
    - name: project-name
      value: "{{ repo_name }}"
    - name: repo-full-name
      value: "{{ repo_owner }}/{{ repo_name }}"
    - name: revision
      value: "{{ revision }}"
    - name: url
      value: "{{ repo_url }}"
  pipelineSpec:
    params:
      - name: project-name
        type: string
      - name: repo-full-name
        type: string
      - name: revision
        type: string
      - name: url
        type: string
    tasks:
      - name: set-status-pending
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - git-clone
        taskRef:
          kind: Task
          name: ocidex-set-status-pending
      - name: git-clone
        params:
          - name: url
            value: $(params.url)
          - name: revision
            value: $(params.revision)
        taskRef:
          kind: Task
          name: ocidex-git-clone
        workspaces:
          - name: workspace
            workspace: workspace
      - name: go-fmt
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - set-status-pending
        taskRef:
          kind: Task
          name: ocidex-go-fmt
        workspaces:
          - name: workspace
            workspace: workspace
      - name: go-build
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - set-status-pending
        taskRef:
          kind: Task
          name: ocidex-go-build
        workspaces:
          - name: go-cache
            workspace: go-cache
          - name: workspace
            workspace: workspace
      - name: go-test
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - go-build
          - set-status-pending
        taskRef:
          kind: Task
          name: ocidex-go-test
        workspaces:
          - name: workspace
            workspace: workspace
      - name: frontend-lint
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - set-status-pending
        taskRef:
          kind: Task
          name: ocidex-frontend-lint
        workspaces:
          - name: node-cache
            workspace: node-cache
          - name: workspace
            workspace: workspace
      - name: openapi-check
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - go-build
          - frontend-lint
          - set-status-pending
        taskRef:
          kind: Task
          name: ocidex-openapi-check
        workspaces:
          - name: workspace
            workspace: workspace
      - name: image-build-api
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - go-test
          - openapi-check
          - set-status-pending
        taskRef:
          kind: Task
          name: ocidex-image-build-api
        workspaces:
          - name: workspace
            workspace: workspace
      - name: image-build-scanner-worker
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - go-test
          - openapi-check
          - set-status-pending
        taskRef:
          kind: Task
          name: ocidex-image-build-scanner-worker
        workspaces:
          - name: workspace
            workspace: workspace
      - name: image-build-enrichment-worker
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - go-test
          - openapi-check
          - set-status-pending
        taskRef:
          kind: Task
          name: ocidex-image-build-enrichment-worker
        workspaces:
          - name: workspace
            workspace: workspace
      - name: image-build-web
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - go-test
          - openapi-check
          - set-status-pending
        taskRef:
          kind: Task
          name: ocidex-image-build-web
        workspaces:
          - name: workspace
            workspace: workspace
      - name: image-build-operator
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - go-test
          - openapi-check
          - set-status-pending
        taskRef:
          kind: Task
          name: ocidex-image-build-operator
        workspaces:
          - name: workspace
            workspace: workspace
      - name: helm-publish
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - image-build-api
          - image-build-scanner-worker
          - image-build-enrichment-worker
          - image-build-web
          - image-build-operator
          - set-status-pending
        taskRef:
          kind: Task
          name: ocidex-helm-publish
        workspaces:
          - name: workspace
            workspace: workspace
    workspaces:
      - name: workspace
      - name: go-cache
      - name: node-cache
  taskRunTemplate:
    podTemplate:
      securityContext:
        fsGroup: 1024
        runAsGroup: 1024
        runAsNonRoot: true
        runAsUser: 1024
        seccompProfile:
          type: RuntimeDefault
    serviceAccountName: default
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: local-path
    - name: go-cache
      persistentVolumeClaim:
        claimName: ocidex-go-cache
    - name: node-cache
      persistentVolumeClaim:
        claimName: ocidex-node-cache
