apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[*]"
    pipelinesascode.tekton.dev/task: "[.tekton/tasks/set-status-pending-ocidex-push.k8s.yaml, .tekton/tasks/git-clone.k8s.yaml, .tekton/tasks/gofmt-check.k8s.yaml, .tekton/tasks/go-test.k8s.yaml, .tekton/tasks/go-build.k8s.yaml, .tekton/tasks/openapi-verify.k8s.yaml, .tekton/tasks/eslint-lint-web.k8s.yaml, .tekton/tasks/govulncheck-scan.k8s.yaml, .tekton/tasks/grype-vuln-web.k8s.yaml, .tekton/tasks/gitleaks-secrets.k8s.yaml, .tekton/tasks/semgrep-sast.k8s.yaml, .tekton/tasks/image-build-api.k8s.yaml, .tekton/tasks/image-build-scanner-worker.k8s.yaml, .tekton/tasks/image-build-enrichment-worker.k8s.yaml, .tekton/tasks/image-build-oci-metadata-worker.k8s.yaml, .tekton/tasks/image-build-git-worker.k8s.yaml, .tekton/tasks/image-build-user-enricher-worker.k8s.yaml, .tekton/tasks/image-build-provenance-worker.k8s.yaml, .tekton/tasks/image-build-vuln-worker.k8s.yaml, .tekton/tasks/image-build-web.k8s.yaml, .tekton/tasks/image-build-operator.k8s.yaml, .tekton/tasks/helm-publish.k8s.yaml, .tekton/tasks/set-status-pending-ocidex-pull-request.k8s.yaml, .tekton/tasks/detect-go.k8s.yaml, .tekton/tasks/detect-node.k8s.yaml, .tekton/tasks/detect-source.k8s.yaml, .tekton/tasks/detect-pipeline.k8s.yaml, .tekton/tasks/tekton-check.k8s.yaml, .tekton/tasks/resolve-skipped-status-ocidex-pull-request.k8s.yaml, .tekton/tasks/set-status-pending-ocidex-tag.k8s.yaml, .tekton/tasks/image-release-api.k8s.yaml, .tekton/tasks/image-release-scanner-worker.k8s.yaml, .tekton/tasks/image-release-enrichment-worker.k8s.yaml, .tekton/tasks/image-release-oci-metadata-worker.k8s.yaml, .tekton/tasks/image-release-git-worker.k8s.yaml, .tekton/tasks/image-release-user-enricher-worker.k8s.yaml, .tekton/tasks/image-release-provenance-worker.k8s.yaml, .tekton/tasks/image-release-vuln-worker.k8s.yaml, .tekton/tasks/image-release-web.k8s.yaml, .tekton/tasks/image-release-operator.k8s.yaml, .tekton/tasks/helm-release.k8s.yaml, .tekton/tasks/gh-release.k8s.yaml]"
  name: ocidex-ocidex-pull-request
spec:
  params:
    - name: project-name
      value: "{{ repo_name }}"
    - name: repo-full-name
      value: "{{ repo_owner }}/{{ repo_name }}"
    - name: source-branch
      value: "{{ source_branch }}"
    - name: revision
      value: "{{ revision }}"
    - name: url
      value: "{{ repo_url }}"
  pipelineSpec:
    finally:
      - name: resolve-skipped-status-ocidex-pull-request
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        taskRef:
          kind: Task
          name: ocidex-resolve-skipped-status-ocidex-pull-request
    params:
      - name: project-name
        type: string
      - name: repo-full-name
        type: string
      - name: source-branch
        type: string
      - name: revision
        type: string
      - name: url
        type: string
    tasks:
      - name: set-status-pending-ocidex-pull-request
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - git-clone
        taskRef:
          kind: Task
          name: ocidex-set-status-pending-ocidex-pull-request
      - name: git-clone
        params:
          - name: url
            value: $(params.url)
          - name: revision
            value: $(params.revision)
        taskRef:
          kind: Task
          name: ocidex-git-clone
        workspaces:
          - name: workspace
            workspace: workspace
      - name: detect-go
        runAfter:
          - git-clone
        taskRef:
          kind: Task
          name: ocidex-detect-go
        workspaces:
          - name: workspace
            workspace: workspace
      - name: detect-node
        runAfter:
          - git-clone
        taskRef:
          kind: Task
          name: ocidex-detect-node
        workspaces:
          - name: workspace
            workspace: workspace
      - name: detect-source
        runAfter:
          - git-clone
        taskRef:
          kind: Task
          name: ocidex-detect-source
        workspaces:
          - name: workspace
            workspace: workspace
      - name: detect-pipeline
        runAfter:
          - git-clone
        taskRef:
          kind: Task
          name: ocidex-detect-pipeline
        workspaces:
          - name: workspace
            workspace: workspace
      - name: gofmt-check
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - set-status-pending-ocidex-pull-request
        taskRef:
          kind: Task
          name: ocidex-gofmt-check
        when:
          - input: $(tasks.detect-go.results.changed)
            operator: in
            values:
              - "true"
        workspaces:
          - name: workspace
            workspace: workspace
      - name: go-build
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - set-status-pending-ocidex-pull-request
        taskRef:
          kind: Task
          name: ocidex-go-build
        workspaces:
          - name: go-cache
            workspace: go-cache
          - name: workspace
            workspace: workspace
      - name: go-test
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - go-build
          - set-status-pending-ocidex-pull-request
        taskRef:
          kind: Task
          name: ocidex-go-test
        when:
          - input: $(tasks.detect-go.results.changed)
            operator: in
            values:
              - "true"
        workspaces:
          - name: go-cache
            workspace: go-cache
          - name: workspace
            workspace: workspace
      - name: eslint-lint-web
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - set-status-pending-ocidex-pull-request
        taskRef:
          kind: Task
          name: ocidex-eslint-lint-web
        workspaces:
          - name: node-cache
            workspace: node-cache
          - name: workspace
            workspace: workspace
      - name: openapi-verify
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - go-build
          - eslint-lint-web
          - set-status-pending-ocidex-pull-request
        taskRef:
          kind: Task
          name: ocidex-openapi-verify
        when:
          - input: $(tasks.detect-go.results.changed)
            operator: in
            values:
              - "true"
        workspaces:
          - name: workspace
            workspace: workspace
      - name: govulncheck-scan
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - go-build
          - set-status-pending-ocidex-pull-request
        taskRef:
          kind: Task
          name: ocidex-govulncheck-scan
        when:
          - input: $(tasks.detect-go.results.changed)
            operator: in
            values:
              - "true"
        workspaces:
          - name: go-cache
            workspace: go-cache
          - name: workspace
            workspace: workspace
      - name: grype-vuln-web
        params:
          - name: source-branch
            value: $(params.source-branch)
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - set-status-pending-ocidex-pull-request
        taskRef:
          kind: Task
          name: ocidex-grype-vuln-web
        when:
          - input: $(tasks.detect-node.results.changed)
            operator: in
            values:
              - "true"
        workspaces:
          - name: workspace
            workspace: workspace
      - name: semgrep-sast
        params:
          - name: source-branch
            value: $(params.source-branch)
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - set-status-pending-ocidex-pull-request
        taskRef:
          kind: Task
          name: ocidex-semgrep-sast
        when:
          - input: $(tasks.detect-source.results.changed)
            operator: in
            values:
              - "true"
        workspaces:
          - name: workspace
            workspace: workspace
      - name: gitleaks-secrets
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - set-status-pending-ocidex-pull-request
        taskRef:
          kind: Task
          name: ocidex-gitleaks-secrets
        workspaces:
          - name: workspace
            workspace: workspace
      - name: tekton-check
        params:
          - name: repo-full-name
            value: $(params.repo-full-name)
          - name: revision
            value: $(params.revision)
        runAfter:
          - set-status-pending-ocidex-pull-request
        taskRef:
          kind: Task
          name: ocidex-tekton-check
        when:
          - input: $(tasks.detect-pipeline.results.changed)
            operator: in
            values:
              - "true"
        workspaces:
          - name: workspace
            workspace: workspace
    workspaces:
      - name: workspace
      - name: go-cache
      - name: node-cache
  taskRunTemplate:
    podTemplate:
      env:
        - name: PAC_EVENT_TYPE
          value: "{{ event_type }}"
        - name: PAC_TARGET_BRANCH
          value: "{{ target_branch }}"
        - name: HOME
          value: /tekton/home
      securityContext:
        fsGroup: 1024
        runAsGroup: 1024
        runAsNonRoot: true
        runAsUser: 1024
        seccompProfile:
          type: RuntimeDefault
    serviceAccountName: default
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: local-path
    - name: go-cache
      persistentVolumeClaim:
        claimName: ocidex-go-cache
    - name: node-cache
      persistentVolumeClaim:
        claimName: ocidex-node-cache
