apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
spec:
  serviceName: nats
  replicas: 3
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: docker.io/nats:2-alpine
          args:
            - "-js"
            - "-cluster"
            - "nats://0.0.0.0:6222"
            - "-routes"
            - "nats://nats-0.nats:6222,nats://nats-1.nats:6222,nats://nats-2.nats:6222"
          ports:
            - containerPort: 4222
              name: client
            - containerPort: 6222
              name: cluster
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  clusterIP: None
  selector:
    app: nats
  ports:
    - port: 4222
      name: client
    - port: 6222
      name: cluster
