// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package client

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
	CookieAuthScopes cookieAuthContextKey = "cookieAuth.Scopes"
)

// Defines values for CreateAPIKeyInputBodyScope.
const (
	CreateAPIKeyInputBodyScopeRead      CreateAPIKeyInputBodyScope = "read"
	CreateAPIKeyInputBodyScopeReadWrite CreateAPIKeyInputBodyScope = "read-write"
)

// Valid indicates whether the value is a known member of the CreateAPIKeyInputBodyScope enum.
func (e CreateAPIKeyInputBodyScope) Valid() bool {
	switch e {
	case CreateAPIKeyInputBodyScopeRead:
		return true
	case CreateAPIKeyInputBodyScopeReadWrite:
		return true
	default:
		return false
	}
}

// Defines values for CreateRegistryInputBodyScanMode.
const (
	CreateRegistryInputBodyScanModeBoth    CreateRegistryInputBodyScanMode = "both"
	CreateRegistryInputBodyScanModePoll    CreateRegistryInputBodyScanMode = "poll"
	CreateRegistryInputBodyScanModeWebhook CreateRegistryInputBodyScanMode = "webhook"
)

// Valid indicates whether the value is a known member of the CreateRegistryInputBodyScanMode enum.
func (e CreateRegistryInputBodyScanMode) Valid() bool {
	switch e {
	case CreateRegistryInputBodyScanModeBoth:
		return true
	case CreateRegistryInputBodyScanModePoll:
		return true
	case CreateRegistryInputBodyScanModeWebhook:
		return true
	default:
		return false
	}
}

// Defines values for CreateRegistryInputBodyType.
const (
	CreateRegistryInputBodyTypeDocker  CreateRegistryInputBodyType = "docker"
	CreateRegistryInputBodyTypeGeneric CreateRegistryInputBodyType = "generic"
	CreateRegistryInputBodyTypeGhcr    CreateRegistryInputBodyType = "ghcr"
	CreateRegistryInputBodyTypeHarbor  CreateRegistryInputBodyType = "harbor"
	CreateRegistryInputBodyTypeZot     CreateRegistryInputBodyType = "zot"
)

// Valid indicates whether the value is a known member of the CreateRegistryInputBodyType enum.
func (e CreateRegistryInputBodyType) Valid() bool {
	switch e {
	case CreateRegistryInputBodyTypeDocker:
		return true
	case CreateRegistryInputBodyTypeGeneric:
		return true
	case CreateRegistryInputBodyTypeGhcr:
		return true
	case CreateRegistryInputBodyTypeHarbor:
		return true
	case CreateRegistryInputBodyTypeZot:
		return true
	default:
		return false
	}
}

// Defines values for CreateRegistryInputBodyVisibility.
const (
	CreateRegistryInputBodyVisibilityPrivate CreateRegistryInputBodyVisibility = "private"
	CreateRegistryInputBodyVisibilityPublic  CreateRegistryInputBodyVisibility = "public"
)

// Valid indicates whether the value is a known member of the CreateRegistryInputBodyVisibility enum.
func (e CreateRegistryInputBodyVisibility) Valid() bool {
	switch e {
	case CreateRegistryInputBodyVisibilityPrivate:
		return true
	case CreateRegistryInputBodyVisibilityPublic:
		return true
	default:
		return false
	}
}

// Defines values for KeyMetaResponseScope.
const (
	KeyMetaResponseScopeRead      KeyMetaResponseScope = "read"
	KeyMetaResponseScopeReadWrite KeyMetaResponseScope = "read-write"
)

// Valid indicates whether the value is a known member of the KeyMetaResponseScope enum.
func (e KeyMetaResponseScope) Valid() bool {
	switch e {
	case KeyMetaResponseScopeRead:
		return true
	case KeyMetaResponseScopeReadWrite:
		return true
	default:
		return false
	}
}

// Defines values for ScanJobResponseState.
const (
	ScanJobResponseStateFailed    ScanJobResponseState = "failed"
	ScanJobResponseStateQueued    ScanJobResponseState = "queued"
	ScanJobResponseStateRunning   ScanJobResponseState = "running"
	ScanJobResponseStateSucceeded ScanJobResponseState = "succeeded"
)

// Valid indicates whether the value is a known member of the ScanJobResponseState enum.
func (e ScanJobResponseState) Valid() bool {
	switch e {
	case ScanJobResponseStateFailed:
		return true
	case ScanJobResponseStateQueued:
		return true
	case ScanJobResponseStateRunning:
		return true
	case ScanJobResponseStateSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for UpdateRegistryInputBodyScanMode.
const (
	UpdateRegistryInputBodyScanModeBoth    UpdateRegistryInputBodyScanMode = "both"
	UpdateRegistryInputBodyScanModePoll    UpdateRegistryInputBodyScanMode = "poll"
	UpdateRegistryInputBodyScanModeWebhook UpdateRegistryInputBodyScanMode = "webhook"
)

// Valid indicates whether the value is a known member of the UpdateRegistryInputBodyScanMode enum.
func (e UpdateRegistryInputBodyScanMode) Valid() bool {
	switch e {
	case UpdateRegistryInputBodyScanModeBoth:
		return true
	case UpdateRegistryInputBodyScanModePoll:
		return true
	case UpdateRegistryInputBodyScanModeWebhook:
		return true
	default:
		return false
	}
}

// Defines values for UpdateRegistryInputBodyType.
const (
	UpdateRegistryInputBodyTypeDocker  UpdateRegistryInputBodyType = "docker"
	UpdateRegistryInputBodyTypeGeneric UpdateRegistryInputBodyType = "generic"
	UpdateRegistryInputBodyTypeGhcr    UpdateRegistryInputBodyType = "ghcr"
	UpdateRegistryInputBodyTypeHarbor  UpdateRegistryInputBodyType = "harbor"
	UpdateRegistryInputBodyTypeZot     UpdateRegistryInputBodyType = "zot"
)

// Valid indicates whether the value is a known member of the UpdateRegistryInputBodyType enum.
func (e UpdateRegistryInputBodyType) Valid() bool {
	switch e {
	case UpdateRegistryInputBodyTypeDocker:
		return true
	case UpdateRegistryInputBodyTypeGeneric:
		return true
	case UpdateRegistryInputBodyTypeGhcr:
		return true
	case UpdateRegistryInputBodyTypeHarbor:
		return true
	case UpdateRegistryInputBodyTypeZot:
		return true
	default:
		return false
	}
}

// Defines values for UpdateRegistryInputBodyVisibility.
const (
	UpdateRegistryInputBodyVisibilityPrivate UpdateRegistryInputBodyVisibility = "private"
	UpdateRegistryInputBodyVisibilityPublic  UpdateRegistryInputBodyVisibility = "public"
)

// Valid indicates whether the value is a known member of the UpdateRegistryInputBodyVisibility enum.
func (e UpdateRegistryInputBodyVisibility) Valid() bool {
	switch e {
	case UpdateRegistryInputBodyVisibilityPrivate:
		return true
	case UpdateRegistryInputBodyVisibilityPublic:
		return true
	default:
		return false
	}
}

// Defines values for UpdateUserRoleInputBodyRole.
const (
	Admin  UpdateUserRoleInputBodyRole = "admin"
	Member UpdateUserRoleInputBodyRole = "member"
	Viewer UpdateUserRoleInputBodyRole = "viewer"
)

// Valid indicates whether the value is a known member of the UpdateUserRoleInputBodyRole enum.
func (e UpdateUserRoleInputBodyRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Member:
		return true
	case Viewer:
		return true
	default:
		return false
	}
}

// Defines values for ListScanJobsParamsState.
const (
	ListScanJobsParamsStateFailed    ListScanJobsParamsState = "failed"
	ListScanJobsParamsStateQueued    ListScanJobsParamsState = "queued"
	ListScanJobsParamsStateRunning   ListScanJobsParamsState = "running"
	ListScanJobsParamsStateSucceeded ListScanJobsParamsState = "succeeded"
)

// Valid indicates whether the value is a known member of the ListScanJobsParamsState enum.
func (e ListScanJobsParamsState) Valid() bool {
	switch e {
	case ListScanJobsParamsStateFailed:
		return true
	case ListScanJobsParamsStateQueued:
		return true
	case ListScanJobsParamsStateRunning:
		return true
	case ListScanJobsParamsStateSucceeded:
		return true
	default:
		return false
	}
}

// ArtifactDetail defines model for ArtifactDetail.
type ArtifactDetail struct {
	// Schema A URL to the JSON Schema for this object.
	Schema              *string   `json:"$schema,omitempty"`
	Cpe                 *string   `json:"cpe,omitempty"`
	CreatedAt           time.Time `json:"createdAt"`
	Group               *string   `json:"group,omitempty"`
	Id                  string    `json:"id"`
	Name                string    `json:"name"`
	Purl                *string   `json:"purl,omitempty"`
	SbomCount           int64     `json:"sbomCount"`
	SufficientSbomCount int64     `json:"sufficientSbomCount"`
	Type                string    `json:"type"`
	VersionCount        int64     `json:"versionCount"`
}

// ArtifactSummary defines model for ArtifactSummary.
type ArtifactSummary struct {
	Group               *string `json:"group,omitempty"`
	Id                  string  `json:"id"`
	Name                string  `json:"name"`
	SbomCount           int64   `json:"sbomCount"`
	SufficientSbomCount int64   `json:"sufficientSbomCount"`
	Type                string  `json:"type"`
}

// ArtifactVersionSummary defines model for ArtifactVersionSummary.
type ArtifactVersionSummary struct {
	Architectures *[]string  `json:"architectures"`
	BuildDate     *time.Time `json:"buildDate,omitempty"`
	CreatedAt     time.Time  `json:"createdAt"`
	ImageVersion  *string    `json:"imageVersion,omitempty"`
	Revision      *string    `json:"revision,omitempty"`

	// SbomCount Total number of SBOMs ingested for this version
	SbomCount  int64   `json:"sbomCount"`
	SbomId     string  `json:"sbomId"`
	SourceUrl  *string `json:"sourceUrl,omitempty"`
	Sufficient bool    `json:"sufficient"`
	VersionKey string  `json:"versionKey"`
}

// CategoryCountEntry defines model for CategoryCountEntry.
type CategoryCountEntry struct {
	Category       string `json:"category"`
	ComponentCount int64  `json:"component_count"`
}

// ChangeCounts defines model for ChangeCounts.
type ChangeCounts struct {
	Added      int64 `json:"added"`
	Downgraded int64 `json:"downgraded"`
	Modified   int64 `json:"modified"`
	Removed    int64 `json:"removed"`
	Upgraded   int64 `json:"upgraded"`
}

// ChangeSummary defines model for ChangeSummary.
type ChangeSummary struct {
	Added      int64 `json:"added"`
	Downgraded int64 `json:"downgraded"`
	Modified   int64 `json:"modified"`
	Removed    int64 `json:"removed"`
	Upgraded   int64 `json:"upgraded"`
}

// Changelog defines model for Changelog.
type Changelog struct {
	// Schema A URL to the JSON Schema for this object.
	Schema                 *string           `json:"$schema,omitempty"`
	ArtifactId             string            `json:"artifactId"`
	AvailableArchitectures *[]string         `json:"availableArchitectures"`
	AvailableFlavors       *[]string         `json:"availableFlavors"`
	Entries                *[]ChangelogEntry `json:"entries"`
}

// ChangelogEntry defines model for ChangelogEntry.
type ChangelogEntry struct {
	// Schema A URL to the JSON Schema for this object.
	Schema  *string          `json:"$schema,omitempty"`
	Changes *[]ComponentDiff `json:"changes"`
	From    SBOMRef          `json:"from"`
	Summary ChangeSummary    `json:"summary"`
	To      SBOMRef          `json:"to"`
}

// ComponentDetail defines model for ComponentDetail.
type ComponentDetail struct {
	// Schema A URL to the JSON Schema for this object.
	Schema             *string             `json:"$schema,omitempty"`
	BomRef             *string             `json:"bomRef,omitempty"`
	Copyright          *string             `json:"copyright,omitempty"`
	Cpe                *string             `json:"cpe,omitempty"`
	DescendantChanges  *ChangeCounts       `json:"descendantChanges,omitempty"`
	Description        *string             `json:"description,omitempty"`
	ExternalReferences *[]ExternalRefEntry `json:"externalReferences"`
	Group              *string             `json:"group,omitempty"`
	Hashes             *[]HashEntry        `json:"hashes"`
	Id                 string              `json:"id"`
	IsDirect           bool                `json:"isDirect"`
	Licenses           *[]LicenseSummary   `json:"licenses"`
	Name               string              `json:"name"`
	Publisher          *string             `json:"publisher,omitempty"`
	Purl               *string             `json:"purl,omitempty"`
	SbomId             string              `json:"sbomId"`
	Scope              *string             `json:"scope,omitempty"`
	Type               string              `json:"type"`
	Version            *string             `json:"version,omitempty"`
}

// ComponentDiff defines model for ComponentDiff.
type ComponentDiff struct {
	Direction       string  `json:"direction"`
	Group           *string `json:"group,omitempty"`
	Name            string  `json:"name"`
	NodeRef         *string `json:"nodeRef,omitempty"`
	PreviousVersion *string `json:"previousVersion,omitempty"`
	Purl            *string `json:"purl,omitempty"`
	Type            string  `json:"type"`
	Version         *string `json:"version,omitempty"`
}

// ComponentSummary defines model for ComponentSummary.
type ComponentSummary struct {
	BomRef            *string       `json:"bomRef,omitempty"`
	DescendantChanges *ChangeCounts `json:"descendantChanges,omitempty"`
	Group             *string       `json:"group,omitempty"`
	Id                string        `json:"id"`
	IsDirect          bool          `json:"isDirect"`
	Name              string        `json:"name"`
	Purl              *string       `json:"purl,omitempty"`
	SbomId            string        `json:"sbomId"`
	Type              string        `json:"type"`
	Version           *string       `json:"version,omitempty"`
}

// ComponentVersionEntry defines model for ComponentVersionEntry.
type ComponentVersionEntry struct {
	Architecture   *string `json:"architecture,omitempty"`
	ArtifactId     *string `json:"artifactId,omitempty"`
	ArtifactName   *string `json:"artifactName,omitempty"`
	Group          *string `json:"group,omitempty"`
	Id             string  `json:"id"`
	Name           string  `json:"name"`
	Purl           *string `json:"purl,omitempty"`
	SbomCreatedAt  string  `json:"sbomCreatedAt"`
	SbomDigest     *string `json:"sbomDigest,omitempty"`
	SbomId         string  `json:"sbomId"`
	SubjectVersion *string `json:"subjectVersion,omitempty"`
	Type           string  `json:"type"`
	Version        *string `json:"version,omitempty"`
}

// CreateAPIKeyInputBody defines model for CreateAPIKeyInputBody.
type CreateAPIKeyInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Name Human-readable label for this key
	Name string `json:"name"`

	// Scope Key scope: read (GET only) or read-write (full access)
	Scope *CreateAPIKeyInputBodyScope `json:"scope,omitempty"`
}

// CreateAPIKeyInputBodyScope Key scope: read (GET only) or read-write (full access)
type CreateAPIKeyInputBodyScope string

// CreateAPIKeyOutputBody defines model for CreateAPIKeyOutputBody.
type CreateAPIKeyOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Key Full API key — shown once, store securely
	Key string `json:"key"`
}

// CreateRegistryInputBody defines model for CreateRegistryInputBody.
type CreateRegistryInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// AuthToken Token or PAT for registry authentication; omit for anonymous access
	AuthToken *string `json:"auth_token,omitempty"`

	// AuthUsername Username for registry authentication; omit for anonymous access
	AuthUsername *string `json:"auth_username,omitempty"`

	// IncludeUntagged Scan untagged manifests via registry-specific APIs (supported: zot, harbor, ghcr)
	IncludeUntagged *bool `json:"include_untagged,omitempty"`

	// Insecure Allow HTTP (non-TLS) connections
	Insecure bool `json:"insecure"`

	// Name Human-readable registry name
	Name string `json:"name"`

	// PollIntervalMinutes Minutes between polls
	PollIntervalMinutes *int64 `json:"poll_interval_minutes,omitempty"`

	// Repositories Explicit repositories to walk; bypasses /v2/_catalog discovery when non-empty
	Repositories *[]string `json:"repositories,omitempty"`

	// RepositoryPatterns Glob patterns for repositories to ingest; empty = all
	RepositoryPatterns *[]string `json:"repository_patterns,omitempty"`

	// ScanMode Scanning mode
	ScanMode *CreateRegistryInputBodyScanMode `json:"scan_mode,omitempty"`

	// TagPatterns Glob patterns or 'semver' for tags to ingest; empty = all
	TagPatterns *[]string `json:"tag_patterns,omitempty"`

	// Type Registry type
	Type CreateRegistryInputBodyType `json:"type"`

	// Url Registry address (e.g. zot:5000)
	Url string `json:"url"`

	// Visibility Registry visibility
	Visibility *CreateRegistryInputBodyVisibility `json:"visibility,omitempty"`

	// WebhookSecret Bearer token required on incoming webhooks; omit to disable auth
	WebhookSecret *string `json:"webhook_secret,omitempty"`
}

// CreateRegistryInputBodyScanMode Scanning mode
type CreateRegistryInputBodyScanMode string

// CreateRegistryInputBodyType Registry type
type CreateRegistryInputBodyType string

// CreateRegistryInputBodyVisibility Registry visibility
type CreateRegistryInputBodyVisibility string

// CreateRegistryResponseBody defines model for CreateRegistryResponseBody.
type CreateRegistryResponseBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema    *string `json:"$schema,omitempty"`
	CreatedAt string  `json:"created_at"`
	Enabled   bool    `json:"enabled"`
	HasAuth   bool    `json:"has_auth"`
	HasSecret bool    `json:"has_secret"`
	Id        string  `json:"id"`

	// IncludeUntagged Scan untagged manifests via registry-specific APIs (supported: zot, harbor, ghcr)
	IncludeUntagged bool    `json:"include_untagged"`
	Insecure        bool    `json:"insecure"`
	LastPolledAt    *string `json:"last_polled_at,omitempty"`
	Name            string  `json:"name"`

	// OwnerId UUID of the registry owner
	OwnerId *string `json:"owner_id,omitempty"`

	// OwnerUsername GitHub username of the registry owner
	OwnerUsername       *string `json:"owner_username,omitempty"`
	PollIntervalMinutes int64   `json:"poll_interval_minutes"`

	// Repositories Explicit repositories to walk; overrides catalog discovery when non-empty
	Repositories *[]string `json:"repositories"`

	// RepositoryPatterns Glob patterns for repositories to ingest; empty = all
	RepositoryPatterns *[]string `json:"repository_patterns"`
	ScanMode           string    `json:"scan_mode"`

	// TagPatterns Glob patterns or 'semver' for tags to ingest; empty = all
	TagPatterns *[]string `json:"tag_patterns"`
	Type        string    `json:"type"`
	UpdatedAt   string    `json:"updated_at"`
	Url         string    `json:"url"`

	// Visibility Registry visibility: public or private
	Visibility string `json:"visibility"`

	// WebhookSecret Generated webhook secret — shown once only. Store it securely; it cannot be retrieved again.
	WebhookSecret *string `json:"webhook_secret,omitempty"`
	WebhookUrl    string  `json:"webhook_url"`
}

// DBStatus defines model for DBStatus.
type DBStatus struct {
	LatencyMs int64 `json:"latency_ms"`
	Ok        bool  `json:"ok"`
}

// DailyCountEntry defines model for DailyCountEntry.
type DailyCountEntry struct {
	Count int64  `json:"count"`
	Day   string `json:"day"`
}

// DashboardStatsOutputBody defines model for DashboardStatsOutputBody.
type DashboardStatsOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema                *string                `json:"$schema,omitempty"`
	ArtifactCount         int64                  `json:"artifact_count"`
	IngestionTimeline     *[]DailyCountEntry     `json:"ingestion_timeline"`
	LicenseCategories     *[]CategoryCountEntry  `json:"license_categories"`
	LicenseCount          int64                  `json:"license_count"`
	PackageCount          int64                  `json:"package_count"`
	PackageGrowthTimeline *[]DailyCountEntry     `json:"package_growth_timeline"`
	SbomCount             int64                  `json:"sbom_count"`
	TopPackages           *[]PackageSummaryEntry `json:"top_packages"`
	VersionCount          int64                  `json:"version_count"`
	VersionGrowthTimeline *[]DailyCountEntry     `json:"version_growth_timeline"`
}

// DependencyEdge defines model for DependencyEdge.
type DependencyEdge struct {
	From string `json:"from"`
	To   string `json:"to"`
}

// DependencyGraph defines model for DependencyGraph.
type DependencyGraph struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string             `json:"$schema,omitempty"`
	Edges  *[]DependencyEdge   `json:"edges"`
	Nodes  *[]ComponentSummary `json:"nodes"`
	Roots  *[]string           `json:"roots"`
}

// DiffTree defines model for DiffTree.
type DiffTree struct {
	// Schema A URL to the JSON Schema for this object.
	Schema  *string             `json:"$schema,omitempty"`
	Changes *[]ComponentDiff    `json:"changes"`
	Edges   *[]DependencyEdge   `json:"edges"`
	From    SBOMRef             `json:"from"`
	Nodes   *[]ComponentSummary `json:"nodes"`
	Roots   *[]string           `json:"roots"`
	Summary ChangeSummary       `json:"summary"`
	To      SBOMRef             `json:"to"`
}

// DistinctComponentSummary defines model for DistinctComponentSummary.
type DistinctComponentSummary struct {
	Group        *string   `json:"group,omitempty"`
	Name         string    `json:"name"`
	PurlTypes    *[]string `json:"purlTypes,omitempty"`
	SbomCount    int64     `json:"sbomCount"`
	Type         string    `json:"type"`
	VersionCount int64     `json:"versionCount"`
}

// EnrichmentStatus defines model for EnrichmentStatus.
type EnrichmentStatus struct {
	Enabled   bool  `json:"enabled"`
	QueueSize int64 `json:"queue_size"`
	Workers   int64 `json:"workers"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Location Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
	Location *string `json:"location,omitempty"`

	// Message Error message text
	Message *string `json:"message,omitempty"`

	// Value The value at the given location
	Value interface{} `json:"value,omitempty"`
}

// ErrorModel defines model for ErrorModel.
type ErrorModel struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Errors Optional list of individual error details
	Errors *[]ErrorDetail `json:"errors,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int64 `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	Title *string `json:"title,omitempty"`

	// Type A URI reference to human-readable documentation for the error.
	Type *string `json:"type,omitempty"`
}

// ExternalRefEntry defines model for ExternalRefEntry.
type ExternalRefEntry struct {
	Comment *string `json:"comment,omitempty"`
	Type    string  `json:"type"`
	Url     string  `json:"url"`
}

// GetArtifactLicenseSummaryOutputBody defines model for GetArtifactLicenseSummaryOutputBody.
type GetArtifactLicenseSummaryOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema   *string         `json:"$schema,omitempty"`
	Licenses *[]LicenseCount `json:"licenses"`
}

// GetComponentVersionsOutputBody defines model for GetComponentVersionsOutputBody.
type GetComponentVersionsOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema   *string                  `json:"$schema,omitempty"`
	Versions *[]ComponentVersionEntry `json:"versions"`
}

// HashEntry defines model for HashEntry.
type HashEntry struct {
	Algorithm string `json:"algorithm"`
	Value     string `json:"value"`
}

// HealthCheckOutputBody defines model for HealthCheckOutputBody.
type HealthCheckOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Status Health status
	Status string `json:"status"`
}

// IngestSBOMOutputBody defines model for IngestSBOMOutputBody.
type IngestSBOMOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// ComponentCount Number of components in the SBOM
	ComponentCount int64 `json:"componentCount"`

	// Id UUID of the created SBOM
	Id string `json:"id"`

	// SerialNumber SBOM serial number
	SerialNumber *string `json:"serialNumber,omitempty"`

	// SpecVersion CycloneDX spec version
	SpecVersion string `json:"specVersion"`

	// Status Ingestion status
	Status string `json:"status"`
}

// KeyMetaResponse defines model for KeyMetaResponse.
type KeyMetaResponse struct {
	CreatedAt time.Time `json:"created_at"`

	// Id Key UUID
	Id         string     `json:"id"`
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	Name       string     `json:"name"`

	// Prefix First 8 characters of the key
	Prefix string `json:"prefix"`

	// Scope Key scope
	Scope KeyMetaResponseScope `json:"scope"`
}

// KeyMetaResponseScope Key scope
type KeyMetaResponseScope string

// LicenseCount defines model for LicenseCount.
type LicenseCount struct {
	Category       string  `json:"category"`
	ComponentCount int64   `json:"componentCount"`
	Id             string  `json:"id"`
	Name           string  `json:"name"`
	SpdxId         *string `json:"spdxId,omitempty"`
	Url            *string `json:"url,omitempty"`
}

// LicenseSummary defines model for LicenseSummary.
type LicenseSummary struct {
	Id     string  `json:"id"`
	Name   string  `json:"name"`
	SpdxId *string `json:"spdxId,omitempty"`
	Url    *string `json:"url,omitempty"`
}

// ListAPIKeysOutputBody defines model for ListAPIKeysOutputBody.
type ListAPIKeysOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string            `json:"$schema,omitempty"`
	Keys   *[]KeyMetaResponse `json:"keys"`
}

// ListArtifactSBOMsOutputBody defines model for ListArtifactSBOMsOutputBody.
type ListArtifactSBOMsOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string        `json:"$schema,omitempty"`
	Data       *[]SBOMSummary `json:"data"`
	Pagination PaginationMeta `json:"pagination"`
}

// ListArtifactVersionsOutputBody defines model for ListArtifactVersionsOutputBody.
type ListArtifactVersionsOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string                   `json:"$schema,omitempty"`
	Data       *[]ArtifactVersionSummary `json:"data"`
	Pagination PaginationMeta            `json:"pagination"`
}

// ListArtifactsOutputBody defines model for ListArtifactsOutputBody.
type ListArtifactsOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string            `json:"$schema,omitempty"`
	Data       *[]ArtifactSummary `json:"data"`
	Pagination PaginationMeta     `json:"pagination"`
}

// ListComponentPurlTypesOutputBody defines model for ListComponentPurlTypesOutputBody.
type ListComponentPurlTypesOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string   `json:"$schema,omitempty"`
	Types  *[]string `json:"types"`
}

// ListComponentsByLicenseOutputBody defines model for ListComponentsByLicenseOutputBody.
type ListComponentsByLicenseOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string             `json:"$schema,omitempty"`
	Data       *[]ComponentSummary `json:"data"`
	Pagination PaginationMeta      `json:"pagination"`
}

// ListLicensesOutputBody defines model for ListLicensesOutputBody.
type ListLicensesOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string         `json:"$schema,omitempty"`
	Data       *[]LicenseCount `json:"data"`
	Pagination PaginationMeta  `json:"pagination"`
}

// ListRegistriesOutputBody defines model for ListRegistriesOutputBody.
type ListRegistriesOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string             `json:"$schema,omitempty"`
	Data       *[]RegistryResponse `json:"data"`
	Pagination PaginationMeta      `json:"pagination"`
}

// ListSBOMComponentsOutputBody defines model for ListSBOMComponentsOutputBody.
type ListSBOMComponentsOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string             `json:"$schema,omitempty"`
	Components *[]ComponentSummary `json:"components"`
}

// ListSBOMsOutputBody defines model for ListSBOMsOutputBody.
type ListSBOMsOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string        `json:"$schema,omitempty"`
	Data       *[]SBOMSummary `json:"data"`
	Pagination PaginationMeta `json:"pagination"`
}

// ListScanJobsOutputBody defines model for ListScanJobsOutputBody.
type ListScanJobsOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string            `json:"$schema,omitempty"`
	Data       *[]ScanJobResponse `json:"data"`
	Pagination PaginationMeta     `json:"pagination"`
}

// ListUsersOutputBody defines model for ListUsersOutputBody.
type ListUsersOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string         `json:"$schema,omitempty"`
	Users  *[]UserResponse `json:"users"`
}

// MeOutputBody defines model for MeOutputBody.
type MeOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// GithubUsername GitHub login
	GithubUsername string `json:"github_username"`

	// Id User UUID
	Id string `json:"id"`

	// Role User role: admin, member, or viewer
	Role string `json:"role"`
}

// NATSStatus defines model for NATSStatus.
type NATSStatus struct {
	Enabled bool   `json:"enabled"`
	Url     string `json:"url"`
}

// PackageSummaryEntry defines model for PackageSummaryEntry.
type PackageSummaryEntry struct {
	Group        *string `json:"group,omitempty"`
	Name         string  `json:"name"`
	SbomCount    int64   `json:"sbom_count"`
	Type         string  `json:"type"`
	VersionCount int64   `json:"version_count"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	// Limit The limit that was applied
	Limit int32 `json:"limit"`

	// Offset The offset that was applied
	Offset int32 `json:"offset"`

	// Total Total number of matching results
	Total int64 `json:"total"`
}

// ReadinessCheckOutputBody defines model for ReadinessCheckOutputBody.
type ReadinessCheckOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Reason Reason for unavailability
	Reason *string `json:"reason,omitempty"`

	// Status Readiness status
	Status string `json:"status"`
}

// RegenerateWebhookSecretOutputBody defines model for RegenerateWebhookSecretOutputBody.
type RegenerateWebhookSecretOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// WebhookSecret New webhook secret — shown once only. The previous secret is immediately invalidated.
	WebhookSecret string `json:"webhook_secret"`
}

// RegistryResponse defines model for RegistryResponse.
type RegistryResponse struct {
	// Schema A URL to the JSON Schema for this object.
	Schema    *string `json:"$schema,omitempty"`
	CreatedAt string  `json:"created_at"`
	Enabled   bool    `json:"enabled"`
	HasAuth   bool    `json:"has_auth"`
	HasSecret bool    `json:"has_secret"`
	Id        string  `json:"id"`

	// IncludeUntagged Scan untagged manifests via registry-specific APIs (supported: zot, harbor, ghcr)
	IncludeUntagged bool    `json:"include_untagged"`
	Insecure        bool    `json:"insecure"`
	LastPolledAt    *string `json:"last_polled_at,omitempty"`
	Name            string  `json:"name"`

	// OwnerId UUID of the registry owner
	OwnerId *string `json:"owner_id,omitempty"`

	// OwnerUsername GitHub username of the registry owner
	OwnerUsername       *string `json:"owner_username,omitempty"`
	PollIntervalMinutes int64   `json:"poll_interval_minutes"`

	// Repositories Explicit repositories to walk; overrides catalog discovery when non-empty
	Repositories *[]string `json:"repositories"`

	// RepositoryPatterns Glob patterns for repositories to ingest; empty = all
	RepositoryPatterns *[]string `json:"repository_patterns"`
	ScanMode           string    `json:"scan_mode"`

	// TagPatterns Glob patterns or 'semver' for tags to ingest; empty = all
	TagPatterns *[]string `json:"tag_patterns"`
	Type        string    `json:"type"`
	UpdatedAt   string    `json:"updated_at"`
	Url         string    `json:"url"`

	// Visibility Registry visibility: public or private
	Visibility string `json:"visibility"`
	WebhookUrl string `json:"webhook_url"`
}

// RegistryWebhookInputBody defines model for RegistryWebhookInputBody.
type RegistryWebhookInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema    *string `json:"$schema,omitempty"`
	Digest    string  `json:"digest"`
	Manifest  string  `json:"manifest"`
	MediaType string  `json:"mediaType"`
	Name      string  `json:"name"`
	Reference string  `json:"reference"`
}

// RetryAllFailedScanJobsOutputBody defines model for RetryAllFailedScanJobsOutputBody.
type RetryAllFailedScanJobsOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Count Number of rows transitioned from 'failed' to 'queued'
	Count int64 `json:"count"`
}

// SBOMDetail defines model for SBOMDetail.
type SBOMDetail struct {
	// Schema A URL to the JSON Schema for this object.
	Schema         *string                 `json:"$schema,omitempty"`
	Architecture   *string                 `json:"architecture,omitempty"`
	ArtifactId     *string                 `json:"artifactId,omitempty"`
	BuildDate      *time.Time              `json:"buildDate,omitempty"`
	ComponentCount *int64                  `json:"componentCount,omitempty"`
	CreatedAt      time.Time               `json:"createdAt"`
	Digest         *string                 `json:"digest,omitempty"`
	Enrichments    *map[string]interface{} `json:"enrichments,omitempty"`
	Flavor         *string                 `json:"flavor,omitempty"`
	Id             string                  `json:"id"`
	ImageVersion   *string                 `json:"imageVersion,omitempty"`
	RawBom         interface{}             `json:"rawBom,omitempty"`
	Revision       *string                 `json:"revision,omitempty"`
	SerialNumber   *string                 `json:"serialNumber,omitempty"`
	SourceUrl      *string                 `json:"sourceUrl,omitempty"`
	SpecVersion    string                  `json:"specVersion"`
	SubjectVersion *string                 `json:"subjectVersion,omitempty"`
	Sufficient     bool                    `json:"sufficient"`
	Version        int32                   `json:"version"`
}

// SBOMRef defines model for SBOMRef.
type SBOMRef struct {
	Architecture   *string    `json:"architecture,omitempty"`
	BuildDate      *time.Time `json:"buildDate,omitempty"`
	CreatedAt      time.Time  `json:"createdAt"`
	Flavor         *string    `json:"flavor,omitempty"`
	Id             string     `json:"id"`
	SubjectVersion *string    `json:"subjectVersion,omitempty"`
}

// SBOMSummary defines model for SBOMSummary.
type SBOMSummary struct {
	Architecture   *string    `json:"architecture,omitempty"`
	ArtifactId     *string    `json:"artifactId,omitempty"`
	BuildDate      *time.Time `json:"buildDate,omitempty"`
	ComponentCount *int64     `json:"componentCount,omitempty"`
	CreatedAt      time.Time  `json:"createdAt"`
	Digest         *string    `json:"digest,omitempty"`
	Flavor         *string    `json:"flavor,omitempty"`
	Id             string     `json:"id"`
	ImageVersion   *string    `json:"imageVersion,omitempty"`
	Revision       *string    `json:"revision,omitempty"`
	SerialNumber   *string    `json:"serialNumber,omitempty"`
	SourceUrl      *string    `json:"sourceUrl,omitempty"`
	SpecVersion    string     `json:"specVersion"`
	SubjectVersion *string    `json:"subjectVersion,omitempty"`
	Sufficient     bool       `json:"sufficient"`
	Version        int32      `json:"version"`
}

// ScanJobResponse defines model for ScanJobResponse.
type ScanJobResponse struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string `json:"$schema,omitempty"`
	Attempts   int32   `json:"attempts"`
	CreatedAt  string  `json:"created_at"`
	Digest     string  `json:"digest"`
	FinishedAt *string `json:"finished_at,omitempty"`

	// Id Job UUID
	Id            string  `json:"id"`
	LastAttemptAt *string `json:"last_attempt_at,omitempty"`
	LastError     *string `json:"last_error,omitempty"`

	// NatsMsgId NATS deduplication message ID
	NatsMsgId *string `json:"nats_msg_id,omitempty"`

	// RegistryId Source registry UUID
	RegistryId *string `json:"registry_id,omitempty"`
	Repository string  `json:"repository"`

	// SbomId Resulting SBOM UUID on success
	SbomId    *string              `json:"sbom_id,omitempty"`
	StartedAt *string              `json:"started_at,omitempty"`
	State     ScanJobResponseState `json:"state"`
	Tag       *string              `json:"tag,omitempty"`

	// WorkerId Pod hostname that is processing this job
	WorkerId *string `json:"worker_id,omitempty"`
}

// ScanJobResponseState defines model for ScanJobResponse.State.
type ScanJobResponseState string

// ScanJobsStatus defines model for ScanJobsStatus.
type ScanJobsStatus struct {
	Failed24h    int64 `json:"failed_24h"`
	Queued       int64 `json:"queued"`
	Running      int64 `json:"running"`
	Succeeded24h int64 `json:"succeeded_24h"`
}

// ScanRegistryOutputBody defines model for ScanRegistryOutputBody.
type ScanRegistryOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Message Confirmation that ad-hoc scan has been initiated
	Message string `json:"message"`
}

// ScannerStatus defines model for ScannerStatus.
type ScannerStatus struct {
	Enabled       bool `json:"enabled"`
	PollerEnabled bool `json:"poller_enabled"`
}

// SearchComponentsOutputBody defines model for SearchComponentsOutputBody.
type SearchComponentsOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string             `json:"$schema,omitempty"`
	Data       *[]ComponentSummary `json:"data"`
	Pagination PaginationMeta      `json:"pagination"`
}

// SearchDistinctComponentsOutputBody defines model for SearchDistinctComponentsOutputBody.
type SearchDistinctComponentsOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string                     `json:"$schema,omitempty"`
	Data       *[]DistinctComponentSummary `json:"data"`
	Pagination PaginationMeta              `json:"pagination"`
}

// SystemStatusOutputBody defines model for SystemStatusOutputBody.
type SystemStatusOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string          `json:"$schema,omitempty"`
	Db         DBStatus         `json:"db"`
	Enrichment EnrichmentStatus `json:"enrichment"`
	Nats       NATSStatus       `json:"nats"`
	ScanJobs   ScanJobsStatus   `json:"scan_jobs"`
	Scanner    ScannerStatus    `json:"scanner"`
}

// TestRegistryConnectionInputBody defines model for TestRegistryConnectionInputBody.
type TestRegistryConnectionInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// AuthToken Token or PAT for registry authentication
	AuthToken *string `json:"auth_token,omitempty"`

	// AuthUsername Username for registry authentication
	AuthUsername *string `json:"auth_username,omitempty"`

	// Insecure Use HTTP instead of HTTPS
	Insecure bool `json:"insecure"`

	// Url Registry address (e.g. zot:5000)
	Url string `json:"url"`
}

// TestRegistryConnectionOutputBody defines model for TestRegistryConnectionOutputBody.
type TestRegistryConnectionOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Message Human-readable result (e.g. HTTP 200 or error text)
	Message string `json:"message"`

	// Reachable Whether the registry responded
	Reachable bool `json:"reachable"`
}

// UpdateRegistryInputBody defines model for UpdateRegistryInputBody.
type UpdateRegistryInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema       *string `json:"$schema,omitempty"`
	AuthToken    *string `json:"auth_token,omitempty"`
	AuthUsername *string `json:"auth_username,omitempty"`
	Enabled      bool    `json:"enabled"`

	// IncludeUntagged Scan untagged manifests via registry-specific APIs (supported: zot, harbor, ghcr)
	IncludeUntagged *bool  `json:"include_untagged,omitempty"`
	Insecure        bool   `json:"insecure"`
	Name            string `json:"name"`

	// PollIntervalMinutes Minutes between polls
	PollIntervalMinutes *int64    `json:"poll_interval_minutes,omitempty"`
	Repositories        *[]string `json:"repositories,omitempty"`
	RepositoryPatterns  *[]string `json:"repository_patterns,omitempty"`

	// ScanMode Scanning mode
	ScanMode    *UpdateRegistryInputBodyScanMode `json:"scan_mode,omitempty"`
	TagPatterns *[]string                        `json:"tag_patterns,omitempty"`
	Type        UpdateRegistryInputBodyType      `json:"type"`
	Url         string                           `json:"url"`

	// Visibility Registry visibility
	Visibility *UpdateRegistryInputBodyVisibility `json:"visibility,omitempty"`
}

// UpdateRegistryInputBodyScanMode Scanning mode
type UpdateRegistryInputBodyScanMode string

// UpdateRegistryInputBodyType defines model for UpdateRegistryInputBody.Type.
type UpdateRegistryInputBodyType string

// UpdateRegistryInputBodyVisibility Registry visibility
type UpdateRegistryInputBodyVisibility string

// UpdateUserRoleInputBody defines model for UpdateUserRoleInputBody.
type UpdateUserRoleInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Role New role
	Role UpdateUserRoleInputBodyRole `json:"role"`
}

// UpdateUserRoleInputBodyRole New role
type UpdateUserRoleInputBodyRole string

// UserResponse defines model for UserResponse.
type UserResponse struct {
	// Schema A URL to the JSON Schema for this object.
	Schema         *string `json:"$schema,omitempty"`
	GithubUsername string  `json:"github_username"`
	Id             string  `json:"id"`
	Role           string  `json:"role"`
}

// VersionOutputBody defines model for VersionOutputBody.
type VersionOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Version API version
	Version string `json:"version"`
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// cookieAuthContextKey is the context key for cookieAuth security scheme
type cookieAuthContextKey string

// ListArtifactsParams defines parameters for ListArtifacts.
type ListArtifactsParams struct {
	// Limit Maximum number of results per page
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`

	// Type Filter by artifact type
	Type *string `form:"type,omitempty" json:"type,omitempty"`

	// Name Filter by artifact name
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Sufficient Filter to artifacts with sufficiently enriched SBOMs; pass 'false' to include all (default: true)
	Sufficient *string `form:"sufficient,omitempty" json:"sufficient,omitempty"`
}

// GetArtifactChangelogParams defines parameters for GetArtifactChangelog.
type GetArtifactChangelogParams struct {
	// SubjectVersion Filter by subject version
	SubjectVersion *string `form:"subject_version,omitempty" json:"subject_version,omitempty"`

	// Arch Architecture to show timeline for (e.g. amd64)
	Arch *string `form:"arch,omitempty" json:"arch,omitempty"`

	// Flavor Flavor to show timeline for (e.g. standard, fips)
	Flavor *string `form:"flavor,omitempty" json:"flavor,omitempty"`
}

// ListArtifactSbomsParams defines parameters for ListArtifactSboms.
type ListArtifactSbomsParams struct {
	// Limit Maximum number of results per page
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`

	// SubjectVersion Filter by subject version
	SubjectVersion *string `form:"subject_version,omitempty" json:"subject_version,omitempty"`

	// ImageVersion Filter by image version
	ImageVersion *string `form:"image_version,omitempty" json:"image_version,omitempty"`
}

// ListArtifactVersionsParams defines parameters for ListArtifactVersions.
type ListArtifactVersionsParams struct {
	// Limit Maximum number of results per page
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`
}

// SearchComponentsParams defines parameters for SearchComponents.
type SearchComponentsParams struct {
	// Limit Maximum number of results per page
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`

	// Name Component name to search for
	Name string `form:"name" json:"name"`

	// Group Filter by component group
	Group *string `form:"group,omitempty" json:"group,omitempty"`

	// Version Filter by component version
	Version *string `form:"version,omitempty" json:"version,omitempty"`
}

// SearchDistinctComponentsParams defines parameters for SearchDistinctComponents.
type SearchDistinctComponentsParams struct {
	// Limit Maximum number of results per page
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`

	// Name Filter by component name
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Group Filter by component group
	Group *string `form:"group,omitempty" json:"group,omitempty"`

	// Type Filter by component type
	Type *string `form:"type,omitempty" json:"type,omitempty"`

	// PurlType Filter by purl type
	PurlType *string `form:"purl_type,omitempty" json:"purl_type,omitempty"`

	// Sort Sort field
	Sort *string `form:"sort,omitempty" json:"sort,omitempty"`

	// SortDir Sort direction (asc or desc)
	SortDir *string `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`
}

// GetComponentVersionsParams defines parameters for GetComponentVersions.
type GetComponentVersionsParams struct {
	// Name Component name
	Name string `form:"name" json:"name"`

	// Group Filter by component group
	Group *string `form:"group,omitempty" json:"group,omitempty"`

	// Version Filter by component version
	Version *string `form:"version,omitempty" json:"version,omitempty"`

	// Type Filter by component type
	Type *string `form:"type,omitempty" json:"type,omitempty"`
}

// ListScanJobsParams defines parameters for ListScanJobs.
type ListScanJobsParams struct {
	// Limit Maximum number of results per page
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`

	// State Filter by job state
	State *ListScanJobsParamsState `form:"state,omitempty" json:"state,omitempty"`
}

// ListScanJobsParamsState defines parameters for ListScanJobs.
type ListScanJobsParamsState string

// ListLicensesParams defines parameters for ListLicenses.
type ListLicensesParams struct {
	// Limit Maximum number of results per page
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`

	// SpdxId Filter by SPDX identifier
	SpdxId *string `form:"spdx_id,omitempty" json:"spdx_id,omitempty"`

	// Name Filter by license name
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Category Filter by license category
	Category *string `form:"category,omitempty" json:"category,omitempty"`
}

// ListComponentsByLicenseParams defines parameters for ListComponentsByLicense.
type ListComponentsByLicenseParams struct {
	// Limit Maximum number of results per page
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListRegistriesParams defines parameters for ListRegistries.
type ListRegistriesParams struct {
	// Limit Maximum number of results per page
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`
}

// RegistryWebhookParams defines parameters for RegistryWebhook.
type RegistryWebhookParams struct {
	Authorization *string `json:"Authorization,omitempty"`
}

// ListSbomsParams defines parameters for ListSboms.
type ListSbomsParams struct {
	// Limit Maximum number of results per page
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`

	// SerialNumber Filter by serial number
	SerialNumber *string `form:"serial_number,omitempty" json:"serial_number,omitempty"`

	// Digest Filter by image digest
	Digest *string `form:"digest,omitempty" json:"digest,omitempty"`
}

// IngestSbomParams defines parameters for IngestSbom.
type IngestSbomParams struct {
	// Version Image version/tag (overrides BOM-extracted value for subject_version and imageVersion)
	Version *string `form:"version,omitempty" json:"version,omitempty"`

	// Architecture Image architecture (e.g. amd64, arm64)
	Architecture *string `form:"architecture,omitempty" json:"architecture,omitempty"`

	// BuildDate Image build date (RFC3339 or date string)
	BuildDate *string `form:"build_date,omitempty" json:"build_date,omitempty"`
}

// DiffSbomsParams defines parameters for DiffSboms.
type DiffSbomsParams struct {
	// From UUID of the source SBOM
	From openapi_types.UUID `form:"from" json:"from"`

	// To UUID of the target SBOM
	To openapi_types.UUID `form:"to" json:"to"`
}

// DiffTreeParams defines parameters for DiffTree.
type DiffTreeParams struct {
	// From UUID of the source SBOM
	From openapi_types.UUID `form:"from" json:"from"`

	// To UUID of the target SBOM
	To openapi_types.UUID `form:"to" json:"to"`
}

// GetSbomParams defines parameters for GetSbom.
type GetSbomParams struct {
	// Include Set to 'raw' to include the raw BOM JSON
	Include *string `form:"include,omitempty" json:"include,omitempty"`
}

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = CreateAPIKeyInputBody

// CreateRegistryJSONRequestBody defines body for CreateRegistry for application/json ContentType.
type CreateRegistryJSONRequestBody = CreateRegistryInputBody

// TestRegistryConnectionJSONRequestBody defines body for TestRegistryConnection for application/json ContentType.
type TestRegistryConnectionJSONRequestBody = TestRegistryConnectionInputBody

// UpdateRegistryJSONRequestBody defines body for UpdateRegistry for application/json ContentType.
type UpdateRegistryJSONRequestBody = UpdateRegistryInputBody

// RegistryWebhookJSONRequestBody defines body for RegistryWebhook for application/json ContentType.
type RegistryWebhookJSONRequestBody = RegistryWebhookInputBody

// UpdateUserRoleJSONRequestBody defines body for UpdateUserRole for application/json ContentType.
type UpdateUserRoleJSONRequestBody = UpdateUserRoleInputBody
