// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package client

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
	CookieAuthScopes cookieAuthContextKey = "cookieAuth.Scopes"
)

// Defines values for ArtifactVersionSummarySigningStatus.
const (
	ArtifactMissing    ArtifactVersionSummarySigningStatus = "artifact_missing"
	Signed             ArtifactVersionSummarySigningStatus = "signed"
	Unsigned           ArtifactVersionSummarySigningStatus = "unsigned"
	VerificationFailed ArtifactVersionSummarySigningStatus = "verification_failed"
	Verified           ArtifactVersionSummarySigningStatus = "verified"
)

// Valid indicates whether the value is a known member of the ArtifactVersionSummarySigningStatus enum.
func (e ArtifactVersionSummarySigningStatus) Valid() bool {
	switch e {
	case ArtifactMissing:
		return true
	case Signed:
		return true
	case Unsigned:
		return true
	case VerificationFailed:
		return true
	case Verified:
		return true
	default:
		return false
	}
}

// Defines values for CreateAPIKeyInputBodyScope.
const (
	CreateAPIKeyInputBodyScopeRead      CreateAPIKeyInputBodyScope = "read"
	CreateAPIKeyInputBodyScopeReadWrite CreateAPIKeyInputBodyScope = "read-write"
)

// Valid indicates whether the value is a known member of the CreateAPIKeyInputBodyScope enum.
func (e CreateAPIKeyInputBodyScope) Valid() bool {
	switch e {
	case CreateAPIKeyInputBodyScopeRead:
		return true
	case CreateAPIKeyInputBodyScopeReadWrite:
		return true
	default:
		return false
	}
}

// Defines values for CreateNamespaceInputBodyVisibility.
const (
	CreateNamespaceInputBodyVisibilityPrivate CreateNamespaceInputBodyVisibility = "private"
	CreateNamespaceInputBodyVisibilityPublic  CreateNamespaceInputBodyVisibility = "public"
)

// Valid indicates whether the value is a known member of the CreateNamespaceInputBodyVisibility enum.
func (e CreateNamespaceInputBodyVisibility) Valid() bool {
	switch e {
	case CreateNamespaceInputBodyVisibilityPrivate:
		return true
	case CreateNamespaceInputBodyVisibilityPublic:
		return true
	default:
		return false
	}
}

// Defines values for CreateRegistryInputBodyScanMode.
const (
	CreateRegistryInputBodyScanModeBoth    CreateRegistryInputBodyScanMode = "both"
	CreateRegistryInputBodyScanModePoll    CreateRegistryInputBodyScanMode = "poll"
	CreateRegistryInputBodyScanModeWebhook CreateRegistryInputBodyScanMode = "webhook"
)

// Valid indicates whether the value is a known member of the CreateRegistryInputBodyScanMode enum.
func (e CreateRegistryInputBodyScanMode) Valid() bool {
	switch e {
	case CreateRegistryInputBodyScanModeBoth:
		return true
	case CreateRegistryInputBodyScanModePoll:
		return true
	case CreateRegistryInputBodyScanModeWebhook:
		return true
	default:
		return false
	}
}

// Defines values for CreateRegistryInputBodyType.
const (
	CreateRegistryInputBodyTypeDocker  CreateRegistryInputBodyType = "docker"
	CreateRegistryInputBodyTypeGeneric CreateRegistryInputBodyType = "generic"
	CreateRegistryInputBodyTypeGhcr    CreateRegistryInputBodyType = "ghcr"
	CreateRegistryInputBodyTypeHarbor  CreateRegistryInputBodyType = "harbor"
	CreateRegistryInputBodyTypeZot     CreateRegistryInputBodyType = "zot"
)

// Valid indicates whether the value is a known member of the CreateRegistryInputBodyType enum.
func (e CreateRegistryInputBodyType) Valid() bool {
	switch e {
	case CreateRegistryInputBodyTypeDocker:
		return true
	case CreateRegistryInputBodyTypeGeneric:
		return true
	case CreateRegistryInputBodyTypeGhcr:
		return true
	case CreateRegistryInputBodyTypeHarbor:
		return true
	case CreateRegistryInputBodyTypeZot:
		return true
	default:
		return false
	}
}

// Defines values for CreateRegistryInputBodyVerificationMode.
const (
	CreateRegistryInputBodyVerificationModeKeyless   CreateRegistryInputBodyVerificationMode = "keyless"
	CreateRegistryInputBodyVerificationModeNone      CreateRegistryInputBodyVerificationMode = "none"
	CreateRegistryInputBodyVerificationModePublicKey CreateRegistryInputBodyVerificationMode = "public_key"
)

// Valid indicates whether the value is a known member of the CreateRegistryInputBodyVerificationMode enum.
func (e CreateRegistryInputBodyVerificationMode) Valid() bool {
	switch e {
	case CreateRegistryInputBodyVerificationModeKeyless:
		return true
	case CreateRegistryInputBodyVerificationModeNone:
		return true
	case CreateRegistryInputBodyVerificationModePublicKey:
		return true
	default:
		return false
	}
}

// Defines values for CreateRegistryInputBodyVisibility.
const (
	CreateRegistryInputBodyVisibilityPrivate CreateRegistryInputBodyVisibility = "private"
	CreateRegistryInputBodyVisibilityPublic  CreateRegistryInputBodyVisibility = "public"
)

// Valid indicates whether the value is a known member of the CreateRegistryInputBodyVisibility enum.
func (e CreateRegistryInputBodyVisibility) Valid() bool {
	switch e {
	case CreateRegistryInputBodyVisibilityPrivate:
		return true
	case CreateRegistryInputBodyVisibilityPublic:
		return true
	default:
		return false
	}
}

// Defines values for CreateRegistryResponseBodyVerificationMode.
const (
	CreateRegistryResponseBodyVerificationModeKeyless   CreateRegistryResponseBodyVerificationMode = "keyless"
	CreateRegistryResponseBodyVerificationModeNone      CreateRegistryResponseBodyVerificationMode = "none"
	CreateRegistryResponseBodyVerificationModePublicKey CreateRegistryResponseBodyVerificationMode = "public_key"
)

// Valid indicates whether the value is a known member of the CreateRegistryResponseBodyVerificationMode enum.
func (e CreateRegistryResponseBodyVerificationMode) Valid() bool {
	switch e {
	case CreateRegistryResponseBodyVerificationModeKeyless:
		return true
	case CreateRegistryResponseBodyVerificationModeNone:
		return true
	case CreateRegistryResponseBodyVerificationModePublicKey:
		return true
	default:
		return false
	}
}

// Defines values for EnrichmentJobResponseEnricherName.
const (
	EnrichmentJobResponseEnricherNameOciMetadata EnrichmentJobResponseEnricherName = "oci-metadata"
	EnrichmentJobResponseEnricherNameProvenance  EnrichmentJobResponseEnricherName = "provenance"
	EnrichmentJobResponseEnricherNameUser        EnrichmentJobResponseEnricherName = "user"
)

// Valid indicates whether the value is a known member of the EnrichmentJobResponseEnricherName enum.
func (e EnrichmentJobResponseEnricherName) Valid() bool {
	switch e {
	case EnrichmentJobResponseEnricherNameOciMetadata:
		return true
	case EnrichmentJobResponseEnricherNameProvenance:
		return true
	case EnrichmentJobResponseEnricherNameUser:
		return true
	default:
		return false
	}
}

// Defines values for EnrichmentJobResponseState.
const (
	EnrichmentJobResponseStateFailed    EnrichmentJobResponseState = "failed"
	EnrichmentJobResponseStateQueued    EnrichmentJobResponseState = "queued"
	EnrichmentJobResponseStateRunning   EnrichmentJobResponseState = "running"
	EnrichmentJobResponseStateSucceeded EnrichmentJobResponseState = "succeeded"
)

// Valid indicates whether the value is a known member of the EnrichmentJobResponseState enum.
func (e EnrichmentJobResponseState) Valid() bool {
	switch e {
	case EnrichmentJobResponseStateFailed:
		return true
	case EnrichmentJobResponseStateQueued:
		return true
	case EnrichmentJobResponseStateRunning:
		return true
	case EnrichmentJobResponseStateSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for KeyMetaResponseScope.
const (
	KeyMetaResponseScopeRead      KeyMetaResponseScope = "read"
	KeyMetaResponseScopeReadWrite KeyMetaResponseScope = "read-write"
)

// Valid indicates whether the value is a known member of the KeyMetaResponseScope enum.
func (e KeyMetaResponseScope) Valid() bool {
	switch e {
	case KeyMetaResponseScopeRead:
		return true
	case KeyMetaResponseScopeReadWrite:
		return true
	default:
		return false
	}
}

// Defines values for ListArtifactVersionsOutputBodyResolvedMode.
const (
	ListArtifactVersionsOutputBodyResolvedModeAll    ListArtifactVersionsOutputBodyResolvedMode = "all"
	ListArtifactVersionsOutputBodyResolvedModeSemver ListArtifactVersionsOutputBodyResolvedMode = "semver"
)

// Valid indicates whether the value is a known member of the ListArtifactVersionsOutputBodyResolvedMode enum.
func (e ListArtifactVersionsOutputBodyResolvedMode) Valid() bool {
	switch e {
	case ListArtifactVersionsOutputBodyResolvedModeAll:
		return true
	case ListArtifactVersionsOutputBodyResolvedModeSemver:
		return true
	default:
		return false
	}
}

// Defines values for NamespaceResponseVisibility.
const (
	NamespaceResponseVisibilityPrivate NamespaceResponseVisibility = "private"
	NamespaceResponseVisibilityPublic  NamespaceResponseVisibility = "public"
)

// Valid indicates whether the value is a known member of the NamespaceResponseVisibility enum.
func (e NamespaceResponseVisibility) Valid() bool {
	switch e {
	case NamespaceResponseVisibilityPrivate:
		return true
	case NamespaceResponseVisibilityPublic:
		return true
	default:
		return false
	}
}

// Defines values for RegistryResponseVerificationMode.
const (
	RegistryResponseVerificationModeKeyless   RegistryResponseVerificationMode = "keyless"
	RegistryResponseVerificationModeNone      RegistryResponseVerificationMode = "none"
	RegistryResponseVerificationModePublicKey RegistryResponseVerificationMode = "public_key"
)

// Valid indicates whether the value is a known member of the RegistryResponseVerificationMode enum.
func (e RegistryResponseVerificationMode) Valid() bool {
	switch e {
	case RegistryResponseVerificationModeKeyless:
		return true
	case RegistryResponseVerificationModeNone:
		return true
	case RegistryResponseVerificationModePublicKey:
		return true
	default:
		return false
	}
}

// Defines values for ScanJobResponseState.
const (
	ScanJobResponseStateFailed    ScanJobResponseState = "failed"
	ScanJobResponseStateQueued    ScanJobResponseState = "queued"
	ScanJobResponseStateRunning   ScanJobResponseState = "running"
	ScanJobResponseStateSucceeded ScanJobResponseState = "succeeded"
)

// Valid indicates whether the value is a known member of the ScanJobResponseState enum.
func (e ScanJobResponseState) Valid() bool {
	switch e {
	case ScanJobResponseStateFailed:
		return true
	case ScanJobResponseStateQueued:
		return true
	case ScanJobResponseStateRunning:
		return true
	case ScanJobResponseStateSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for SourceResponseKind.
const (
	OciRegistry SourceResponseKind = "oci_registry"
	Upload      SourceResponseKind = "upload"
)

// Valid indicates whether the value is a known member of the SourceResponseKind enum.
func (e SourceResponseKind) Valid() bool {
	switch e {
	case OciRegistry:
		return true
	case Upload:
		return true
	default:
		return false
	}
}

// Defines values for UpdateNamespaceInputBodyVisibility.
const (
	UpdateNamespaceInputBodyVisibilityPrivate UpdateNamespaceInputBodyVisibility = "private"
	UpdateNamespaceInputBodyVisibilityPublic  UpdateNamespaceInputBodyVisibility = "public"
)

// Valid indicates whether the value is a known member of the UpdateNamespaceInputBodyVisibility enum.
func (e UpdateNamespaceInputBodyVisibility) Valid() bool {
	switch e {
	case UpdateNamespaceInputBodyVisibilityPrivate:
		return true
	case UpdateNamespaceInputBodyVisibilityPublic:
		return true
	default:
		return false
	}
}

// Defines values for UpdateRegistryInputBodyScanMode.
const (
	UpdateRegistryInputBodyScanModeBoth    UpdateRegistryInputBodyScanMode = "both"
	UpdateRegistryInputBodyScanModePoll    UpdateRegistryInputBodyScanMode = "poll"
	UpdateRegistryInputBodyScanModeWebhook UpdateRegistryInputBodyScanMode = "webhook"
)

// Valid indicates whether the value is a known member of the UpdateRegistryInputBodyScanMode enum.
func (e UpdateRegistryInputBodyScanMode) Valid() bool {
	switch e {
	case UpdateRegistryInputBodyScanModeBoth:
		return true
	case UpdateRegistryInputBodyScanModePoll:
		return true
	case UpdateRegistryInputBodyScanModeWebhook:
		return true
	default:
		return false
	}
}

// Defines values for UpdateRegistryInputBodyType.
const (
	UpdateRegistryInputBodyTypeDocker  UpdateRegistryInputBodyType = "docker"
	UpdateRegistryInputBodyTypeGeneric UpdateRegistryInputBodyType = "generic"
	UpdateRegistryInputBodyTypeGhcr    UpdateRegistryInputBodyType = "ghcr"
	UpdateRegistryInputBodyTypeHarbor  UpdateRegistryInputBodyType = "harbor"
	UpdateRegistryInputBodyTypeZot     UpdateRegistryInputBodyType = "zot"
)

// Valid indicates whether the value is a known member of the UpdateRegistryInputBodyType enum.
func (e UpdateRegistryInputBodyType) Valid() bool {
	switch e {
	case UpdateRegistryInputBodyTypeDocker:
		return true
	case UpdateRegistryInputBodyTypeGeneric:
		return true
	case UpdateRegistryInputBodyTypeGhcr:
		return true
	case UpdateRegistryInputBodyTypeHarbor:
		return true
	case UpdateRegistryInputBodyTypeZot:
		return true
	default:
		return false
	}
}

// Defines values for UpdateRegistryInputBodyVerificationMode.
const (
	UpdateRegistryInputBodyVerificationModeKeyless   UpdateRegistryInputBodyVerificationMode = "keyless"
	UpdateRegistryInputBodyVerificationModeNone      UpdateRegistryInputBodyVerificationMode = "none"
	UpdateRegistryInputBodyVerificationModePublicKey UpdateRegistryInputBodyVerificationMode = "public_key"
)

// Valid indicates whether the value is a known member of the UpdateRegistryInputBodyVerificationMode enum.
func (e UpdateRegistryInputBodyVerificationMode) Valid() bool {
	switch e {
	case UpdateRegistryInputBodyVerificationModeKeyless:
		return true
	case UpdateRegistryInputBodyVerificationModeNone:
		return true
	case UpdateRegistryInputBodyVerificationModePublicKey:
		return true
	default:
		return false
	}
}

// Defines values for UpdateRegistryInputBodyVisibility.
const (
	Private UpdateRegistryInputBodyVisibility = "private"
	Public  UpdateRegistryInputBodyVisibility = "public"
)

// Valid indicates whether the value is a known member of the UpdateRegistryInputBodyVisibility enum.
func (e UpdateRegistryInputBodyVisibility) Valid() bool {
	switch e {
	case Private:
		return true
	case Public:
		return true
	default:
		return false
	}
}

// Defines values for UpdateUserRoleInputBodyRole.
const (
	Admin  UpdateUserRoleInputBodyRole = "admin"
	Member UpdateUserRoleInputBodyRole = "member"
	Viewer UpdateUserRoleInputBodyRole = "viewer"
)

// Valid indicates whether the value is a known member of the UpdateUserRoleInputBodyRole enum.
func (e UpdateUserRoleInputBodyRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Member:
		return true
	case Viewer:
		return true
	default:
		return false
	}
}

// Defines values for RetryAllFailedEnrichmentJobsParamsEnricherName.
const (
	RetryAllFailedEnrichmentJobsParamsEnricherNameOciMetadata RetryAllFailedEnrichmentJobsParamsEnricherName = "oci-metadata"
	RetryAllFailedEnrichmentJobsParamsEnricherNameProvenance  RetryAllFailedEnrichmentJobsParamsEnricherName = "provenance"
	RetryAllFailedEnrichmentJobsParamsEnricherNameUser        RetryAllFailedEnrichmentJobsParamsEnricherName = "user"
)

// Valid indicates whether the value is a known member of the RetryAllFailedEnrichmentJobsParamsEnricherName enum.
func (e RetryAllFailedEnrichmentJobsParamsEnricherName) Valid() bool {
	switch e {
	case RetryAllFailedEnrichmentJobsParamsEnricherNameOciMetadata:
		return true
	case RetryAllFailedEnrichmentJobsParamsEnricherNameProvenance:
		return true
	case RetryAllFailedEnrichmentJobsParamsEnricherNameUser:
		return true
	default:
		return false
	}
}

// Defines values for GetArtifactChangelogParamsMode.
const (
	GetArtifactChangelogParamsModeAll    GetArtifactChangelogParamsMode = "all"
	GetArtifactChangelogParamsModeSemver GetArtifactChangelogParamsMode = "semver"
)

// Valid indicates whether the value is a known member of the GetArtifactChangelogParamsMode enum.
func (e GetArtifactChangelogParamsMode) Valid() bool {
	switch e {
	case GetArtifactChangelogParamsModeAll:
		return true
	case GetArtifactChangelogParamsModeSemver:
		return true
	default:
		return false
	}
}

// Defines values for ListArtifactVersionsParamsMode.
const (
	All    ListArtifactVersionsParamsMode = "all"
	Semver ListArtifactVersionsParamsMode = "semver"
)

// Valid indicates whether the value is a known member of the ListArtifactVersionsParamsMode enum.
func (e ListArtifactVersionsParamsMode) Valid() bool {
	switch e {
	case All:
		return true
	case Semver:
		return true
	default:
		return false
	}
}

// Defines values for ListEnrichmentJobsParamsState.
const (
	ListEnrichmentJobsParamsStateFailed    ListEnrichmentJobsParamsState = "failed"
	ListEnrichmentJobsParamsStateQueued    ListEnrichmentJobsParamsState = "queued"
	ListEnrichmentJobsParamsStateRunning   ListEnrichmentJobsParamsState = "running"
	ListEnrichmentJobsParamsStateSucceeded ListEnrichmentJobsParamsState = "succeeded"
)

// Valid indicates whether the value is a known member of the ListEnrichmentJobsParamsState enum.
func (e ListEnrichmentJobsParamsState) Valid() bool {
	switch e {
	case ListEnrichmentJobsParamsStateFailed:
		return true
	case ListEnrichmentJobsParamsStateQueued:
		return true
	case ListEnrichmentJobsParamsStateRunning:
		return true
	case ListEnrichmentJobsParamsStateSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for ListEnrichmentJobsParamsEnricherName.
const (
	OciMetadata ListEnrichmentJobsParamsEnricherName = "oci-metadata"
	Provenance  ListEnrichmentJobsParamsEnricherName = "provenance"
	User        ListEnrichmentJobsParamsEnricherName = "user"
)

// Valid indicates whether the value is a known member of the ListEnrichmentJobsParamsEnricherName enum.
func (e ListEnrichmentJobsParamsEnricherName) Valid() bool {
	switch e {
	case OciMetadata:
		return true
	case Provenance:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for ListScanJobsParamsState.
const (
	ListScanJobsParamsStateFailed    ListScanJobsParamsState = "failed"
	ListScanJobsParamsStateQueued    ListScanJobsParamsState = "queued"
	ListScanJobsParamsStateRunning   ListScanJobsParamsState = "running"
	ListScanJobsParamsStateSucceeded ListScanJobsParamsState = "succeeded"
)

// Valid indicates whether the value is a known member of the ListScanJobsParamsState enum.
func (e ListScanJobsParamsState) Valid() bool {
	switch e {
	case ListScanJobsParamsStateFailed:
		return true
	case ListScanJobsParamsStateQueued:
		return true
	case ListScanJobsParamsStateRunning:
		return true
	case ListScanJobsParamsStateSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for ListTopVulnerabilitiesParamsSeverity.
const (
	CRITICAL ListTopVulnerabilitiesParamsSeverity = "CRITICAL"
	HIGH     ListTopVulnerabilitiesParamsSeverity = "HIGH"
	LOW      ListTopVulnerabilitiesParamsSeverity = "LOW"
	MEDIUM   ListTopVulnerabilitiesParamsSeverity = "MEDIUM"
)

// Valid indicates whether the value is a known member of the ListTopVulnerabilitiesParamsSeverity enum.
func (e ListTopVulnerabilitiesParamsSeverity) Valid() bool {
	switch e {
	case CRITICAL:
		return true
	case HIGH:
		return true
	case LOW:
		return true
	case MEDIUM:
		return true
	default:
		return false
	}
}

// Defines values for ListTopVulnerabilitiesParamsSort.
const (
	AffectedPurlCount ListTopVulnerabilitiesParamsSort = "affected_purl_count"
	AffectedSbomCount ListTopVulnerabilitiesParamsSort = "affected_sbom_count"
	CanonicalId       ListTopVulnerabilitiesParamsSort = "canonical_id"
	CvssScore         ListTopVulnerabilitiesParamsSort = "cvss_score"
	PublishedAt       ListTopVulnerabilitiesParamsSort = "published_at"
	Severity          ListTopVulnerabilitiesParamsSort = "severity"
)

// Valid indicates whether the value is a known member of the ListTopVulnerabilitiesParamsSort enum.
func (e ListTopVulnerabilitiesParamsSort) Valid() bool {
	switch e {
	case AffectedPurlCount:
		return true
	case AffectedSbomCount:
		return true
	case CanonicalId:
		return true
	case CvssScore:
		return true
	case PublishedAt:
		return true
	case Severity:
		return true
	default:
		return false
	}
}

// Defines values for ListTopVulnerabilitiesParamsSortDir.
const (
	Asc  ListTopVulnerabilitiesParamsSortDir = "asc"
	Desc ListTopVulnerabilitiesParamsSortDir = "desc"
)

// Valid indicates whether the value is a known member of the ListTopVulnerabilitiesParamsSortDir enum.
func (e ListTopVulnerabilitiesParamsSortDir) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}

// AffectedArtifact defines model for AffectedArtifact.
type AffectedArtifact struct {
	AffectedPurlCount int64   `json:"affectedPurlCount"`
	AffectedSbomCount int64   `json:"affectedSbomCount"`
	Group             *string `json:"group,omitempty"`
	Id                string  `json:"id"`
	Name              string  `json:"name"`
}

// AffectedComponent defines model for AffectedComponent.
type AffectedComponent struct {
	AffectedVersionCount int64   `json:"affectedVersionCount"`
	FixedVersion         *string `json:"fixedVersion,omitempty"`
	Group                *string `json:"group,omitempty"`
	Name                 string  `json:"name"`
}

// ArtifactDetail defines model for ArtifactDetail.
type ArtifactDetail struct {
	// Schema A URL to the JSON Schema for this object.
	Schema              *string   `json:"$schema,omitempty"`
	Cpe                 *string   `json:"cpe,omitempty"`
	CreatedAt           time.Time `json:"createdAt"`
	Group               *string   `json:"group,omitempty"`
	Id                  string    `json:"id"`
	Name                string    `json:"name"`
	Purl                *string   `json:"purl,omitempty"`
	SbomCount           int64     `json:"sbomCount"`
	SigningStatus       string    `json:"signingStatus"`
	SufficientSbomCount int64     `json:"sufficientSbomCount"`
	Type                string    `json:"type"`
	VersionCount        int64     `json:"versionCount"`
}

// ArtifactRelation defines model for ArtifactRelation.
type ArtifactRelation struct {
	ArtifactGroup  *string    `json:"artifactGroup,omitempty"`
	ArtifactId     string     `json:"artifactId"`
	ArtifactName   string     `json:"artifactName"`
	ArtifactType   string     `json:"artifactType"`
	CurrentVersion *string    `json:"currentVersion,omitempty"`
	Digest         *string    `json:"digest,omitempty"`
	Flavor         *string    `json:"flavor,omitempty"`
	IsCurrent      *bool      `json:"isCurrent,omitempty"`
	MatchedVersion *string    `json:"matchedVersion,omitempty"`
	ObservedAt     *time.Time `json:"observedAt,omitempty"`
	SbomId         string     `json:"sbomId"`
	SubjectVersion *string    `json:"subjectVersion,omitempty"`
}

// ArtifactSummary defines model for ArtifactSummary.
type ArtifactSummary struct {
	Group               *string `json:"group,omitempty"`
	Id                  string  `json:"id"`
	Name                string  `json:"name"`
	SbomCount           int64   `json:"sbomCount"`
	SigningStatus       string  `json:"signingStatus"`
	SufficientSbomCount int64   `json:"sufficientSbomCount"`
	Type                string  `json:"type"`
}

// ArtifactTypeCountEntry defines model for ArtifactTypeCountEntry.
type ArtifactTypeCountEntry struct {
	ArtifactCount int64  `json:"artifact_count"`
	Type          string `json:"type"`
}

// ArtifactVersionSummary defines model for ArtifactVersionSummary.
type ArtifactVersionSummary struct {
	Architectures *[]string  `json:"architectures"`
	BuildDate     *time.Time `json:"buildDate,omitempty"`
	CreatedAt     time.Time  `json:"createdAt"`
	ImageVersion  *string    `json:"imageVersion,omitempty"`
	Revision      *string    `json:"revision,omitempty"`

	// SbomCount Total number of SBOMs ingested for this version
	SbomCount int64  `json:"sbomCount"`
	SbomId    string `json:"sbomId"`

	// SigningStatus Signing status derived from provenance enrichment
	SigningStatus ArtifactVersionSummarySigningStatus `json:"signingStatus"`
	SourceUrl     *string                             `json:"sourceUrl,omitempty"`
	Sufficient    bool                                `json:"sufficient"`
	VersionKey    string                              `json:"versionKey"`
}

// ArtifactVersionSummarySigningStatus Signing status derived from provenance enrichment
type ArtifactVersionSummarySigningStatus string

// CategoryCountEntry defines model for CategoryCountEntry.
type CategoryCountEntry struct {
	Category       string `json:"category"`
	ComponentCount int64  `json:"component_count"`
}

// ChangeCounts defines model for ChangeCounts.
type ChangeCounts struct {
	Added      int64 `json:"added"`
	Downgraded int64 `json:"downgraded"`
	Modified   int64 `json:"modified"`
	Removed    int64 `json:"removed"`
	Upgraded   int64 `json:"upgraded"`
}

// ChangeSummary defines model for ChangeSummary.
type ChangeSummary struct {
	Added      int64 `json:"added"`
	Downgraded int64 `json:"downgraded"`
	Modified   int64 `json:"modified"`
	Removed    int64 `json:"removed"`
	Upgraded   int64 `json:"upgraded"`
}

// Changelog defines model for Changelog.
type Changelog struct {
	// Schema A URL to the JSON Schema for this object.
	Schema                 *string           `json:"$schema,omitempty"`
	ArtifactId             string            `json:"artifactId"`
	AvailableArchitectures *[]string         `json:"availableArchitectures"`
	AvailableFlavors       *[]string         `json:"availableFlavors"`
	Entries                *[]ChangelogEntry `json:"entries"`
	HasSemver              bool              `json:"hasSemver"`
	ResolvedMode           string            `json:"resolvedMode"`
}

// ChangelogEntry defines model for ChangelogEntry.
type ChangelogEntry struct {
	// Schema A URL to the JSON Schema for this object.
	Schema  *string          `json:"$schema,omitempty"`
	Changes *[]ComponentDiff `json:"changes"`
	From    SBOMRef          `json:"from"`
	Summary ChangeSummary    `json:"summary"`
	To      SBOMRef          `json:"to"`
}

// ComponentDetail defines model for ComponentDetail.
type ComponentDetail struct {
	// Schema A URL to the JSON Schema for this object.
	Schema             *string             `json:"$schema,omitempty"`
	BomRef             *string             `json:"bomRef,omitempty"`
	Confidence         *string             `json:"confidence,omitempty"`
	Copyright          *string             `json:"copyright,omitempty"`
	Cpe                *string             `json:"cpe,omitempty"`
	CriticalCount      *int64              `json:"criticalCount,omitempty"`
	DescendantChanges  *ChangeCounts       `json:"descendantChanges,omitempty"`
	Description        *string             `json:"description,omitempty"`
	ExternalReferences *[]ExternalRefEntry `json:"externalReferences"`
	FoundBy            *string             `json:"foundBy,omitempty"`
	FromBaseImage      *bool               `json:"fromBaseImage,omitempty"`
	Group              *string             `json:"group,omitempty"`
	Hashes             *[]HashEntry        `json:"hashes"`
	HighCount          *int64              `json:"highCount,omitempty"`
	Id                 string              `json:"id"`
	IsDirect           bool                `json:"isDirect"`
	Layer              *int64              `json:"layer,omitempty"`
	LayerId            *string             `json:"layerId,omitempty"`
	Licenses           *[]LicenseSummary   `json:"licenses"`
	LowCount           *int64              `json:"lowCount,omitempty"`
	MaxSeverity        *string             `json:"maxSeverity,omitempty"`
	MediumCount        *int64              `json:"mediumCount,omitempty"`
	Name               string              `json:"name"`
	Publisher          *string             `json:"publisher,omitempty"`
	Purl               *string             `json:"purl,omitempty"`
	SbomId             string              `json:"sbomId"`
	Scope              *string             `json:"scope,omitempty"`
	SourcePackage      *string             `json:"sourcePackage,omitempty"`
	Type               string              `json:"type"`
	UnknownCount       *int64              `json:"unknownCount,omitempty"`
	Version            *string             `json:"version,omitempty"`
	VulnCount          *int64              `json:"vulnCount,omitempty"`
}

// ComponentDiff defines model for ComponentDiff.
type ComponentDiff struct {
	Direction       string  `json:"direction"`
	Group           *string `json:"group,omitempty"`
	Name            string  `json:"name"`
	NodeRef         *string `json:"nodeRef,omitempty"`
	PreviousVersion *string `json:"previousVersion,omitempty"`
	Purl            *string `json:"purl,omitempty"`
	Type            string  `json:"type"`
	Version         *string `json:"version,omitempty"`
}

// ComponentSummary defines model for ComponentSummary.
type ComponentSummary struct {
	BomRef            *string       `json:"bomRef,omitempty"`
	CriticalCount     *int64        `json:"criticalCount,omitempty"`
	DescendantChanges *ChangeCounts `json:"descendantChanges,omitempty"`
	Group             *string       `json:"group,omitempty"`
	HighCount         *int64        `json:"highCount,omitempty"`
	Id                string        `json:"id"`
	IsDirect          bool          `json:"isDirect"`
	LowCount          *int64        `json:"lowCount,omitempty"`
	MaxSeverity       *string       `json:"maxSeverity,omitempty"`
	MediumCount       *int64        `json:"mediumCount,omitempty"`
	Name              string        `json:"name"`
	Purl              *string       `json:"purl,omitempty"`
	SbomId            string        `json:"sbomId"`
	Type              string        `json:"type"`
	UnknownCount      *int64        `json:"unknownCount,omitempty"`
	Version           *string       `json:"version,omitempty"`
	VulnCount         *int64        `json:"vulnCount,omitempty"`
}

// ComponentVersionEntry defines model for ComponentVersionEntry.
type ComponentVersionEntry struct {
	Architecture   *string `json:"architecture,omitempty"`
	ArtifactId     *string `json:"artifactId,omitempty"`
	ArtifactName   *string `json:"artifactName,omitempty"`
	CriticalCount  *int64  `json:"criticalCount,omitempty"`
	Group          *string `json:"group,omitempty"`
	HighCount      *int64  `json:"highCount,omitempty"`
	Id             string  `json:"id"`
	LowCount       *int64  `json:"lowCount,omitempty"`
	MaxSeverity    *string `json:"maxSeverity,omitempty"`
	MediumCount    *int64  `json:"mediumCount,omitempty"`
	Name           string  `json:"name"`
	Purl           *string `json:"purl,omitempty"`
	SbomCreatedAt  string  `json:"sbomCreatedAt"`
	SbomDigest     *string `json:"sbomDigest,omitempty"`
	SbomId         string  `json:"sbomId"`
	SubjectVersion *string `json:"subjectVersion,omitempty"`
	Type           string  `json:"type"`
	UnknownCount   *int64  `json:"unknownCount,omitempty"`
	Version        *string `json:"version,omitempty"`
	VulnCount      int64   `json:"vulnCount"`
}

// ComponentVulnEntry defines model for ComponentVulnEntry.
type ComponentVulnEntry struct {
	CanonicalId      string   `json:"canonicalId"`
	CvssScore        *float32 `json:"cvssScore,omitempty"`
	FixedVersion     *string  `json:"fixedVersion,omitempty"`
	Id               string   `json:"id"`
	MatchedViaSource bool     `json:"matchedViaSource"`
	Severity         string   `json:"severity"`
	Summary          *string  `json:"summary,omitempty"`
}

// CreateAPIKeyInputBody defines model for CreateAPIKeyInputBody.
type CreateAPIKeyInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Name Human-readable label for this key
	Name string `json:"name"`

	// Scope Key scope: read (GET only) or read-write (full access)
	Scope *CreateAPIKeyInputBodyScope `json:"scope,omitempty"`
}

// CreateAPIKeyInputBodyScope Key scope: read (GET only) or read-write (full access)
type CreateAPIKeyInputBodyScope string

// CreateAPIKeyOutputBody defines model for CreateAPIKeyOutputBody.
type CreateAPIKeyOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Key Full API key — shown once, store securely
	Key string `json:"key"`
}

// CreateNamespaceInputBody defines model for CreateNamespaceInputBody.
type CreateNamespaceInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Name Human-readable namespace name
	Name string `json:"name"`

	// Visibility Namespace visibility; defaults to private
	Visibility *CreateNamespaceInputBodyVisibility `json:"visibility,omitempty"`
}

// CreateNamespaceInputBodyVisibility Namespace visibility; defaults to private
type CreateNamespaceInputBodyVisibility string

// CreateRegistryInputBody defines model for CreateRegistryInputBody.
type CreateRegistryInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// AuthToken Token or PAT for registry authentication; omit for anonymous access
	AuthToken *string `json:"auth_token,omitempty"`

	// AuthUsername Username for registry authentication; omit for anonymous access
	AuthUsername *string `json:"auth_username,omitempty"`

	// IncludeUntagged Scan untagged manifests via registry-specific APIs (supported: zot, harbor, ghcr)
	IncludeUntagged *bool `json:"include_untagged,omitempty"`

	// Insecure Allow HTTP (non-TLS) connections
	Insecure bool `json:"insecure"`

	// ManagedBy External system that owns this registry's configuration (e.g. kubernetes); set by that system's controller, not by hand
	ManagedBy *string `json:"managed_by,omitempty"`

	// ManagedRef Identifier within the managing system, e.g. '<namespace>/<name>' of the OCIRegistry resource
	ManagedRef *string `json:"managed_ref,omitempty"`

	// Name Human-readable registry name
	Name string `json:"name"`

	// Namespace Namespace to create the registry in, created on first use; omit to give the registry a namespace of its own named after it
	Namespace *string `json:"namespace,omitempty"`

	// PollIntervalMinutes Minutes between polls
	PollIntervalMinutes *int64 `json:"poll_interval_minutes,omitempty"`

	// Repositories Explicit repositories to walk; bypasses /v2/_catalog discovery when non-empty
	Repositories *[]string `json:"repositories,omitempty"`

	// RepositoryPatterns Glob patterns for repositories to ingest; empty = all
	RepositoryPatterns *[]string `json:"repository_patterns,omitempty"`

	// ScanMode Scanning mode
	ScanMode *CreateRegistryInputBodyScanMode `json:"scan_mode,omitempty"`

	// TagPatterns Glob patterns or 'semver' for tags to ingest; empty = all
	TagPatterns *[]string `json:"tag_patterns,omitempty"`

	// TrustIdentity Regex matched against the Fulcio certificate SAN; required when verification_mode is keyless
	TrustIdentity *string `json:"trust_identity,omitempty"`

	// TrustIssuer Expected OIDC issuer URL; required when verification_mode is keyless
	TrustIssuer *string `json:"trust_issuer,omitempty"`

	// TrustPublicKey PEM-encoded EC public key; required when verification_mode is public_key
	TrustPublicKey *string `json:"trust_public_key,omitempty"`

	// Type Registry type
	Type CreateRegistryInputBodyType `json:"type"`

	// Url Registry address (e.g. zot:5000)
	Url string `json:"url"`

	// VerificationMode Signature verification mode; defaults to none
	VerificationMode *CreateRegistryInputBodyVerificationMode `json:"verification_mode,omitempty"`

	// Visibility Registry visibility
	Visibility *CreateRegistryInputBodyVisibility `json:"visibility,omitempty"`

	// WebhookSecret Bearer token required on incoming webhooks; omit to disable auth
	WebhookSecret *string `json:"webhook_secret,omitempty"`
}

// CreateRegistryInputBodyScanMode Scanning mode
type CreateRegistryInputBodyScanMode string

// CreateRegistryInputBodyType Registry type
type CreateRegistryInputBodyType string

// CreateRegistryInputBodyVerificationMode Signature verification mode; defaults to none
type CreateRegistryInputBodyVerificationMode string

// CreateRegistryInputBodyVisibility Registry visibility
type CreateRegistryInputBodyVisibility string

// CreateRegistryResponseBody defines model for CreateRegistryResponseBody.
type CreateRegistryResponseBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema    *string `json:"$schema,omitempty"`
	CreatedAt string  `json:"created_at"`
	Enabled   bool    `json:"enabled"`
	HasAuth   bool    `json:"has_auth"`
	HasSecret bool    `json:"has_secret"`
	Id        string  `json:"id"`

	// IncludeUntagged Scan untagged manifests via registry-specific APIs (supported: zot, harbor, ghcr)
	IncludeUntagged bool    `json:"include_untagged"`
	Insecure        bool    `json:"insecure"`
	LastPolledAt    *string `json:"last_polled_at,omitempty"`

	// ManagedBy External system that owns this registry's configuration (e.g. kubernetes); absent when managed through this API
	ManagedBy *string `json:"managed_by,omitempty"`

	// ManagedRef Identifier within the managing system, e.g. '<namespace>/<name>' of the OCIRegistry resource
	ManagedRef *string `json:"managed_ref,omitempty"`
	Name       string  `json:"name"`

	// OwnerId UUID of the registry owner
	OwnerId *string `json:"owner_id,omitempty"`

	// OwnerUsername GitHub username of the registry owner
	OwnerUsername       *string `json:"owner_username,omitempty"`
	PollIntervalMinutes int64   `json:"poll_interval_minutes"`

	// Repositories Explicit repositories to walk; overrides catalog discovery when non-empty
	Repositories *[]string `json:"repositories"`

	// RepositoryPatterns Glob patterns for repositories to ingest; empty = all
	RepositoryPatterns *[]string `json:"repository_patterns"`
	ScanMode           string    `json:"scan_mode"`

	// TagPatterns Glob patterns or 'semver' for tags to ingest; empty = all
	TagPatterns *[]string `json:"tag_patterns"`

	// TrustIdentity Regex matched against the Fulcio certificate SAN; required for keyless verification mode
	TrustIdentity *string `json:"trust_identity,omitempty"`

	// TrustIssuer Expected OIDC issuer URL; required for keyless verification mode
	TrustIssuer *string `json:"trust_issuer,omitempty"`

	// TrustPublicKey PEM-encoded EC public key for public_key verification mode
	TrustPublicKey *string `json:"trust_public_key,omitempty"`
	Type           string  `json:"type"`
	UpdatedAt      string  `json:"updated_at"`
	Url            string  `json:"url"`

	// VerificationMode Signature verification mode
	VerificationMode CreateRegistryResponseBodyVerificationMode `json:"verification_mode"`

	// Visibility Registry visibility: public or private
	Visibility string `json:"visibility"`

	// WebhookSecret Generated webhook secret — shown once only. Store it securely; it cannot be retrieved again.
	WebhookSecret *string `json:"webhook_secret,omitempty"`
	WebhookUrl    string  `json:"webhook_url"`
}

// CreateRegistryResponseBodyVerificationMode Signature verification mode
type CreateRegistryResponseBodyVerificationMode string

// CreateSourceInputBody defines model for CreateSourceInputBody.
type CreateSourceInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Name Source name, unique within the namespace
	Name string `json:"name"`

	// NamespaceId Owning namespace UUID
	NamespaceId openapi_types.UUID `json:"namespace_id"`
}

// CursorMeta defines model for CursorMeta.
type CursorMeta struct {
	// HasMore Whether more results exist after this page
	HasMore bool `json:"hasMore"`

	// Limit The limit that was applied
	Limit int32 `json:"limit"`

	// NextCursor Opaque cursor to fetch the next page; null when hasMore is false
	NextCursor *string `json:"nextCursor,omitempty"`
}

// DBStatus defines model for DBStatus.
type DBStatus struct {
	LatencyMs int64 `json:"latency_ms"`
	Ok        bool  `json:"ok"`
}

// DailyCountEntry defines model for DailyCountEntry.
type DailyCountEntry struct {
	Count int64  `json:"count"`
	Day   string `json:"day"`
}

// DashboardStatsOutputBody defines model for DashboardStatsOutputBody.
type DashboardStatsOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema                *string                   `json:"$schema,omitempty"`
	ArtifactCount         int64                     `json:"artifact_count"`
	ArtifactTypes         *[]ArtifactTypeCountEntry `json:"artifact_types"`
	IngestionTimeline     *[]DailyCountEntry        `json:"ingestion_timeline"`
	LicenseCategories     *[]CategoryCountEntry     `json:"license_categories"`
	LicenseCount          int64                     `json:"license_count"`
	PackageCount          int64                     `json:"package_count"`
	PackageGrowthTimeline *[]DailyCountEntry        `json:"package_growth_timeline"`
	SbomCount             int64                     `json:"sbom_count"`
	TopPackages           *[]PackageSummaryEntry    `json:"top_packages"`
	VersionCount          int64                     `json:"version_count"`
	VersionGrowthTimeline *[]DailyCountEntry        `json:"version_growth_timeline"`
	VulnCount             int64                     `json:"vuln_count"`
	VulnSeverity          VulnSeverityEntry         `json:"vuln_severity"`

	// Warming No snapshot is available yet and every count is a zero placeholder; render a loading state and retry
	Warming bool `json:"warming"`
}

// DependencyEdge defines model for DependencyEdge.
type DependencyEdge struct {
	From string `json:"from"`
	To   string `json:"to"`
}

// DependencyGraph defines model for DependencyGraph.
type DependencyGraph struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string             `json:"$schema,omitempty"`
	Edges  *[]DependencyEdge   `json:"edges"`
	Nodes  *[]ComponentSummary `json:"nodes"`
	Roots  *[]string           `json:"roots"`
}

// DiffTree defines model for DiffTree.
type DiffTree struct {
	// Schema A URL to the JSON Schema for this object.
	Schema  *string             `json:"$schema,omitempty"`
	Changes *[]ComponentDiff    `json:"changes"`
	Edges   *[]DependencyEdge   `json:"edges"`
	From    SBOMRef             `json:"from"`
	Nodes   *[]ComponentSummary `json:"nodes"`
	Roots   *[]string           `json:"roots"`
	Summary ChangeSummary       `json:"summary"`
	To      SBOMRef             `json:"to"`
}

// DistinctComponentSummary defines model for DistinctComponentSummary.
type DistinctComponentSummary struct {
	Group        *string   `json:"group,omitempty"`
	Name         string    `json:"name"`
	PurlTypes    *[]string `json:"purlTypes,omitempty"`
	SbomCount    int64     `json:"sbomCount"`
	Type         string    `json:"type"`
	VersionCount int64     `json:"versionCount"`
}

// EnrichmentJobResponse defines model for EnrichmentJobResponse.
type EnrichmentJobResponse struct {
	// ArtifactName Name of the artifact, for display
	ArtifactName *string `json:"artifact_name,omitempty"`
	Attempts     int32   `json:"attempts"`
	CreatedAt    string  `json:"created_at"`

	// EnricherName Which enricher this job runs
	EnricherName EnrichmentJobResponseEnricherName `json:"enricher_name"`
	FinishedAt   *string                           `json:"finished_at,omitempty"`

	// Id Job UUID
	Id            string  `json:"id"`
	LastAttemptAt *string `json:"last_attempt_at,omitempty"`
	LastError     *string `json:"last_error,omitempty"`

	// SbomDigest Digest of the SBOM's image, for display
	SbomDigest *string `json:"sbom_digest,omitempty"`

	// SbomId SBOM being enriched
	SbomId    *string                    `json:"sbom_id,omitempty"`
	StartedAt *string                    `json:"started_at,omitempty"`
	State     EnrichmentJobResponseState `json:"state"`

	// WorkerId Pod hostname that is processing this job
	WorkerId *string `json:"worker_id,omitempty"`
}

// EnrichmentJobResponseEnricherName Which enricher this job runs
type EnrichmentJobResponseEnricherName string

// EnrichmentJobResponseState defines model for EnrichmentJobResponse.State.
type EnrichmentJobResponseState string

// EnrichmentJobSummaryRow defines model for EnrichmentJobSummaryRow.
type EnrichmentJobSummaryRow struct {
	Count        int64  `json:"count"`
	EnricherName string `json:"enricher_name"`
	State        string `json:"state"`
}

// EnrichmentJobsSummaryOutputBody defines model for EnrichmentJobsSummaryOutputBody.
type EnrichmentJobsSummaryOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string                    `json:"$schema,omitempty"`
	Data   *[]EnrichmentJobSummaryRow `json:"data"`
}

// EnrichmentStatus defines model for EnrichmentStatus.
type EnrichmentStatus struct {
	Enabled   bool  `json:"enabled"`
	QueueSize int64 `json:"queue_size"`
	Workers   int64 `json:"workers"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Location Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
	Location *string `json:"location,omitempty"`

	// Message Error message text
	Message *string `json:"message,omitempty"`

	// Value The value at the given location
	Value interface{} `json:"value,omitempty"`
}

// ErrorModel defines model for ErrorModel.
type ErrorModel struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Errors Optional list of individual error details
	Errors *[]ErrorDetail `json:"errors,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int64 `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	Title *string `json:"title,omitempty"`

	// Type A URI reference to human-readable documentation for the error.
	Type *string `json:"type,omitempty"`
}

// ExternalRefEntry defines model for ExternalRefEntry.
type ExternalRefEntry struct {
	Comment *string `json:"comment,omitempty"`
	Type    string  `json:"type"`
	Url     string  `json:"url"`
}

// GetArtifactContainsOutputBody defines model for GetArtifactContainsOutputBody.
type GetArtifactContainsOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema   *string             `json:"$schema,omitempty"`
	Contains *[]ArtifactRelation `json:"contains"`
}

// GetArtifactLicenseSummaryOutputBody defines model for GetArtifactLicenseSummaryOutputBody.
type GetArtifactLicenseSummaryOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema   *string         `json:"$schema,omitempty"`
	Licenses *[]LicenseCount `json:"licenses"`
}

// GetArtifactUsagesOutputBody defines model for GetArtifactUsagesOutputBody.
type GetArtifactUsagesOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string             `json:"$schema,omitempty"`
	Usages *[]ArtifactRelation `json:"usages"`
}

// GetArtifactVulnSummaryOutputBody defines model for GetArtifactVulnSummaryOutputBody.
type GetArtifactVulnSummaryOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema  *string     `json:"$schema,omitempty"`
	Summary VulnSummary `json:"summary"`
}

// GetComponentVersionsOutputBody defines model for GetComponentVersionsOutputBody.
type GetComponentVersionsOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema   *string                  `json:"$schema,omitempty"`
	Versions *[]ComponentVersionEntry `json:"versions"`
}

// GetComponentVulnsOutputBody defines model for GetComponentVulnsOutputBody.
type GetComponentVulnsOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string               `json:"$schema,omitempty"`
	Data   *[]ComponentVulnEntry `json:"data"`
}

// GetRegistryTrustSummaryOutputBody defines model for GetRegistryTrustSummaryOutputBody.
type GetRegistryTrustSummaryOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string               `json:"$schema,omitempty"`
	Data   *[]RegistryTrustCount `json:"data"`
}

// GetVulnerabilityOutputBody defines model for GetVulnerabilityOutputBody.
type GetVulnerabilityOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema               *string              `json:"$schema,omitempty"`
	AffectedArtifacts    *[]AffectedArtifact  `json:"affectedArtifacts"`
	AffectedComponents   *[]AffectedComponent `json:"affectedComponents"`
	ComponentsPagination PaginationMeta       `json:"componentsPagination"`
	Pagination           PaginationMeta       `json:"pagination"`
	Vulnerability        VulnDetail           `json:"vulnerability"`
}

// HashEntry defines model for HashEntry.
type HashEntry struct {
	Algorithm string `json:"algorithm"`
	Value     string `json:"value"`
}

// HealthCheckOutputBody defines model for HealthCheckOutputBody.
type HealthCheckOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Status Health status
	Status string `json:"status"`
}

// IngestSBOMOutputBody defines model for IngestSBOMOutputBody.
type IngestSBOMOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// ComponentCount Number of components in the SBOM
	ComponentCount int64 `json:"componentCount"`

	// Id UUID of the created SBOM
	Id string `json:"id"`

	// SerialNumber SBOM serial number
	SerialNumber *string `json:"serialNumber,omitempty"`

	// SpecVersion CycloneDX spec version
	SpecVersion string `json:"specVersion"`

	// Status Ingestion status
	Status string `json:"status"`
}

// KeyMetaResponse defines model for KeyMetaResponse.
type KeyMetaResponse struct {
	CreatedAt time.Time `json:"created_at"`

	// Id Key UUID
	Id         string     `json:"id"`
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	Name       string     `json:"name"`

	// Prefix First 8 characters of the key
	Prefix string `json:"prefix"`

	// Scope Key scope
	Scope KeyMetaResponseScope `json:"scope"`
}

// KeyMetaResponseScope Key scope
type KeyMetaResponseScope string

// LicenseCount defines model for LicenseCount.
type LicenseCount struct {
	// Schema A URL to the JSON Schema for this object.
	Schema         *string `json:"$schema,omitempty"`
	Category       string  `json:"category"`
	ComponentCount int64   `json:"componentCount"`
	Id             string  `json:"id"`
	Name           string  `json:"name"`
	SpdxId         *string `json:"spdxId,omitempty"`
	Url            *string `json:"url,omitempty"`
}

// LicenseSummary defines model for LicenseSummary.
type LicenseSummary struct {
	Id     string  `json:"id"`
	Name   string  `json:"name"`
	SpdxId *string `json:"spdxId,omitempty"`
	Url    *string `json:"url,omitempty"`
}

// ListAPIKeysOutputBody defines model for ListAPIKeysOutputBody.
type ListAPIKeysOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string            `json:"$schema,omitempty"`
	Keys   *[]KeyMetaResponse `json:"keys"`
}

// ListArtifactSBOMsOutputBody defines model for ListArtifactSBOMsOutputBody.
type ListArtifactSBOMsOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string        `json:"$schema,omitempty"`
	Data       *[]SBOMSummary `json:"data"`
	Pagination CursorMeta     `json:"pagination"`
}

// ListArtifactVersionsOutputBody defines model for ListArtifactVersionsOutputBody.
type ListArtifactVersionsOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string                   `json:"$schema,omitempty"`
	Data   *[]ArtifactVersionSummary `json:"data"`

	// HasSemver Whether the artifact has any semver-parseable version
	HasSemver  bool           `json:"hasSemver"`
	Pagination PaginationMeta `json:"pagination"`

	// ResolvedMode Concrete sort mode applied after auto-resolution
	ResolvedMode ListArtifactVersionsOutputBodyResolvedMode `json:"resolvedMode"`
}

// ListArtifactVersionsOutputBodyResolvedMode Concrete sort mode applied after auto-resolution
type ListArtifactVersionsOutputBodyResolvedMode string

// ListArtifactsOutputBody defines model for ListArtifactsOutputBody.
type ListArtifactsOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string            `json:"$schema,omitempty"`
	Data       *[]ArtifactSummary `json:"data"`
	Pagination CursorMeta         `json:"pagination"`
}

// ListComponentPurlTypesOutputBody defines model for ListComponentPurlTypesOutputBody.
type ListComponentPurlTypesOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string   `json:"$schema,omitempty"`
	Types  *[]string `json:"types"`
}

// ListComponentsByLicenseOutputBody defines model for ListComponentsByLicenseOutputBody.
type ListComponentsByLicenseOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string             `json:"$schema,omitempty"`
	Data       *[]ComponentSummary `json:"data"`
	Pagination PaginationMeta      `json:"pagination"`
}

// ListEnrichmentJobsOutputBody defines model for ListEnrichmentJobsOutputBody.
type ListEnrichmentJobsOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string                  `json:"$schema,omitempty"`
	Data       *[]EnrichmentJobResponse `json:"data"`
	Pagination PaginationMeta           `json:"pagination"`
}

// ListLicensesOutputBody defines model for ListLicensesOutputBody.
type ListLicensesOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string         `json:"$schema,omitempty"`
	Data       *[]LicenseCount `json:"data"`
	Pagination PaginationMeta  `json:"pagination"`
}

// ListNamespacesOutputBody defines model for ListNamespacesOutputBody.
type ListNamespacesOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string              `json:"$schema,omitempty"`
	Data   *[]NamespaceResponse `json:"data"`
}

// ListRecentDriftOutputBody defines model for ListRecentDriftOutputBody.
type ListRecentDriftOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string             `json:"$schema,omitempty"`
	Data       *[]RecentDriftEntry `json:"data"`
	Pagination CursorMeta          `json:"pagination"`
}

// ListRegistriesOutputBody defines model for ListRegistriesOutputBody.
type ListRegistriesOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string             `json:"$schema,omitempty"`
	Data       *[]RegistryResponse `json:"data"`
	Pagination PaginationMeta      `json:"pagination"`
}

// ListSBOMComponentsOutputBody defines model for ListSBOMComponentsOutputBody.
type ListSBOMComponentsOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string             `json:"$schema,omitempty"`
	Components *[]ComponentSummary `json:"components"`
	Pagination CursorMeta          `json:"pagination"`
}

// ListSBOMDriftHistoryOutputBody defines model for ListSBOMDriftHistoryOutputBody.
type ListSBOMDriftHistoryOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string                   `json:"$schema,omitempty"`
	Data       *[]ProvenanceDriftSummary `json:"data"`
	Pagination CursorMeta                `json:"pagination"`
}

// ListSBOMsOutputBody defines model for ListSBOMsOutputBody.
type ListSBOMsOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string        `json:"$schema,omitempty"`
	Data       *[]SBOMSummary `json:"data"`
	Pagination CursorMeta     `json:"pagination"`
}

// ListScanJobsOutputBody defines model for ListScanJobsOutputBody.
type ListScanJobsOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string            `json:"$schema,omitempty"`
	Data       *[]ScanJobResponse `json:"data"`
	Pagination PaginationMeta     `json:"pagination"`
}

// ListSourcesOutputBody defines model for ListSourcesOutputBody.
type ListSourcesOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string           `json:"$schema,omitempty"`
	Data   *[]SourceResponse `json:"data"`
}

// ListTopVulnerabilitiesOutputBody defines model for ListTopVulnerabilitiesOutputBody.
type ListTopVulnerabilitiesOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string         `json:"$schema,omitempty"`
	Data       *[]TopVulnEntry `json:"data"`
	Pagination PaginationMeta  `json:"pagination"`
}

// ListUsersOutputBody defines model for ListUsersOutputBody.
type ListUsersOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string         `json:"$schema,omitempty"`
	Users  *[]UserResponse `json:"users"`
}

// LookupCandidate defines model for LookupCandidate.
type LookupCandidate struct {
	// Id Canonical UUID of the matching resource
	Id string `json:"id"`

	// Qualifiers Qualifier values that distinguish this candidate, keyed by resolver query parameter
	Qualifiers map[string]string `json:"qualifiers"`
}

// LookupConflictError defines model for LookupConflictError.
type LookupConflictError struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Candidates Matching resources; retry one rung further down the qualifier ladder to select one
	Candidates *[]LookupCandidate `json:"candidates"`

	// Detail Explanation of the ambiguity
	Detail string `json:"detail"`

	// Status HTTP status code
	Status int64 `json:"status"`

	// Title Short, human-readable summary
	Title string `json:"title"`
}

// MeOutputBody defines model for MeOutputBody.
type MeOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// GithubUsername GitHub login
	GithubUsername string `json:"github_username"`

	// Id User UUID
	Id string `json:"id"`

	// Role User role: admin, member, or viewer
	Role string `json:"role"`
}

// NATSStatus defines model for NATSStatus.
type NATSStatus struct {
	Enabled bool   `json:"enabled"`
	Url     string `json:"url"`
}

// NamespaceResponse defines model for NamespaceResponse.
type NamespaceResponse struct {
	// Schema A URL to the JSON Schema for this object.
	Schema    *string `json:"$schema,omitempty"`
	CreatedAt string  `json:"created_at"`
	Id        string  `json:"id"`
	Name      string  `json:"name"`

	// OwnerId UUID of the namespace owner
	OwnerId *string `json:"owner_id,omitempty"`

	// OwnerUsername GitHub username of the namespace owner
	OwnerUsername *string `json:"owner_username,omitempty"`
	UpdatedAt     string  `json:"updated_at"`

	// Visibility Namespace visibility: public or private
	Visibility NamespaceResponseVisibility `json:"visibility"`
}

// NamespaceResponseVisibility Namespace visibility: public or private
type NamespaceResponseVisibility string

// PackageSummaryEntry defines model for PackageSummaryEntry.
type PackageSummaryEntry struct {
	Group        *string `json:"group,omitempty"`
	Name         string  `json:"name"`
	SbomCount    int64   `json:"sbom_count"`
	Type         string  `json:"type"`
	VersionCount int64   `json:"version_count"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	// Limit The limit that was applied
	Limit int32 `json:"limit"`

	// Offset The offset that was applied
	Offset int32 `json:"offset"`

	// Total Total number of matching results
	Total int64 `json:"total"`
}

// ProvenanceDriftSummary defines model for ProvenanceDriftSummary.
type ProvenanceDriftSummary struct {
	DetectedAt     time.Time `json:"detectedAt"`
	Id             *string   `json:"id,omitempty"`
	NewStatus      string    `json:"newStatus"`
	PreviousStatus string    `json:"previousStatus"`
	Reason         string    `json:"reason"`
}

// ReadinessCheckOutputBody defines model for ReadinessCheckOutputBody.
type ReadinessCheckOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Reason Reason for unavailability
	Reason *string `json:"reason,omitempty"`

	// Status Readiness status
	Status string `json:"status"`
}

// RecentDriftEntry defines model for RecentDriftEntry.
type RecentDriftEntry struct {
	ArtifactId     *string   `json:"artifactId,omitempty"`
	ArtifactName   *string   `json:"artifactName,omitempty"`
	ArtifactType   *string   `json:"artifactType,omitempty"`
	DetectedAt     time.Time `json:"detectedAt"`
	Id             *string   `json:"id,omitempty"`
	NewStatus      string    `json:"newStatus"`
	PreviousStatus string    `json:"previousStatus"`
	Reason         string    `json:"reason"`
	RegistryId     *string   `json:"registryId,omitempty"`
	RegistryName   *string   `json:"registryName,omitempty"`
	SbomId         string    `json:"sbomId"`
}

// RegenerateWebhookSecretOutputBody defines model for RegenerateWebhookSecretOutputBody.
type RegenerateWebhookSecretOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// WebhookSecret New webhook secret — shown once only. The previous secret is immediately invalidated.
	WebhookSecret string `json:"webhook_secret"`
}

// RegistryResponse defines model for RegistryResponse.
type RegistryResponse struct {
	// Schema A URL to the JSON Schema for this object.
	Schema    *string `json:"$schema,omitempty"`
	CreatedAt string  `json:"created_at"`
	Enabled   bool    `json:"enabled"`
	HasAuth   bool    `json:"has_auth"`
	HasSecret bool    `json:"has_secret"`
	Id        string  `json:"id"`

	// IncludeUntagged Scan untagged manifests via registry-specific APIs (supported: zot, harbor, ghcr)
	IncludeUntagged bool    `json:"include_untagged"`
	Insecure        bool    `json:"insecure"`
	LastPolledAt    *string `json:"last_polled_at,omitempty"`

	// ManagedBy External system that owns this registry's configuration (e.g. kubernetes); absent when managed through this API
	ManagedBy *string `json:"managed_by,omitempty"`

	// ManagedRef Identifier within the managing system, e.g. '<namespace>/<name>' of the OCIRegistry resource
	ManagedRef *string `json:"managed_ref,omitempty"`
	Name       string  `json:"name"`

	// OwnerId UUID of the registry owner
	OwnerId *string `json:"owner_id,omitempty"`

	// OwnerUsername GitHub username of the registry owner
	OwnerUsername       *string `json:"owner_username,omitempty"`
	PollIntervalMinutes int64   `json:"poll_interval_minutes"`

	// Repositories Explicit repositories to walk; overrides catalog discovery when non-empty
	Repositories *[]string `json:"repositories"`

	// RepositoryPatterns Glob patterns for repositories to ingest; empty = all
	RepositoryPatterns *[]string `json:"repository_patterns"`
	ScanMode           string    `json:"scan_mode"`

	// TagPatterns Glob patterns or 'semver' for tags to ingest; empty = all
	TagPatterns *[]string `json:"tag_patterns"`

	// TrustIdentity Regex matched against the Fulcio certificate SAN; required for keyless verification mode
	TrustIdentity *string `json:"trust_identity,omitempty"`

	// TrustIssuer Expected OIDC issuer URL; required for keyless verification mode
	TrustIssuer *string `json:"trust_issuer,omitempty"`

	// TrustPublicKey PEM-encoded EC public key for public_key verification mode
	TrustPublicKey *string `json:"trust_public_key,omitempty"`
	Type           string  `json:"type"`
	UpdatedAt      string  `json:"updated_at"`
	Url            string  `json:"url"`

	// VerificationMode Signature verification mode
	VerificationMode RegistryResponseVerificationMode `json:"verification_mode"`

	// Visibility Registry visibility: public or private
	Visibility string `json:"visibility"`
	WebhookUrl string `json:"webhook_url"`
}

// RegistryResponseVerificationMode Signature verification mode
type RegistryResponseVerificationMode string

// RegistryTrustCount defines model for RegistryTrustCount.
type RegistryTrustCount struct {
	Count         int64  `json:"count"`
	RegistryId    string `json:"registryId"`
	SigningStatus string `json:"signingStatus"`
}

// RegistryWebhookInputBody defines model for RegistryWebhookInputBody.
type RegistryWebhookInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema    *string `json:"$schema,omitempty"`
	Digest    string  `json:"digest"`
	Manifest  string  `json:"manifest"`
	MediaType string  `json:"mediaType"`
	Name      string  `json:"name"`
	Reference string  `json:"reference"`
}

// RetryAllFailedEnrichmentJobsOutputBody defines model for RetryAllFailedEnrichmentJobsOutputBody.
type RetryAllFailedEnrichmentJobsOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Count Number of rows transitioned from 'failed' to 'queued'
	Count int64 `json:"count"`
}

// RetryAllFailedScanJobsOutputBody defines model for RetryAllFailedScanJobsOutputBody.
type RetryAllFailedScanJobsOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Count Number of rows transitioned from 'failed' to 'queued'
	Count int64 `json:"count"`
}

// SBOMDetail defines model for SBOMDetail.
type SBOMDetail struct {
	// Schema A URL to the JSON Schema for this object.
	Schema          *string                 `json:"$schema,omitempty"`
	Architecture    *string                 `json:"architecture,omitempty"`
	ArtifactId      *string                 `json:"artifactId,omitempty"`
	BuildDate       *time.Time              `json:"buildDate,omitempty"`
	ComponentCount  *int64                  `json:"componentCount,omitempty"`
	CreatedAt       time.Time               `json:"createdAt"`
	Digest          *string                 `json:"digest,omitempty"`
	Enrichments     *map[string]interface{} `json:"enrichments,omitempty"`
	Flavor          *string                 `json:"flavor,omitempty"`
	Id              string                  `json:"id"`
	ImageVersion    *string                 `json:"imageVersion,omitempty"`
	PackageCount    int64                   `json:"packageCount"`
	ProvenanceDrift *ProvenanceDriftSummary `json:"provenanceDrift,omitempty"`
	RawBom          interface{}             `json:"rawBom,omitempty"`
	Revision        *string                 `json:"revision,omitempty"`
	SerialNumber    *string                 `json:"serialNumber,omitempty"`
	SigningStatus   string                  `json:"signingStatus"`
	SourceUrl       *string                 `json:"sourceUrl,omitempty"`
	SpecVersion     string                  `json:"specVersion"`
	SubjectVersion  *string                 `json:"subjectVersion,omitempty"`
	Sufficient      bool                    `json:"sufficient"`
	Version         int32                   `json:"version"`
	VulnSummary     *VulnSummary            `json:"vulnSummary,omitempty"`
}

// SBOMRef defines model for SBOMRef.
type SBOMRef struct {
	Architecture   *string    `json:"architecture,omitempty"`
	BuildDate      *time.Time `json:"buildDate,omitempty"`
	CreatedAt      time.Time  `json:"createdAt"`
	Flavor         *string    `json:"flavor,omitempty"`
	Id             string     `json:"id"`
	SubjectVersion *string    `json:"subjectVersion,omitempty"`
}

// SBOMSummary defines model for SBOMSummary.
type SBOMSummary struct {
	Architecture   *string    `json:"architecture,omitempty"`
	ArtifactId     *string    `json:"artifactId,omitempty"`
	BuildDate      *time.Time `json:"buildDate,omitempty"`
	ComponentCount *int64     `json:"componentCount,omitempty"`
	CreatedAt      time.Time  `json:"createdAt"`
	Digest         *string    `json:"digest,omitempty"`
	Flavor         *string    `json:"flavor,omitempty"`
	Id             string     `json:"id"`
	ImageVersion   *string    `json:"imageVersion,omitempty"`
	Revision       *string    `json:"revision,omitempty"`
	SerialNumber   *string    `json:"serialNumber,omitempty"`
	SourceUrl      *string    `json:"sourceUrl,omitempty"`
	SpecVersion    string     `json:"specVersion"`
	SubjectVersion *string    `json:"subjectVersion,omitempty"`
	Sufficient     bool       `json:"sufficient"`
	Version        int32      `json:"version"`
}

// ScanJobResponse defines model for ScanJobResponse.
type ScanJobResponse struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string `json:"$schema,omitempty"`
	Attempts   int32   `json:"attempts"`
	CreatedAt  string  `json:"created_at"`
	Digest     string  `json:"digest"`
	FinishedAt *string `json:"finished_at,omitempty"`

	// Id Job UUID
	Id            string  `json:"id"`
	LastAttemptAt *string `json:"last_attempt_at,omitempty"`
	LastError     *string `json:"last_error,omitempty"`

	// NatsMsgId NATS deduplication message ID
	NatsMsgId *string `json:"nats_msg_id,omitempty"`

	// RegistryId Source registry UUID
	RegistryId *string `json:"registry_id,omitempty"`
	Repository string  `json:"repository"`

	// SbomId Resulting SBOM UUID on success
	SbomId    *string              `json:"sbom_id,omitempty"`
	StartedAt *string              `json:"started_at,omitempty"`
	State     ScanJobResponseState `json:"state"`
	Tag       *string              `json:"tag,omitempty"`

	// WorkerId Pod hostname that is processing this job
	WorkerId *string `json:"worker_id,omitempty"`
}

// ScanJobResponseState defines model for ScanJobResponse.State.
type ScanJobResponseState string

// ScanJobsStatus defines model for ScanJobsStatus.
type ScanJobsStatus struct {
	Failed24h    int64 `json:"failed_24h"`
	Queued       int64 `json:"queued"`
	Running      int64 `json:"running"`
	Succeeded24h int64 `json:"succeeded_24h"`
}

// ScanRegistryOutputBody defines model for ScanRegistryOutputBody.
type ScanRegistryOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Message Confirmation that ad-hoc scan has been initiated
	Message string `json:"message"`
}

// ScannerStatus defines model for ScannerStatus.
type ScannerStatus struct {
	Enabled       bool `json:"enabled"`
	PollerEnabled bool `json:"poller_enabled"`
}

// SearchComponentsOutputBody defines model for SearchComponentsOutputBody.
type SearchComponentsOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string             `json:"$schema,omitempty"`
	Data       *[]ComponentSummary `json:"data"`
	Pagination PaginationMeta      `json:"pagination"`
}

// SearchDistinctComponentsOutputBody defines model for SearchDistinctComponentsOutputBody.
type SearchDistinctComponentsOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string                     `json:"$schema,omitempty"`
	Data       *[]DistinctComponentSummary `json:"data"`
	Pagination PaginationMeta              `json:"pagination"`
}

// SourceResponse defines model for SourceResponse.
type SourceResponse struct {
	// Schema A URL to the JSON Schema for this object.
	Schema    *string `json:"$schema,omitempty"`
	CreatedAt string  `json:"created_at"`
	Id        string  `json:"id"`

	// Kind Ingest channel kind
	Kind        SourceResponseKind `json:"kind"`
	Name        string             `json:"name"`
	NamespaceId string             `json:"namespace_id"`

	// NamespaceName Owning namespace name; populated on list responses
	NamespaceName *string `json:"namespace_name,omitempty"`
	UpdatedAt     string  `json:"updated_at"`
}

// SourceResponseKind Ingest channel kind
type SourceResponseKind string

// SystemStatusOutputBody defines model for SystemStatusOutputBody.
type SystemStatusOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string          `json:"$schema,omitempty"`
	Db         DBStatus         `json:"db"`
	Enrichment EnrichmentStatus `json:"enrichment"`
	Nats       NATSStatus       `json:"nats"`
	ScanJobs   ScanJobsStatus   `json:"scan_jobs"`
	Scanner    ScannerStatus    `json:"scanner"`
}

// TestRegistryConnectionInputBody defines model for TestRegistryConnectionInputBody.
type TestRegistryConnectionInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// AuthToken Token or PAT for registry authentication
	AuthToken *string `json:"auth_token,omitempty"`

	// AuthUsername Username for registry authentication
	AuthUsername *string `json:"auth_username,omitempty"`

	// Insecure Use HTTP instead of HTTPS
	Insecure bool `json:"insecure"`

	// Url Registry address (e.g. zot:5000)
	Url string `json:"url"`
}

// TestRegistryConnectionOutputBody defines model for TestRegistryConnectionOutputBody.
type TestRegistryConnectionOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Message Human-readable result (e.g. HTTP 200 or error text)
	Message string `json:"message"`

	// Reachable Whether the registry responded
	Reachable bool `json:"reachable"`
}

// TopVulnEntry defines model for TopVulnEntry.
type TopVulnEntry struct {
	AffectedPurlCount int64      `json:"affectedPurlCount"`
	AffectedSbomCount int64      `json:"affectedSbomCount"`
	Aliases           *[]string  `json:"aliases"`
	CanonicalId       string     `json:"canonicalId"`
	CvssScore         *float32   `json:"cvssScore,omitempty"`
	Id                string     `json:"id"`
	PublishedAt       *time.Time `json:"publishedAt,omitempty"`
	Severity          string     `json:"severity"`
	Summary           *string    `json:"summary,omitempty"`
}

// UpdateNamespaceInputBody defines model for UpdateNamespaceInputBody.
type UpdateNamespaceInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Name New namespace name; omit to keep the current one
	Name *string `json:"name,omitempty"`

	// Visibility New visibility; omit to keep the current one
	Visibility *UpdateNamespaceInputBodyVisibility `json:"visibility,omitempty"`
}

// UpdateNamespaceInputBodyVisibility New visibility; omit to keep the current one
type UpdateNamespaceInputBodyVisibility string

// UpdateRegistryInputBody defines model for UpdateRegistryInputBody.
type UpdateRegistryInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema       *string `json:"$schema,omitempty"`
	AuthToken    *string `json:"auth_token,omitempty"`
	AuthUsername *string `json:"auth_username,omitempty"`
	Enabled      bool    `json:"enabled"`

	// IncludeUntagged Scan untagged manifests via registry-specific APIs (supported: zot, harbor, ghcr)
	IncludeUntagged *bool `json:"include_untagged,omitempty"`
	Insecure        bool  `json:"insecure"`

	// ManagedBy External system that owns this registry's configuration; omit to leave the existing marker untouched
	ManagedBy *string `json:"managed_by,omitempty"`

	// ManagedRef Identifier within the managing system; omit to leave the existing value untouched
	ManagedRef *string `json:"managed_ref,omitempty"`
	Name       string  `json:"name"`

	// PollIntervalMinutes Minutes between polls
	PollIntervalMinutes *int64    `json:"poll_interval_minutes,omitempty"`
	Repositories        *[]string `json:"repositories,omitempty"`
	RepositoryPatterns  *[]string `json:"repository_patterns,omitempty"`

	// ScanMode Scanning mode
	ScanMode    *UpdateRegistryInputBodyScanMode `json:"scan_mode,omitempty"`
	TagPatterns *[]string                        `json:"tag_patterns,omitempty"`

	// TrustIdentity Regex matched against the Fulcio certificate SAN; required when verification_mode is keyless
	TrustIdentity *string `json:"trust_identity,omitempty"`

	// TrustIssuer Expected OIDC issuer URL; required when verification_mode is keyless
	TrustIssuer *string `json:"trust_issuer,omitempty"`

	// TrustPublicKey PEM-encoded EC public key; required when verification_mode is public_key
	TrustPublicKey *string                     `json:"trust_public_key,omitempty"`
	Type           UpdateRegistryInputBodyType `json:"type"`
	Url            string                      `json:"url"`

	// VerificationMode Signature verification mode; defaults to none
	VerificationMode *UpdateRegistryInputBodyVerificationMode `json:"verification_mode,omitempty"`

	// Visibility Registry visibility
	Visibility *UpdateRegistryInputBodyVisibility `json:"visibility,omitempty"`
}

// UpdateRegistryInputBodyScanMode Scanning mode
type UpdateRegistryInputBodyScanMode string

// UpdateRegistryInputBodyType defines model for UpdateRegistryInputBody.Type.
type UpdateRegistryInputBodyType string

// UpdateRegistryInputBodyVerificationMode Signature verification mode; defaults to none
type UpdateRegistryInputBodyVerificationMode string

// UpdateRegistryInputBodyVisibility Registry visibility
type UpdateRegistryInputBodyVisibility string

// UpdateSourceInputBody defines model for UpdateSourceInputBody.
type UpdateSourceInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Name New source name
	Name string `json:"name"`
}

// UpdateUserRoleInputBody defines model for UpdateUserRoleInputBody.
type UpdateUserRoleInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Role New role
	Role UpdateUserRoleInputBodyRole `json:"role"`
}

// UpdateUserRoleInputBodyRole New role
type UpdateUserRoleInputBodyRole string

// UserResponse defines model for UserResponse.
type UserResponse struct {
	// Schema A URL to the JSON Schema for this object.
	Schema         *string `json:"$schema,omitempty"`
	GithubUsername string  `json:"github_username"`
	Id             string  `json:"id"`
	Role           string  `json:"role"`
}

// VersionOutputBody defines model for VersionOutputBody.
type VersionOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Version API version
	Version string `json:"version"`
}

// VulnDetail defines model for VulnDetail.
type VulnDetail struct {
	Aliases     *[]string        `json:"aliases"`
	CanonicalId string           `json:"canonicalId"`
	CvssScore   *float32         `json:"cvssScore,omitempty"`
	CvssVector  *string          `json:"cvssVector,omitempty"`
	Details     *string          `json:"details,omitempty"`
	Id          string           `json:"id"`
	ModifiedAt  *time.Time       `json:"modifiedAt,omitempty"`
	PublishedAt *time.Time       `json:"publishedAt,omitempty"`
	References  *[]VulnReference `json:"references,omitempty"`
	Severity    string           `json:"severity"`
	Summary     *string          `json:"summary,omitempty"`
}

// VulnReference defines model for VulnReference.
type VulnReference struct {
	Type string `json:"type"`
	Url  string `json:"url"`
}

// VulnSeverityEntry defines model for VulnSeverityEntry.
type VulnSeverityEntry struct {
	Critical int64 `json:"critical"`
	High     int64 `json:"high"`
	Low      int64 `json:"low"`
	Medium   int64 `json:"medium"`
	Unknown  int64 `json:"unknown"`
}

// VulnSummary defines model for VulnSummary.
type VulnSummary struct {
	Critical int64 `json:"critical"`
	High     int64 `json:"high"`
	Low      int64 `json:"low"`
	Medium   int64 `json:"medium"`
	Total    int64 `json:"total"`
	Unknown  int64 `json:"unknown"`
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// cookieAuthContextKey is the context key for cookieAuth security scheme
type cookieAuthContextKey string

// RetryAllFailedEnrichmentJobsParams defines parameters for RetryAllFailedEnrichmentJobs.
type RetryAllFailedEnrichmentJobsParams struct {
	// EnricherName Limit the reset to a single enricher; omit to reset all
	EnricherName *RetryAllFailedEnrichmentJobsParamsEnricherName `form:"enricher_name,omitempty" json:"enricher_name,omitempty"`
}

// RetryAllFailedEnrichmentJobsParamsEnricherName defines parameters for RetryAllFailedEnrichmentJobs.
type RetryAllFailedEnrichmentJobsParamsEnricherName string

// ListArtifactsParams defines parameters for ListArtifacts.
type ListArtifactsParams struct {
	// Limit Maximum number of results per page
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor from a previous response's nextCursor; omit for the first page
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Type Filter by artifact type
	Type *string `form:"type,omitempty" json:"type,omitempty"`

	// Name Filter by artifact name
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Sufficient Filter to artifacts with sufficiently enriched SBOMs; pass 'false' to include all (default: true)
	Sufficient *string `form:"sufficient,omitempty" json:"sufficient,omitempty"`
}

// LookupArtifactParams defines parameters for LookupArtifact.
type LookupArtifactParams struct {
	// Name Exact artifact name, e.g. ghcr.io/pfenerty/ocidex
	Name string `form:"name" json:"name"`

	// Type Optional artifact type qualifier; omit or leave empty to match any type
	Type *string `form:"type,omitempty" json:"type,omitempty"`

	// Group Optional artifact group qualifier; omit or leave empty to match any group
	Group *string `form:"group,omitempty" json:"group,omitempty"`
}

// GetArtifactChangelogParams defines parameters for GetArtifactChangelog.
type GetArtifactChangelogParams struct {
	// SubjectVersion Filter by subject version
	SubjectVersion *string `form:"subject_version,omitempty" json:"subject_version,omitempty"`

	// Arch Architecture to show timeline for (e.g. amd64)
	Arch *string `form:"arch,omitempty" json:"arch,omitempty"`

	// Flavor Flavor to show timeline for (e.g. standard, fips)
	Flavor *string `form:"flavor,omitempty" json:"flavor,omitempty"`

	// Mode Sort/filter mode: 'semver' (semver versions, semver order), 'all' (every version, build-time order). Empty auto-selects semver when available.
	Mode *GetArtifactChangelogParamsMode `form:"mode,omitempty" json:"mode,omitempty"`
}

// GetArtifactChangelogParamsMode defines parameters for GetArtifactChangelog.
type GetArtifactChangelogParamsMode string

// ListArtifactSbomsParams defines parameters for ListArtifactSboms.
type ListArtifactSbomsParams struct {
	// Limit Maximum number of results per page
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor from a previous response's nextCursor; omit for the first page
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// SubjectVersion Filter by subject version
	SubjectVersion *string `form:"subject_version,omitempty" json:"subject_version,omitempty"`

	// ImageVersion Filter by image version
	ImageVersion *string `form:"image_version,omitempty" json:"image_version,omitempty"`
}

// ListArtifactVersionsParams defines parameters for ListArtifactVersions.
type ListArtifactVersionsParams struct {
	// Limit Maximum number of results per page
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`

	// Mode Sort/filter mode: 'semver' (semver versions, semver order), 'all' (every version, build-time order). Empty auto-selects semver when available.
	Mode *ListArtifactVersionsParamsMode `form:"mode,omitempty" json:"mode,omitempty"`
}

// ListArtifactVersionsParamsMode defines parameters for ListArtifactVersions.
type ListArtifactVersionsParamsMode string

// SearchComponentsParams defines parameters for SearchComponents.
type SearchComponentsParams struct {
	// Limit Maximum number of results per page
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`

	// Name Component name to search for; required unless purl is given
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Purl Exact package URL, e.g. pkg:npm/lodash@4.17.21; the cross-SBOM key for a component (ADR-042 R6)
	Purl *string `form:"purl,omitempty" json:"purl,omitempty"`

	// Group Filter by component group
	Group *string `form:"group,omitempty" json:"group,omitempty"`

	// Version Filter by component version
	Version *string `form:"version,omitempty" json:"version,omitempty"`
}

// SearchDistinctComponentsParams defines parameters for SearchDistinctComponents.
type SearchDistinctComponentsParams struct {
	// Limit Maximum number of results per page
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`

	// Name Filter by component name
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Group Filter by component group
	Group *string `form:"group,omitempty" json:"group,omitempty"`

	// Type Filter by component type
	Type *string `form:"type,omitempty" json:"type,omitempty"`

	// PurlType Filter by purl type
	PurlType *string `form:"purl_type,omitempty" json:"purl_type,omitempty"`

	// Sort Sort field
	Sort *string `form:"sort,omitempty" json:"sort,omitempty"`

	// SortDir Sort direction (asc or desc)
	SortDir *string `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`
}

// GetComponentVersionsParams defines parameters for GetComponentVersions.
type GetComponentVersionsParams struct {
	// Name Component name
	Name string `form:"name" json:"name"`

	// Group Filter by component group
	Group *string `form:"group,omitempty" json:"group,omitempty"`

	// Version Filter by component version
	Version *string `form:"version,omitempty" json:"version,omitempty"`

	// Type Filter by component type
	Type *string `form:"type,omitempty" json:"type,omitempty"`
}

// ListEnrichmentJobsParams defines parameters for ListEnrichmentJobs.
type ListEnrichmentJobsParams struct {
	// Limit Maximum number of results per page
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`

	// State Filter by job state
	State *ListEnrichmentJobsParamsState `form:"state,omitempty" json:"state,omitempty"`

	// EnricherName Filter by enricher
	EnricherName *ListEnrichmentJobsParamsEnricherName `form:"enricher_name,omitempty" json:"enricher_name,omitempty"`
}

// ListEnrichmentJobsParamsState defines parameters for ListEnrichmentJobs.
type ListEnrichmentJobsParamsState string

// ListEnrichmentJobsParamsEnricherName defines parameters for ListEnrichmentJobs.
type ListEnrichmentJobsParamsEnricherName string

// ListScanJobsParams defines parameters for ListScanJobs.
type ListScanJobsParams struct {
	// Limit Maximum number of results per page
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`

	// State Filter by job state
	State *ListScanJobsParamsState `form:"state,omitempty" json:"state,omitempty"`
}

// ListScanJobsParamsState defines parameters for ListScanJobs.
type ListScanJobsParamsState string

// ListLicensesParams defines parameters for ListLicenses.
type ListLicensesParams struct {
	// Limit Maximum number of results per page
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`

	// SpdxId Filter by SPDX identifier
	SpdxId *string `form:"spdx_id,omitempty" json:"spdx_id,omitempty"`

	// Name Filter by license name
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Category Filter by license category
	Category *string `form:"category,omitempty" json:"category,omitempty"`
}

// LookupLicenseParams defines parameters for LookupLicense.
type LookupLicenseParams struct {
	// SpdxId SPDX license identifier, e.g. Apache-2.0
	SpdxId string `form:"spdxId" json:"spdxId"`
}

// ListComponentsByLicenseParams defines parameters for ListComponentsByLicense.
type ListComponentsByLicenseParams struct {
	// Limit Maximum number of results per page
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListRegistriesParams defines parameters for ListRegistries.
type ListRegistriesParams struct {
	// Limit Maximum number of results per page
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListRecentDriftParams defines parameters for ListRecentDrift.
type ListRecentDriftParams struct {
	// Limit Maximum number of results per page
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor from a previous response's nextCursor; omit for the first page
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ScanRegistryParams defines parameters for ScanRegistry.
type ScanRegistryParams struct {
	// Force Re-scan every image, including digests already ingested. Default false: already-scanned digests are skipped.
	Force *bool `form:"force,omitempty" json:"force,omitempty"`
}

// RegistryWebhookParams defines parameters for RegistryWebhook.
type RegistryWebhookParams struct {
	Authorization *string `json:"Authorization,omitempty"`
}

// ListSbomsParams defines parameters for ListSboms.
type ListSbomsParams struct {
	// Limit Maximum number of results per page
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor from a previous response's nextCursor; omit for the first page
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// SerialNumber Filter by serial number
	SerialNumber *string `form:"serial_number,omitempty" json:"serial_number,omitempty"`

	// Digest Filter by image digest
	Digest *string `form:"digest,omitempty" json:"digest,omitempty"`
}

// IngestSbomParams defines parameters for IngestSbom.
type IngestSbomParams struct {
	// Source Ingest channel this SBOM arrived through, as a source UUID or <namespace>/<name>. Required — the source's namespace owns the SBOM.
	Source *string `form:"source,omitempty" json:"source,omitempty"`

	// Version Image version/tag (overrides BOM-extracted value for subject_version and imageVersion)
	Version *string `form:"version,omitempty" json:"version,omitempty"`

	// Architecture Image architecture (e.g. amd64, arm64)
	Architecture *string `form:"architecture,omitempty" json:"architecture,omitempty"`

	// BuildDate Image build date (RFC3339 or date string)
	BuildDate *string `form:"build_date,omitempty" json:"build_date,omitempty"`

	// SubjectType CycloneDX component type of the subject (e.g. application, library, file)
	SubjectType *string `form:"subject_type,omitempty" json:"subject_type,omitempty"`

	// SubjectName Subject name (e.g. ocidex)
	SubjectName *string `form:"subject_name,omitempty" json:"subject_name,omitempty"`

	// SubjectGroup Subject group/namespace (e.g. github.com/pfenerty)
	SubjectGroup *string `form:"subject_group,omitempty" json:"subject_group,omitempty"`

	// SubjectPurl Subject package URL (e.g. pkg:golang/github.com/pfenerty/ocidex@v1.2.3)
	SubjectPurl *string `form:"subject_purl,omitempty" json:"subject_purl,omitempty"`

	// Digest sha256 of the artifact file itself, not of this SBOM document. Required for a non-container subject.
	Digest *string `form:"digest,omitempty" json:"digest,omitempty"`
}

// DiffSbomsParams defines parameters for DiffSboms.
type DiffSbomsParams struct {
	// From UUID of the source SBOM
	From openapi_types.UUID `form:"from" json:"from"`

	// To UUID of the target SBOM
	To openapi_types.UUID `form:"to" json:"to"`
}

// DiffTreeParams defines parameters for DiffTree.
type DiffTreeParams struct {
	// From UUID of the source SBOM
	From openapi_types.UUID `form:"from" json:"from"`

	// To UUID of the target SBOM
	To openapi_types.UUID `form:"to" json:"to"`
}

// LookupSbomParams defines parameters for LookupSbom.
type LookupSbomParams struct {
	// Artifact Exact artifact name, e.g. ghcr.io/pfenerty/ocidex; required unless digest is given
	Artifact *string `form:"artifact,omitempty" json:"artifact,omitempty"`

	// Version Artifact version, e.g. 1.2.3; required unless digest is given
	Version *string `form:"version,omitempty" json:"version,omitempty"`

	// Arch Optional architecture qualifier; omit or leave empty to match any architecture
	Arch *string `form:"arch,omitempty" json:"arch,omitempty"`

	// Flavor Optional image flavor qualifier (ADR-020); omit or leave empty to match any flavor
	Flavor *string `form:"flavor,omitempty" json:"flavor,omitempty"`

	// Digest SBOM digest. Unique by construction, so this form never returns 409; supply it instead of artifact and version
	Digest *string `form:"digest,omitempty" json:"digest,omitempty"`

	// Include Set to 'raw' to include the raw BOM JSON
	Include *string `form:"include,omitempty" json:"include,omitempty"`
}

// GetSbomParams defines parameters for GetSbom.
type GetSbomParams struct {
	// Include Set to 'raw' to include the raw BOM JSON
	Include *string `form:"include,omitempty" json:"include,omitempty"`
}

// ListSbomComponentsParams defines parameters for ListSbomComponents.
type ListSbomComponentsParams struct {
	// Limit Maximum number of results per page
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor from a previous response's nextCursor; omit for the first page
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListSbomDriftHistoryParams defines parameters for ListSbomDriftHistory.
type ListSbomDriftHistoryParams struct {
	// Limit Maximum number of results per page
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor from a previous response's nextCursor; omit for the first page
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListSourcesParams defines parameters for ListSources.
type ListSourcesParams struct {
	// NamespaceId Limit to sources in this namespace
	NamespaceId *string `form:"namespace_id,omitempty" json:"namespace_id,omitempty"`
}

// ListTopVulnerabilitiesParams defines parameters for ListTopVulnerabilities.
type ListTopVulnerabilitiesParams struct {
	// Limit Maximum number of results per page
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`

	// Severity Filter by severity
	Severity *ListTopVulnerabilitiesParamsSeverity `form:"severity,omitempty" json:"severity,omitempty"`

	// Sort Sort field
	Sort *ListTopVulnerabilitiesParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// SortDir Sort direction (asc or desc)
	SortDir *ListTopVulnerabilitiesParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`
}

// ListTopVulnerabilitiesParamsSeverity defines parameters for ListTopVulnerabilities.
type ListTopVulnerabilitiesParamsSeverity string

// ListTopVulnerabilitiesParamsSort defines parameters for ListTopVulnerabilities.
type ListTopVulnerabilitiesParamsSort string

// ListTopVulnerabilitiesParamsSortDir defines parameters for ListTopVulnerabilities.
type ListTopVulnerabilitiesParamsSortDir string

// GetVulnerabilityParams defines parameters for GetVulnerability.
type GetVulnerabilityParams struct {
	// Limit Maximum number of results per page
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = CreateAPIKeyInputBody

// CreateNamespaceJSONRequestBody defines body for CreateNamespace for application/json ContentType.
type CreateNamespaceJSONRequestBody = CreateNamespaceInputBody

// UpdateNamespaceJSONRequestBody defines body for UpdateNamespace for application/json ContentType.
type UpdateNamespaceJSONRequestBody = UpdateNamespaceInputBody

// CreateRegistryJSONRequestBody defines body for CreateRegistry for application/json ContentType.
type CreateRegistryJSONRequestBody = CreateRegistryInputBody

// TestRegistryConnectionJSONRequestBody defines body for TestRegistryConnection for application/json ContentType.
type TestRegistryConnectionJSONRequestBody = TestRegistryConnectionInputBody

// UpdateRegistryJSONRequestBody defines body for UpdateRegistry for application/json ContentType.
type UpdateRegistryJSONRequestBody = UpdateRegistryInputBody

// RegistryWebhookJSONRequestBody defines body for RegistryWebhook for application/json ContentType.
type RegistryWebhookJSONRequestBody = RegistryWebhookInputBody

// CreateSourceJSONRequestBody defines body for CreateSource for application/json ContentType.
type CreateSourceJSONRequestBody = CreateSourceInputBody

// UpdateSourceJSONRequestBody defines body for UpdateSource for application/json ContentType.
type UpdateSourceJSONRequestBody = UpdateSourceInputBody

// UpdateUserRoleJSONRequestBody defines body for UpdateUserRole for application/json ContentType.
type UpdateUserRoleJSONRequestBody = UpdateUserRoleInputBody
